force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Assignment_Validity_Date__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Validity_Date__c</fullName>
    <label>Assignment Validity Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Closing_Manager__c.field-meta.xml
<CustomField>
    <fullName>Closing_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Opportunities (Closing Manager)</relationshipLabel>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/SV_Count__c.field-meta.xml
<CustomField>
    <fullName>SV_Count__c</fullName>
    <label>SV Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Assignment_TAT__c.field-meta.xml
<CustomField>
    <fullName>Assignment_TAT__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Assignment TAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GRE QR User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Closing_Manager__c.field-meta.xml
<CustomField>
    <fullName>Closing_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Is_Sales_Manager_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Is_Sales_Manager_Assigned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sales Manager Assigned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Is_Sales_TL_Re_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Is_Sales_TL_Re_Assigned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sales TL Re- Assigned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Re_Assign_Sales_TL__c.field-meta.xml
<CustomField>
    <fullName>Re_Assign_Sales_TL__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Re-Assign Sales TL</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Re_Assignment_Sales_TL_Date__c.field-meta.xml
<CustomField>
    <fullName>Re_Assignment_Sales_TL_Date__c</fullName>
    <label>Re-Assignment Sales TL Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/SM_Assignment_Date__c.field-meta.xml
<CustomField>
    <fullName>SM_Assignment_Date__c</fullName>
    <label>SM Assignment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Team_Type__c.field-meta.xml
<CustomField>
    <fullName>Team_Type__c</fullName>
    <label>Team Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Presales Team</fullName>
            </value>
            <value>
                <fullName>Sales Team</fullName>
            </value>
            <value>
                <fullName>Unapproved Discount Team</fullName>
            </value>
            <value>
                <fullName>Booking Approval</fullName>
                <isActive>false</isActive>
                <label>Booking Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Assignment_Counter__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Assignment Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Availability__c.field-meta.xml
<CustomField>
    <fullName>Availability__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Availability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/DayOff__c.field-meta.xml
<CustomField>
    <fullName>DayOff__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DayOff</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Last_Assignment_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Last_Assignment_DateTime__c</fullName>
    <label>Last Assignment DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Last_Assignment_Milliseconds__c.field-meta.xml
<CustomField>
    <fullName>Last_Assignment_Milliseconds__c</fullName>
    <label>Last Assignment Milliseconds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Site_Visit__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Visit</label>
    <referenceTo>Site_Visit__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/User_Active_Status__c.field-meta.xml
<CustomField>
    <fullName>User_Active_Status__c</fullName>
    <formula>User__r.IsActive</formula>
    <label>User Active Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Ex_SMAssignmentController.cls
public class Ex_SMAssignmentController {
    // Check if Sales Manager is assigned and check if Is_Sales_Manager_Assigned is true
    @AuraEnabled(cacheable=true)
    public static Site_Visit__c getSVRecord(Id recordId) {
        Site_Visit__c svRecord = [SELECT Id, SM_Assignment_Date__c, OwnerId, SV_Count__c , Opportunity__r.OwnerId, Project__r.Name, 
                                  Opportunity__c, Sales_Manager__c, Is_Sales_Manager_Assigned__c 
                                  FROM Site_Visit__c where Id =: recordId];
        system.debug('svRecord:: '+svRecord);
        if(svRecord != Null){
            return svRecord;
        }else{
            return Null;
        }
    }	
    
    // Get all Sales Manager(Team Members) of Project tagged on Site Visit 
    @AuraEnabled
    public static List<Team_Member__c> getAllSalesManager(Site_Visit__c svRecord) {
        List<Team_Member__c> userList = [Select Id, User__r.Name, Availability__c, Assignment_Counter__c ,Last_Assignment_DateTime__c, 
                                         Last_Assignment_Milliseconds__c, Team__r.Project__c from Team_Member__c
                                         where Team__r.Project__c =: svRecord.Project__c AND  User_Active_Status__c = true  AND DayOff__c = false 
                                         AND Team__r.Team_Type__c = 'Sales Team' ORDER BY Last_Assignment_DateTime__c ASC];
        system.debug('userList:: '+ userList);
        if(!userList.isEmpty() && userList != null){
            return userList;
        }else{
            return null;
        }
    }
    
    // Get all Sales TL(Team Members) of Project tagged on Site Visit 
    @AuraEnabled
    public static List<Team_Member__c> getAllSalesManagerTL(Site_Visit__c svRecord) {
        List<Team_Member__c> userList = [Select Id, User__r.Name, Availability__c, Assignment_Counter__c ,Last_Assignment_DateTime__c, 
                                         Last_Assignment_Milliseconds__c, Team__r.Project__c from Team_Member__c
                                         where Team__r.Project__c =: svRecord.Project__c AND  User_Active_Status__c = true  AND DayOff__c = false 
                                         AND Team__r.Team_Type__c = 'TL Team' ORDER BY Last_Assignment_DateTime__c ASC];
        system.debug('userList .: '+ userList);
        if(!userList.isEmpty() && userList != null){
            return userList;
        }else{
            return null;
        }
    }
    
    // Get the Sales Manager who is Owner of Opportunity according to Avaliablity
    @AuraEnabled
    public static List<Team_Member__c> getPreferredSalesManager(Site_Visit__c svRecord) {
        List<Team_Member__c> userList = new List<Team_Member__c>();
        if(svRecord.SV_Count__c > 1){
            userList = [Select Id, User__r.Name, DayOff__c, User__c, Availability__c, Assignment_Counter__c ,Last_Assignment_DateTime__c, 
                        Last_Assignment_Milliseconds__c, Team__r.Project__c from Team_Member__c
                        where Team__r.Project__c =: svRecord.Project__c AND  User_Active_Status__c = true AND DayOff__c = false 
                        AND Team__r.Team_Type__c = 'Sales Team' AND User__c =: svRecord.Opportunity__r.OwnerId  
                        ORDER BY Last_Assignment_DateTime__c ASC];
        }
        system.debug('userList:: '+ userList);
        if(!userList.isEmpty() && userList != null){
            return userList;
        }else{
            return null;
        }
    }
    
    // Handle for checking the User (Team Member) Availability
    @AuraEnabled
    public static Team_Member__c checkUserAvailability(String userId) {
        System.debug('userId .: '+userId);
        Team_Member__c salesManager = [Select Id, User__r.Name, Availability__c, Assignment_Counter__c ,Last_Assignment_DateTime__c, 
                                       Last_Assignment_Milliseconds__c, DayOff__c, User__c from Team_Member__c
                                       where ID =: userId AND User_Active_Status__c = true AND Availability__c = true AND DayOff__c = false  
                                       ORDER BY Last_Assignment_DateTime__c ASC limit 1];
        system.debug('salesManager: '+salesManager);
        if(salesManager != Null){
            return salesManager;
        }else{
            return null;
        }
    }
    
    // Assigning the Sales Manager to the Site Visit 
    @AuraEnabled
    public static boolean assignSalesManager(Site_Visit__c svRecord, Team_Member__c salesManager) {
        Set<Id> teamIdset = new Set<Id>();
        if(salesManager.User__c != null){
            teamIdset.add(salesManager.User__c);
        }
        List<Team_Member__c> tmList = new List<Team_Member__c>();
        List<Team_Member__c> updateTmList = new List<Team_Member__c>();
        if(!teamIdset.isEmpty() && teamIdset != null){
            tmList = [Select Id, User__r.Id, Availability__c from Team_Member__c where User__c IN: teamIdset];
        }
        
        if(!tmList.isEmpty() && tmList != null){
            for(Team_Member__c tm: tmList){
                if(tm.Availability__c){
                    tm.Availability__c = True;
                    updateTmList.add(tm);
                }
            }
        }
        System.debug('tmList'+tmList);
        svRecord.Sales_Manager__c = salesManager.User__r.Id;
        svRecord.OwnerId = salesManager.User__r.Id;
        svRecord.Is_Sales_Manager_Assigned__c = TRUE;
        svRecord.SM_Assignment_Date__c = System.now();
        salesManager.Last_Assignment_DateTime__c = System.now();
        salesManager.Last_Assignment_Milliseconds__c = System.now().millisecondGMT();
        if(salesManager.Assignment_Counter__c == null){
            salesManager.Assignment_Counter__c  = 1;
        }else{
            salesManager.Assignment_Counter__c = salesManager.Assignment_Counter__c + 1;
        }
        Opportunity__c oppRecord = [SELECT Id, Assignment_Validity_Date__c, Assignment_Date__c,Project__r.Assignment_TAT__c FROM Opportunity__c WHERE Id = :svRecord.Opportunity__c LIMIT 1];
        if (oppRecord != null) {
            oppRecord.Assignment_Date__c = System.today();
            if(oppRecord.Project__r.Assignment_TAT__c != null){
            oppRecord.Assignment_Validity_Date__c = System.today().addDays(Integer.valueOf(oppRecord.Project__r.Assignment_TAT__c));
            }
        }
        try {
            List<SObject> recordsToUpdate = new List<SObject>{ svRecord, salesManager, oppRecord };
                if(!recordsToUpdate.isEmpty() && recordsToUpdate != null){
                    update recordsToUpdate;
                }
            if(!updateTmList.isEmpty() && updateTmList != null){
                update updateTmList; 
            }
            System.debug('svRecord: '+svRecord);
            System.debug('salesManager: '+salesManager);
            System.debug('Opportunity Assignment Date .:' + oppRecord.Assignment_Date__c);
            System.debug('Opportunity Assignment Date updated');
            return true;
        } catch(Exception ex) {
            System.debug('Error: '+Ex.getMessage());
            return false;   
        }
    }
    
    @AuraEnabled
    public static boolean reAssignSalesManager(Site_Visit__c svRecord, Team_Member__c salesManager, Boolean reAssign) {
        System.debug('svRecord: ' + svRecord);
        System.debug('salesManager: ' + salesManager);
        System.debug('reAssign: ' + reAssign);
        
        Set<Id> teamIdset = new Set<Id>();
        
        if(salesManager.User__c != null){
            teamIdset.add(salesManager.User__c);
        }
        List<Team_Member__c> tmList = new List<Team_Member__c>();
        List<Team_Member__c> updateTmList = new List<Team_Member__c>();
        if(!teamIdset.isEmpty() && teamIdset != null){
            tmList = [Select Id, User__r.Id, Availability__c from Team_Member__c where User__c IN: teamIdset];
        }
        
        if(!tmList.isEmpty() && tmList != null){
            for(Team_Member__c tm: tmList){
                if(tm.Availability__c){
                    tm.Availability__c = true;
                    updateTmList.add(tm);
                }
            }
        }
        
        if (salesManager.User__r != null && salesManager.User__r.Id != null) {
            svRecord.Re_Assign_Sales_TL__c = salesManager.User__r.Id;
            svRecord.OwnerId = salesManager.User__r.Id;
        }
        
        svRecord.Is_Sales_TL_Re_Assigned__c = reAssign;
        svRecord.Re_Assignment_Sales_TL_Date__c = System.now();
        
        salesManager.Last_Assignment_DateTime__c = System.now();
        salesManager.Last_Assignment_Milliseconds__c = System.now().millisecondGMT();
        
        if(salesManager.Assignment_Counter__c == null){
            salesManager.Assignment_Counter__c  = 1;
        }else{
            salesManager.Assignment_Counter__c = salesManager.Assignment_Counter__c + 1;
        }
        
        Opportunity__c oppRecord = [SELECT Id, Closing_Manager__c, OwnerId FROM Opportunity__c WHERE Id = :svRecord.Opportunity__c LIMIT 1];
        if (oppRecord != null) {
            oppRecord.OwnerId = salesManager.User__r.Id;
        }
        try {
            List<SObject> recordsToUpdate = new List<SObject>{ svRecord, salesManager, oppRecord };
                if(!recordsToUpdate.isEmpty() && recordsToUpdate != null){
                    update recordsToUpdate;
                }
            if(!updateTmList.isEmpty() && updateTmList != null){
                update updateTmList; 
            }
            return true;
        } catch (Exception ex) {
            System.debug('Error: ' + ex.getMessage());
            return false;
        }
    }
}