force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <formula>Account__r.Alternate_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Site_Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Count__c</fullName>
    <label>Site Visit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>In Follow-up</fullName>
                <default>true</default>
                <label>In Follow-up</label>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Booking In-Process</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/TAT_Days_for_Walkin__c.field-meta.xml
<CustomField>
    <fullName>TAT_Days_for_Walkin__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TAT Days for Walkin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Age_Group__c.field-meta.xml
<CustomField>
    <fullName>Age_Group__c</fullName>
    <label>Age Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Age_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cities_Picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Current_Residence_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Current_Residence_Configuration__c</fullName>
    <label>Current Residence Configuration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Current_Resident_Configuration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acountant</fullName>
            </value>
            <value>
                <fullName>Advocate</fullName>
            </value>
            <value>
                <fullName>Air Force</fullName>
            </value>
            <value>
                <fullName>Application Developer</fullName>
            </value>
            <value>
                <fullName>Application Engineer</fullName>
            </value>
            <value>
                <fullName>Architects</fullName>
            </value>
            <value>
                <fullName>Army</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant Director</fullName>
            </value>
            <value>
                <fullName>Assistant Manager</fullName>
            </value>
            <value>
                <fullName>Assistant Proj Manager</fullName>
            </value>
            <value>
                <fullName>Associate</fullName>
            </value>
            <value>
                <fullName>Associate Director</fullName>
            </value>
            <value>
                <fullName>Associate Vice President</fullName>
            </value>
            <value>
                <fullName>Asst. General Manager</fullName>
            </value>
            <value>
                <fullName>Asst. Manager</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>Cardiologist</fullName>
            </value>
            <value>
                <fullName>CEO</fullName>
            </value>
            <value>
                <fullName>CFO</fullName>
            </value>
            <value>
                <fullName>Chairman</fullName>
            </value>
            <value>
                <fullName>Chairman cum Managing Director</fullName>
            </value>
            <value>
                <fullName>Chartered Accountant</fullName>
            </value>
            <value>
                <fullName>Chief Executive</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer</fullName>
            </value>
            <value>
                <fullName>Chief Financial Officer</fullName>
            </value>
            <value>
                <fullName>Chief Investment Officer</fullName>
            </value>
            <value>
                <fullName>Chief Manager</fullName>
            </value>
            <value>
                <fullName>Chief Marketing Officer</fullName>
            </value>
            <value>
                <fullName>Chief Operating Officer</fullName>
            </value>
            <value>
                <fullName>Owner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Family_Size__c.field-meta.xml
<CustomField>
    <fullName>Family_Size__c</fullName>
    <label>Family Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Joint Family</fullName>
            </value>
            <value>
                <fullName>Nuclear Family without Elders</fullName>
            </value>
            <value>
                <fullName>Nuclear Family with Elders</fullName>
            </value>
            <value>
                <fullName>Siblings Living Together</fullName>
            </value>
            <value>
                <fullName>Singles/Friends Living Together</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <label>Occupation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Employed in Pvt. company</fullName>
            </value>
            <value>
                <fullName>Govt. Employee</fullName>
            </value>
            <value>
                <fullName>Shop owner</fullName>
            </value>
            <value>
                <fullName>Professionals like lawyers, doctors, CAs, etc</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Homemaker / Housewife</fullName>
            </value>
            <value>
                <fullName>Freelancer</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Professionals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <label>Pincode</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Site_Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Site Visit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Follow-up</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States_of_India</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Team_Type__c.field-meta.xml
<CustomField>
    <fullName>Team_Type__c</fullName>
    <label>Team Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Presales Team</fullName>
            </value>
            <value>
                <fullName>Sales Team</fullName>
            </value>
            <value>
                <fullName>Unapproved Discount Team</fullName>
            </value>
            <value>
                <fullName>Booking Approval</fullName>
                <isActive>false</isActive>
                <label>Booking Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Site_Visit__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Visit</label>
    <referenceTo>Site_Visit__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Age_Group.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Less than 25 Years</fullName>
    </customValue>
    <customValue>
        <fullName>25 to 30 Years</fullName>
    </customValue>
    <customValue>
        <fullName>31 to 35 Years</fullName>
    </customValue>
    <customValue>
        <fullName>36 to 40 Years</fullName>
    </customValue>
    <customValue>
        <fullName>41 to 45 Years</fullName>
    </customValue>
    <customValue>
        <fullName>46 to 50 Years</fullName>
    </customValue>
    <customValue>
        <fullName>51 to 60 Years</fullName>
    </customValue>
    <customValue>
        <fullName>Above 60</fullName>
    </customValue>
    <masterLabel>Age Group</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Cities_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Achalpur</fullName>
    </customValue>
    <customValue>
        <fullName>Ahmednagar</fullName>
    </customValue>
    <customValue>
        <fullName>Aheri</fullName>
    </customValue>
    <customValue>
        <fullName>Akola</fullName>
    </customValue>
    <customValue>
        <fullName>Amalner</fullName>
    </customValue>
    <customValue>
        <fullName>Amravati</fullName>
    </customValue>
    <customValue>
        <fullName>Arni</fullName>
    </customValue>
    <customValue>
        <fullName>Arvi</fullName>
    </customValue>
    <customValue>
        <fullName>Bhadravati</fullName>
    </customValue>
    <customValue>
        <fullName>Bhokar</fullName>
    </customValue>
    <customValue>
        <fullName>Bhokardan</fullName>
    </customValue>
    <customValue>
        <fullName>Bhiwandi</fullName>
    </customValue>
    <customValue>
        <fullName>Beed</fullName>
    </customValue>
    <customValue>
        <fullName>Chalisgaon</fullName>
    </customValue>
    <customValue>
        <fullName>Chamorshi</fullName>
    </customValue>
    <customValue>
        <fullName>Chandrapur</fullName>
    </customValue>
    <customValue>
        <fullName>Chimur</fullName>
    </customValue>
    <customValue>
        <fullName>Dhule</fullName>
    </customValue>
    <customValue>
        <fullName>Dharmabad</fullName>
    </customValue>
    <customValue>
        <fullName>Dhanora</fullName>
    </customValue>
    <customValue>
        <fullName>Digras</fullName>
    </customValue>
    <customValue>
        <fullName>Deulgaon Raja</fullName>
    </customValue>
    <customValue>
        <fullName>Gadchiroli</fullName>
    </customValue>
    <customValue>
        <fullName>Georai</fullName>
    </customValue>
    <customValue>
        <fullName>Gondia</fullName>
    </customValue>
    <customValue>
        <fullName>Hadgaon</fullName>
    </customValue>
    <customValue>
        <fullName>Hinganghat</fullName>
    </customValue>
    <customValue>
        <fullName>Ichalkaranji</fullName>
    </customValue>
    <customValue>
        <fullName>Jalgaon</fullName>
    </customValue>
    <customValue>
        <fullName>Jalna</fullName>
    </customValue>
    <masterLabel>Cities Picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Current_Resident_Configuration.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 RK</fullName>
    </customValue>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Villa</fullName>
    </customValue>
    <masterLabel>Current Resident Configuration</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/States_of_India.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Andhra Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Arunachal Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Assam</fullName>
    </customValue>
    <customValue>
        <fullName>Bihar</fullName>
    </customValue>
    <customValue>
        <fullName>Chhattisgarh</fullName>
    </customValue>
    <customValue>
        <fullName>Goa</fullName>
    </customValue>
    <customValue>
        <fullName>Gujarat</fullName>
    </customValue>
    <customValue>
        <fullName>Haryana</fullName>
    </customValue>
    <customValue>
        <fullName>Himachal Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Jharkhand</fullName>
    </customValue>
    <customValue>
        <fullName>Karnataka</fullName>
    </customValue>
    <customValue>
        <fullName>Kerala</fullName>
    </customValue>
    <customValue>
        <fullName>Madhya Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Maharashtra</fullName>
    </customValue>
    <customValue>
        <fullName>Manipur</fullName>
    </customValue>
    <customValue>
        <fullName>Meghalaya</fullName>
    </customValue>
    <customValue>
        <fullName>Mizoram</fullName>
    </customValue>
    <customValue>
        <fullName>Nagaland</fullName>
    </customValue>
    <customValue>
        <fullName>Odisha</fullName>
    </customValue>
    <customValue>
        <fullName>Punjab</fullName>
    </customValue>
    <customValue>
        <fullName>Rajasthan</fullName>
    </customValue>
    <customValue>
        <fullName>Sikkim</fullName>
    </customValue>
    <customValue>
        <fullName>Tamil Nadu</fullName>
    </customValue>
    <customValue>
        <fullName>Telangana</fullName>
    </customValue>
    <customValue>
        <fullName>Tripura</fullName>
    </customValue>
    <customValue>
        <fullName>Uttar Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Uttarakhand</fullName>
    </customValue>
    <customValue>
        <fullName>West Bengal</fullName>
    </customValue>
    <masterLabel>States of India</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Test_Ex_TeamMemberHandlerServices.cls
@isTest
public class Test_Ex_TeamMemberHandlerServices {
    @isTest
    Public static Void SmAssignment(){
        Set<Id> smId = new Set<Id>();
        
        Project__c p1 = new Project__c();
        p1.Name = 'New Project';
        p1.TAT_Days_for_Walkin__c = 30;
        insert p1;
        
        Team__c t = new Team__c();
        t.Name = 'Sales Team';
        t.Project__c = p1.Id;
        t.Team_Type__c = 'Sales Team';
        insert t;
        
        
        
                
         Account acc = new Account();
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        acc.LastName = 'acc111';
        acc.Phone = '99854887584';
        acc.PersonMobilePhone = '9958455544';
        acc.Alternate_Email__c = 'acc111@gmail.com';
        acc.PersonEmail = 'acc1122@gmail.com';
        insert acc;
        
        Opportunity__c op = new Opportunity__c();
        op.Name = 'Test';
        op.Account__c = acc.id;
        op.Stage__c = '';
        op.Close_Date__c = system.today().addDays(30);
        
        insert op ;
        
        //Insert Sv
        Site_Visit__c sv = new Site_Visit__c();
        sv.Site_Visit_Count__c = 1;
        sv.Project__c = p1.Id;
        sv.Opportunity__c = op.Id;
        sv.Age_Group__c = '25 to 30 Years';
        sv.Gender__c = 'Male';
        sv.Designation__c = 'Owner';
        sv.Marital_Status__c = 'Married';
        sv.Occupation__c = 'Shop owner';
        sv.Family_Size__c = '2';
        sv.Current_Residence_Configuration__c = '1 BHK';
        sv.Industry__c = 'Consulting';
        sv.Company_Name__c = 'Test Company';
        sv.Residential_Address__c = 'Test Street';
        sv.City__c = 'Ahmednagar';
        sv.State__c = 'Maharashtra';
        sv.PinCode__c = '477522';
        sv.Is_Sales_Manager_Assigned__c = false;
        
        
        
            Test.startTest();
             insert sv;
        System.debug('sv::'+sv);
        Team_Member__c tmb1 = new Team_Member__c();
        tmb1.Team__c = t.Id;
        tmb1.User__c = UserInfo.getUserId();
        tmb1.Availability__c = true;
        tmb1.DayOff__c = false;
        insert tmb1;
        smId.add(tmb1.Id);
            Ex_TeamMemberHandlerServices.checkVisitForAssignment(smId);
            
            Test.stopTest();
           
    }
    
}