force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Site_Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Count__c</fullName>
    <label>Site Visit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Is_Sales_Manager_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Is_Sales_Manager_Assigned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sales Manager Assigned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Site_Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Site Visit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Team_Type__c.field-meta.xml
<CustomField>
    <fullName>Team_Type__c</fullName>
    <label>Team Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Presales Team</fullName>
            </value>
            <value>
                <fullName>Sales Team</fullName>
            </value>
            <value>
                <fullName>Unapproved Discount Team</fullName>
            </value>
            <value>
                <fullName>Booking Approval</fullName>
                <isActive>false</isActive>
                <label>Booking Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Site_Visit__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Visit</label>
    <referenceTo>Site_Visit__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ex_TeamMemberTriggerHandlerServices.cls
public class Ex_TeamMemberTriggerHandlerServices {
    public static void testDemo(){
        
    }
    /*
     *  public static void checkVisitForAssignment(Set<Id> tmIdSet) {
        Map<Id, List<Site_Visit__c>> unAssignedVisitMap = new Map<Id, List<Site_Visit__c>>();
        List<Team_Member__c> tmList = new List<Team_Member__c>();
        List<Site_Visit__c> unAssignedVisitList = new List<Site_Visit__c>();
        Set<Id> pIdSet = new Set<Id>();
        Set<Id> unAssignedVisitOppIdSet = new Set<Id>();
        
        tmList = [Select Id, Name, Team__r.Project__c from Team_Member__c where Id IN: tmIdSet AND Team__r.Team_Type__c = 'Sales Team'];
        system.debug('tmList: '+tmList);
        
        if(!tmList.isEmpty() && tmList != null) {
            for(Team_Member__c tm: tmList) {
                if(tm.Team__r.Project__c != null)
                    pIdSet.add(tm.Team__r.Project__c);
            }
        }
        
        if(!pIdSet.isEmpty() && pIdSet != null) {
            unAssignedVisitList = [Select Id, Name, Project_Name__c, Opportunity__c, Is_Sales_Manager_Assigned__c, Sales_Manager__c, Site_Visit_count__c from Site_Visit__c
                                   where Is_Sales_Manager_Assigned__c = false AND Sales_Manager__c = null AND Project_Name__c IN: pIdSet AND Opportunity__c != null
                                   ORDER BY CreatedDate ASC];
            system.debug('unAssignedVisitList: '+unAssignedVisitList);
            
            if(!unAssignedVisitList.isEmpty() && unAssignedVisitList != null) {
                for(Site_Visit__c sv: unAssignedVisitList) {
                    if(!unAssignedVisitMap.containsKey(sv.Project_Name__c)) {
                        List<Site_Visit__c> newList = new List<Site_Visit__c>();
                        newList.add(sv);
                        unAssignedVisitMap.put(sv.Project_Name__c, newList);
                    } else {
                        unAssignedVisitMap.get(sv.Project_Name__c).add(sv);
                    }
                    unAssignedVisitOppIdSet.add(sv.Opportunity__c);
                }
            }
        }
        if(!unAssignedVisitMap.isEmpty() && unAssignedVisitMap != null && !unAssignedVisitOppIdSet.isEmpty() && unAssignedVisitOppIdSet != null)
            Ex_SiteVisitHandlerServices.applyRoundRobin(unAssignedVisitMap, unAssignedVisitOppIdSet, 'After');
    }
*/
   
}