force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Pre_Registration__c/Visit_Pre_Registration__c.object-meta.xml
<CustomObject>
    <label>Visit Pre Registration</label>
    <nameField>
        <displayFormat>VPR-{000000}</displayFormat>
        <label>Visit Pre Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Pre Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Pre_Registration_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Pre_Registration_Expiry__c</fullName>
    <label>Pre Registration Expiry</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Visit Pre Registrations</relationshipLabel>
    <relationshipName>Visit_Pre_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
                <default>true</default>
                <label>Valid</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestEx_VisitPreRegistrationOTPBatch.cls
@isTest
public class TestEx_VisitPreRegistrationOTPBatch {
    @isTest
    public static void testValidateOpp(){
        
        List<Visit_Pre_Registration__c> vps = new List<Visit_Pre_Registration__c>();
        
        Project__c project = new Project__c();
        project.Name = 'Test Project';
        project.Project_Logo__c = 'Test image';
        insert project;
        
        Visit_Pre_Registration__c preReg = new Visit_Pre_Registration__c(
            Customer_Name__c = 'Test Customer',
            Mobile_Number__c = '1234567890',
            Project__c = project.Id,
            Status__c= 'Valid',
            Pre_Registration_Expiry__c = System.now().addDays(-2) // Set expiry to 30 days ago 
        );
        vps.add(preReg);
        insert vps;
        
        Test.setCreatedDate(preReg.Id, DateTime.now().addDays(-2)); 
        Test.startTest();
        Ex_VisitPreRegistrationOTPValidityBatch vprOtpBatch = new Ex_VisitPreRegistrationOTPValidityBatch();
        Database.QueryLocator queryLocator = vprOtpBatch.start(null);
        vprOtpBatch.execute(null, vps);
        vprOtpBatch.execute(null);
        Test.stopTest();
        
    }  
    
    
}