force-app/main/default/objects/Knowledge_Articles__c/Knowledge_Articles__c.object-meta.xml
<CustomObject>
    <label>Knowledge Article</label>
    <nameField>
        <label>Knowledge Article Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Knowledge Article</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Knowledge_Articles__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Knowledge_Articles__c/fields/Article_Type__c.field-meta.xml
<CustomField>
    <fullName>Article_Type__c</fullName>
    <label>Article Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CP Portal</fullName>
            </value>
            <value>
                <fullName>Customer Portal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Knowledge_Articles__c/fields/hreflink__c.field-meta.xml
<CustomField>
    <fullName>hreflink__c</fullName>
    <formula>&quot;#&quot; + TEXT(Question_No__c)</formula>
    <label>hreflink</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Knowledge_Articles__c/fields/Question_No__c.field-meta.xml
<CustomField>
    <fullName>Question_No__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Question No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Ex_KnowledgeArticleController.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 05-1-2024
//-------------------------------------------//

public with sharing class  Ex_KnowledgeArticleController {
    
    @AuraEnabled(cacheable=true)
    public static List<questionsAnswers> getQuestionsAnswers(){
        List<questionsAnswers> QAnsWrapperList = new List<questionsAnswers>();
        List<Knowledge_Articles__c> queansList = new List<Knowledge_Articles__c>();
        queansList = [Select Id,Article_Type__c,Question_No__c,Question_Text__c,Answer__c,hreflink__c from Knowledge_Articles__c order by Question_No__c ASC ];
        if(!queansList.isEmpty() && queansList != null){
            for(Knowledge_Articles__c q : queansList){
                QAnsWrapperList.add(new questionsAnswers(q.Question_No__c,q.Question_Text__c,q.Answer__c,q.hreflink__c)); 
            }
        }
        if(!QAnsWrapperList.isEmpty() && QAnsWrapperList != null){
            return QAnsWrapperList;
        }else{
            return null;
        }
        
    }
    
    public class questionsAnswers{
        @AuraEnabled
        public Decimal getQueno {get;set;}
        @AuraEnabled
        public String queName {get;set;}
        @AuraEnabled
        public String queAns {get;set;}
        @AuraEnabled
        public String href {get;set;}
        
        public questionsAnswers(Decimal getQueno,String queName,String queAns,String href){
            this.getQueno = getQueno;
            this.queName = queName;
            this.queAns = queAns;
            this.href = href;
            
        }
    }
    
}