force-app/main/default/objects/Payment_Scheme__c/Payment_Scheme__c.object-meta.xml
<CustomObject>
    <label>Payment Scheme</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Scheme</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Scheme__c/fields/Number_of_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Milestone__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Milestone</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Scheme_Milestone__c/Payment_Scheme_Milestone__c.object-meta.xml
<CustomObject>
    <label>Payment Scheme Milestone</label>
    <nameField>
        <displayFormat>PSM-{0000}</displayFormat>
        <label>Payment Scheme Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Scheme Milestone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Scheme_Milestone__c/fields/Charge_Bucket_1__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_1__c</fullName>
    <label>Charge Bucket 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agreement Value</fullName>
            </value>
            <value>
                <fullName>Other Charges</fullName>
            </value>
            <value>
                <fullName>Statutory Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Scheme_Milestone__c/fields/Payment_Scheme__c.field-meta.xml
<CustomField>
    <fullName>Payment_Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Scheme</label>
    <referenceTo>Payment_Scheme__c</referenceTo>
    <relationshipLabel>Payment Scheme Milestone</relationshipLabel>
    <relationshipName>Payment_Scheme_Milestone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Scheme_Milestone__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sequence No.</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Ex_PaymentSchemeHandlerServices.cls
public class Ex_PaymentSchemeHandlerServices {
    public static void insertPaymentSchemeMilstone(Set<Id> psId){
        List<Payment_Scheme_Milestone__c> psMilestoneList = new List<Payment_Scheme_Milestone__c> ();
        
        Payment_scheme__c paymentScheme = [SELECT Id, Name, Number_of_Milestone__c FROM Payment_scheme__c WHERE Id =: psId];
        
        for (Integer i = 1; i <= paymentScheme.Number_of_Milestone__c; i++) {
            Payment_Scheme_Milestone__c psm = new Payment_Scheme_Milestone__c();
            psm.Payment_scheme__c = paymentScheme.Id;
            psm.Milestone_Type__c = 'Date Linked';
            psm.Number_of_Days__c = 0;
            psm.Sequence_No__c = i;
            psm.Charge_Bucket_1__c = 'Agreement Value';
            for (Integer j = 1; j <= 5; j++) {
                String chargeBucketType = 'Charge_Bucket_' + j + '_Type__c';
                psm.put(chargeBucketType, 'Percentage');
                
                String chargeBucketAmount = 'Charge_Bucket_' + j + '_Amount__c';
                psm.put(chargeBucketAmount, 0);
                
                String chargeBucketPercentage = 'Charge_Bucket_' + j + '_Percentage__c';
                psm.put(chargeBucketPercentage, 0.0);
            }
            
            psMilestoneList.add(psm);
        }
        if(psMilestoneList != null && !psMilestoneList.isEmpty()){
            insert psMilestoneList ;
        }
    }
}