force-app/main/default/objects/Payment_Scheme__c/Payment_Scheme__c.object-meta.xml
<CustomObject>
    <label>Payment Scheme</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Scheme</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Scheme__c/fields/Number_of_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Milestone__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number of Milestone</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Ex_PaymentSchemeTriggerHandler.cls
public class Ex_PaymentSchemeTriggerHandler {
    public static void afterInsert(List<Payment_Scheme__c> paymentSchemeList){
        Set<Id> psId = new Set<Id> ();
        if(paymentSchemeList != null){
            for(Payment_Scheme__c ps : paymentSchemeList){
                if(ps.Number_of_Milestone__c != null){
                    psId.add(ps.Id);
                }
            }
        }
        if(psId != null && !psId.isEmpty()){
            Ex_PaymentSchemeHandlerServices.insertPaymentSchemeMilstone(psId);
        }
    }
}