force-app/main/default/objects/Blocking_Details__c/Blocking_Details__c.object-meta.xml
<CustomObject>
    <label>Blocking Details</label>
    <nameField>
        <displayFormat>Block Detail-{00}</displayFormat>
        <label>Blocking Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blocking Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Blocking_Details__c/fields/Blocked_by_token__c.field-meta.xml
<CustomField>
    <fullName>Blocked_by_token__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked by token</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Blocking_Details__c/fields/Blocking_Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Blocking_Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Blocking Requested By</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Blocking Details</relationshipLabel>
    <relationshipName>Blocking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Blocking_Details__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>DD</fullName>
            </value>
            <value>
                <fullName>Payment Gateway</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>RTGSNEFT</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>IMPS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blocking_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Blocking Details</relationshipLabel>
    <relationshipName>Blocking_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Blocking_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Mode_of_Payment__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Payment__c</fullName>
    <label>Mode of Payment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Self Funding</fullName>
            </value>
            <value>
                <fullName>Partial Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Sales_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_Status__c</fullName>
    <label>Sales Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booking-In-Process</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Not for Sale</fullName>
                <isActive>false</isActive>
                <label>Not for Sale</label>
            </value>
            <value>
                <fullName>UnBlocked</fullName>
                <isActive>false</isActive>
                <label>UnBlocked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EX_BlockingDetailsController.cls
//-------------------------------------------//
//	Created By: Exceller Tech
//	Created Date: 27-09-2024
//-------------------------------------------//
public class EX_BlockingDetailsController {
    @AuraEnabled(cacheable=true)
    public static Blocking_Details__c getBlockDetails(string uniId)
    {
        try {
            Blocking_Details__c blockingDetailList = [select id,Name,Status__c,Blocked_with_token__c,Amount__c,Transaction_ID__c,
                                                      Blocking_Comments__c from Blocking_Details__c where Unit__c =:  uniId AND Status__c ='Blocked'];
            
            return blockingDetailList;
        } catch(QueryException e) {
            System.debug('Exception is : ' + e.getMessage()); 
            return null;
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<Unit__c> fetchUnits(string uniId)
    {
        List<Unit__c> unitList = [select id,Name,Tower__r.Name , Project__r.Name /*,Project__r.Blocking_Approvar__c */,Sales_Status__c from Unit__c where Id =:  uniId];
        return unitList;
    }
    @AuraEnabled(cacheable=true)
    public static List<Opportunity__c> getOppName(string oppId){
        List<Opportunity__c> oppList = [SELECT Id , Name FROM Opportunity__c where Id =: oppId] ;
        return oppList ;
    }
    @AuraEnabled(cacheable=true)
    public static Map<String, List<String>> getModeOfFundingPicklist() {
        Map<String, List<String>> picklistValuesMap = new Map<String, List<String>>();
        Schema.DescribeFieldResult MOPFieldResult = Blocking_Details__c.Mode_of_Payment__c.getDescribe();
        List<Schema.PicklistEntry> ModeOfFundingPicklistEntries = MOPFieldResult.getPicklistValues();
        List<String> ModeOfFundingPicklist = new List<String>();
        for (Schema.PicklistEntry entry : ModeOfFundingPicklistEntries) {
            ModeOfFundingPicklist.add(entry.getValue());
        }
        
        picklistValuesMap.put('Mode_of_Payment__c', ModeOfFundingPicklist);
        system.debug('picklistValuesMap ' +picklistValuesMap);
        return picklistValuesMap;
    }
    @AuraEnabled
    public static Blocking_Details__c createBlockingRecord(Boolean blockByToken,Integer amount,String blockComment,String chequeNo,String unitName , string oppId ,string MOPpicklistValue)
    {
        System.debug('Inside CreateBlocking');
        Blocking_Details__c blockInfo=new Blocking_Details__c();
        blockInfo.Blocked_with_token__c=blockByToken;
        blockInfo.Amount__c=amount;
        blockInfo.Blocking_Comments__c=blockComment;
        blockInfo.Transaction_ID__c = chequeNo;
        blockInfo.Unit__c=unitName;
        blockInfo.Opportunity__c = oppId ;
        blockInfo.Blocking_Requested_By__c = UserInfo.getUserId();
        blockInfo.Mode_of_Payment__c = MOPpicklistValue ;
        try{
           // if((blockInfo.Blocked_by_token__c==true))
                insert blockInfo;
        }
        catch(exception ex)
        {
            throw new AuraHandledException(ex.getMessage());
        }
        blockInfo.Status__c='Blocked';
        
        Unit__c unit=[select id,Name,Sales_Status__c /*Project__r.Blocking_Approvar__c*/ from Unit__c where id =: unitName];
        
        unit.Sales_Status__c='Blocked';
        
     /*   if(unit.Project__r.Blocking_Approvar__c !=null)
        {
            unit.Block_Approvar__c= unit.Project__r.Blocking_Approvar__c;
        } */
        unit.Opportunity__c = oppId;  
        update blockInfo;
        update unit;
      
        return blockInfo;
    }
    @AuraEnabled
    public static Blocking_Details__c unblockLogic(String blockId,String unblockComment)
    {
        Blocking_Details__c unblock=[select id,Status__c,Unit__c from Blocking_Details__c where id=:blockId AND Status__c ='Blocked' limit 1];
        Unit__c unit=[select id,Name,Sales_Status__c,Blocking_Comments__c from Unit__c where Id=:unblock.Unit__c];
        unblock.Status__c='Released';
        unit.Sales_Status__c='Vacant';
        unit.Blocking_Comments__c = unblockComment;
        unit.Opportunity__c = null ;
        update unit;
        update unblock;
        return unblock;
    }
}