force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>IL-{000000}</displayFormat>
        <label>Integration Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/API_Hit_Status__c.field-meta.xml
<CustomField>
    <fullName>API_Hit_Status__c</fullName>
    <label>API Hit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Whatsapp_Template__c.field-meta.xml
<CustomField>
    <fullName>Whatsapp_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Whatsapp Template</label>
    <referenceTo>Whatsapp_Template__c</referenceTo>
    <relationshipLabel>Integration Logs</relationshipLabel>
    <relationshipName>Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/WA_API_Details_Gupshup__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Gupshup APIs</description>
    <label>WA API Details Gupshup</label>
</CustomObject>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/appId__c.field-meta.xml
<CustomField>
    <fullName>appId__c</fullName>
    <label>appId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/Connection__c.field-meta.xml
<CustomField>
    <fullName>Connection__c</fullName>
    <label>Connection</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>EndPoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/HandleId_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>HandleId_Endpoint__c</fullName>
    <label>HandleId Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/Source_Phone__c.field-meta.xml
<CustomField>
    <fullName>Source_Phone__c</fullName>
    <label>Source Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/src_name__c.field-meta.xml
<CustomField>
    <fullName>src_name__c</fullName>
    <label>src.name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/token__c.field-meta.xml
<CustomField>
    <fullName>token__c</fullName>
    <label>token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/Whatsapp_Template__c.object-meta.xml
<CustomObject>
    <label>Whatsapp Template</label>
    <nameField>
        <displayFormat>WT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Whatsapp Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Whatsapp_Template__c/fields/API_Hit_Status__c.field-meta.xml
<CustomField>
    <fullName>API_Hit_Status__c</fullName>
    <label>API Hit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Whatsapp_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Whatsapp_Template_Name__c</fullName>
    <label>Whatsapp Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Ex_DeleteWhatsappTemplate.cls
public class Ex_DeleteWhatsappTemplate{

    @AuraEnabled
    public static String DeleteTemplate(String recId){
        String result = null;
        List<WA_API_Details_Gupshup__c> WhatsappDetails = [select Id, IsDeleted, Name, EndPoint__c, token__c, Connection__c,
                                                           appId__c, Source_Phone__c, src_name__c, Channel__c, Name__c,
                                                           isActive__c, HandleId_Endpoint__c, API_Key__c, EndPoint_URL__c
                                                           /*APIKey__c, Key_API__c*/ from WA_API_Details_Gupshup__c where isActive__c =: true];
        
		List<Whatsapp_Template__c> whatsapptemplate = [Select Id, Whatsapp_Template_Name__c from Whatsapp_Template__c where Id =: recId];

        
        if(!WhatsappDetails.isEmpty() && WhatsappDetails != null && !whatsapptemplate.isEmpty() && whatsapptemplate != null){
            
            
            String appId = WhatsappDetails[0].appId__c;
            String elementName = whatsapptemplate[0].Whatsapp_Template_Name__c;
            String partnerAppToken = WhatsappDetails[0].token__c;
            
            // Construct the endpoint URL
            String endpoint = WhatsappDetails[0].EndPoint__c + appId + '/template/' + elementName;
            
            Integration_Log__c IntLogs = new Integration_Log__c();
            IntLogs.EndPoint__c = endpoint;
            
            
            // Create an HTTP request
            HttpRequest req = new HttpRequest();
            req.setEndpoint(endpoint);
            req.setMethod('DELETE');
            req.setHeader('Authorization', partnerAppToken);
            
            // Create an HTTP object to send the request
            Http http = new Http();
            HttpResponse res = http.send(req);
            
            // Check the response
            if (res.getStatusCode() >= 200 && res.getStatusCode() < 300) {
                // Successful deletion
                IntLogs.API_Hit_Status__c = 'Success';
                System.debug('Template deleted successfully');
               	result = 'success';
                Delete whatsapptemplate;
                
            } else {
                // Handle error
                IntLogs.Whatsapp_Template__c = whatsapptemplate[0].Id;
                IntLogs.API_Hit_Status__c = 'Failed';
                result = 'error';
                System.debug('Error deleting template. Status code: ' + res.getStatusCode() + ', Response: ' + res.getBody());
            }
            
            IntLogs.Request__c = req.getBody();
            IntLogs.Response__c = res.getBody();
            
            insert IntLogs;
            
            return result;
        }
        else{
            return result;
        }
    }
}