force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incoming</fullName>
                <default>true</default>
                <label>Incoming</label>
            </value>
            <value>
                <fullName>SNP</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Visit Confirmed</fullName>
            </value>
            <value>
                <fullName>Visit Done</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ex_TaskTriggerHandler.cls
public class Ex_TaskTriggerHandler {
    public static void beforeInsert(List<Task> taskList) {
        Map<Id, List<Task>> taskMap = new Map<Id, List<Task>>();
        List<Task> newTaskList = new List<Task>();
        
        for(Task t: taskList) {
            if(Schema.SObjectType.Task.getRecordTypeInfosById().get(t.RecordTypeId).getName() == 'Presales Call') {
                if(t.WhatId != null && t.WhatId.getSObjectType().getDescribe().getName() == 'Lead__c') { 
                    if(!taskMap.containsKey(t.WhatId)) {
                        List<Task> tList = new List<Task>();
                        if(!t.Subject.contains('Email:')){
                          tList.add(t);  
                        }
                        taskMap.put(t.WhatId, tList);
                    } else {
                        taskMap.get(t.WhatId).add(t);
                    }
                }
            }
            if(t.Proposed_Date_Of_Visit__c != null && t.Next_Follow_Up_Date__c != null){
                newTaskList.add(t);
            }
        }
        if(!taskMap.isEmpty() && taskMap != null)
            Ex_TaskHandlerServices.validationCheckforPresaleCall(taskMap);
        if(!newTaskList.isEmpty() && newTaskList != null)
            Ex_TaskHandlerServices.validateProposedVisitAndNextFollowUp(newTaskList);
    }
    
    public static void afterInsert(List<Task> taskList) {
        Set<Id> taskIdSet = new Set<Id>();
        List<Task> enqList = new List<Task>();
        
        for(Task t: taskList) {
            if(t.Stage__c != null && t.Status.equalsIgnoreCase('Completed') &&
               (Schema.SObjectType.Task.getRecordTypeInfosById().get(t.RecordTypeId).getName() == 'Presales Call' || 
                Schema.SObjectType.Task.getRecordTypeInfosById().get(t.RecordTypeId).getName() == 'Sales Call'))
            {
                taskIdSet.add(t.Id);
            }
            if(Schema.SObjectType.Task.getRecordTypeInfosById().get(t.RecordTypeId).getName() == 'CP Call' ||
               Schema.SObjectType.Task.getRecordTypeInfosById().get(t.RecordTypeId).getName() == 'CP Meeting' ||
              	Schema.SObjectType.Task.getRecordTypeInfosById().get(t.RecordTypeId).getName() == 'Enquiry') 
            {
                taskIdSet.add(t.Id);
            }
            if(Schema.SObjectType.Task.getRecordTypeInfosById().get(t.RecordTypeId).getName() == 'CP Meeting'){
                if(t.Location__latitude__s != Null && t.Location__Longitude__s != Null){
                    if (!Test.isRunningTest()) {
                      //  EX_LiveLocationOnTask.trackGMap(t.Id,t.Location__latitude__s, t.Location__Longitude__s);
                    }
                }
            }
            if(Schema.SObjectType.Task.getRecordTypeInfosById().get(t.RecordTypeId).getName() == 'Enquiry')//&& t.Campaign__c != null
                enqList.add(t);            
        }
        if(!taskIdSet.isEmpty() && taskIdSet != null){
            Ex_TaskHandlerServices.CallHandlerServices(taskIdSet, 'insert', true);
        }
        //if(!enqList.isEmpty() && enqList != null)
           // Ex_CampaignHandlerServices.calculateCampaignPerformance('Task', null, enqList);
    }
    
    public static void beforeUpdate(Map<Id, Task> oldMap, Map<Id, Task> newMap) {
        Map<Id, List<Task>> taskMap = new Map<Id, List<Task>>();
        
        for(Task oldTask: oldMap.values()) {
            Task newTask = newMap.get(oldTask.Id);
            
            if(oldTask.Stage__c != newTask.Stage__c && newTask.Stage__c != null) {
                if(Schema.SObjectType.Task.getRecordTypeInfosById().get(newTask.RecordTypeId).getName() == 'Presales Call') {
                    if(newTask.WhatId != null && newTask.WhatId.getSObjectType().getDescribe().getName() == 'Lead__c') {
                        if(!taskMap.containsKey(newTask.WhatId)) {
                            List<Task> tList = new List<Task>();
                            tList.add(newTask);
                            taskMap.put(newTask.WhatId, tList);
                        } else {
                            taskMap.get(newTask.WhatId).add(newTask);
                        }
                    }
                }
            }
        }
        if(!taskMap.isEmpty() && taskMap != null)
            Ex_TaskHandlerServices.validationCheckforPresaleCall(taskMap);
    }
    
    public static void afterUpdate(Map<Id, Task> oldMap, Map<Id, Task> newMap) {
        Set<Id> taskIdSet = new Set<Id>();      
        
        for(Task oldTask: oldMap.values()) {
            Task newTask = newMap.get(oldTask.Id);
            
            if(oldTask.Status != newTask.Status && newTask.Status == 'Completed' && newTask.Stage__c != null)
                taskIdSet.add(newTask.Id);
        }
        if(!taskIdSet.isEmpty() && taskIdSet != null)
            Ex_TaskHandlerServices.CallHandlerServices(taskIdSet, 'update', true);
    }
}