force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Is_CTI_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Is_CTI_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is CTI Campaign?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>IF( ISPICKVAL( Approver_Status__c , &apos;Approved&apos;) , AND((Start_Date__c &lt;= TODAY()), OR((TODAY()&lt;= End_Date__c),isblank (End_Date__c))) ,false )</formula>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Offline_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Offline_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>It is used In case of Mobile User</inlineHelpText>
    <label>Offline Campaign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Ozontel_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Ozontel_Campaign_Name__c</fullName>
    <inlineHelpText>It is used for CTI Campaign for Ozontel</inlineHelpText>
    <label>Ozontel Campaign Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Virtual_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Number__c</fullName>
    <label>Virtual Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/CP_Project__c.object-meta.xml
<CustomObject>
    <label>CP Project</label>
    <nameField>
        <displayFormat>CPP-{00000}</displayFormat>
        <label>CP Project No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria.
Please choose different CP Project</errorMessage>
        <filterItems>
            <field>CP_Project__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</description>
    <inlineHelpText>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</inlineHelpText>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Leads (Opportunity)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Virtual_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Number__c</fullName>
    <label>Virtual Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Ola_Pickup__c/Ola_Pickup__c.object-meta.xml
<CustomObject>
    <label>Ola Pickup</label>
    <nameField>
        <displayFormat>Ola-{00000}</displayFormat>
        <label>Ola Pickup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ola Pickups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ola_Pickup__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Ola Pickups</relationshipLabel>
    <relationshipName>Ola_Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ola_Pickup__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Ola Pickups</relationshipLabel>
    <relationshipName>Ola_Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ola_Pickup__c/fields/Visit_Pre_Registration__c.field-meta.xml
<CustomField>
    <fullName>Visit_Pre_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit Pre-Registration</label>
    <referenceTo>Visit_Pre_Registration__c</referenceTo>
    <relationshipLabel>Ola Pickups</relationshipLabel>
    <relationshipName>Ola_Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile__c</fullName>
    <formula>Account__r.PersonContact.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Campaign_Custom__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Custom</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria.
Please select different CP Project</errorMessage>
        <filterItems>
            <field>CP_Project__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>Account__r.PersonContact.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Pre_Registration__c/Visit_Pre_Registration__c.object-meta.xml
<CustomObject>
    <label>Visit Pre Registration</label>
    <nameField>
        <displayFormat>VPR-{000000}</displayFormat>
        <label>Visit Pre Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Pre Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>Visit Pre-Registrations</relationshipLabel>
    <relationshipName>Visit_Pre_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Visit Pre-Registrations</relationshipLabel>
    <relationshipName>Visit_Pre_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Visit Pre-Registrations</relationshipLabel>
    <relationshipName>Visit_Pre_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Visit Pre Registrations</relationshipLabel>
    <relationshipName>Visit_Pre_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ex_CallCustomerServices.cls
global class Ex_CallCustomerServices {
    @Auraenabled(cacheable=true)
    public static List<campWrapper> getCampaign(String recordId, String getFormType){
        System.debug('getFormType: '+getFormType);
        List<campWrapper> campWrapperList = new List<campWrapper>();
        List<Campaign__c> campList = new List<Campaign__c>();
        List<String> getCampList = new List<String>();
        List<Lead__c> ldlist = new List<Lead__c>();
        List<Ola_Pickup__c> olaPickupList = new  List<Ola_Pickup__c> ();
        List<Opportunity__c> oppList = new List<Opportunity__c> ();
        List<CP_Project__c> cpProjectList =  new List<CP_Project__c> ();
        if((String.isNotBlank(recordId)) && recordId != null){
            if(String.isNotBlank(getFormType) && getFormType == 'Large'){
                ldlist = [Select Id, Project__c, Campaign__c,Mobile__c,Phone__c from Lead__c where Id =: recordId];
                System.debug('getLead: '+ldlist);
                if(!ldlist.isEmpty() && ldlist != null){
                    campList = [Select Id, Project__c,IsActive__c, Ozontel_Campaign_Name__c, Virtual_Number__c, Offline_Campaign__c, Is_CTI_Campaign__c from Campaign__c where Project__c =: ldlist[0].Project__c AND Ozontel_Campaign_Name__c != null AND Virtual_Number__c != null AND Is_CTI_Campaign__c = true AND Offline_Campaign__c = false AND IsActive__c = true];
                }
            }else{
                ldlist = [Select Id, Project__c, Campaign__c,Mobile__c,Phone__c,Campaign__r.Ozontel_Campaign_Name__c,Campaign__r.Virtual_Number__c from Lead__c where Id =: recordId];
                System.debug('getLead: '+ldlist);
                if(!ldlist.isEmpty() && ldlist != null){
                    campList = [Select Id, Project__c,IsActive__c, Ozontel_Campaign_Name__c, Virtual_Number__c, Offline_Campaign__c, Is_CTI_Campaign__c from Campaign__c where Project__c =: ldlist[0].Project__c AND Ozontel_Campaign_Name__c != null AND Virtual_Number__c != null AND Is_CTI_Campaign__c = true AND Offline_Campaign__c = true AND IsActive__c = true];
                }
            }
            if(!ldlist.isEmpty() && ldlist != null){
                if(!campList.isEmpty() && campList != null){
                    for(Campaign__c c: campList){
                        campWrapperList.add(new campWrapper(c.Ozontel_Campaign_Name__c,c.Virtual_Number__c));
                    }
                }
            }else {
                olaPickupList = [Select Id, Lead__r.Mobile__c, Opportunity__r.Mobile__c, Visit_Pre_Registration__r.Mobile__c, Lead__r.Phone__c,Opportunity__r.Phone__c from Ola_Pickup__c where Id =: recordId ];
                System.debug('olaPickupList: '+olaPickupList);                
                if(!olaPickupList.isEmpty() && olaPickupList != null){
                    if(String.isNotBlank(getFormType) && getFormType == 'Large'){
                        campList = [Select Id, Project__c, Ozontel_Campaign_Name__c,IsActive__c, Virtual_Number__c, Offline_Campaign__c, Is_CTI_Campaign__c from Campaign__c where Ozontel_Campaign_Name__c != null AND Virtual_Number__c != null AND Is_CTI_Campaign__c = true AND  Offline_Campaign__c = false AND IsActive__c = true];
                        System.debug('campList: '+campList);
                    }else{
                        campList = [Select Id, Project__c, Ozontel_Campaign_Name__c,IsActive__c, Virtual_Number__c, Offline_Campaign__c, Is_CTI_Campaign__c from Campaign__c where Ozontel_Campaign_Name__c != null AND Virtual_Number__c != null AND Is_CTI_Campaign__c = true AND Offline_Campaign__c = true AND IsActive__c = true];
                        System.debug('campList: '+campList);
                    }
                    if(!campList.isEmpty() && campList != null){
                        for(Campaign__c c: campList){
                             campWrapperList.add(new campWrapper(c.Ozontel_Campaign_Name__c,c.Virtual_Number__c));
                        }
                    }
                }else{
                    if(String.isNotBlank(getFormType) && getFormType == 'Large'){
                        oppList = [Select Id, Mobile__c,Phone__c,Project__c from Opportunity__c where Id =: recordId ];
                        if(!oppList.isEmpty() && oppList != null){
                            campList = [Select Id, Project__c, Ozontel_Campaign_Name__c,IsActive__c, Virtual_Number__c, Offline_Campaign__c, Is_CTI_Campaign__c from Campaign__c where Project__c =: oppList[0].Project__c AND Ozontel_Campaign_Name__c != null AND Virtual_Number__c != null AND Is_CTI_Campaign__c = true AND Offline_Campaign__c = false  AND IsActive__c = true];
                        }
                    }else{
                        oppList = [Select Id, Mobile__c,Phone__c,Project__c from Opportunity__c where Id =: recordId];
                        if(!oppList.isEmpty() && oppList != null){
                            campList = [Select Id, Project__c, Ozontel_Campaign_Name__c,IsActive__c, Virtual_Number__c, Offline_Campaign__c, Is_CTI_Campaign__c from Campaign__c where Project__c =: oppList[0].Project__c AND Ozontel_Campaign_Name__c != null AND Virtual_Number__c != null AND Is_CTI_Campaign__c = true AND Offline_Campaign__c = true AND IsActive__c = true];
                        }
                    }
                    System.debug('oppList: '+oppList);
                    System.debug('campList:'+campList);
                    if(!oppList.isEmpty() && oppList != null){
                        if(!campList.isEmpty() && campList != null){
                            for(Campaign__c c: campList){
                                 campWrapperList.add(new campWrapper(c.Ozontel_Campaign_Name__c,c.Virtual_Number__c));
                            }
                        }                        
                    }else{
                        cpProjectList = [Select Id,Mobile__c From CP_Project__c where Mobile__c != null AND Id=: recordId];
                        if(String.isNotBlank(getFormType) && getFormType == 'Large'){
                            campList = [Select Id, Project__c, Ozontel_Campaign_Name__c,  Virtual_Number__c, IsActive__c, Offline_Campaign__c, Is_CTI_Campaign__c   from Campaign__c where Ozontel_Campaign_Name__c != null AND Virtual_Number__c != null AND Is_CTI_Campaign__c = true AND Offline_Campaign__c = false  AND IsActive__c = true];
                             System.debug('campList: '+campList);
                        }else{
                            campList = [Select Id, Project__c, Ozontel_Campaign_Name__c, Virtual_Number__c,IsActive__c, Offline_Campaign__c, Is_CTI_Campaign__c   from Campaign__c where Ozontel_Campaign_Name__c != null AND Virtual_Number__c != null AND Is_CTI_Campaign__c = true AND Offline_Campaign__c = true  AND IsActive__c = true];
                        }
                        System.debug('campList: '+campList);
                        if(!campList.isEmpty() && campList != null){
                            for(Campaign__c c: campList){
                                 campWrapperList.add(new campWrapper(c.Ozontel_Campaign_Name__c,c.Virtual_Number__c));
                            }
                        }else{
                            return null;
                        }
                    }
                }
            }
        }
        System.debug('campWrapperList: '+campWrapperList);
        if(!campWrapperList.isEmpty() && campWrapperList != null){
            return campWrapperList;
        }else{
            return null;
        }
    }
    
    @Auraenabled(cacheable=true)
    public static list<callWrapper> getMobileNumber(String recordId){
        System.debug('recordId: '+recordId);
        List<callWrapper> getMobileWrapper = new List<callWrapper>();
        List<Lead__c> ldlist = new List<Lead__c>();
        List<Ola_Pickup__c> olaPickupList = new  List<Ola_Pickup__c> ();
        List<Opportunity__c> oppList = new List<Opportunity__c> ();
        List<CP_Project__c> cpProjectList =  new List<CP_Project__c> ();
        if((String.isNotBlank(recordId)) && recordId != null){
            ldlist = [Select Id, Project__c, Campaign__c,Mobile__c,Phone__c from Lead__c where Id =: recordId AND IsConverted__c = false AND Mobile__c != null];
            System.debug('getLead: '+ldlist);
            if(!ldlist.isEmpty() && ldlist != null){
                if(ldlist[0].Phone__c != null && ldlist[0].Mobile__c != null){
                    getMobileWrapper.add(new callWrapper('XXXXXX'+ldlist[0].Mobile__c.substring(ldlist[0].Mobile__c.length() - 4) ,'XXXXXX'+ldlist[0].Phone__c.substring(ldlist[0].Phone__c.length() - 4) , ldlist[0].Mobile__c , ldlist[0].Phone__c));  
                }else{
                    getMobileWrapper.add(new callWrapper('XXXXXX'+ldlist[0].Mobile__c.substring(ldlist[0].Mobile__c.length() - 4) ,'',ldlist[0].Mobile__c,''));   
                }
            }else {
                olaPickupList = [Select Id, Primary_Mobile__c, Alternate_Mobile__c, Lead__r.Mobile__c, Opportunity__r.Mobile__c, Visit_Pre_Registration__r.Mobile__c, Lead__r.Phone__c,Opportunity__r.Phone__c from Ola_Pickup__c where Id =: recordId];
                System.debug('olaPickupList: '+olaPickupList);                
                if(!olaPickupList.isEmpty() && olaPickupList != null){
                    if(olaPickupList[0].Lead__r != null && olaPickupList[0].Primary_Mobile__c != null && olaPickupList[0].Alternate_Mobile__c != null){
                        getMobileWrapper.add(new callWrapper('XXXXXX'+olaPickupList[0].Primary_Mobile__c.substring(olaPickupList[0].Primary_Mobile__c.length() - 4) ,'XXXXXX'+olaPickupList[0].Alternate_Mobile__c.substring(olaPickupList[0].Alternate_Mobile__c.length() - 4),olaPickupList[0].Primary_Mobile__c, olaPickupList[0].Alternate_Mobile__c));
                    }else if(olaPickupList[0].Lead__r != null && olaPickupList[0].Primary_Mobile__c != null){
                        getMobileWrapper.add(new callWrapper('XXXXXX'+olaPickupList[0].Primary_Mobile__c.substring(olaPickupList[0].Primary_Mobile__c.length() - 4) , '', olaPickupList[0].Primary_Mobile__c,''));
                    }else if(olaPickupList[0].Opportunity__r != null && olaPickupList[0].Alternate_Mobile__c != null && olaPickupList[0].Primary_Mobile__c != null){
                        getMobileWrapper.add(new callWrapper('XXXXXX'+olaPickupList[0].Primary_Mobile__c.substring(olaPickupList[0].Primary_Mobile__c.length() - 4) ,'XXXXXX'+olaPickupList[0].Alternate_Mobile__c.substring(olaPickupList[0].Alternate_Mobile__c.length() - 4),olaPickupList[0].Primary_Mobile__c, olaPickupList[0].Alternate_Mobile__c));
                    }else if(olaPickupList[0].Opportunity__r != null && olaPickupList[0].Primary_Mobile__c != null){
                        getMobileWrapper.add(new callWrapper('XXXXXX'+olaPickupList[0].Primary_Mobile__c.substring(olaPickupList[0].Primary_Mobile__c.length() - 4) , '', olaPickupList[0].Primary_Mobile__c,''));
                    }else if(olaPickupList[0].Visit_Pre_Registration__r != null && olaPickupList[0].Primary_Mobile__c != null){
                        getMobileWrapper.add( new callWrapper('XXXXXX'+olaPickupList[0].Primary_Mobile__c.substring(olaPickupList[0].Primary_Mobile__c.length() - 4) ,'',olaPickupList[0].Primary_Mobile__c,''));
                    }
                }else{
                    oppList = [Select Id, Mobile__c,Phone__c from Opportunity__c where Id =: recordId AND Mobile__c != null];
                    if(!oppList.isEmpty() && oppList != null){
                        if(oppList[0].Mobile__c != null && oppList[0].Phone__c != null){
                            getMobileWrapper.add(new callWrapper('XXXXXX'+oppList[0].Mobile__c.substring(oppList[0].Mobile__c.length() - 4), 'XXXXXX'+ oppList[0].Phone__c.substring(oppList[0].Phone__c.length() - 4), oppList[0].Mobile__c, oppList[0].Phone__c));
                            
                        }else{
                            getMobileWrapper.add(new callWrapper('XXXXXX'+oppList[0].Mobile__c.substring(oppList[0].Mobile__c.length() - 4), '',oppList[0].Mobile__c,''));
                            
                        }
                    }else{
                        cpProjectList = [Select Id,Mobile__c From CP_Project__c where Mobile__c != null AND Id =: recordId];
                        if(!cpProjectList.isEmpty() && cpProjectList != null){
                            getMobileWrapper.add(new callWrapper('XXXXXX'+cpProjectList[0].Mobile__c.substring(cpProjectList[0].Mobile__c.length() - 4),'',cpProjectList[0].Mobile__c,''));
                        }else{
                            return null;
                        }
                        
                    }
                }
            }
        }else{
            return null;
        }
        System.debug('getMobileWrapper: '+getMobileWrapper);
        if(!getMobileWrapper.isEmpty() && getMobileWrapper != null){
            return getMobileWrapper;
        }else{
            return null;
        }
    }
    
    @Auraenabled(cacheable=false)
    global static String ClickToCall(String customerPh, String campaignName, String did, String getFormType, String uui){
        List<User> uList = new List<User>();
        String userName = '';
        String apiKey = '';
        String agentId = '';
        String parameterString = '';
        String endPoint = '';
        System.debug('uui: '+uui);
        
        try{
            uList = [Select Id,Name, Ozonetel_AgentId__c From User Where Id =: UserInfo.getUserId()];
            if(!uList.isEmpty() && uList != null) {
                agentId = uList[0].Ozonetel_AgentId__c;
                System.debug('agentId: '+agentId);
            }
            if(system.label.Ozontel_Username != null && system.label.Ozonetel_Apikey != null){
                userName = system.label.Ozontel_Username;
                apiKey = system.label.Ozonetel_Apikey ;
            }
            if(String.isNotBlank(did) && String.isNotBlank(customerPh) && String.isNotBlank(getFormType) && getFormType == 'Small' && String.isNotBlank(uui)){
                parameterString = 'apiKey='+apiKey+'&userName='+userName+'&custNumber='+customerPh+'&phoneName='+agentId+'&did='+did+'&uui='+uui;   
                endPoint = 'https://in1-ccaas-api.ozonetel.com/CAServices/PhoneManualDial.php?'+parameterString;   
            }else{
                parameterString = 'api_key='+apiKey+'&username='+userName+'&agentID='+agentId+'&campaignName='+campaignName+'&customerNumber='+customerPh+'&uui='+uui;   
                endPoint = 'https://in1-ccaas-api.ozonetel.com/CAServices/AgentManualDial.php?'+parameterString;
            }
        
            System.debug('click2call URL:' + endpoint);
            Http httpProtocol = new Http();
            HttpRequest request = new HttpRequest();
            request.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            request.setMethod('GET');        
            request.setEndPoint(endpoint);        
            System.Debug('Request:'+request);
            System.debug('ResponseStart: ');
            HttpResponse response = new HttpResponse();
            if(!Test.isRunningTest()) {
                response = httpProtocol.send(request);
            }/* else {
response.setBody('DUMMY');
}*/
            system.debug('ResponseCode: '+response.getStatusCode());        
            system.debug('Response: '+response.getBody());
            String tempResponse = response.getBody() + '- called customer';// on: ' + customerPh;
            return (tempResponse);
            
        }catch(Exception e){
            return null;
        }    
        
    }
    Public Class campWrapper{
        @Auraenabled
        public String ozoneTelcampName{get;set;}
        @Auraenabled
        public String didNumber{get;set;}
        
        public campWrapper(String ozoneTelcampName,String didNumber){
            this.ozoneTelcampName = ozoneTelcampName;
            this.didNumber = didNumber;
        }
        
        
    }
    
    public class callWrapper{
        @Auraenabled
        public String maskcallNo{get;set;}
        @Auraenabled
        public String maskAlternateNo {get;set;}
        @Auraenabled
        public String callNo{get;set;}
        @Auraenabled
        public String AlternateNo {get;set;}
        
        public callWrapper(String maskcallNo, String maskAlternateNo, String callNo,String AlternateNo){
            this.maskcallNo = maskcallNo;
            this.maskAlternateNo = maskAlternateNo;
            this.callNo = callNo;
            this.AlternateNo = AlternateNo;
        }
    }
}