force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>IF( ISPICKVAL( Approver_Status__c , &apos;Approved&apos;) , AND((Start_Date__c &lt;= TODAY()), OR((TODAY()&lt;= End_Date__c),isblank (End_Date__c))) ,false )</formula>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign_Performance__c/Campaign_Performance__c.object-meta.xml
<CustomObject>
    <label>Campaign Performance</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Campaign Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Performances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Performance__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign_c</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Campaign Performances</relationshipLabel>
    <relationshipName>Campaign_Performances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ex_CampaignBatchClass.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 17-10-2023
//-------------------------------------------//
public class Ex_CampaignBatchClass implements Database.Batchable<sObject>,Schedulable {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        Date today = System.today();
        
        return Database.getQueryLocator([
            SELECT  Id, Name, IsActive__c, Start_Date__c, End_Date__c
            FROM Campaign__c
            WHERE Start_Date__c <= :today AND (End_Date__c = NULL OR End_Date__c >= today)
        ]);
    }
    
    public void execute(Database.BatchableContext bc, List<Campaign__c> scope) {
        List<Campaign_Performance__c> cpList = new List<Campaign_Performance__c>();
        
        for (Campaign__c campaign : scope) {
            Campaign_Performance__c cp = new Campaign_Performance__c();
            cp.Campaign__c = campaign.Id;
            cp.Date__c = System.today();
            cpList.add(cp);
        }
        
        if (!cpList.isEmpty()) {
            insert cpList;
        }
    }
    public void execute(SchedulableContext sc) {
        Ex_CampaignBatchClass batch = new Ex_CampaignBatchClass();
        Database.executeBatch(batch, 200); 
        
        // Schedule the batch to run daily at 12 PM
        //System.schedule('CampaignBatchClass Job', '0 12 0  * * ?', batch);
    }
    
    public void finish(Database.BatchableContext bc) {
        
    }
    
}