force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Is_CTI_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Is_CTI_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is CTI Campaign?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>IF( ISPICKVAL( Approver_Status__c , &apos;Approved&apos;) , AND((Start_Date__c &lt;= TODAY()), OR((TODAY()&lt;= End_Date__c),isblank (End_Date__c))) ,false )</formula>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Virtual_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Number__c</fullName>
    <label>Virtual Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/CP_Project__c.object-meta.xml
<CustomObject>
    <label>CP Project</label>
    <nameField>
        <displayFormat>CPP-{00000}</displayFormat>
        <label>CP Project No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria.
Please choose different CP Project</errorMessage>
        <filterItems>
            <field>CP_Project__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</description>
    <inlineHelpText>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</inlineHelpText>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Leads (Opportunity)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Virtual_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Number__c</fullName>
    <label>Virtual Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Ola_Pickup__c/Ola_Pickup__c.object-meta.xml
<CustomObject>
    <label>Ola Pickup</label>
    <nameField>
        <displayFormat>Ola-{00000}</displayFormat>
        <label>Ola Pickup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ola Pickups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ola_Pickup__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Ola Pickups</relationshipLabel>
    <relationshipName>Ola_Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ola_Pickup__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Ola Pickups</relationshipLabel>
    <relationshipName>Ola_Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria.
Please select different CP Project</errorMessage>
        <filterItems>
            <field>CP_Project__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <formula>IF(ISPICKVAL(Stage__c , &quot;In Follow-up&quot;), True,  False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>Account__r.PersonContact.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Google</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregators</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Television</fullName>
    </customValue>
    <customValue>
        <fullName>Hoarding</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp</fullName>
    </customValue>
    <customValue>
        <fullName>Events</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Reference</fullName>
    </customValue>
    <customValue>
        <fullName>VDNB</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Calling</fullName>
    </customValue>
    <customValue>
        <fullName>Start Connect</fullName>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_ScreenPopupCallController.cls
public class Ex_ScreenPopupCallController {
        public String mobileNo {get;set;}
        public String callerId {get;set;}
        public String uui{get;set;}
        
        public Ex_ScreenPopupCallController() {
            
            Map<String, String> mapT = ApexPages.currentPage().getParameters();
            for(String key: mapT.keySet()) {
                System.debug('key: '+key+' value: '+mapT.get(key));
            }
            if(ApexPages.currentPage().getParameters().containsKey('phone'))  {     
                mobileNo = ApexPages.currentPage().getParameters().get('phone'); 
            }
            system.debug('mobileNo: '+mobileNo);
            if(ApexPages.currentPage().getParameters().containsKey('did'))  {     
                callerId = ApexPages.currentPage().getParameters().get('did'); 
            }
            system.debug('callerId: '+callerId);
            if(ApexPages.currentPage().getParameters().containsKey('uui'))  {     
                uui = ApexPages.currentPage().getParameters().get('uui'); 
            }
            system.debug('uui: '+uui);
        }
        
        public pageReference screenPop() {
            pageReference pRef;
            String projectId = null;
            List<Campaign__c> cList = new List<Campaign__c>();
            List<Lead__c> leadList = new List<Lead__c>();
            List<Opportunity__c> oppList = new List<Opportunity__c>();
            List<CP_Project__c> cpProjectList = new List<CP_Project__c>();
            List<Ola_Pickup__c> olaList = new List<Ola_Pickup__c>();
            
            
            if(String.isNotBlank(callerId) && callerId != null) {
                cList = [Select Id, Virtual_Number__c, Source__c, Project__c from Campaign__c
                         where IsActive__c = true AND Is_CTI_Campaign__c = true AND Virtual_Number__c =: callerId];
                system.debug('cList: '+cList);
                
                if(!cList.isEmpty() && cList != null) {
                    projectId = cList[0].Project__c;
                }
            }
            if(String.isNotBlank(uui) && uui != null) {
                oppList = [Select Id, Mobile__c, Phone__c  from Opportunity__c where id =: uui];
                System.debug('oppList: '+oppList);
                
                if(!oppList.isEmpty() && oppList != null) {
                    pRef = new PageReference('/' + oppList[0].Id);
                } else {
                    leadList = [Select Id, First_Name__c, Last_Name__c, Mobile__c,Phone__c from Lead__c where id =: uui];
                    system.debug('leadList: '+leadList); 
                    
                    if(!leadList.isEmpty() && leadList != null) {
                        pRef = new PageReference('/' + leadList[0].Id);
                    } else{
                        cpProjectList = [Select Id, Name, OwnerId from CP_Project__c where Id =: uui];
                        system.debug('cpProjectList: '+cpProjectList);
                        if(!cpProjectList.isEmpty() && cpProjectList != null){
                            pRef = new PageReference('/' + cpProjectList[0].Id);
                        }else{
                            olaList = [Select Id, Name, OwnerId from Ola_Pickup__c where Id =: uui];
                            system.debug('olaList: '+olaList);
                            if(!olaList.isEmpty() && olaList != null){
                                pRef = new PageReference('/' + olaList[0].Id);
                            }
                        }
                    } 
                }
            }else{
                if(String.isNotBlank(mobileNo) && mobileNo != ''){
                    if(mobileNo.length() > 10) {
                        mobileNo = mobileNo.substring(mobileNo.length()-10);
                    }
                    oppList = [Select Id, Mobile__c, Phone__c  from Opportunity__c where (Mobile__c =: mobileNo OR Phone__c =: mobileNo) AND Is_Active__c = true AND Project__c =: projectId ];
                    System.debug('oppList: '+oppList);
                    
                    if(!oppList.isEmpty() && oppList != null) {
                        pRef = new PageReference('/' + oppList[0].Id);
                    } else {
                        leadList = [Select Id, First_Name__c, Last_Name__c, Mobile__c,Phone__c from Lead__c where (Mobile__c =: mobileNo OR Phone__c =: mobileNo) AND IsConverted__c = false AND Project__c =: projectId ];
                        system.debug('leadList: '+leadList); 
                        
                        if(!leadList.isEmpty() && leadList != null) {
                            pRef = new PageReference('/' + leadList[0].Id);
                        }
                        
                    }
                }
            }
            return pRef;
        }
    }