force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Approver_Status__c.field-meta.xml
<CustomField>
    <fullName>Approver_Status__c</fullName>
    <label>Approver Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending For Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Is_CTI_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Is_CTI_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is CTI Campaign?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Aggregators</fullName>
            </value>
            <value>
                <fullName>Organic</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Television</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>VDNB</fullName>
            </value>
            <value>
                <fullName>Cold Calling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Lead_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Source__c</fullName>
    <label>Lead Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Google Search</fullName>
            </value>
            <value>
                <fullName>Google Display</fullName>
            </value>
            <value>
                <fullName>YouTube</fullName>
            </value>
            <value>
                <fullName>Discovery Ads</fullName>
            </value>
            <value>
                <fullName>Lead Gen Form</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>Web Conversion</fullName>
            </value>
            <value>
                <fullName>MagicBricks</fullName>
            </value>
            <value>
                <fullName>NoBroker</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>99Acres</fullName>
            </value>
            <value>
                <fullName>Corporate Website</fullName>
            </value>
            <value>
                <fullName>ORM</fullName>
            </value>
            <value>
                <fullName>Jacket</fullName>
            </value>
            <value>
                <fullName>Power Jacket</fullName>
            </value>
            <value>
                <fullName>Full Page</fullName>
            </value>
            <value>
                <fullName>Half Page</fullName>
            </value>
            <value>
                <fullName>Inserts</fullName>
            </value>
            <value>
                <fullName>RJ Mentions</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Show Sponsorship</fullName>
            </value>
            <value>
                <fullName>Advertisement</fullName>
            </value>
            <value>
                <fullName>Billboard</fullName>
            </value>
            <value>
                <fullName>Bus Shelter</fullName>
            </value>
            <value>
                <fullName>Kiosk</fullName>
            </value>
            <value>
                <fullName>Cantilever</fullName>
            </value>
            <value>
                <fullName>Gantry</fullName>
            </value>
            <value>
                <fullName>Mobile Van</fullName>
            </value>
            <value>
                <fullName>Bus Panel</fullName>
            </value>
            <value>
                <fullName>Railway Station Boards</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Offline_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Offline_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>It is used In case of Mobile User</inlineHelpText>
    <label>Offline Campaign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Ozontel_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Ozontel_Campaign_Name__c</fullName>
    <inlineHelpText>It is used for CTI Campaign for Ozontel</inlineHelpText>
    <label>Ozontel Campaign Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Virtual_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Number__c</fullName>
    <label>Virtual Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestEx_RESTCTIAgentServices.cls
@isTest
public class TestEx_RESTCTIAgentServices {
    @isTest
    public static void getFreshLeadAgentId() {
        Project__c p = new Project__c();
        p.Name = 'Test Project';
        insert p;
        
        Campaign__c c = new Campaign__c();
        c.Name = 'Test CTI Campaign';
        c.Start_Date__c = system.today();
        c.Is_CTI_Campaign__c = true;
        c.Offline_Campaign__c = true;
        c.Ozontel_Campaign_Name__c = 'CTI Campaign';
        c.Virtual_Number__c = '1234';
        c.Project__c = p.Id;
        c.Lead_Source__c = 'Hoarding';
        c.Lead_Sub_Source__c = 'Billboard';
        c.Source__c = 'Bus Stand';
        c.Approver_Status__c = 'Approved';
        insert c;
        
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.httpMethod = 'POST';
        String json = '{"mobileNo":"1234567890", "did":"1234"}';
        req.requestBody = Blob.valueOf(json);
        RestContext.request = req;
        RestContext.response = res;
      
        Test.startTest();   
            Ex_RESTCTIAgentServices.getAgentId('01234567890', '1234');
        Test.stopTest();
    }
}