force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(AND(NOT(ISBLANK(End_Date__c)), End_Date__c &gt;= TODAY(), Start_Date__c &lt;= TODAY(), Text(Approval_Status__c) = &quot;Approved&quot;), true,
IF(AND(ISBLANK(End_Date__c), Start_Date__c &lt;= TODAY(), Text(Approval_Status__c) = &quot;Approved&quot;), true, false))</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CampaignTriggerHandler.cls
//-------------------------------------------//
//  Project: Nandi Vardhan Constructioin 
//  Created By: Exceller Consultancy
//  Created Date: 17-5-2023
//-------------------------------------------//
public class CampaignTriggerHandler {
	public static void afterUpdate(Map<Id, Campaign__c> oldMap, Map<Id, Campaign__c> newMap) {
        Set<Id> cIdSet = new Set<Id>();
        
         for(Campaign__c oldCamp: oldMap.values()) {
            Campaign__c newCamp = newMap.get(oldCamp.Id);
            
            if(oldCamp.Active__c != newCamp.Active__c && newCamp.Active__c == true)
                cIdSet.add(newCamp.Id);
        }
       
        if(!cIdSet.isEmpty() && cIdSet != null)
           CampaignHandlerServices.createCampaignPerformance(cIdSet);
    }
}