force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(AND(NOT(ISBLANK(End_Date__c)), End_Date__c &gt;= TODAY(), Start_Date__c &lt;= TODAY(), Text(Approval_Status__c) = &quot;Approved&quot;), true,
IF(AND(ISBLANK(End_Date__c), Start_Date__c &lt;= TODAY(), Text(Approval_Status__c) = &quot;Approved&quot;), true, false))</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Aggregators</fullName>
            </value>
            <value>
                <fullName>Organic</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Television</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>VDNB</fullName>
            </value>
            <value>
                <fullName>Cold Calling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Digital_Lead__c/Digital_Lead__c.object-meta.xml
<CustomObject>
    <label>Digital Lead</label>
    <nameField>
        <displayFormat>DL-{000000}</displayFormat>
        <label>Digital Lead Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Digital_Lead__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Digital Leads</relationshipLabel>
    <relationshipName>Digital_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Digital_Lead__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <label>Alternate Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Digital_Lead__c/fields/Executed__c.field-meta.xml
<CustomField>
    <fullName>Executed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Executed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Digital_Lead__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Digital Leads</relationshipLabel>
    <relationshipName>Digital_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Digital_Lead__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity_c</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Digital Leads</relationshipLabel>
    <relationshipName>Digital_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Digital_Lead__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Digital_Lead__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New Lead</fullName>
            </value>
            <value>
                <fullName>New Enquiry Against Lead</fullName>
            </value>
            <value>
                <fullName>New Enquiry Against Account</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>New Enquiry Against Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account)</relationshipLabel>
    <relationshipName>Leads2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>AName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Leads (Opportunity)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <formula>Account__r.Alternate_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile__c</fullName>
    <formula>Account__r.PersonContact.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Code__c</fullName>
    <label>Campaign Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account__r.PersonContact.Email</formula>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>Account__r.PersonContact.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>NameA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Google</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregators</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Television</fullName>
    </customValue>
    <customValue>
        <fullName>Hoarding</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp</fullName>
    </customValue>
    <customValue>
        <fullName>Events</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Reference</fullName>
    </customValue>
    <customValue>
        <fullName>VDNB</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Calling</fullName>
    </customValue>
    <customValue>
        <fullName>Start Connect</fullName>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_DigitalLeadHandlerServices.cls
//-------------------------------------------//
//  Project: Avant Infra 
//  Created By: Exceller Tech
//  Created Date: 05-09-2024
//  Author: Sarjerao Deshmukh
//-------------------------------------------//
public class Ex_DigitalLeadHandlerServices {
    public static void leadProcess(Set<Id> dLeadId) {
        List<Opportunity__c> oppList = New List<Opportunity__c>();
        String mobile = '';
        String altMobile = '';
        String details = '';
        
        List<Digital_Lead__c> dLeadList = [Select Id, Name, First_Name__c, Last_Name__c, Mobile__c, Alternate_Mobile__c, Email__c, Alternate_Email__c,
                                           Campaign_Code__c, Location__c, Company_Name__c,
                                           Platform__c, Executed__c, Result__c, Lead__c, Account__c, Opportunity__c
                                           from Digital_Lead__c
                                           where Id IN: dLeadId];
        system.debug('dLeadList: '+dLeadList);
        
        if(!dLeadList.isEmpty() && dLeadList.size() == 1) {
            List<Lead__c> leadList = new List<Lead__c>();
            List<Digital_Lead__c> updateDigitalLeadList = new List<Digital_Lead__c>();
            
            mobile = dLeadList[0].Mobile__c;
            system.debug('Before Substring Mobile: '+mobile);
            if(mobile.length() > 10) {
                mobile = mobile.substring(mobile.length() - 10);
            }
            system.debug('After Substring Mobile: '+mobile);
            
            if(dLeadList[0].Alternate_Mobile__c != null) {
                altmobile = dLeadList[0].Alternate_Mobile__c;
                system.debug('Before Substring Mobile: '+altmobile);
                if(altmobile.length() > 10) {
                    altmobile = altmobile.substring(altmobile.length() - 10);
                }
                system.debug('After Substring Mobile: '+altmobile);
            }
            
            if(dLeadList[0].Platform__c.equalsIgnoreCase('Website')) {
                details = 'First Name: '+dLeadList[0].First_Name__c+ '\n'
                    +'Last Name: '+dLeadList[0].Last_Name__c+ '\n'
                    +'Mobile No: '+dLeadList[0].Mobile__c+ '\n'
                    +'Email Id: '+dLeadList[0].Email__c+ '\n'
                    +'Campaign Code: '+dLeadList[0].Campaign_Code__c+ '\n'
                    +'Location: '+dLeadList[0].Location__c+ '\n'
                    +'Company Name: '+dLeadList[0].Company_Name__c+ '\n'
                    +'Platform:'+dLeadList[0].Platform__c;
            }
            
            String projectId;
            String campaignId;
            String source;
            String subSource;
            String sourceDescription;
            
            if(dLeadList[0].Campaign_Code__c != Null && !String.isEmpty(dLeadList[0].Campaign_Code__c)) {
                List<Campaign__c> cList = [Select Id, Campaign_Code__c, Active__c, Project__c, Lead_Source__c, Lead_Sub_Source__c, Source_Description__c from Campaign__c
                                           where Campaign_Code__c =: dLeadList[0].Campaign_Code__c AND Active__c =: true];
                system.debug('cList: '+cList);
                
                if(cList != null) {
                    projectId = cList[0].Project__c;
                    campaignId = cList[0].Id;
                    source = cList[0].Lead_Source__c;
                    subSource = cList[0].Lead_Sub_Source__c;
                    sourceDescription = cList[0].Source_Description__c;
                }
            }
            
            Lead__c l = new Lead__c();
            l.First_Name__c = dLeadList[0].First_Name__c;
            l.Last_Name__c = dLeadList[0].Last_Name__c;
            l.Mobile__c = mobile;
            l.Alternate_Mobile__c = altMobile;
            l.Email__c = dLeadList[0].Email__c;
            l.Alternate_Email__c = dLeadList[0].Alternate_Email__c;
            l.Company_Name__c = dLeadList[0].Company_Name__c;
            l.Location__c = dLeadList[0].Location__c;
            l.Lead_Identifier__c = dLeadList[0].Platform__c;
            l.Project__c = projectId;
            l.Campaign_Code__c = dLeadList[0].Campaign_Code__c;
            l.Campaign__c = campaignId;
            l.Lead_Source__c = source;
            l.Lead_Sub_Source__c = subSource;
            l.Source_Description__c = sourceDescription;
            l.Remarks__c = details;
            l.Apply_Round_Robin__c = true;
            l.Is_Serviced__c = false;   
            
            if(l != null){  
                Database.DMLOptions dml = new Database.DMLOptions();
                dml.DuplicateRuleHeader.AllowSave = true;
                leadList.add(l);
                system.debug('leadList: '+leadList);   
                
                try {
                    Map<Lead__c, List<Ex_DuplicationHandlerServices.duplicateWrapper>> duplicateWrapperMap = new Map<Lead__c, List<Ex_DuplicationHandlerServices.duplicateWrapper>>();
                    duplicateWrapperMap = Ex_DuplicationHandlerServices.duplicationCheck(leadList);
                    
                    for(Lead__c newLead: leadList) {
                        if(!duplicateWrapperMap.containsKey(l)) {
                            try {
                                Database.saveResult[] srList = Database.insert(leadList,dml);
                                for(Database.SaveResult sr: srList) {
                                    if(sr.isSuccess()) {
                                        try {
                                            task t = new task();
                                            t.Status = 'Completed';
                                            t.RecordTypeId =  Schema.SObjectType.Task.getRecordTypeInfosByName().get('Enquiry').getRecordTypeId();
                                            t.Subject = 'New Enquiry Received From: '+ newLead.Lead_Source__c;
                                            t.WhatId = sr.getId();
                                            
                                            List<Lead__c> newLeadList = [Select Id, Name, OwnerId from Lead__c where Id =: sr.getId()];
                                            system.debug('newLeadList: '+newLeadList);
                                            
                                            if(!newLeadList.isEmpty()) {
                                                t.OwnerId = newLeadList[0].OwnerId;
                                            }
                                            if(String.isNotBlank(newLead.First_Name__c))
                                                t.Name__c = newLead.First_Name__c + ' ';
                                            if(String.isNotBlank(newLead.Last_Name__c))
                                                t.Name__c += newLead.Last_Name__c;
                                            if(String.isNotBlank(newLead.Mobile__c))
                                                t.Mobile__c = newLead.Mobile__c;
                                            if(String.isNotBlank(newLead.Alternate_Mobile__c))
                                                t.Mobile__c = newLead.Alternate_Mobile__c;
                                            if(String.isNotBlank(newLead.Email__c))
                                                t.Email__c = newLead.Email__c;
                                            if(String.isNotBlank(newLead.Alternate_Email__c))
                                                t.Alternate_Email__c = newLead.Alternate_Email__c;
                                            if(newLead.Project__c != null)
                                                t.Project__c = newLead.Project__c;
                                            if(newLead.Campaign__c != null)
                                                t.Campaign__c = newLead.Campaign__c;
                                            if(String.isNotBlank(newLead.Campaign_Code__c))
                                                t.Campaign_Code__c = newLead.Campaign_Code__c;
                                            if(String.isNotBlank(newLead.Location__c))
                                                t.Location__c = newLead.Location__c;
                                            if(String.isNotBlank(newLead.Company_Name__c))
                                                t.Company_Name__c = newLead.Company_Name__c;
                                            if(String.isNotBlank(newLead.Remarks__c))
                                                t.Description = newLead.Remarks__c;
                                            if(String.isNotBlank(newLead.Lead_Identifier__c))
                                                t.Task_Identifier__c = newLead.Lead_Identifier__c;
                                            t.Is_New_Lead_Created__c = true;
                                            insert t;
                                            
                                            //Update Digital Lead
                                            dLeadList[0].Executed__c = True;
                                            dLeadList[0].Result__c = 'New Lead';
                                            dLeadList[0].Lead__c = leadList[0].Id;
                                            update dLeadList[0];
                                        } catch(Exception ex) {
                                            system.debug('Error: '+ex);
                                            //Update Digital Lead
                                            dLeadList[0].Executed__c = True;
                                            dLeadList[0].Result__c = 'Error';
                                            dLeadList[0].Error__c = ex.getMessage();
                                            update dLeadList[0];
                                        }
                                    } else {
                                        String msg = '';
                                        for(Database.Error err: sr.getErrors()) {
                                            msg = 'Lead Creation Failed: ' + err.getMessage();
                                        }
                                        system.debug('Error: '+msg);
                                        //Update Digital Lead
                                        dLeadList[0].Executed__c = True;
                                        dLeadList[0].Result__c = 'Error';
                                        dLeadList[0].Error__c = msg;
                                        update dLeadList[0];
                                    }
                                }
                            } catch(Exception ex) {
                                system.debug('Error: '+ex);
                                //Update Digital Lead
                                dLeadList[0].Executed__c = True;
                                dLeadList[0].Result__c = 'Error';
                                dLeadList[0].Error__c = ex.getMessage();
                                update dLeadList[0];
                            }
                        } else {
                            Ex_DuplicationHandlerServices.duplicateWrapper dw = duplicateWrapperMap.get(newLead)[0];
                            if(dw.objectType.equalsIgnoreCase('Lead')) {
                                try {
                                    task t = new task();
                                    t.Status = 'Completed';
                                    t.RecordTypeId =  Schema.SObjectType.Task.getRecordTypeInfosByName().get('Enquiry').getRecordTypeId();
                                    t.Subject = 'New Enquiry Received From: '+ newLead.Lead_Source__c;
                                    t.WhatId = dw.dupLead.Id;
                                    t.OwnerId = dw.dupLead.OwnerId;
                                    
                                    if(String.isNotBlank(newLead.First_Name__c))
                                        t.Name__c = newLead.First_Name__c + ' ';
                                    if(String.isNotBlank(newLead.Last_Name__c))
                                        t.Name__c += newLead.Last_Name__c;
                                    if(String.isNotBlank(newLead.Mobile__c))
                                        t.Mobile__c = newLead.Mobile__c;
                                    if(String.isNotBlank(newLead.Alternate_Mobile__c))
                                        t.Mobile__c = newLead.Alternate_Mobile__c;
                                    if(String.isNotBlank(newLead.Email__c))
                                        t.Email__c = newLead.Email__c;
                                    if(String.isNotBlank(newLead.Alternate_Email__c))
                                        t.Alternate_Email__c = newLead.Alternate_Email__c;
                                    if(newLead.Project__c != null)
                                        t.Project__c = newLead.Project__c;
                                    if(newLead.Campaign__c != null)
                                        t.Campaign__c = newLead.Campaign__c;
                                    if(String.isNotBlank(newLead.Campaign_Code__c))
                                        t.Campaign_Code__c = newLead.Campaign_Code__c;
                                    if(String.isNotBlank(newLead.Location__c))
                                        t.Location__c = newLead.Location__c;
                                    if(String.isNotBlank(newLead.Company_Name__c))
                                        t.Company_Name__c = newLead.Company_Name__c;
                                    if(String.isNotBlank(newLead.Remarks__c))
                                        t.Description = newLead.Remarks__c;
                                    if(String.isNotBlank(newLead.Lead_Identifier__c))
                                        t.Task_Identifier__c = newLead.Lead_Identifier__c;
                                    insert t;
                                    
                                    //Update Digital Lead
                                    dLeadList[0].Executed__c = True;
                                    dLeadList[0].Result__c = 'New Enquiry Against Lead';
                                    dLeadList[0].Lead__c = dw.dupLead.Id;
                                    update dLeadList[0];
                                } catch(Exception ex) {
                                    system.debug('Error: '+ex);
                                    //Update Digital Lead
                                    dLeadList[0].Executed__c = True;
                                    dLeadList[0].Result__c = 'Error';
                                    dLeadList[0].Error__c = ex.getMessage();
                                    update dLeadList[0];
                                }
                            } else if(dw.objectType.equalsIgnoreCase('Account')) {
                                oppList = [Select Id, Name, Is_Active__c, Account__c, Account__r.PersonContactId, OwnerId from Opportunity__c 
                                           Where Project__c =: newLead.Project__c AND Account__c =: dw.dupAccount.Id AND Is_Active__c = true];
                                
                                try {
                                    task t = new task();
                                    t.Status = 'Completed';
                                    t.RecordTypeId =  Schema.SObjectType.Task.getRecordTypeInfosByName().get('Enquiry').getRecordTypeId();
                                    t.Subject = 'New Enquiry Received From: '+ newLead.Lead_Source__c;
                                    if(!oppList.isEmpty() && oppList != null) {
                                        t.WhatId = oppList[0].Id;
                                        t.WhoId = oppList[0].Account__r.PersonContactId;
                                        t.OwnerId = oppList[0].OwnerId;
                                    } else {
                                        t.WhoId = dw.dupAccount.PersonContactId;
                                        t.OwnerId = dw.dupAccount.OwnerId;
                                    }
                                    
                                    if(String.isNotBlank(newLead.First_Name__c))
                                        t.Name__c = newLead.First_Name__c + ' ';
                                    if(String.isNotBlank(newLead.Last_Name__c))
                                        t.Name__c += newLead.Last_Name__c;
                                    if(String.isNotBlank(newLead.Mobile__c))
                                        t.Mobile__c = newLead.Mobile__c;
                                    if(String.isNotBlank(newLead.Alternate_Mobile__c))
                                        t.Mobile__c = newLead.Alternate_Mobile__c;
                                    if(String.isNotBlank(newLead.Email__c))
                                        t.Email__c = newLead.Email__c;
                                    if(String.isNotBlank(newLead.Alternate_Email__c))
                                        t.Alternate_Email__c = newLead.Alternate_Email__c;
                                    if(newLead.Project__c != null)
                                        t.Project__c = newLead.Project__c;
                                    if(newLead.Campaign__c != null)
                                        t.Campaign__c = newLead.Campaign__c;
                                    if(String.isNotBlank(newLead.Campaign_Code__c))
                                        t.Campaign_Code__c = newLead.Campaign_Code__c;
                                    if(String.isNotBlank(newLead.Location__c))
                                        t.Location__c = newLead.Location__c;
                                    if(String.isNotBlank(newLead.Company_Name__c))
                                        t.Company_Name__c = newLead.Company_Name__c;
                                    if(String.isNotBlank(newLead.Remarks__c))
                                        t.Description = newLead.Remarks__c;
                                    if(String.isNotBlank(newLead.Lead_Identifier__c))
                                        t.Task_Identifier__c = newLead.Lead_Identifier__c;
                                    insert t;
                                    
                                    //Update Digital Lead
                                    dLeadList[0].Executed__c = True;
                                    if(!oppList.isEmpty() && oppList != null) {
                                        dLeadList[0].Account__c = oppList[0].Account__c;
                                        dLeadList[0].Opportunity__c = oppList[0].Id;
                                        dLeadList[0].Result__c = 'New Enquiry Against Opportunity';
                                    } else {
                                        dLeadList[0].Account__c = dw.dupAccount.Id;
                                        dLeadList[0].Result__c = 'New Enquiry Against Account';
                                    }
                                    update dLeadList[0];
                                } catch(Exception ex) {
                                    system.debug('Error: '+ex);
                                    //Update Digital Lead
                                    dLeadList[0].Executed__c = True;
                                    dLeadList[0].Result__c = 'Error';
                                    dLeadList[0].Error__c = ex.getMessage();
                                    update dLeadList[0];
                                }
                            }
                        }
                    }
                } catch(Exception ex) {
                    system.debug('Error: '+ex);
                    //Update Digital Lead
                    dLeadList[0].Executed__c = True;
                    dLeadList[0].Result__c = 'Error';
                    dLeadList[0].Error__c = ex.getMessage();
                    update dLeadList[0];
                }
            } 
        }
    }
}