force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(AND(NOT(ISBLANK(End_Date__c)), End_Date__c &gt;= TODAY(), Start_Date__c &lt;= TODAY(), Text(Approval_Status__c) = &quot;Approved&quot;), true,
IF(AND(ISBLANK(End_Date__c), Start_Date__c &lt;= TODAY(), Text(Approval_Status__c) = &quot;Approved&quot;), true, false))</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Is_CTI_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Is_CTI_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is CTI Campaign?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Aggregators</fullName>
            </value>
            <value>
                <fullName>Organic</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Television</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>VDNB</fullName>
            </value>
            <value>
                <fullName>Cold Calling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Lead_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Source__c</fullName>
    <label>Lead Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Google Search</fullName>
            </value>
            <value>
                <fullName>Google Display</fullName>
            </value>
            <value>
                <fullName>YouTube</fullName>
            </value>
            <value>
                <fullName>Discovery Ads</fullName>
            </value>
            <value>
                <fullName>Lead Gen Form</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>Web Conversion</fullName>
            </value>
            <value>
                <fullName>MagicBricks</fullName>
            </value>
            <value>
                <fullName>NoBroker</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>99Acres</fullName>
            </value>
            <value>
                <fullName>Corporate Website</fullName>
            </value>
            <value>
                <fullName>ORM</fullName>
            </value>
            <value>
                <fullName>Jacket</fullName>
            </value>
            <value>
                <fullName>Power Jacket</fullName>
            </value>
            <value>
                <fullName>Full Page</fullName>
            </value>
            <value>
                <fullName>Half Page</fullName>
            </value>
            <value>
                <fullName>Inserts</fullName>
            </value>
            <value>
                <fullName>RJ Mentions</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Show Sponsorship</fullName>
            </value>
            <value>
                <fullName>Advertisement</fullName>
            </value>
            <value>
                <fullName>Billboard</fullName>
            </value>
            <value>
                <fullName>Bus Shelter</fullName>
            </value>
            <value>
                <fullName>Kiosk</fullName>
            </value>
            <value>
                <fullName>Cantilever</fullName>
            </value>
            <value>
                <fullName>Gantry</fullName>
            </value>
            <value>
                <fullName>Mobile Van</fullName>
            </value>
            <value>
                <fullName>Bus Panel</fullName>
            </value>
            <value>
                <fullName>Railway Station Boards</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Source_Description__c.field-meta.xml
<CustomField>
    <fullName>Source_Description__c</fullName>
    <label>Source Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Virtual_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Number__c</fullName>
    <label>Virtual Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Apply_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Apply_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field to assign the Lead to a member of the Presales Team. The assignment occurs only if the Presales Team is maintained on the Project and has active team members, designating one as the Lead owner using the Round Robin method.</description>
    <inlineHelpText>This field to assign the Lead to a member of the Presales Team. The assignment occurs only if the Presales Team is maintained on the Project and has active team members, designating one as the Lead owner using the Round Robin method.</inlineHelpText>
    <label>Apply Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</description>
    <inlineHelpText>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</inlineHelpText>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Created_From__c.field-meta.xml
<CustomField>
    <fullName>Lead_Created_From__c</fullName>
    <label>Lead Created From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facebook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Source__c</fullName>
    <label>Lead Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lead_Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Source_Description__c.field-meta.xml
<CustomField>
    <fullName>Source_Description__c</fullName>
    <label>Source Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Virtual_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Number__c</fullName>
    <label>Virtual Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Google</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregators</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Television</fullName>
    </customValue>
    <customValue>
        <fullName>Hoarding</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp</fullName>
    </customValue>
    <customValue>
        <fullName>Events</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Reference</fullName>
    </customValue>
    <customValue>
        <fullName>VDNB</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Calling</fullName>
    </customValue>
    <customValue>
        <fullName>Start Connect</fullName>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lead_Sub_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Google Search</fullName>
    </customValue>
    <customValue>
        <fullName>Google Display</fullName>
    </customValue>
    <customValue>
        <fullName>YouTube</fullName>
    </customValue>
    <customValue>
        <fullName>Discovery Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Gen Form</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Web Conversion</fullName>
    </customValue>
    <customValue>
        <fullName>MagicBricks</fullName>
    </customValue>
    <customValue>
        <fullName>NoBroker</fullName>
    </customValue>
    <customValue>
        <fullName>Housing</fullName>
    </customValue>
    <customValue>
        <fullName>99Acres</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Website</fullName>
    </customValue>
    <customValue>
        <fullName>ORM</fullName>
    </customValue>
    <customValue>
        <fullName>Jacket</fullName>
    </customValue>
    <customValue>
        <fullName>Power Jacket</fullName>
    </customValue>
    <customValue>
        <fullName>Full Page</fullName>
    </customValue>
    <customValue>
        <fullName>Half Page</fullName>
    </customValue>
    <customValue>
        <fullName>Inserts</fullName>
    </customValue>
    <customValue>
        <fullName>RJ Mentions</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Advertisement</fullName>
    </customValue>
    <customValue>
        <fullName>Show Sponsorship</fullName>
    </customValue>
    <customValue>
        <fullName>Billboard</fullName>
    </customValue>
    <customValue>
        <fullName>Bus Shelter</fullName>
    </customValue>
    <customValue>
        <fullName>Kiosk</fullName>
    </customValue>
    <customValue>
        <fullName>Cantilever</fullName>
    </customValue>
    <customValue>
        <fullName>Gantry</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Van</fullName>
    </customValue>
    <customValue>
        <fullName>Bus Panel</fullName>
    </customValue>
    <customValue>
        <fullName>Railway Station Boards</fullName>
    </customValue>
    <masterLabel>Lead Sub Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_RESTCTIAgentServices.cls
//-------------------------------------------//
//  Project: Avant Infra 
//  Created By: Exceller Tech
//  Created Date: 12-09-2024
//  Author: Sarjerao
//-------------------------------------------//
@RestResource(urlMapping='/CTI/routeCall/')
global class Ex_RESTCTIAgentServices {
    @HttpPOST
    global static Rest_result getAgentId() {
        Rest_result r = new Rest_result();
        String campaignId;
        String fromnumber;
        String landingnumber;
        String IVRSelection;
        String campaignCode;
        String campaignSource;
        String campaignLeadSource;
        String campaignLeadSubSource;
        String SourceDescription;
        String projectId;
        String virtualNumber;
        String mcubeURL = '';
        Boolean isOffline = false;
        List<Campaign__c> cList = new List<Campaign__c>();
        List<Account> accList = new List<Account>();
        List<Lead__c> leadList = new List<Lead__c>();
        List<User> userList = new List<User>();
        
        Id ownerId = null;
        
        fromnumber = RestContext.request.params.get('fromnumber');
        landingnumber = RestContext.request.params.get('landingnumber');
        System.debug('fromnumber::::::'+fromnumber);
        System.debug('landingnumber:::::::::'+landingnumber);
        
        if(String.isNotBlank(landingnumber) && landingnumber != null) {            
            
            cList = [Select Id, Virtual_Number__c, Lead_Source__c, Lead_Sub_Source__c, Source_Description__c, Project__c, Campaign_Code__c, Active__c from Campaign__c
                     where Active__c = true AND Is_CTI_Campaign__c = true AND Virtual_Number__c =: landingnumber];
            system.debug('cList: '+cList);
            
            if(!cList.isEmpty() && cList != null) {
                campaignId = cList[0].Id;
                campaignCode = cList[0].Campaign_Code__c;
                campaignSource = cList[0].Lead_Source__c;
                campaignLeadSource = cList[0].Lead_Sub_Source__c;
                SourceDescription = cList[0].Source_Description__c;
                projectId = cList[0].Project__c;
                virtualNumber = cList[0].Virtual_Number__c;
            }
            
            if(String.isNotBlank(fromnumber) && fromnumber != null) {
                if(fromnumber.length() > 10) {
                    fromnumber = fromnumber.substring(fromnumber.length()-10);
                }
                accList = [Select Id, Name, OwnerId from Account where (PersonMobilePhone =: fromnumber OR Phone =: fromnumber) AND RecordType.DeveloperName = 'PersonAccount'];
                System.debug('accList: '+accList);
                if(!accList.isEmpty() && accList != null) {
                    ownerId = accList[0].OwnerId;
                } else {
                    
                    leadList = [Select Id, First_Name__c, Last_Name__c, Mobile__c, Alternate_Mobile__c, OwnerId from Lead__c where ((Mobile__c =:fromnumber  OR Alternate_Mobile__c =:fromnumber))
                                AND IsConverted__c  = false ORDER BY LastModifiedDate DESC];
                    system.debug('leadList: '+leadList);
                    
                    if(!leadList.isEmpty() && leadList != null) {
                        ownerId = leadList[0].OwnerId;
                    } else {
                        Lead__c l = new Lead__c();
                        l.First_Name__c = 'Incoming';
                        l.Last_Name__c = 'Customer';
                        l.Mobile__c = fromnumber;
                        l.Campaign__c = campaignId;
                        l.Campaign_Code__c = campaignCode;
                        l.Project__c = projectId;
                        l.Lead_Created_From__c = 'CTI';
                        l.Apply_Round_Robin__c = true;
                        l.Source_Description__c = SourceDescription;
                        l.Lead_Source__c = campaignSource;
                        l.Lead_Sub_Source__c = campaignLeadSource;
                        try {
                            insert l;
                            List<Lead__c> getList = [Select Id, OwnerId from Lead__c where Id =: l.Id];
                            system.debug('getList: '+getList);
                            
                            if(!getList.isEmpty() && getList != null) {
                                ownerId = getList[0].OwnerId;
                            }
                        } catch(Exception ex) {
                            system.debug('Error: '+ex.getMessage());
                        }
                    }
                }
            }
        }
        
        if(ownerId != null) {
            userList = [Select Id, Agent_Id__c, Agent_Phone__c,MobilePhone from User where Id =: ownerId];
            system.debug('userList: '+userList);
            
            if(!userList.isEmpty() && userList != null) {
                if(userList[0].Agent_Id__c != null && userList[0].Agent_Id__c != '' && userList[0].MobilePhone != null && userList[0].MobilePhone != '') {
                    r.agentId = userList[0].Agent_Id__c;
                    r.agentNo = userList[0].MobilePhone;
                } else {
                    r.agentId = null;
                    r.agentNo = null;
                }
            } else {
                r.agentId = null;
                r.agentNo = null;
            }
        } else {
            r.agentId = null;
            r.agentNo = null;
        }
        return r;
    }
    global class REST_result{
        webservice String AgentId;
        webservice String AgentNo;
    }
}