force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Approver_Status__c.field-meta.xml
<CustomField>
    <fullName>Approver_Status__c</fullName>
    <label>Approver Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending For Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <formula>IF( ISPICKVAL( Approver_Status__c , &apos;Approved&apos;) , AND((Start_Date__c &lt;= TODAY()), OR((TODAY()&lt;= End_Date__c),isblank (End_Date__c))) ,false )</formula>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Ex_CampaignTriggerHandler.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 17-10-2023
//-------------------------------------------//
public class Ex_CampaignTriggerHandler {
    /*public static void afterInsert(List<Campaign__c> campaignList) {
        Set<Id> cIdSet = new Set<Id>();
        
        for(Campaign__c c: campaignList) {
            if(c.IsActive__c == true)
                cIdSet.add(c.Id);
        }
        if(!cIdSet.isEmpty() && cIdSet != null)
            Ex_CampaignHandlerServices.createCampaignPerformance(cIdSet);
    }*/
    
    public static void beforeupdate(Map<Id, Campaign__c> oldMap, Map<Id, Campaign__c> newMap){
        Set<Id> cIdSet = new Set<Id>();
        for(Campaign__c oldCampaign: oldMap.values()) {
            Campaign__c newCampaign = newMap.get(oldCampaign.Id);
            if((oldCampaign.Approver_Status__c != newCampaign.Approver_Status__c ) &&
               newCampaign.Approver_Status__c != null && newCampaign.Approver_Status__c == 'Approved' ){
                   cIdSet.add(newCampaign.Id);
               }
            
        }
        system.debug('cIdSet: '+cIdSet);
        if(!cIdSet.isEmpty() && cIdSet != null)
            Ex_CampaignHandlerServices.createCampaignPerformance(cIdSet);
    }
}