force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Is_Opp_Share__c.field-meta.xml
<CustomField>
    <fullName>Is_Opp_Share__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Opp Share</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Opportunity Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Site_Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Count__c</fullName>
    <label>Site Visit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Sourcing_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sourcing_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sourcing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Sourcing_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sourcing_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sourcing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Opportunity_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Follow-up</fullName>
        <default>true</default>
        <label>In Follow-up</label>
    </customValue>
    <customValue>
        <fullName>Booking In-Process</fullName>
    </customValue>
    <customValue>
        <fullName>Booked</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation In-Process</fullName>
    </customValue>
    <masterLabel>Opportunity Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_OpportunityTriggerHandler.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 27-10-2023
//-------------------------------------------//
public class Ex_OpportunityTriggerHandler {
    public static void beforeInsert(List<Opportunity__c> opportunityList) {
        Ex_OpportunityHandlerServices.duplicationCheck(opportunityList);
    }
    
    public static void beforeUpdate(Map<Id, Opportunity__c> oldMap, Map<Id, Opportunity__c> newMap) {
        List<Opportunity__c> oppList = new List<Opportunity__c>();
        Map<Id, Id> OppSourcingMap = new Map<Id, Id>();
        
        for(Opportunity__c oldOpp: oldMap.values()) {
            Opportunity__c newOpp = newMap.get(oldOpp.Id);
            
            if(oldOpp.Project__c != newOpp.Project__c || oldOpp.Account__c != newOpp.Account__c || oldOpp.Opportunity_Stage__c != newOpp.Opportunity_Stage__c)
                oppList.add(newOpp);
            
            if(oldOpp.Sourcing_Manager__c != newOpp.Sourcing_Manager__c && oldOpp.Sourcing_Manager__c != null) {
                if(OppSourcingMap.containsKey(newOpp.Id)) {
                    OppSourcingMap.get(newOpp.Id);
                } else {
                    OppSourcingMap.put(newOpp.Id, oldOpp.Sourcing_Manager__c);
                }
            }
        }
        if(!OppSourcingMap.isEmpty() && OppSourcingMap != null)
            Ex_OpportunityHandlerServices.removeSharingWithSourcingManager(OppSourcingMap);
        if(!oppList.isEmpty() && oppList != null)
            Ex_OpportunityHandlerServices.duplicationCheck(oppList);
    }
     public static void afterInsert(List<Opportunity__c> oppLst) {
        Set<Id> updateConvertedCount = new  Set<Id>();
        for(Opportunity__c opp: oppLst) {
            if(opp.Campaign__c != null){
                updateConvertedCount.add(opp.Campaign__c);
            }
            if(!updateConvertedCount.isEmpty() && updateConvertedCount != null){
                Ex_CampaignHandlerServices.updateCampaignDetails(updateConvertedCount, 'Opportunity');
            }
        }
     }
    
	public static void afterUpdate(Map<Id, Opportunity__c> oldMap, Map<Id, Opportunity__c> newMap) {
        Set<Id> svCampaignIdSet = new Set<Id>();
        Set<Id> bookingCampaignIdSet = new Set<Id>();
        Set<Id> updateConvertedCount = new  Set<Id>();
        Map<Id, List<Opportunity__c>> OppSourcingMap = new Map<Id, List<Opportunity__c>>();
        Map<Id, List<Opportunity__c>> OppSourcingMapShare = new Map<Id, List<Opportunity__c>>();
        
        
        for(Opportunity__c oldOpp: oldMap.values()) {
            Opportunity__c newOpp = newMap.get(oldOpp.Id);
            
            if(oldOpp.Campaign__c != newOpp.Campaign__c) {
                
                if(newOpp.Site_Visit_Count__c > 0) {
                    svCampaignIdSet.add(newOpp.Campaign__c);
                    svCampaignIdSet.add(oldOpp.Campaign__c);
                }
                if(newOpp.Opportunity_Stage__c != null) {
                    bookingCampaignIdSet.add(newOpp.Campaign__c);
                    bookingCampaignIdSet.add(oldOpp.Campaign__c);
                }
            }
            if(oldOpp.Is_Opp_Share__c != newOpp.Is_Opp_Share__c && newOpp.Is_Opp_Share__c){
                if(OppSourcingMapShare.containsKey(newOpp.Sourcing_Manager__c)) {
                    OppSourcingMapShare.get(newOpp.Sourcing_Manager__c).add(newOpp);
                } else {
                    List<Opportunity__c> newList = new List<Opportunity__c>();
                    newList.add(newOpp);
                    OppSourcingMapShare.put(newOpp.Sourcing_Manager__c, newList);
                }
            }
            
            if(oldOpp.Sourcing_Manager__c != newOpp.Sourcing_Manager__c && newOpp.Sourcing_Manager__c != null){
                if(OppSourcingMap.containsKey(newOpp.Sourcing_Manager__c)) {
                    OppSourcingMap.get(newOpp.Sourcing_Manager__c).add(newOpp);
                } else {
                    List<Opportunity__c> newList = new List<Opportunity__c>();
                    newList.add(newOpp);
                    OppSourcingMap.put(newOpp.Sourcing_Manager__c, newList);
                }
            }
                
            if(oldOpp.Site_Visit_Count__c != newOpp.Site_Visit_Count__c && newOpp.Campaign__c != null)
                svCampaignIdSet.add(newOpp.Campaign__c);
            if(oldOpp.Opportunity_Stage__c != newOpp.Opportunity_Stage__c && newOpp.Campaign__c != null)
                bookingCampaignIdSet.add(newOpp.Campaign__c);
            if(oldOpp.Campaign__c != newOpp.Campaign__c && newOpp.Campaign__c != null)
                updateConvertedCount.add(newOpp.Campaign__c);
                
        }
        if(!OppSourcingMap.isEmpty() && OppSourcingMap != null){
            Ex_OpportunityHandlerServices.shareSiteVisitWithSourcingManager(OppSourcingMap);   
        }
         if(!OppSourcingMapShare.isEmpty() && OppSourcingMapShare != null){
            Ex_OpportunityHandlerServices.shareSiteVisitWithSourcingManager(OppSourcingMapShare);   
        }
        
        if(!svCampaignIdSet.isEmpty() && svCampaignIdSet != null)
            Ex_CampaignHandlerServices.updateCampaignDetails(svCampaignIdSet, 'Site Visit');
        if(!updateConvertedCount.isEmpty() && updateConvertedCount != null)
            Ex_CampaignHandlerServices.updateCampaignDetails(updateConvertedCount, 'Opportunity');
      //  if(!bookingCampaignIdSet.isEmpty() && bookingCampaignIdSet != null)
       //     Ex_CampaignHandlerServices.updateBookingonCampaign(bookingCampaignIdSet, 'Opportunity');
    }

}