force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Enquiry_Count__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Count__c</fullName>
    <label>Enquiry Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Lead_Count__c.field-meta.xml
<CustomField>
    <fullName>Lead_Count__c</fullName>
    <label>Lead Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign_Performance__c/Campaign_Performance__c.object-meta.xml
<CustomObject>
    <label>Campaign Performance</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Campaign Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Performances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Performance__c/fields/Amount_Spend__c.field-meta.xml
<CustomField>
    <fullName>Amount_Spend__c</fullName>
    <label>Amount Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign_Performance__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign_c</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Campaign Performances</relationshipLabel>
    <relationshipName>Campaign_Performances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Performance__c/fields/Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Code__c</fullName>
    <label>Campaign Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign_Performance__c/fields/Enquiry_Count__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Count__c</fullName>
    <label>Enquiry Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign_Performance__c/fields/Lead_Count__c.field-meta.xml
<CustomField>
    <fullName>Lead_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lead Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestEx_CampaignPerformance.cls
@isTest
public class TestEx_CampaignPerformance {
@isTest
     public static void testMethod1(){
         
         List<Campaign__c> campaigns = new List<Campaign__c>();
            Campaign__c camp = new Campaign__c();
                camp.Name = 'Test Campaign ';
                camp.Campaign_Code__c = 'Code';
                camp.Start_Date__c = Date.today();
                camp.End_Date__c = Date.today().addDays(10);
            campaigns.add(camp);
        
        insert campaigns;
         
         List<Campaign_Performance__c> campList=new List<Campaign_Performance__c>();
         Campaign_Performance__c camper=new Campaign_Performance__c();
         camper.Lead_Count__c=1;
         camper.Campaign__c=camp.id;
         camper.Amount_Spend__c=1000;
         camper.Enquiry_Count__c=5;
         campList.add(camper);
         
         insert campList;
         
          List<Campaign_Performance__c> campaignPerformances = [SELECT Id, Campaign__c, Amount_Spend__c, Lead_Count__c, Enquiry_Count__c FROM Campaign_Performance__c];

        // Create old and new maps for the after update trigger context
        Map<Id, Campaign_Performance__c> oldMap = new Map<Id, Campaign_Performance__c>(campaignPerformances);
        
        // Update records with new values
        for (Campaign_Performance__c cp : campaignPerformances) {
            if(cp.Amount_Spend__c != null)
            cp.Amount_Spend__c += 500; 
            if(cp.Lead_Count__c != null)
            cp.Lead_Count__c += 5; 
        }
        update campaignPerformances;
        
        Test.startTest();
        Ex_CampaignPerformanceTriggerHandler.afterUpdate(oldMap, new Map<Id, Campaign_Performance__c>([SELECT Id, Campaign__c, Amount_Spend__c, Lead_Count__c, Enquiry_Count__c FROM Campaign_Performance__c]));
        Test.stopTest();
     }
}