force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Lead__c/CP_Lead__c.object-meta.xml
<CustomObject>
    <label>CP Lead</label>
    <nameField>
        <displayFormat>CPL-{00000}</displayFormat>
        <label>CP Lead No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Lead__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>CP Leads</relationshipLabel>
    <relationshipName>CP_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Leads</relationshipLabel>
    <relationshipName>CP_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <formula>Account__r.Alternate_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/CP_Lead__c.field-meta.xml
<CustomField>
    <fullName>CP_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Lead</label>
    <referenceTo>CP_Lead__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account__r.PersonContact.Email</formula>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>Account__r.PersonContact.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>In Follow-up</fullName>
                <default>true</default>
                <label>In Follow-up</label>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Booking In-Process</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/SV_Count__c.field-meta.xml
<CustomField>
    <fullName>SV_Count__c</fullName>
    <label>SV Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestEx_OpportunityHandlerServices.cls
@isTest
public class TestEx_OpportunityHandlerServices {
    @isTest
    public static void testMethod1(){
        Campaign__c cc = new Campaign__c();
        cc.Name = 'Test Campaign';
        insert cc;
        
        Campaign__c cc1 = new Campaign__c();
        cc1.Name = 'Test Campaign';
        insert cc1;
        
        Project__c proj = new Project__c();
        proj.Name = 'Test Project';
        insert proj;
        
        Account acc = new Account();
        acc.Phone = '1234567890';
        acc.PersonEmail = 'dummy@gmail.com';
        acc.LastName = 'Test';
        //acc.Alternate_Email__c = 'dummy1@gmail.com';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        insert acc;
        
        Opportunity__c opp = new Opportunity__c();
        opp.Name = 'Test Opporunity';
        opp.Campaign__c = cc.Id;
        opp.Account__c = acc.Id;
        opp.Stage__c = 'In Follow-up';
        insert opp;
        opp.Project__c = proj.Id;
        opp.Campaign__c = cc1.Id;
        opp.SV_Count__c = 1;
        update opp;
        
        Opportunity__c opp1 = new Opportunity__c();
        opp1.Name = 'Test Opporunity';
        opp1.Account__c = acc.Id;
        opp1.Stage__c = 'In Follow-up';
        opp1.Project__c = proj.Id;
        insert opp1;
        opp1.Stage__c = 'Booked';
        opp1.Campaign__c = cc1.Id;
        update opp1;
        
        List<Opportunity__c> oppList = [Select Id , Name, Project__c,Account__c From Opportunity__c Where Id =:opp1.id ];
        
        Test.startTest();
       
        Ex_OpportunityHandlerServices.duplicationCheck(oppList);
        Test.stopTest();   
    }
    
    @isTest
    public static void testMethod2(){
        
        Campaign__c cc1 = new Campaign__c();
        cc1.Name = 'Test Campaign';
        insert cc1;
        
        Project__c proj = new Project__c();
        proj.Name = 'Test Project';
        insert proj;
        
        Account account = new Account(
            Phone = '1234567890',
            PersonEmail = 'test@example.com',
            LastName = 'Test Account',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId()
        );
        insert account;

        CP_Lead__c cpLead = new CP_Lead__c(
            First_Name__c = 'Test',
            Last_Name__c = 'CP Lead',
            Mobile__c = '1234567890',
            Email__c = 'cpLead@test.com',
            Project__c = proj.Id
        );
        insert cpLead;
        
        Opportunity__c opp1 = new Opportunity__c();
        opp1.Name = 'Test Opporunity';
        opp1.Account__c = account.Id;
        opp1.Campaign__c = cc1.Id;
        opp1.Stage__c = 'In Follow-up';
        opp1.Project__c = proj.Id;
        opp1.CP_Lead__c = cpLead.Id;
        insert opp1;
        
        Opportunity__c opp2 = new Opportunity__c();
        opp2.Name = 'Test Opporunity';
        opp2.Account__c = account.Id;
        opp2.Campaign__c = cc1.Id;
        opp2.Stage__c = 'In Follow-up';
        opp2.Project__c = proj.Id;
        opp2.CP_Lead__c = cpLead.Id;
        insert opp2;
        
        Task task = new Task(
            Subject = 'CP Lead Call',
            WhatId = cpLead.Id,
            RecordTypeId = Schema.SObjectType.Task.getRecordTypeInfosByName().get('CP Lead Call').getRecordTypeId()
        );
        insert task;
        
        List<Opportunity__c> oppList = [
            SELECT Id, Name, Account__c, Project__c, CP_Lead__c
            FROM Opportunity__c
            WHERE Id IN :new List<Id>{opp1.Id, opp2.Id}
        ];
        
        Test.startTest();
        Ex_OpportunityHandlerServices.updateTaskOnOpp(oppList);
        Test.stopTest();
    }
}