force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Actual_Cost__c.field-meta.xml
<CustomField>
    <fullName>Actual_Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Actual Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Actual_Enquiries__c.field-meta.xml
<CustomField>
    <fullName>Actual_Enquiries__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Actual Enquiries</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Actual_Leads__c.field-meta.xml
<CustomField>
    <fullName>Actual_Leads__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Actual Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Enquiry_Count__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Count__c</fullName>
    <label>Enquiry Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Lead_Count__c.field-meta.xml
<CustomField>
    <fullName>Lead_Count__c</fullName>
    <label>Lead Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign_Performance__c/Campaign_Performance__c.object-meta.xml
<CustomObject>
    <label>Campaign Performance</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Campaign Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Performances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Performance__c/fields/Amount_Spend__c.field-meta.xml
<CustomField>
    <fullName>Amount_Spend__c</fullName>
    <label>Amount Spend</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Campaign_Performance__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign_c</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Campaign Performances</relationshipLabel>
    <relationshipName>Campaign_Performances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Performance__c/fields/Enquiry_Count__c.field-meta.xml
<CustomField>
    <fullName>Enquiry_Count__c</fullName>
    <label>Enquiry Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign_Performance__c/fields/Lead_Count__c.field-meta.xml
<CustomField>
    <fullName>Lead_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lead Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Ex_CampaignPerformanceHandlerServices.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 17-10-2023
//-------------------------------------------//
public class Ex_CampaignPerformanceHandlerServices {
     public static void updateCampaignDetails(Set<Id> cIdSet) {
        List<Campaign__c> cList = new List<Campaign__c>();
        List<Campaign__c> updateCampaignList = new List<Campaign__c>();
    	List<AggregateResult> cpList = new List<AggregateResult>();
        Map<Id, Campaign__c> campaignMap = new Map<Id, Campaign__c>();
        
        cList = [Select Id, Actual_Leads__c, Actual_Enquiries__c, Actual_Cost__c from Campaign__c where Id IN: cIdSet];
        system.debug('cList: '+cList);
        
        if(!cList.isEmpty()) {
            for(Campaign__c c: cList) {
                campaignMap.put(c.Id, c);
            }
        }
        
        cpList = [Select Campaign__c, SUM(Lead_Count__c) leadCount, SUM(Enquiry_Count__c) enqCount, SUM(Amount_Spend__c) amtSpend from Campaign_Performance__c 
                  where Campaign__c IN: cIdSet GROUP BY Campaign__c];
		system.debug('cp: '+cpList);
        
        if(!cpList.isEmpty() && cpList != null) {
            for(AggregateResult ag: cpList) {
                if(campaignMap.containsKey((String) ag.get('Campaign__c'))) {
                    Campaign__c c = campaignMap.get((String) ag.get('Campaign__c'));
                    
                    c.Actual_Cost__c = (Decimal) ag.get('amtSpend');
                    c.Actual_Leads__c = (Decimal) ag.get('leadCount');
                    c.Actual_Enquiries__c = (Decimal) ag.get('enqCount');
                    updateCampaignList.add(c);
                }
            }
        }
        if(!updateCampaignList.isEmpty() && updateCampaignList != null)
            update updateCampaignList;
    }
 }