force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <formula>IF(AND(NOT(ISBLANK(End_Date__c)), End_Date__c &gt;= TODAY(), Start_Date__c &lt;= TODAY(), Text(Approval_Status__c) = &quot;Approved&quot;), true,
IF(AND(ISBLANK(End_Date__c), Start_Date__c &lt;= TODAY(), Text(Approval_Status__c) = &quot;Approved&quot;), true, false))</formula>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Performance_measure_on__c.field-meta.xml
<CustomField>
    <fullName>Performance_measure_on__c</fullName>
    <label>Performance measure on</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>Approval Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Targeted_Leads__c.field-meta.xml
<CustomField>
    <fullName>Targeted_Leads__c</fullName>
    <label>Targeted Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign_Performance__c/Campaign_Performance__c.object-meta.xml
<CustomObject>
    <label>Campaign Performance</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Campaign Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Performances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign_Performance__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign_c</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Campaign Performances</relationshipLabel>
    <relationshipName>Campaign_Performances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign_Performance__c/fields/Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Code__c</fullName>
    <label>Campaign Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account)</relationshipLabel>
    <relationshipName>Leads2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Budget of 50 to 75 lakhs</fullName>
            </value>
            <value>
                <fullName>Budget of 75 lac to 1Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 1 to 1.25 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 1.25 to 1.50 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 1.50 to 1.75 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 1.75 to 2.00 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 2.00 to 2.25 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 2.25 to 2.50 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 2.50 to 2.75 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 2.75 to 3.00 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 3.00 to 3.25 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 3.25 to 3.50 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 3.50 to 3.75 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 3.75 to 4.00 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 4.00 to 4.25 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 4.25 to 4.50 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 4.50 to 4.75 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 4.75 to 5.00 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 5.00 to 5.25 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 5.25 to 5.50 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 5.50 to 5.75 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 5.75 to 6.00 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 6.00 to 6.25 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 6.25 to 6.50 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 6.50 to 6.75 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 6.75 to 7.00 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 7.00 to 7.25 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 7.25 to 7.50 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 7.50 to 7.75 Cr.</fullName>
            </value>
            <value>
                <fullName>Budget of 7.75 to 8.00 Cr.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Campaign_Custom__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Custom</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Configuration_Required__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Required__c</fullName>
    <label>Configuration Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Configuration_Required</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Leads (Opportunity)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incoming</fullName>
                <default>true</default>
                <label>Incoming</label>
            </value>
            <value>
                <fullName>SNP</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Visit Confirmed</fullName>
            </value>
            <value>
                <fullName>Visit Done</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <formula>Account__r.Alternate_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Budget_Range</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Code__c</fullName>
    <label>Campaign Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Campaign_Custom__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Custom</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Budget_Range.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Budget less than 30 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 30 to 40 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 40 to 50 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 50 to 60 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 60 to 70 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 70 to 80 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 80 to 90 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 90 lac to 1Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 1Cr to 1.25 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 1.25Cr to 1.5 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 1.5Cr to 1.75 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 1.75Cr to 2 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 2Cr to 2.5 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 2.5Cr to 3 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 3Cr to 3.5 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 3.5Cr to 4 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget more than 4 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget less than 20 lakhs</fullName>
        <isActive>false</isActive>
        <label>Budget less than 20 lakhs</label>
    </customValue>
    <customValue>
        <fullName>Budget of 20 to 30 lakhs</fullName>
        <isActive>false</isActive>
        <label>Budget of 20 to 30 lakhs</label>
    </customValue>
    <customValue>
        <fullName>Budget of 1Cr to 1.5 Cr.</fullName>
        <isActive>false</isActive>
        <label>Budget of 1Cr to 1.5 Cr.</label>
    </customValue>
    <customValue>
        <fullName>Budget of 1.5Cr to 2 Cr.</fullName>
        <isActive>false</isActive>
        <label>Budget of 1.5Cr to 2 Cr.</label>
    </customValue>
    <customValue>
        <fullName>Budget of 2 Cr to 3 Cr.</fullName>
        <isActive>false</isActive>
        <label>Budget of 2 Cr to 3 Cr.</label>
    </customValue>
    <customValue>
        <fullName>Budget 3 Cr.+</fullName>
        <isActive>false</isActive>
        <label>Budget 3 Cr.+</label>
    </customValue>
    <masterLabel>Budget Range</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Configuration_Required.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Villa</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Shop</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <masterLabel>Configuration Required</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestCampaignHandlerService.cls
@isTest
public class TestCampaignHandlerService {
  
    	@isTest
       public static void CreateCampaign() {
       
       Account a = new Account ();
       a.LastName = 'acc 2';
       a.Phone = '9822341223';
       a.PersonMobilePhone = '9922341223';
       a.Alternate_Email__c = 'acc12@gmail.com';
       a.PersonEmail = 'acc32@gmail.com';
       
        insert a;
           
       Project__c p = new Project__c();
       p.Name = 'Test Project';
       insert p;
       
       Project__c p1 = new Project__c();
       p1.Name = 'Test Project1';
       insert p1;
        
       
        
        Campaign__c c2 = new Campaign__c();
        c2.Name = 'Test Project';
        c2.Active__c = true;
       // c2.Type__c = 'Event'; 
        c2.Project__c = p.id;
        c2.Start_Date__c = system.today();
        c2.End_Date__c = system.today().addDays(1);
        c2.Performance_Measure_On__c = 'Daily';
        c2.Status__c = 'Completed';
       
        c2.Campaign_Code__c = 'AVJH7';
        insert c2;
           
      
        c2.Campaign_Code__c = 'ANCUYTEE';
        update c2;
       
        
        
        Campaign__c c4 = new Campaign__c();
        c4.Name = 'Test Project';
        c4.Active__c = true;
      //  c4.Type__c = 'Email'; 
        c4.Project__c = p.id;
        c4.Start_Date__c = system.today();
        c4.End_Date__c = system.today().addDays(60);
        c4.Performance_Measure_On__c = 'Weekly';
        c4.Status__c = 'Completed';
       
        insert c4;
        update c4;
		
        
        
        Campaign__c c3 = new Campaign__c();
        c3.Name = 'Test Project';
        c3.Active__c = true;
       // c3.Type__c = 'Social Media'; 
        c3.Project__c = p.id;
        c3.Start_Date__c = system.today();
        c3.End_Date__c = system.today().addDays(60);
        c3.Performance_Measure_On__c = 'Monthly';      
        c3.Status__c = 'Completed';
        c3.Targeted_Leads__c = 5;
        insert c3;
           
        c3.Targeted_Leads__c = 100;
        update c3;
        
           
        Lead__c Ld = new Lead__c();
        Ld.Last_Name__c = 'test';   
        Ld.Campaign_Custom__c = c2.id;
        Ld.Budget__c = 'Budget of 80 to 90 lakhs';
        Ld.Configuration_Required__c = '1 BHK';
        Ld.Project__c = p.id;
        insert Ld;
        
       
       Opportunity__c Opp = new Opportunity__c();
       opp.Name = 'Test Opp';
       opp.Account__c = a.id;
       opp.Stage__c = 'In Follow-up';
       opp.Project__c = p.Id;
       opp.Sales_Next_Follow_up_Date__c = system.now();
       opp.Site_Visit_Count__c = 0;
       opp.Campaign_Custom__c = c2.id;
        insert opp;
        
        opp.Site_Visit_Count__c = 10;
        update opp;
           
           
        
        Campaign_Performance__c cpl = new Campaign_Performance__c();
        cpl.Lead_Count__c = 0;
        cpl.Start_Date__c = system.today();
        cpl.End_Date__c = system.today();
        cpl.Campaign__c = c2.id;
        
        insert cpl;
       
           
    // CampaignHandlerServices cs = new CampaignHandlerServices();
		
    }
    @isTest
       public static void CreateCampaign5() {
       
       Account a = new Account ();
       a.LastName = 'acc 2';
       a.Phone = '9822341223';
       a.PersonMobilePhone = '9922341223';
       a.Alternate_Email__c = 'acc12@gmail.com';
       a.PersonEmail = 'acc32@gmail.com';
       
        insert a;
           
       Project__c p = new Project__c();
       p.Name = 'Test Project';
       insert p;
       
       Project__c p1 = new Project__c();
       p1.Name = 'Test Project1';
       insert p1;
        
       
        
        Campaign__c c2 = new Campaign__c();
        c2.Name = 'Test Project';
        c2.Active__c = true;
        c2.Project__c = p.id;
        c2.Start_Date__c = system.today();
        c2.End_Date__c = system.today().addDays(1);
        c2.Performance_Measure_On__c = 'Daily';
        c2.Status__c = 'Completed';
        c2.Budgeted_Cost__c = 234;
        c2.Lead_Count__c = 2;
        c2.Targeted_Leads__c = 200;
        c2.Campaign_Code__c = 'AVJH7';
        insert c2;
           
        c2.Budgeted_Cost__c = 294;
        c2.Lead_Count__c = 5;
        c2.Targeted_Leads__c = 240;
        c2.Campaign_Code__c = 'AVTTJH7';
        update c2;
       
        
        
        Campaign__c c4 = new Campaign__c();
        c4.Name = 'Test Project';
        c4.Active__c = true;
       // c4.Type__c = 'Email'; 
        c4.Project__c = p.id;
        c4.Start_Date__c = system.today();
        c4.End_Date__c = system.today().addDays(60);
        c4.Performance_Measure_On__c = 'Weekly';
        c4.Status__c = 'Completed';
        c4.Budgeted_Cost__c = 0;
       
        insert c4;
        c4.Budgeted_Cost__c = 100;
        update c4;
		
        
        
        Campaign__c c3 = new Campaign__c();
        c3.Name = 'Test Project';
        c3.Active__c = true;
        c3.Project__c = p.id;
        c3.Start_Date__c = system.today();
        c3.End_Date__c = system.today().addDays(60);
        c3.Performance_Measure_On__c = 'Monthly';      
        c3.Status__c = 'Completed';
        c3.Budgeted_Cost__c = 0;
        insert c3;
           
        c3.Budgeted_Cost__c = 100;
        update c3;
        
           
        Lead__c Ld = new Lead__c();
        Ld.Last_Name__c = 'test';   
        Ld.Campaign_Custom__c = c2.id;
        Ld.Budget__c = 'Budget of 80 to 90 lakhs';
        Ld.Configuration_Required__c = '1 BHK';
        Ld.Project__c = p.id;
        insert Ld;
        
       
       Opportunity__c Opp = new Opportunity__c();
       opp.Name = 'Test Opp';
       opp.Account__c = a.id;
       opp.Stage__c = 'In Follow-up';
       opp.Project__c = p.Id;
       opp.Sales_Next_Follow_up_Date__c = system.now();
       opp.Site_Visit_Count__c = 0;
       opp.Campaign_Custom__c = c2.id;
       insert opp;
        
       opp.project__c = p1.Id;
       update opp;
           

           
        
        Campaign_Performance__c cpl = new Campaign_Performance__c();
        cpl.Lead_Count__c = 0;
        cpl.Start_Date__c = system.today();
        cpl.End_Date__c = system.today();
        cpl.Campaign__c = c2.id;
        
        insert cpl;
       
           
    // CampaignHandlerServices cs = new CampaignHandlerServices();
		
    }
    @isTest
       public static void CreateCampaign6() {
       
       Account a = new Account ();
       a.LastName = 'acc 2';
       a.Phone = '9822341223';
       a.PersonMobilePhone = '9922341223';
       a.Alternate_Email__c = 'acc12@gmail.com';
       a.PersonEmail = 'acc32@gmail.com';
       
        insert a;
           
       Project__c p = new Project__c();
       p.Name = 'Test Project';
       insert p;
       
       Project__c p1 = new Project__c();
       p1.Name = 'Test Project1';
       insert p1;
        
        
        Campaign__c c2 = new Campaign__c();
        c2.Name = 'Test Project';
        c2.Active__c = true;
        c2.Project__c = p.id;
        c2.Start_Date__c = system.today();
        c2.End_Date__c = system.today().addDays(1);
        c2.Performance_Measure_On__c = 'Daily';
        c2.Status__c = 'Completed';
      c2.Budgeted_Cost__c = 234;
        c2.Lead_Count__c = 2;
        c2.Targeted_Leads__c = 200;
        c2.Campaign_Code__c = 'AVJH7';
        insert c2;
           
        c2.Budgeted_Cost__c = 294;
        c2.Lead_Count__c = 5;
        c2.Targeted_Leads__c = 240;
        c2.Campaign_Code__c = 'AVTTJH7';
        update c2; 
        
        
        Campaign__c c4 = new Campaign__c();
        c4.Name = 'Test Project';
        c4.Active__c = true;
        c4.Project__c = p.id;
        c4.Start_Date__c = system.today();
        c4.End_Date__c = system.today().addDays(60);
        c4.Performance_Measure_On__c = 'Weekly';
        c4.Status__c = 'Completed';
        c4.Budgeted_Cost__c = 0;
       
        insert c4;
        c4.Budgeted_Cost__c = 100;
        update c4;
		
        
        
        Campaign__c c3 = new Campaign__c();
        c3.Name = 'Test Project';
        c3.Active__c = true;
        c3.Project__c = p.id;
        c3.Start_Date__c = system.today();
        c3.End_Date__c = system.today().addDays(60);
        c3.Performance_Measure_On__c = 'Monthly';      
        c3.Status__c = 'Completed';
        c3.Budgeted_Cost__c = 0;
        insert c3;
           
        c3.Budgeted_Cost__c = 100;
        update c3;
        
           
        Lead__c Ld = new Lead__c();
        Ld.Last_Name__c = 'test';   
        Ld.Campaign_Custom__c = c2.id;
        Ld.Budget__c = 'Budget of 80 to 90 lakhs';
        Ld.Configuration_Required__c = '1 BHK';
        Ld.Project__c = p.id;
        insert Ld;
        
       
       Opportunity__c Opp = new Opportunity__c();
       opp.Name = 'Test Opp';
       opp.Account__c = a.id;
       opp.Stage__c = 'In Follow-up';
       opp.Project__c = p.Id;
       opp.Sales_Next_Follow_up_Date__c = system.now();
       opp.Site_Visit_Count__c = 0;
       opp.Campaign_Custom__c = c2.id;
       insert opp;
        
       opp.Campaign_Custom__c = c3.id;
       update opp;
           
      
           
        
        Campaign_Performance__c cpl = new Campaign_Performance__c();
        cpl.Lead_Count__c = 0;
        cpl.Start_Date__c = system.today();
        cpl.End_Date__c = system.today();
        cpl.Campaign__c = c2.id;
        
        insert cpl;
       
           
    // CampaignHandlerServices cs = new CampaignHandlerServices();
		
    }
    @isTest
       public static void CreateCampaign2() {
       Project__c p = new Project__c();
      
           
       
        
        Campaign__c c2 = new Campaign__c();
        c2.Name = 'Test Project';
        c2.Active__c = true;
        c2.Project__c = p.id;
        c2.Start_Date__c = system.today();
        c2.End_Date__c = system.today().addDays(1);
        c2.Performance_Measure_On__c = 'Daily';
        c2.Status__c = 'Completed';
         c2.Budgeted_Cost__c = 234;
        c2.Lead_Count__c = 2;
        c2.Targeted_Leads__c = 200;
        c2.Campaign_Code__c = 'AVJH7';
        insert c2;
           
        c2.Budgeted_Cost__c = 294;
        c2.Lead_Count__c = 5;
        c2.Targeted_Leads__c = 240;
        c2.Campaign_Code__c = 'AVTTJH7';
        update c2; 
     
        
        
        Campaign__c c4 = new Campaign__c();
        c4.Name = 'Test Project';
        c4.Active__c = true;
        c4.Project__c = p.id;
        c4.Start_Date__c = system.today();
        c4.End_Date__c = system.today().addDays(60);
        c4.Performance_Measure_On__c = 'Weekly';
        c4.Status__c = 'Completed';
        c4.Budgeted_Cost__c = 0;
       
        insert c4;
        c4.Budgeted_Cost__c = 100;
        update c4;
		
        
        
        Campaign__c c3 = new Campaign__c();
        c3.Name = 'Test Project';
        c3.Active__c = true;
        c3.Project__c = p.id;
        c3.Start_Date__c = system.today();
        c3.End_Date__c = system.today().addDays(60);
        c3.Performance_Measure_On__c = 'Monthly';      
        c3.Status__c = 'Completed';
      //  c3.Amount__c = 0;
        insert c3;
           
       // c3.Amount__c = 100;
       // update c3;
        
           
        Lead__c Ld = new Lead__c();
        Ld.Last_Name__c = 'test';   
        Ld.Campaign_Custom__c = c2.id;
        Ld.Budget__c = 'Budget of 80 to 90 lakhs';
        Ld.Configuration_Required__c = '1 BHK';
        Ld.Project__c = p.id;
        insert Ld;
           
           
        
        Campaign_Performance__c cpl = new Campaign_Performance__c();
        cpl.Lead_Count__c = 0;
        cpl.Start_Date__c = system.today();
        cpl.End_Date__c = system.today();
        cpl.Campaign__c = c2.id;
        
        insert cpl;
       
           
    // CampaignHandlerServices cs = new CampaignHandlerServices();
		
    }
    
    
    @isTest
       public static void CreateCampaign3() {
       Project__c p = new Project__c();
      
           
     
        
        Campaign__c c2 = new Campaign__c();
        c2.Name = 'Test Project';
        c2.Active__c = true;
        c2.Project__c = p.id;
        c2.Start_Date__c = system.today();
        c2.End_Date__c = system.today().addDays(1);
        c2.Performance_Measure_On__c = 'Weekly'; 
        c2.Status__c = 'Completed';
         c2.Budgeted_Cost__c = 234;
        c2.Lead_Count__c = 2;
        c2.Targeted_Leads__c = 200;
        c2.Campaign_Code__c = 'AVJH7';
        insert c2;
           
        c2.Budgeted_Cost__c = 294;
        c2.Lead_Count__c = 5;
        c2.Targeted_Leads__c = 240;
        c2.Campaign_Code__c = 'AVTTJH7';
        update c2; 
     
        
        
        Campaign__c c4 = new Campaign__c();
        c4.Name = 'Test Project';
        c4.Active__c = true;
        c4.Project__c = p.id;
        c4.Start_Date__c = system.today();
        c4.End_Date__c = system.today().addDays(60);
        c4.Performance_Measure_On__c = 'Daily';
        c4.Status__c = 'Completed';
        c4.Budgeted_Cost__c = 0;
       
        insert c4;
        c4.Budgeted_Cost__c = 100;
        update c4;
		
        
        
        Campaign__c c3 = new Campaign__c();
        c3.Name = 'Test Project';
        c3.Active__c = true;
        c3.Project__c = p.id;
        c3.Start_Date__c = system.today();
        c3.End_Date__c = system.today().addDays(60);
        c3.Performance_Measure_On__c = 'Monthly';      
        c3.Status__c = 'Completed';
        c3.Budgeted_Cost__c = 0;
        insert c3;
           
        c3.Budgeted_Cost__c = 100;
        update c3;
        
           
        Lead__c Ld = new Lead__c();
        Ld.Last_Name__c = 'test';   
        Ld.Campaign_Custom__c = c2.id;
        Ld.Budget__c = 'Budget of 80 to 90 lakhs';
        Ld.Configuration_Required__c = '1 BHK';
        Ld.Project__c = p.id;
        insert Ld;
           
           
        
        Campaign_Performance__c cpl = new Campaign_Performance__c();
        cpl.Lead_Count__c = 0;
        cpl.Start_Date__c = system.today();
        cpl.End_Date__c = system.today();
        cpl.Campaign__c = c2.id;
        
        insert cpl;
       
           
    // CampaignHandlerServices cs = new CampaignHandlerServices();
		
    }
    
    @isTest
       public static void CreateCampaign4() {
       Project__c p = new Project__c();
           
        Campaign__c c2 = new Campaign__c();
        c2.Name = 'Test Project';
        c2.Active__c = true;
        c2.Project__c = p.id;
        c2.Start_Date__c = system.today();
        c2.End_Date__c = system.today().addDays(1);
        c2.Performance_Measure_On__c = 'Monthly'; 
        c2.Status__c = 'Completed';
          c2.Budgeted_Cost__c = 234;
        c2.Lead_Count__c = 2;
        c2.Targeted_Leads__c = 200;
        c2.Campaign_Code__c = 'AVJH7';
        insert c2;
           
        c2.Budgeted_Cost__c = 294;
        c2.Lead_Count__c = 5;
        c2.Targeted_Leads__c = 240;
        c2.Campaign_Code__c = 'AVTTJH7';
        update c2; 
     
        
        
        Campaign__c c4 = new Campaign__c();
        c4.Name = 'Test Project';
        c4.Active__c = true;
        c4.Project__c = p.id;
        c4.Start_Date__c = system.today();
        c4.End_Date__c = system.today().addDays(60);
        c4.Performance_Measure_On__c = 'Daily';
        c4.Status__c = 'Completed';
        c4.Budgeted_Cost__c = 0;
       
        insert c4;
        c4.Budgeted_Cost__c = 100;
        update c4;
		
        
        
        Campaign__c c3 = new Campaign__c();
        c3.Name = 'Test Project';
        c3.Active__c = true;
        c3.Project__c = p.id;
        c3.Start_Date__c = system.today();
        c3.End_Date__c = system.today().addDays(60);
        c3.Performance_Measure_On__c = 'Weekly';      
        c3.Status__c = 'Completed';
        c3.Budgeted_Cost__c = 0;
        insert c3;
           
        c3.Budgeted_Cost__c = 100;
        update c3;
        
           
        Lead__c Ld = new Lead__c();
        Ld.Last_Name__c = 'test';   
        Ld.Campaign_Custom__c = c2.id;
        Ld.Budget__c = 'Budget of 80 to 90 lakhs';
        Ld.Configuration_Required__c = '1 BHK';
        Ld.Project__c = p.id;
        insert Ld;
           
           
        
        Campaign_Performance__c cpl = new Campaign_Performance__c();
        cpl.Lead_Count__c = 0;
        cpl.Start_Date__c = system.today();
        cpl.End_Date__c = system.today();
        cpl.Campaign__c = c2.id;
        
        insert cpl;
       		
    }
       @IsTest
        static void testCreateCampaignMember() {
         Project__c p = new Project__c();
 
            
        Campaign__c c3 = new Campaign__c();
        c3.Name = 'Test Project';
        c3.Active__c = true;
        c3.Project__c = p.id;
        c3.Start_Date__c = system.today();
        c3.End_Date__c = system.today().addDays(60);
        c3.Performance_Measure_On__c = 'Weekly';      
        c3.Status__c = 'Completed';
        c3.Budgeted_Cost__c = 0;
        insert c3;
         

        List<Lead__c> testLeads = new List<Lead__c>();
        testLeads.add(new Lead__c(Campaign_Code__c = 'TEST'));
        testLeads.add(new Lead__c(Campaign_Code__c = 'TEST'));
        
        Test.startTest();
        CampaignHandlerServices.createCampaignMember(testLeads);
        Test.stopTest();

       
    }

 }