force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Aggregators</fullName>
            </value>
            <value>
                <fullName>Organic</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Television</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>VDNB</fullName>
            </value>
            <value>
                <fullName>Cold Calling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Lead_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Source__c</fullName>
    <label>Lead Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Google Search</fullName>
            </value>
            <value>
                <fullName>Google Display</fullName>
            </value>
            <value>
                <fullName>YouTube</fullName>
            </value>
            <value>
                <fullName>Discovery Ads</fullName>
            </value>
            <value>
                <fullName>Lead Gen Form</fullName>
            </value>
            <value>
                <fullName>Instagram</fullName>
            </value>
            <value>
                <fullName>Web Conversion</fullName>
            </value>
            <value>
                <fullName>MagicBricks</fullName>
            </value>
            <value>
                <fullName>NoBroker</fullName>
            </value>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>99Acres</fullName>
            </value>
            <value>
                <fullName>Corporate Website</fullName>
            </value>
            <value>
                <fullName>ORM</fullName>
            </value>
            <value>
                <fullName>Jacket</fullName>
            </value>
            <value>
                <fullName>Power Jacket</fullName>
            </value>
            <value>
                <fullName>Full Page</fullName>
            </value>
            <value>
                <fullName>Half Page</fullName>
            </value>
            <value>
                <fullName>Inserts</fullName>
            </value>
            <value>
                <fullName>RJ Mentions</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
            <value>
                <fullName>Show Sponsorship</fullName>
            </value>
            <value>
                <fullName>Advertisement</fullName>
            </value>
            <value>
                <fullName>Billboard</fullName>
            </value>
            <value>
                <fullName>Bus Shelter</fullName>
            </value>
            <value>
                <fullName>Kiosk</fullName>
            </value>
            <value>
                <fullName>Cantilever</fullName>
            </value>
            <value>
                <fullName>Gantry</fullName>
            </value>
            <value>
                <fullName>Mobile Van</fullName>
            </value>
            <value>
                <fullName>Bus Panel</fullName>
            </value>
            <value>
                <fullName>Railway Station Boards</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Source_Description__c.field-meta.xml
<CustomField>
    <fullName>Source_Description__c</fullName>
    <label>Source Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Digital_Lead__c/Digital_Lead__c.object-meta.xml
<CustomObject>
    <label>Digital Lead</label>
    <nameField>
        <displayFormat>DL-{000000}</displayFormat>
        <label>Digital Lead Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Digital Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Digital_Lead__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Digital Leads</relationshipLabel>
    <relationshipName>Digital_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Digital_Lead__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <label>Alternate Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Digital_Lead__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity_c</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Digital Leads</relationshipLabel>
    <relationshipName>Digital_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Digital_Lead__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <formula>Account__r.Alternate_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile__c</fullName>
    <formula>Account__r.PersonContact.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Code__c</fullName>
    <label>Campaign Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account__r.PersonContact.Email</formula>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead_Sub_source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_source__c</fullName>
    <label>Lead Sub-source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lead_Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>Account__r.PersonContact.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>In Follow-up</fullName>
                <default>true</default>
                <label>In Follow-up</label>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Booking In-Process</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Lead_Sub_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Google Search</fullName>
    </customValue>
    <customValue>
        <fullName>Google Display</fullName>
    </customValue>
    <customValue>
        <fullName>YouTube</fullName>
    </customValue>
    <customValue>
        <fullName>Discovery Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Gen Form</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Web Conversion</fullName>
    </customValue>
    <customValue>
        <fullName>MagicBricks</fullName>
    </customValue>
    <customValue>
        <fullName>NoBroker</fullName>
    </customValue>
    <customValue>
        <fullName>Housing</fullName>
    </customValue>
    <customValue>
        <fullName>99Acres</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Website</fullName>
    </customValue>
    <customValue>
        <fullName>ORM</fullName>
    </customValue>
    <customValue>
        <fullName>Jacket</fullName>
    </customValue>
    <customValue>
        <fullName>Power Jacket</fullName>
    </customValue>
    <customValue>
        <fullName>Full Page</fullName>
    </customValue>
    <customValue>
        <fullName>Half Page</fullName>
    </customValue>
    <customValue>
        <fullName>Inserts</fullName>
    </customValue>
    <customValue>
        <fullName>RJ Mentions</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Advertisement</fullName>
    </customValue>
    <customValue>
        <fullName>Show Sponsorship</fullName>
    </customValue>
    <customValue>
        <fullName>Billboard</fullName>
    </customValue>
    <customValue>
        <fullName>Bus Shelter</fullName>
    </customValue>
    <customValue>
        <fullName>Kiosk</fullName>
    </customValue>
    <customValue>
        <fullName>Cantilever</fullName>
    </customValue>
    <customValue>
        <fullName>Gantry</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Van</fullName>
    </customValue>
    <customValue>
        <fullName>Bus Panel</fullName>
    </customValue>
    <customValue>
        <fullName>Railway Station Boards</fullName>
    </customValue>
    <masterLabel>Lead Sub Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestEx_DigitalLeadHandlerServices.cls
@isTest
public class TestEx_DigitalLeadHandlerServices {
    @isTest
    public static void createfbLead()
    {
        Map<String, Id> returnMap = new Map<String,Id>();
        Project__c p = new Project__c();
        p.Name = 'Test Project';
        insert p;
        
        Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account a = new Account(FirstName = 'Test', LastName = 'Account',  PersonMobilePhone = '4455667722', RecordtypeId = rtId);
        insert a;
        Opportunity__c op = new Opportunity__c(Name = 'Test Opp', Account__c = a.Id, Stage__c = 'In Follow-up', Close_Date__c = system.today().addDays(30), Project__c = p.id);
        insert op;
        
        Campaign__c camp = new Campaign__c();
        camp.Name = 'Test Campaign ';
        camp.Campaign_Code__c = 'a06H3000000NLnFIAW';
        camp.Lead_Source__c = 'Google';
        camp.Lead_Sub_Source__c = 'YouTube';
        camp.Source_Description__c = 'Social Campaign';
        camp.Project__c=p.id;
        camp.Start_Date__c = Date.today();
        camp.End_Date__c = Date.today().addDays(10);
        insert camp;   
        
        
        Campaign__c c3 = new Campaign__c();
        c3.Name = 'Test Campaign ';
        c3.Campaign_Code__c = 'a06H3000000NLnFIAW';
        c3.Lead_Source__c = 'Google';
        c3.Lead_Sub_Source__c = 'YouTube';
        c3.Source_Description__c = 'Social Campaign';
        c3.Project__c=p.id;
        c3.Start_Date__c = Date.today();
        c3.End_Date__c = Date.today().addDays(10);
        insert c3;
        
        Digital_Lead__c dl = new Digital_Lead__c();
         dl.First_Name__c = 'Test';
        dl.Last_Name__c = 'Test fb';
        dl.Location__c = 'Test Location';
        dl.Campaign_Code__c = c3.Campaign_Code__c;
        dl.Mobile__c = '+14455667722';
        dl.Alternate_Mobile__c = '+9994455660822';
        dl.Alternate_Email__c = 'test@fb.com';
        dl.Email__c = 'test@fb.com';
        dl.Platform__c = 'Facebook';
        insert dl;
        
        Digital_Lead__c dl1 = new Digital_Lead__c();
        dl1.Last_Name__c = 'Test fb';
         dl1.First_Name__c = 'Lead';
        dl1.Campaign_Code__c = c3.Campaign_Code__c;
        dl1.Location__c = 'Test Location';
        dl1.Mobile__c = '+17874455667722';
        dl1.Email__c = 'test@fb.com';
        dl1.Alternate_Email__c = 'test@fb.com';
        dl1.Alternate_Mobile__c = '+9994455660777';
        dl1.Platform__c = 'Facebook';
        insert dl1;
        
        Digital_Lead__c dl2 = new Digital_Lead__c();
        dl2.Last_Name__c = 'Test';
         dl2.First_Name__c = 'Lead';
        dl2.Location__c = 'Test Location';
        dl2.Campaign_Code__c = c3.id;
        dl2.Mobile__c = '+18094455667723';
        dl2.Email__c = 'test@fb1.com';
        dl2.Alternate_Email__c = 'test@fb.com';
        dl2.Alternate_Mobile__c = '+8884455660723';
        dl2.Platform__c = 'Facebook';
        insert dl2;  
        
        Digital_Lead__c dl3 = new Digital_Lead__c();
         dl3.First_Name__c = 'Test';
        dl3.Last_Name__c = 'Test1';
        dl3.Campaign_Code__c = c3.id;
        dl3.Location__c = 'Test Location';
        dl3.Mobile__c = '+9984455667723';
        dl3.Alternate_Mobile__c = '+9914455660723';
        dl3.Email__c = 'test@fb1.com';
        dl3.Alternate_Email__c = 'test@fb.com';

        dl3.Platform__c = 'Facebook';
        insert dl3;  
        
        Digital_Lead__c dl4 = new Digital_Lead__c();
        dl4.First_Name__c = 'Test';
        dl4.Location__c = 'Test Location';
        dl4.Last_Name__c = '123';
        dl4.Campaign_Code__c = camp.id;
        dl4.Mobile__c = '+9994455667723';
        dl4.Alternate_Mobile__c = '+9994455660723';
        dl4.Email__c = 'test@fb1.com';
        dl4.Alternate_Email__c = 'test@fb.com';

        dl4.Platform__c = 'Website';
        insert dl4;
        
    }   
    
}