force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <label>Campaign</label>
    <nameField>
        <label>Campagin Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Approver_Name__c.field-meta.xml
<CustomField>
    <fullName>Approver_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Approver_Status__c.field-meta.xml
<CustomField>
    <fullName>Approver_Status__c</fullName>
    <label>Approver Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending For Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Is_CTI_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Is_CTI_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is CTI Campaign?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Offline_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Offline_Campaign__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>It is used In case of Mobile User</inlineHelpText>
    <label>Offline Campaign</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Ozontel_Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Ozontel_Campaign_Name__c</fullName>
    <inlineHelpText>It is used for CTI Campaign for Ozontel</inlineHelpText>
    <label>Ozontel Campaign Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Campaigns1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign__c/fields/Virtual_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Number__c</fullName>
    <label>Virtual Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account)</relationshipLabel>
    <relationshipName>Leads2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</description>
    <inlineHelpText>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</inlineHelpText>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Leads (Opportunity)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Virtual_Number__c.field-meta.xml
<CustomField>
    <fullName>Virtual_Number__c</fullName>
    <label>Virtual Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Ola_Pickup__c/Ola_Pickup__c.object-meta.xml
<CustomObject>
    <label>Ola Pickup</label>
    <nameField>
        <displayFormat>Ola-{00000}</displayFormat>
        <label>Ola Pickup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ola Pickups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ola_Pickup__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Ola Pickups</relationshipLabel>
    <relationshipName>Ola_Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ola_Pickup__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Ola Pickups</relationshipLabel>
    <relationshipName>Ola_Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <formula>Account__r.Alternate_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Mobile__c</fullName>
    <formula>Account__r.PersonContact.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>Account__r.PersonContact.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Opportunity Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Opportunity_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Follow-up</fullName>
        <default>true</default>
        <label>In Follow-up</label>
    </customValue>
    <customValue>
        <fullName>Booking In-Process</fullName>
    </customValue>
    <customValue>
        <fullName>Booked</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation In-Process</fullName>
    </customValue>
    <masterLabel>Opportunity Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestEx_CallCustomerServices.cls
@isTest
public class TestEx_CallCustomerServices {
    
    @isTest
    public static void testClickToCallforLead() {
        
        Project__c pr = new Project__c();
        pr.Name = 'Test Project';
        insert pr;
        
        Campaign__c c = new Campaign__c();
        c.Virtual_Number__c = '912245811703';
        c.Is_CTI_Campaign__c = true;
        c.Project__c = pr.id;
        c.Approver_Status__c = 'Approved';
        c.Start_Date__c = System.today();
        c.Approver_Name__c = UserInfo.getuserId();
        c.Ozontel_Campaign_Name__c = 'Inbound_912245811703';
        c.Offline_Campaign__c = false;
        insert c;
        
        Campaign__c c2 = new Campaign__c();
        c2.Virtual_Number__c = '912245811701';
        c2.Is_CTI_Campaign__c = true;
        c2.Project__c = pr.id;
        c2.Approver_Status__c = 'Approved';
        c2.Start_Date__c = System.today();
        c2.Approver_Name__c = UserInfo.getuserId();
        c2.Offline_Campaign__c = true;
        c2.Ozontel_Campaign_Name__c = 'Inbound_912245811701';
        insert c2;
        
        Lead__c ld = new Lead__c();
        ld.Last_Name__c = 'Test Lead';
        ld.IsConverted__c = false;
        ld.Mobile__c = '08871430235';
        insert ld;
        System.debug('uui: '+ld.Id);
        
        List<Ex_CallCustomerServices.campWrapper> resultLeadCamp = Ex_CallCustomerServices.getCampaign(ld.Id, 'Large');
        List<Ex_CallCustomerServices.campWrapper> resultLeadOffline = Ex_CallCustomerServices.getCampaign(ld.Id, 'Small');
        List<Ex_CallCustomerServices.callWrapper> resultLeadMobile = Ex_CallCustomerServices.getMobileNumber(ld.id);
        String resultLead = Ex_CallCustomerServices.ClickToCall('1122334456', c2.Name, c2.Virtual_Number__c, 'Small', ld.Id);        
    }
    
    @isTest
    public static void testClickToCallforOpportunity() {
        Project__c pr = new Project__c();
        pr.Name = 'Test Project';
        insert pr;
        
        Campaign__c c2 = new Campaign__c();
        c2.Virtual_Number__c = '912245811701';
        c2.Is_CTI_Campaign__c = true;
        c2.Project__c = pr.id;
        c2.Approver_Status__c = 'Approved';
        c2.Start_Date__c = System.today();
        c2.Approver_Name__c = UserInfo.getuserId();
        c2.Offline_Campaign__c = true;
        c2.Ozontel_Campaign_Name__c = 'Inbound_912245811701';
        insert c2;
        
        String RecTypeId= Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account a2 = new Account(Salutation = 'Mr.' , FirstName = 'Test', LastName = 'Lead 2', PersonMobilePhone = '1122334456', PersonEmail = 'lead2@test.in', Alternate_Email__c = 'lead@test.in',RecordTypeId = RecTypeId);
        insert a2;
        Opportunity__c op = new Opportunity__c(Name = 'Test1', Opportunity_Stage__c = 'In Follow-up', Project__c = pr.Id,Account__c = a2.id);
        insert op;
        System.debug('op: '+op);  
        
        List<Ex_CallCustomerServices.campWrapper> resultoppcamp = Ex_CallCustomerServices.getCampaign(op.Id, 'Large');
        List<Ex_CallCustomerServices.campWrapper> resultoppoffline = Ex_CallCustomerServices.getCampaign(op.Id, 'Small');
        List<Ex_CallCustomerServices.callWrapper> resultoppMobile = Ex_CallCustomerServices.getMobileNumber(op.id);
        String resultopp = Ex_CallCustomerServices.ClickToCall('1122334456', c2.Name, c2.Virtual_Number__c, 'Small', op.Id);
        
    }
    
    @isTest
    public static void testClickToCallforOla() {
        
        Project__c pr = new Project__c();
        pr.Name = 'Test Project';
        insert pr;
        
        Campaign__c c2 = new Campaign__c();
        c2.Virtual_Number__c = '912245811701';
        c2.Is_CTI_Campaign__c = true;
        c2.Project__c = pr.id;
        c2.Approver_Status__c = 'Approved';
        c2.Start_Date__c = System.today();
        c2.Approver_Name__c = UserInfo.getuserId();
        c2.Offline_Campaign__c = true;
        c2.Ozontel_Campaign_Name__c = 'Inbound_912245811701';
        insert c2;
        
        Ola_Pickup__c ola = new Ola_Pickup__c();
        ola.Primary_Mobile__c = '7878787877';
        ola.Alternate_Mobile__c = '8888000000';
        insert ola;
        
        List<Ex_CallCustomerServices.campWrapper> resultolaCamp = Ex_CallCustomerServices.getCampaign(ola.Id, 'Large');
        List<Ex_CallCustomerServices.campWrapper> resultLolaOffline = Ex_CallCustomerServices.getCampaign(ola.Id, 'Small');
        List<Ex_CallCustomerServices.callWrapper> resultolaMobile = Ex_CallCustomerServices.getMobileNumber(ola.id);
        String resultola = Ex_CallCustomerServices.ClickToCall('1122334456', c2.Name, c2.Virtual_Number__c, 'Small', ola.Id);
        
    }    
}