force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>CP Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Channel Partner)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Fist_SV_Date__c.field-meta.xml
<CustomField>
    <fullName>Fist_SV_Date__c</fullName>
    <label>Fist SV Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Last_Source_Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Source_Change_Date__c</fullName>
    <label>Last Source Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead_Sub_source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_source__c</fullName>
    <label>Lead Sub-source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lead_Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Referrer_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Mobile__c</fullName>
    <label>Referrer_Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Referrer_Name__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referrer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity (Referrer Name)</relationshipLabel>
    <relationshipName>Opportunity1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/TAT_Days_for_Walkin__c.field-meta.xml
<CustomField>
    <fullName>TAT_Days_for_Walkin__c</fullName>
    <defaultValue>0</defaultValue>
    <label>TAT Days for Walkin</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Visits (Channel Partner)</relationshipLabel>
    <relationshipName>Site_Visits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/GRE__c.field-meta.xml
<CustomField>
    <fullName>GRE__c</fullName>
    <label>GRE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nitin Choudhary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Is_Preregister_Visit__c.field-meta.xml
<CustomField>
    <fullName>Is_Preregister_Visit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Preregister Visit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Aggregators</fullName>
            </value>
            <value>
                <fullName>Organic</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Television</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Reference</fullName>
            </value>
            <value>
                <fullName>VDNB</fullName>
            </value>
            <value>
                <fullName>Cold Calling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Lead_Sub_source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_source__c</fullName>
    <label>Lead Sub-source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Referrer_Name__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Referrer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Lead_Sub_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Google Search</fullName>
    </customValue>
    <customValue>
        <fullName>Google Display</fullName>
    </customValue>
    <customValue>
        <fullName>YouTube</fullName>
    </customValue>
    <customValue>
        <fullName>Discovery Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Gen Form</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Web Conversion</fullName>
    </customValue>
    <customValue>
        <fullName>MagicBricks</fullName>
    </customValue>
    <customValue>
        <fullName>NoBroker</fullName>
    </customValue>
    <customValue>
        <fullName>Housing</fullName>
    </customValue>
    <customValue>
        <fullName>99Acres</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Website</fullName>
    </customValue>
    <customValue>
        <fullName>ORM</fullName>
    </customValue>
    <customValue>
        <fullName>Jacket</fullName>
    </customValue>
    <customValue>
        <fullName>Power Jacket</fullName>
    </customValue>
    <customValue>
        <fullName>Full Page</fullName>
    </customValue>
    <customValue>
        <fullName>Half Page</fullName>
    </customValue>
    <customValue>
        <fullName>Inserts</fullName>
    </customValue>
    <customValue>
        <fullName>RJ Mentions</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Advertisement</fullName>
    </customValue>
    <customValue>
        <fullName>Show Sponsorship</fullName>
    </customValue>
    <customValue>
        <fullName>Billboard</fullName>
    </customValue>
    <customValue>
        <fullName>Bus Shelter</fullName>
    </customValue>
    <customValue>
        <fullName>Kiosk</fullName>
    </customValue>
    <customValue>
        <fullName>Cantilever</fullName>
    </customValue>
    <customValue>
        <fullName>Gantry</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Van</fullName>
    </customValue>
    <customValue>
        <fullName>Bus Panel</fullName>
    </customValue>
    <customValue>
        <fullName>Railway Station Boards</fullName>
    </customValue>
    <masterLabel>Lead Sub Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sub_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Mindicator</fullName>
    </customValue>
    <customValue>
        <fullName>Timesjob</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Whatsapp</fullName>
    </customValue>
    <customValue>
        <fullName>Call Verified</fullName>
    </customValue>
    <customValue>
        <fullName>One Native</fullName>
    </customValue>
    <customValue>
        <fullName>Taboola</fullName>
    </customValue>
    <customValue>
        <fullName>Times Colombia</fullName>
    </customValue>
    <customValue>
        <fullName>Yahoo Native</fullName>
    </customValue>
    <customValue>
        <fullName>Quikr</fullName>
    </customValue>
    <customValue>
        <fullName>99Acres</fullName>
    </customValue>
    <customValue>
        <fullName>Housing</fullName>
    </customValue>
    <customValue>
        <fullName>Magicbricks</fullName>
    </customValue>
    <customValue>
        <fullName>NoBroker</fullName>
    </customValue>
    <customValue>
        <fullName>Google Search</fullName>
    </customValue>
    <customValue>
        <fullName>Google Display</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube LG</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube Bumper Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Discovery Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Gen</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Gen Insta</fullName>
    </customValue>
    <customValue>
        <fullName>Web Conversion</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Generation</fullName>
    </customValue>
    <customValue>
        <fullName>InMail</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Website</fullName>
    </customValue>
    <customValue>
        <fullName>ORM</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>User</fullName>
    </customValue>
    <masterLabel>Sub-Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_GREUpdateDetails.cls
public class Ex_GREUpdateDetails {
    public class SVWrapper{
        @AuraEnabled 
        public Site_Visit__c sv { get; set; }
        public SVWrapper(){
            sv = new Site_Visit__c();
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static list<sObject> fetchLookupData(string searchKey , string sObjectApiName, String projectId) { 
        System.debug('projectId: '+projectId);
        System.debug('sObjectApiName '+sObjectApiName);
        List <sObject> returnList = new List < sObject > ();
        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Channel_Partner').getRecordTypeId();
        System.debug('recordTypeId: ' + recordTypeId);
        
        if(String.isNotBlank(searchKey) && String.isNotBlank(sObjectApiName) && sObjectApiName.equalsIgnoreCase('User')){
            
            string sWildCardText = '%' + searchKey + '%';
            string sQuery = 'Select Id, Name From ' + sObjectApiName + ' Where Name Like : sWildCardText order by createdDate DESC LIMIT 5';
            for (sObject obj: database.query(sQuery)) {
                returnList.add(obj);
            }
        }
        
        if(String.isNotBlank(searchKey) && String.isNotBlank(sObjectApiName) && sObjectApiName.equalsIgnoreCase('Account')){
            string sWildCardText = '%' + searchKey + '%';
            string sQuery = 'Select Id, Name From ' + sObjectApiName + ' Where Name Like : sWildCardText AND RecordTypeId =: recordTypeId order by createdDate DESC LIMIT 5';
            for (sObject obj: database.query(sQuery)) {
                returnList.add(obj);
            }
        }
        System.debug('returnList: '+returnList);
        System.debug('returnList: '+returnList.size());
        return returnList;
    }
    
    @AuraEnabled 
    public static sObject fetchDefaultRecord(string recordId , string sObjectApiName, String projectId) {
        System.debug('fetchDefaultRecord: '+recordId);
        string sRecId = recordId;    
        string sQuery = 'Select Id,Name From ' + sObjectApiName + ' Where Id = : sRecId LIMIT 1';
        for (sObject obj: database.query(sQuery)) {
            System.debug('obj: '+obj);
            return obj;
        }
        
        return null;
    }
    
    @AuraEnabled
    public static SVWrapper getSVWrapper(String svRecordId){
        SVWrapper sv = new SVWrapper();
        List<Site_Visit__c> svList = new List<Site_Visit__c>();
        svList = [Select Id, Name, Lead_Source__c, Lead_Sub_Source__c, Channel_Partner__c, Channel_Partner__r.Name, Project__c, Project__r.Name, Opportunity__c,
                  Opportunity__r.Last_Source_Change_Date__c, Project__r.TAT_Days_for_Walkin__c, Referrer_Name__c, Referrer_Mobile__c, Referrer_Address__c, GRE__c, Gender__c,
                  Opportunity__r.Fist_SV_Date__c, Is_Preregister_Visit__c
                  from Site_visit__c where Id=: svRecordId];
        System.debug('svList: '+svList);
        if(!svList.isEmpty() && svList != null){
            sv.sv = svList[0];
        }
        System.debug('sv: '+sv);
        return sv;
    }
    
    @AuraEnabled
    public static void updateSiteVisit(svWrapper svWrapper){
        System.debug('svWrapper: '+svWrapper);
          List<Site_Visit__c> svList = new List<Site_Visit__c>();
         /*svList = [Select Id, Name from Site_Visit__c where Id =: svWrapper.sv.Id];
        System.debug('svList: '+svList);*/
        if(svWrapper != null){
            Site_Visit__c sv = svWrapper.sv;
            if(sv != null){
                svList.add(sv);
            }
            System.debug('svList: '+svList);
            if(svList != null){
                update svList;
            }
        }
        
    }
    

}