force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/MahaRERA_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>MahaRERA_Registration_No__c</fullName>
    <label>MahaRERA Registration No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/RERA_Available__c.field-meta.xml
<CustomField>
    <fullName>RERA_Available__c</fullName>
    <label>RERA Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CP_Document__c/CP_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CP Document</label>
</CustomObject>

force-app/main/default/objects/CP_Document__c/fields/Document_Required__c.field-meta.xml
<CustomField>
    <fullName>Document_Required__c</fullName>
    <label>Document Required</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Document No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pan Card</fullName>
            </value>
            <value>
                <fullName>GST Registration Certificate</fullName>
            </value>
            <value>
                <fullName>RERA Certificate</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/recordTypes/CP_Documents.recordType-meta.xml
<RecordType>
    <fullName>CP_Documents</fullName>
    <active>true</active>
    <label>CP Documents</label>
</RecordType>

force-app/main/default/classes/Ex_ChannelPartnerHandlerServices.cls
public class Ex_ChannelPartnerHandlerServices {
    
    public static void duplicationCheckOnCP(List<Channel_Partner__c> accountList) {
        Map<Channel_Partner__c, List<Ex_CPDuplicationHandlerServices.duplicateWrapper>> cpduplicateWrapperMap = new Map<Channel_Partner__c, List<Ex_CPDuplicationHandlerServices.duplicateWrapper>>();
        cpduplicateWrapperMap = Ex_CPDuplicationHandlerServices.duplicationCheckCPAcccount(accountList);
        System.debug('CPduplicateWrapperMap::'+cpduplicateWrapperMap);
        
        for(Channel_Partner__c cp: accountList) {
            if(cpduplicateWrapperMap.containsKey(cp)) {
                for(Ex_CPDuplicationHandlerServices.duplicateWrapper dw: cpduplicateWrapperMap.get(cp)) {
                    if(!test.isRunningTest())
                        cp.addError('Duplicate CP Account Found with Name: '+dw.dupAccount.Name + ' & MahaRERA Registration No. '+ dw.dupAccount.MahaRERA_Registration_No__c);
                }
            }
        }
    }
    
    public static void insertDocument(List<Channel_Partner__c> newCpList) {
        List<Document__c> cpDocumentList = new List<Document__c>();
        String customValues = '';
        Id recordTypeId = null;
        List<String> sList = new List<String>();
        
        if (!newCpList.isEmpty() && newCpList != null) {
            for (Channel_Partner__c cp : newCpList) {
                if(cp.RERA_Available__c != null){
                customValues = CP_Document__c.getValues(cp.RERA_Available__c).Document_Required__c;
                }
                System.debug('customValues::' + customValues);
                
                if (String.isNotBlank(customValues)) {
                    sList = customValues.split(',');
                    System.debug('string list=' + sList);
                }
                
                if (!sList.isEmpty() && sList != null) {
                    for (String s : sList) {
                        System.debug('document type :' + s);
                        Document__c cpd = new Document__c();
                        cpd.Document_Type__c = s;
                        cpd.RecordTypeId = Schema.SObjectType.Document__c
                            .getRecordTypeInfosByDeveloperName()
                            .get('CP_Documents')
                            .getRecordTypeId();
                        cpd.Channel_Partner__c = cp.Id;
                        cpDocumentList.add(cpd);
                        System.debug('cpDocumentList' + cpDocumentList);
                    }
                }
            }
        }
        
        if (!cpDocumentList.isEmpty() && cpDocumentList != null) {
            insert cpDocumentList;
        }
    }
    
    public static void updateDocument(List<Channel_Partner__c> accountList) {
        Set<Id> accountIds = new Set<Id>();
        List<Document__c> cpDocumentList = new List<Document__c>();
        Set<String> existingDocumentTypes = new Set<String>();
        String customValues = '';
        
        for (Channel_Partner__c a : accountList) {
            accountIds.add(a.Id);
        }
        
        List<Document__c> existingDocuments = [SELECT Id, Document_Type__c, Channel_Partner__c
                                               FROM Document__c
                                               WHERE Channel_Partner__c IN :accountIds];
        
        for (Document__c existingDoc : existingDocuments) {
            existingDocumentTypes.add(existingDoc.Document_Type__c);
        }
        
        for (Channel_Partner__c a : accountList) {
            if(a.RERA_Available__c != null)
            customValues = CP_Document__c.getValues(a.RERA_Available__c).Document_Required__c;
            
            List<String> sList = customValues.split(',');
            System.debug('string list=' + sList);
            
            for (String s : sList) {
                System.debug('document type=' + s);
                if (!existingDocumentTypes.contains(s)) {
                    Document__c cpd = new Document__c();
                    cpd.Document_Type__c = s; 
                    cpd.Channel_Partner__c = a.Id;
                    cpd.RecordTypeId = Schema.SObjectType.Document__c.getRecordTypeInfosByDeveloperName().get('CP_Documents').getRecordTypeId();
                    
                    cpDocumentList.add(cpd);
                    System.debug('cpDocumentList' + cpDocumentList);
                }
            }
        }
        
        if (!cpDocumentList.isEmpty() && cpDocumentList != null) {
            insert cpDocumentList;
        }
    }
}