force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/MahaRERA_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>MahaRERA_Registration_No__c</fullName>
    <label>MahaRERA Registration No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/RERA_Available__c.field-meta.xml
<CustomField>
    <fullName>RERA_Available__c</fullName>
    <label>RERA Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CP_Document__c/CP_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CP Document</label>
</CustomObject>

force-app/main/default/objects/CP_Document__c/fields/Document_Required__c.field-meta.xml
<CustomField>
    <fullName>Document_Required__c</fullName>
    <label>Document Required</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/CP_Project__c.object-meta.xml
<CustomObject>
    <label>CP Project</label>
    <nameField>
        <displayFormat>CPP-{00000}</displayFormat>
        <label>CP Project No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/CP_Account__c.field-meta.xml
<CustomField>
    <fullName>CP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>CP Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Document No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/CP_Account__c.field-meta.xml
<CustomField>
    <fullName>CP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pan Card</fullName>
            </value>
            <value>
                <fullName>GST Registration Certificate</fullName>
            </value>
            <value>
                <fullName>RERA Certificate</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document__c/recordTypes/CP_Document.recordType-meta.xml
<RecordType>
    <fullName>CP_Document</fullName>
    <active>true</active>
    <label>CP Document</label>
</RecordType>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Pan_No__c.field-meta.xml
<CustomField>
    <fullName>Pan_No__c</fullName>
    <label>Pan No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Visits (Channel Partner)</relationshipLabel>
    <relationshipName>Site_Visits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Google</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Aggregators</fullName>
            </value>
            <value>
                <fullName>Organic</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Television</fullName>
            </value>
            <value>
                <fullName>Hoarding</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>WhatsApp</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Reference</fullName>
            </value>
            <value>
                <fullName>VDNB</fullName>
            </value>
            <value>
                <fullName>Cold Calling</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestEx_GREUpdateDetails.cls
@isTest
public class TestEx_GREUpdateDetails {

    @testSetup
    static void setupTestData() {
        // Query for the existing Channel Partner Record Type
        RecordType rt = [SELECT Id FROM RecordType WHERE DeveloperName = 'Channel_Partner' LIMIT 1];
        
        
        CP_Document__c cpd = new CP_Document__c();
        cpd.Name = 'Yes';
        cpd.Document_Required__c = 'Aadhaar Card,Pan Card,GST Registration Certificate,RERA Certificate,RERA Competency Certificate';
        insert cpd;
        
        CP_Document__c cpd2 = new CP_Document__c();
        cpd2.Name = 'No';
        cpd2.Document_Required__c = 'Aadhaar Card,Pan Card';
        insert cpd2;

        // Create an Account with the Channel Partner Record Type
        Account channelPartner = new Account(
            Name = 'Test Channel Partner',
            RecordTypeId = rt.Id,
            PAN_NO__c='6774',
            RERA_Available__c='Yes',
            MahaRERA_Registration_No__c = '7878756'
        );
        insert channelPartner;
        
        Document__c cpDoc = new Document__c();
        cpDoc.CP_Account__c = channelPartner.Id;
        cpDoc.RecordTypeId = Schema.SObjectType.Document__c.getRecordTypeInfosByDeveloperName().get('CP_Document').getRecordTypeId();        
        cpDoc.Uploaded__c = false;
        cpDoc.Document_Type__c = 'Pan Card';
        cpDoc.Document_Upload_Required__c='yes';
        insert cpDoc;

       
        
        
        
        
        // Create a Project
        Project__c project = new Project__c(
            Name = 'Test Project'
        );
        insert project;

        // Create a CP_Project__c record
        CP_Project__c cpProject = new CP_Project__c(
            Channel_Partner__c = channelPartner.Id,
            Project_Name__c = project.Id
        );
        insert cpProject;

        // Create a Site Visit record
        Site_Visit__c siteVisit = new Site_Visit__c(
            //Name = 'Test Site Visit',
            Lead_Source__c = 'Channel Partner',
            Channel_Partner__c = channelPartner.Id,
            Project__c = project.Id
        );
        insert siteVisit;
    }

    @isTest
    static void testFetchLookupData_Account() {
        Test.startTest();
        // Test the Account lookup functionality
        List<sObject> accounts = Ex_GREUpdateDetails.fetchLookupData('Test', 'Account');
        Test.stopTest();
    }

    @isTest
    static void testFetchLookupData_User() {
        Test.startTest();
        // Test the User lookup functionality
        List<sObject> users = Ex_GREUpdateDetails.fetchLookupData('Test', 'User');
        Test.stopTest();
    }

    @isTest
    static void testGetSVWrapper() {
        // Query the created Site Visit from setup data
        Site_Visit__c siteVisit = [SELECT Id FROM Site_Visit__c LIMIT 1];

        Test.startTest();
        // Call the method
        Ex_GREUpdateDetails.SVWrapper svWrapper = Ex_GREUpdateDetails.getSVWrapper(siteVisit.Id);
        Test.stopTest();
    }

    @isTest
    static void testUpdateSiteVisit() {
        // Query the created Site Visit from setup data
        Site_Visit__c siteVisit = [SELECT Id, Lead_Source__c, Channel_Partner__c, Project__c FROM Site_Visit__c LIMIT 1];

        // Create a wrapper
        Ex_GREUpdateDetails.SVWrapper svWrapper = new Ex_GREUpdateDetails.SVWrapper();
        svWrapper.sv = siteVisit;

        Test.startTest();
        // Call the updateSiteVisit method
        Ex_GREUpdateDetails.updateSiteVisit(svWrapper);

        // Verify that the Site Visit is updated
        Site_Visit__c updatedSV = [SELECT Id, CP_Project__c FROM Site_Visit__c WHERE Id = :siteVisit.Id];
        Test.stopTest();
    }
}