force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/MahaRERA_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>MahaRERA_Registration_No__c</fullName>
    <label>MahaRERA Registration No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Document No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pan Card</fullName>
            </value>
            <value>
                <fullName>GST Registration Certificate</fullName>
            </value>
            <value>
                <fullName>RERA Certificate</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestEx_CPDocumentUploadController.cls
@isTest
public class TestEx_CPDocumentUploadController {
	@isTest
    public static void testMethod1(){
        test.startTest();
        Channel_Partner__c acc = new Channel_Partner__c();
        acc.Name = 'Test Account';
        acc.Mobile__c = '1234567892';
        acc.MahaRERA_Registration_No__c = 'abcdefghijklm';
        acc.PAN_No__c = 'ABCDE6312P';
        insert acc;
        
        Channel_Partner__c acc1 = new Channel_Partner__c();
        acc1.Name = 'Test Account2';
        acc1.Mobile__c = '1234567892';
        acc1.MahaRERA_Registration_No__c = 'abcdefghijkln';
        acc1.PAN_No__c = 'ABCDE2312O';
        insert acc1;
        
         Channel_Partner__c acc2 = new Channel_Partner__c();
        acc2.Name = 'Test Account2';
        acc2.Mobile__c = '1234567802';
        acc2.PAN_No__c = 'ABCDE2312O';
        acc2.MahaRERA_Registration_No__c = 'abcdefghijklo';
        insert acc2;
        
        Channel_Partner__c acc3 = new Channel_Partner__c();
        acc3.Name = 'Test Account2';
        acc3.Mobile__c = '1234567809';
        acc3.PAN_No__c = 'ABCDE2312I';
        acc3.MahaRERA_Registration_No__c = 'abcdefghijklo';
        insert acc3;

        
        Document__c d = new Document__c();
        d.Document_Type__c = 'Pan Card';
        d.Channel_Partner__c = acc.Id;
        d.Uploaded__c = false;
        insert d;
        
        String base64Data = EncodingUtil.base64Encode(Blob.valueOf('Test Content'));
        String cpDocumentList = '[{"Uploaded__c": true, "Id": "' + d.Id + '", "base64": "' + base64Data + '", "filename": "testfile.txt"}]';
        
        Id resultId = Ex_CPDocumentUploadController.uploadFile(cpDocumentList);
        Document__c updatedDocument = [SELECT Id, Uploaded__c FROM Document__c WHERE Id = :resultId];
        
        ContentVersion cv = [SELECT Id, Title FROM ContentVersion WHERE Title = 'testfile.txt'];
        
        ContentDocumentLink cdl = [SELECT Id, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId = :updatedDocument.Id];
        
        Ex_CPDocumentUploadController.getCPDocumentDetails(d.Channel_Partner__c);
        test.stopTest();
    }
}