force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/CP_Project__c.object-meta.xml
<CustomObject>
    <label>CP Project</label>
    <nameField>
        <displayFormat>CPP-{00000}</displayFormat>
        <label>CP Project No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/CP_Account_Id__c.field-meta.xml
<CustomField>
    <fullName>CP_Account_Id__c</fullName>
    <inlineHelpText>It is used for matching duplicate rule</inlineHelpText>
    <label>CP Account Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Ex_CPProjectTriggerHandlerServices.cls
public class Ex_CPProjectTriggerHandlerServices {
    public static void assignCPAccountId(Boolean isUpdateCP, List<CP_Project__c> cpProjectList){
        for(CP_Project__c cp:  cpProjectList){
            if(cp.Channel_Partner__c != null){
                cp.CP_Account_Id__c = cp.Channel_Partner__c;
                if(isUpdateCP){
                    cp.CP_Account_Id__c = cp.Channel_Partner__c;
                }
            }
        }
    }
}