force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Lead__c/CP_Lead__c.object-meta.xml
<CustomObject>
    <label>CP Lead</label>
    <nameField>
        <displayFormat>CPL-{00000}</displayFormat>
        <label>CP Lead No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Lead__c/fields/Channel_Partner_Name__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CP Leads</relationshipLabel>
    <relationshipName>CP_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Lead__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>CP Leads</relationshipLabel>
    <relationshipName>CP_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Leads</relationshipLabel>
    <relationshipName>CP_Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/CP_Project__c.object-meta.xml
<CustomObject>
    <label>CP Project</label>
    <nameField>
        <displayFormat>CPP-{00000}</displayFormat>
        <label>CP Project No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Ex_CPLeadHandlerServices.cls
/**
* @File Name : Ex_CPLeadHandlerServices.cls
* @Description : for CP Document Upload 
* @Author : Nitin Choudhary
* @Last Modified By : Nitin Choudhary
* @Last Modified On : September 19, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | September 18, 2024 |   | Initial Version
**/
public class Ex_CPLeadHandlerServices {
    public static void duplicationCheck(String performRoundRobin, List<CP_Lead__c> leadList) {
        Map<CP_Lead__c, List<Ex_DuplicationHandlerServices.duplicateWrapper>> duplicateWrapperMap = Ex_DuplicationHandlerServices.duplicationCheckCPLead(leadList);
        List<CP_Lead__c> CPProjectForAssignment = new List<CP_Lead__c>();
        
        for(CP_Lead__c l : leadList) {
            String errMsg = '';
            if (duplicateWrapperMap.containsKey(l)) {
                for (Ex_DuplicationHandlerServices.duplicateWrapper dw : duplicateWrapperMap.get(l)) {
                    System.debug('dw: '+dw);
                    if (dw.objectType.equalsIgnoreCase('CP Lead'))
                        errMsg = 'Duplicate CP Lead Found With Record Id is ' + dw.dupCPLead.Id;
                    else if (dw.objectType.equalsIgnoreCase('Account'))
                        errMsg = 'Duplicate Account Found With Name: ' + dw.dupAccount.LastName +' Owner Name: '+ dw.dupAccount.Owner.Name + '. Record Id is ' + dw.dupAccount.Id;
                }
                if (!Test.isRunningTest() && errMsg != '')
                    l.addError(errMsg);
            } else {
                if(l.Channel_Partner_Name__c != null && l.Project__c != null/* && performRoundRobin.equalsIgnoreCase('Yes')*/) {
                    CPProjectForAssignment.add(l);
                }
            }
            
        }
        if(!CPProjectForAssignment.isEmpty() && CPProjectForAssignment != null) {
            AssignCPProject(CPProjectForAssignment);
        }
    }
    
    public static void AssignCPProject(List<CP_Lead__c> CPProjectForAssignment) {
        Map<String, CP_Project__c> cpProjectMap = new Map<String, CP_Project__c>();
        Set<Id> channelPartnerIds = new Set<Id>();
        Set<Id> projectIds = new Set<Id>();
        List<CP_Project__c> cpProjects = new List<CP_Project__c>();
        
        
        for (CP_Lead__c lead : CPProjectForAssignment) {
            if (lead.Channel_Partner_Name__c != null) {
                channelPartnerIds.add(lead.Channel_Partner_Name__c);
            }
            if (lead.Project__c != null) {
                projectIds.add(lead.Project__c);
            }
        }
        
        if(!channelPartnerIds.isEmpty() && projectIds != null){
            cpProjects = [SELECT Id, Channel_Partner__c, Project_Name__c FROM CP_Project__c
                          WHERE Channel_Partner__c IN :channelPartnerIds AND Project_Name__c IN :projectIds
                         ];
        }
        System.debug('cpProjects: '+cpProjects);
        
        if(!cpProjects.isEmpty() && cpProjects != null){
            for (CP_Project__c cpProject : cpProjects) {
                if(!cpProjectMap.containsKey(cpProject.Channel_Partner__c + '-' + cpProject.Project_Name__c)) {
                    cpProjectMap.put(cpProject.Channel_Partner__c + '-' + cpProject.Project_Name__c, cpProject);
                } else {
                    cpProjectMap.get(cpProject.Channel_Partner__c + '-' + cpProject.Project_Name__c);
                }
            }
        }
        System.debug('cpProjectMap: '+cpProjectMap);
        if(!cpProjectMap.isEmpty() && cpProjectMap != null){
            for (CP_Lead__c lead : CPProjectForAssignment) {
                if(!cpProjectMap.containsKey(lead.Channel_Partner_Name__c + '-' + lead.Project__c)) {
                    lead.CP_Project__c = cpProjectMap.get(lead.Channel_Partner_Name__c + '-' + lead.Project__c).Id; 
                } else {
                    lead.CP_Project__c = cpProjectMap.get(lead.Channel_Partner_Name__c + '-' + lead.Project__c).Id; 
                }
            }
        }
    } 
}