force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/MahaRERA_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>MahaRERA_Registration_No__c</fullName>
    <label>MahaRERA Registration No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/RERA_Available__c.field-meta.xml
<CustomField>
    <fullName>RERA_Available__c</fullName>
    <label>RERA Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CP_Document__c/CP_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CP Document</label>
</CustomObject>

force-app/main/default/objects/CP_Document__c/fields/Document_Required__c.field-meta.xml
<CustomField>
    <fullName>Document_Required__c</fullName>
    <label>Document Required</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/CP_Project__c.object-meta.xml
<CustomObject>
    <label>CP Project</label>
    <nameField>
        <displayFormat>CPP-{00000}</displayFormat>
        <label>CP Project No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/CP_Account__c.field-meta.xml
<CustomField>
    <fullName>CP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>CP Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Document No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/CP_Account__c.field-meta.xml
<CustomField>
    <fullName>CP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pan Card</fullName>
            </value>
            <value>
                <fullName>GST Registration Certificate</fullName>
            </value>
            <value>
                <fullName>RERA Certificate</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Pan_No__c.field-meta.xml
<CustomField>
    <fullName>Pan_No__c</fullName>
    <label>Pan No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestEx_CpDocumentUpload.cls
@isTest
public class TestEx_CpDocumentUpload {
    @isTest
    Public static void testCpDocument()  {
        Test.startTest();
        CP_Document__c cpd = new CP_Document__c();
        cpd.Name = 'Yes';
        cpd.Document_Required__c = 'PAN Card,RERA Competency Certificate,GST Registration Certificate,RERA Certificate';
        insert cpd;
        
         CP_Document__c cpd2 = new CP_Document__c();
        cpd2.Name = 'No';
        cpd2.Document_Required__c = 'PAN Card,RERA Competency Certificate';
        insert cpd2;
        
        Id cpAccountRecordTypeId = SObjectType.Account.getRecordTypeInfosByName().get('Channel Partner').getRecordTypeId();
        
         //if(cp.RERA_Available__c != null){
        Account cpAccount = new Account();
        cpAccount.Name = 'Test CP1';
        cpAccount.Name_as_per_MahaRERA__c = 'Prop Tiger';
        cpAccount.RERA_Available__c = 'No';
        cpAccount.Phone = '9876543210';
        cpAccount.PAN_No__c = 'ABCDE1234A';
        cpAccount.RecordTypeId =cpAccountRecordTypeId;
        insert cpAccount;
        
         // Insert Project
        Project__c p = new Project__c();
        p.Name = 'Test Project';
        insert p;
        // Insert Project2
        Project__c p2 = new Project__c();
        p2.Name = 'Test Project2';
        insert p2;
        
        cp_Project__c cppPr1 = new cp_Project__c ();
        cppPr1.Channel_Partner__c = cpAccount.id;
        cppPr1.Project_Name__c = p.id;
        insert cppPr1;
        
        cppPr1.Project_Name__c = p2.id;
        update cppPr1;
        
         Account cpAccount1 = new Account();
        cpAccount1.Name = 'Test CP2';
        cpAccount1.Name_as_per_MahaRERA__c = 'Prop Tiger';
        cpAccount1.RERA_Available__c = 'No';
        cpAccount1.Phone = '9876543210';
        cpAccount1.PAN_No__c = 'ABCDE1234A';
        cpAccount1.RecordTypeId =cpAccountRecordTypeId;
        insert cpAccount1;
         
        Account cpAccount2 = new Account();
        cpAccount2.Name = 'Test CP3';
        cpAccount2.Name_as_per_MahaRERA__c = 'Prop Tiger';
        cpAccount2.RERA_Available__c = 'Yes';
        cpAccount2.MahaRERA_Registration_No__c = '1232123ASAS';
        cpAccount2.Phone = '9876543210';
        cpAccount2.PAN_No__c = 'ABCDE1234A';
        cpAccount2.RecordTypeId =cpAccountRecordTypeId;
        insert cpAccount2;
        
        
        cpAccount.Phone = '9876543211';
        cpAccount.PAN_No__c = 'ABCDE1234A';
        update cpAccount;
        
        Account cpAccount4 = new Account();
        cpAccount4.Name = 'Test CP4';
        cpAccount4.Name_as_per_MahaRERA__c = 'Prop Tiger';
        cpAccount4.RERA_Available__c = 'Yes';
        cpAccount4.MahaRERA_Registration_No__c = '1232123ASAS';
        cpAccount4.Phone = '9876543210';
        cpAccount4.PAN_No__c = 'ABCDE1234A';
        cpAccount4.RecordTypeId =cpAccountRecordTypeId;
        insert cpAccount4;
        
        Document__c doc = new Document__c();
        doc.Document_Type__c = 'RERA Certificate';
        doc.RecordTypeId = SObjectType.Document__c.getRecordTypeInfosByName().get('Applicant Document').getRecordTypeId();
        doc.CP_Account__c = cpAccount4.Id;
		insert doc;
        
        String cpDocList ='[{"Id":"'+ String.valueOf(doc.Id) +'","Name":"D-0242","Document_Type__c":"RERA Certificate","Channel_Partner__c":"' + String.valueOf(cpAccount4.Id) + '","Uploaded__c":true,"isUploadedFalse":true,"isUploadedTrue":false,"filename":"Aadhar.png","base64":"base64"}]';
        Ex_CPDocumentUploadController.getCPDocumentDetails(cpd.id);
        Ex_CPDocumentUploadController.uploadFile(cpDocList);
        
      
         Test.StopTest();
    }
}