force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/MahaRERA_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>MahaRERA_Registration_No__c</fullName>
    <label>MahaRERA Registration No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/RERA_Available__c.field-meta.xml
<CustomField>
    <fullName>RERA_Available__c</fullName>
    <label>RERA Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CP_Document__c/CP_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CP Document</label>
</CustomObject>

force-app/main/default/objects/CP_Document__c/fields/Document_Required__c.field-meta.xml
<CustomField>
    <fullName>Document_Required__c</fullName>
    <label>Document Required</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/CP_Project__c.object-meta.xml
<CustomObject>
    <label>CP Project</label>
    <nameField>
        <displayFormat>CPP-{00000}</displayFormat>
        <label>CP Project No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Pan_No__c.field-meta.xml
<CustomField>
    <fullName>Pan_No__c</fullName>
    <label>Pan No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestEx_ChannelPartnerHandlerServices.cls
@isTest
public class TestEx_ChannelPartnerHandlerServices {

   @isTest
    static void testCPduplicationCheck(){
        Test.startTest();
        CP_Document__c cpDoc = new CP_Document__c();
        cpDoc.Name = 'Yes';
        cpDoc.Document_Required__c = 'PAN Card,RERA Competency Certificate,GST Registration Certificate,RERA Certificate';
        insert cpDoc;
        
        CP_Document__c cpDoc1 = new CP_Document__c();
        cpDoc1.Name = 'No';
        cpDoc1.Document_Required__c = 'PAN Card,RERA Competency Certificate';
        insert cpDoc1;
        
        // Create test data
        Channel_Partner__c cp1 = new Channel_Partner__c(
            Name = 'CP1',
            Mobile__c = '1234567891',
            MahaRERA_Registration_No__c = 'MH123',
            PAN_No__c = 'ABCDE1234F',
            RERA_Available__c = 'Yes'
        );
        insert cp1;
        
        Channel_Partner__c cp2 = new Channel_Partner__c(
            Name = 'CP2',
            Mobile__c = '1234567890', 
            MahaRERA_Registration_No__c = 'MH124',
            PAN_No__c = 'ABCDE1234E'
           
        );
        insert cp2;
        
        Channel_Partner__c cp3 = new Channel_Partner__c(
            Name = 'CP3',
            Mobile__c = '0987654321',
            MahaRERA_Registration_No__c = 'MH125',
            PAN_No__c = 'FGHIJ5678K'
        );
        insert cp3;
            
        cp3.Mobile__c = '0987654328';
        update cp3;
        
          // Insert Project
        Project__c p = new Project__c();
        p.Name = 'Test Project';
        insert p;
        // Insert Project2
        Project__c p2 = new Project__c();
        p2.Name = 'Test Project2';
        insert p2;
        
        cp_Project__c cppPr1 = new cp_Project__c ();
        
        cppPr1.Channel_Partner__c = cp1.id;
        cppPr1.Project__c = p.id;
        insert cppPr1;
        
         cppPr1.Project__c = p2.id;
        update cppPr1;
        
        cp_Project__c cppPr2 = new cp_Project__c ();
        
        cppPr2.Channel_Partner__c = cp1.id;
        cppPr2.Project__c = p.id;
        insert cppPr2;
        
         cppPr2.Project__c = p2.id;
        update cppPr2;
        
        
        Test.stopTest();
    }
}