force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/MahaRERA_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>MahaRERA_Registration_No__c</fullName>
    <label>MahaRERA Registration No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/RERA_Available__c.field-meta.xml
<CustomField>
    <fullName>RERA_Available__c</fullName>
    <label>RERA Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ex_ChannelPartnerTriggerHandler.cls
public class Ex_ChannelPartnerTriggerHandler { 
    public static void afterInsert(List<Channel_Partner__c> cpList){
        List<Channel_Partner__c> newCpList = new List<Channel_Partner__c>();
        
        for(Channel_Partner__c cp: cpList) {
            newCpList.add(cp);
        }
        if(!newCpList.isEmpty() && newCpList != null )
            Ex_ChannelPartnerHandlerServices.insertDocument(newCpList);
        Ex_ChannelPartnerHandlerServices.duplicationCheckOnCP(newCpList);
    }
    
    public static void afterUpdate(Map<Id, Channel_Partner__c> oldMap, Map<Id, Channel_Partner__c> newMap) {
        List<Channel_Partner__c> cpList = new List<Channel_Partner__c>();
        
        for(Channel_Partner__c oldCPAccount: oldMap.values()) {
            Channel_Partner__c newCPAccount = newMap.get(oldCPAccount.Id);
            
            if((oldCPAccount.Mobile__c != newCPAccount.Mobile__c || oldCPAccount.PAN_No__c != newCPAccount.PAN_No__c || oldCPAccount.MahaRERA_Registration_No__c != newCPAccount.MahaRERA_Registration_No__c))
            {
                cpList.add(newCPAccount);
            }
            
            if(oldCPAccount.RERA_Available__c != newCPAccount.RERA_Available__c && newCPAccount.RERA_Available__c == 'Yes')
            { 
                cpList.add(newCPAccount);
            }                       
        }
        
        if(!cpList.isEmpty() && cpList != null){
            Ex_ChannelPartnerHandlerServices.updateDocument(cpList);
            Ex_ChannelPartnerHandlerServices.duplicationCheckOnCP(cpList);
        }
    }    
}