force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/CP_Project__c.object-meta.xml
<CustomObject>
    <label>CP Project</label>
    <nameField>
        <displayFormat>CPP-{00000}</displayFormat>
        <label>CP Project No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ex_CPProjectTriggerHandler.cls
public class Ex_CPProjectTriggerHandler {
     public static void beforeInsert(List<CP_Project__c> cpProjectList) {
        List<CP_Project__c> lList = new List<CP_Project__c>();
        
        for(CP_Project__c l: cpProjectList) {
            lList.add(l);
        }
        if(!lList.isEmpty() && lList != null)
            Ex_CPProjectTriggerHandlerServices.assignCPAccountId(false, lList);
    }
    
    public static void beforeUpdate(Map<Id, CP_Project__c> oldMap, Map<Id, CP_Project__c> newMap) {
        List<CP_Project__c> lList = new List<CP_Project__c>();
        
        for(CP_Project__c oldCPProject: oldMap.values()) {
            CP_Project__c newCPProject = newMap.get(oldCPProject.Id);
            
            if(oldCPProject.Channel_Partner__c != newCPProject.Channel_Partner__c && newCPProject.Channel_Partner__c != null)
            {
                lList.add(newCPProject);   
            }
                
        }
        if(!lList.isEmpty() && lList != null)
            Ex_CPProjectTriggerHandlerServices.assignCPAccountId(true, lList);
    }

}