force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partner</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/CP_Type__c.field-meta.xml
<CustomField>
    <fullName>CP_Type__c</fullName>
    <label>CP Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CP_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/MahaRERA_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>MahaRERA_Registration_No__c</fullName>
    <label>MahaRERA Registration No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/RERA_Available__c.field-meta.xml
<CustomField>
    <fullName>RERA_Available__c</fullName>
    <label>RERA Available</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CP_Document__c/CP_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CP Document</label>
</CustomObject>

force-app/main/default/objects/CP_Document__c/fields/Document_Required__c.field-meta.xml
<CustomField>
    <fullName>Document_Required__c</fullName>
    <label>Document Required</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/CP_Project__c.object-meta.xml
<CustomObject>
    <label>CP Project</label>
    <nameField>
        <displayFormat>CPP-{00000}</displayFormat>
        <label>CP Project No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/fields/CP_Account__c.field-meta.xml
<CustomField>
    <fullName>CP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>CP Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <formula>Account__r.Alternate_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria.
Please select different CP Project</errorMessage>
        <filterItems>
            <field>CP_Project__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Opportunity Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Site_Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Count__c</fullName>
    <label>Site Visit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GRE QR User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Is_Sales_Manager_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Is_Sales_Manager_Assigned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sales Manager Assigned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Opportunity Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Follow-up</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Team_Type__c.field-meta.xml
<CustomField>
    <fullName>Team_Type__c</fullName>
    <label>Team Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Presales Team</fullName>
            </value>
            <value>
                <fullName>Sales Team</fullName>
            </value>
            <value>
                <fullName>Unapproved Discount Team</fullName>
            </value>
            <value>
                <fullName>Booking Approval</fullName>
                <isActive>false</isActive>
                <label>Booking Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Availability__c.field-meta.xml
<CustomField>
    <fullName>Availability__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Availability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/DayOff__c.field-meta.xml
<CustomField>
    <fullName>DayOff__c</fullName>
    <defaultValue>false</defaultValue>
    <label>DayOff</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sequence Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Site_Visit__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Visit</label>
    <referenceTo>Site_Visit__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/CP_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ICP</fullName>
    </customValue>
    <customValue>
        <fullName>RCP</fullName>
    </customValue>
    <customValue>
        <fullName>IPC</fullName>
    </customValue>
    <masterLabel>CP Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Opportunity_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Follow-up</fullName>
        <default>true</default>
        <label>In Follow-up</label>
    </customValue>
    <customValue>
        <fullName>Booking In-Process</fullName>
    </customValue>
    <customValue>
        <fullName>Booked</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation In-Process</fullName>
    </customValue>
    <masterLabel>Opportunity Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/test_Ex_teamMemberTriggerHandler.cls
@isTest
public class test_Ex_teamMemberTriggerHandler {
	@isTest
    public static void test_Ex_teamMemberTriggerHandler(){
        List<Team_Member__c> teamMemberList = new List<Team_Member__c>();
        Set<Id> teamSet = new Set<Id>();
        Test.startTest();
        
        Project__c p = new Project__c();
        p.Name = 'Satyam Group';
        insert p;
        
        Team__c t = new Team__c();
        t.Name = 'Test Sales Team';
        t.Project__c = p.Id;
        t.Team_Type__c = 'Sales Team';
        insert t;
        
        Team_Member__c tm = new Team_Member__c();
        tm.Name = 'test team member';
        tm.Sequence_Number__c = 1;
        tm.Team__c = t.Id;
		tm.Availability__c = false;
        tm.User__c = userInfo.getUserId();
        insert tm;
        
        Team_Member__c tm1 = new Team_Member__c();
        tm1.Name = 'test team member';
        tm1.Sequence_Number__c = 1;
        tm1.Team__c = t.Id;
		tm1.Availability__c = false;
        tm1.DayOff__c = true;
        tm1.User__c = userInfo.getUserId();
        insert tm1;
        
        Team_Member__c tm3 = new Team_Member__c();
        tm3.Name = 'test team member';
        tm3.Sequence_Number__c = 1;
        tm3.Team__c = t.Id;
		tm3.Availability__c = false;
        tm3.DayOff__c = FALSE;
        tm3.User__c = userInfo.getUserId();
        insert tm3;
        
        tm.Availability__c = true;
        update tm;
        tm3.Availability__c = true;
        update tm3;
        
        
        // Create a test CP_Document__c custom setting record for RERA_Available__c set to 'Yes'
        CP_Document__c cpd = new CP_Document__c();
        cpd.Name='Yes';
        cpd.Document_Required__c='Pan Card, GST Registration Certificate, RERA Certificate, Passport';
        insert cpd;
        
        // Create a test record for Account with RERA_Available__c set to 'Yes'
        Account testAccount = new Account(
            Name = 'Test Account',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('CP Account').getRecordTypeId(),
            RERA_Available__c = 'Yes',
            MahaRERA_Registration_No__c = 'mah123',
            CP_Type__c = 'ICP',
            Owner_Name__c = 'Test',
            Owner_Mobile_No__c = '8989898989',
            Name_as_per_MahaRERA__c = 'testt'
        );
        
        Account testAccount1 = new Account(
            Name = 'Test Account',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('CP Account').getRecordTypeId(),
            RERA_Available__c = 'Yes',
            MahaRERA_Registration_No__c = 'mah123',
            CP_Type__c = 'ICP',
            Owner_Name__c = 'Test',
            Owner_Mobile_No__c = '8989898989',
            Name_as_per_MahaRERA__c = 'testt'
        );
        
        CP_Project__c cp1 = new CP_Project__c();
        cp1.Project__c = p.Id;
        cp1.CP_Account__c = testAccount1.Id;
        insert cp1;
        
        String RecTypeId= Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        Account a2 = new Account(Salutation = 'Mr.' , FirstName = 'Test', LastName = 'Lead 2', PersonMobilePhone = '1122334456', PersonEmail = 'lead2@test.in', Alternate_Email__c = 'lead@test.in',RecordTypeId = RecTypeId);
        insert a2;
        Opportunity__c o1 = new Opportunity__c(Name = 'Test1', Opportunity_Stage__c = 'In Follow-up', Project__c = p.Id,Account__c = a2.id);
        insert o1;
        
        Opportunity__c o2 = new Opportunity__c(Name = 'Test1', Opportunity_Stage__c = 'In Follow-up', Project__c = p.Id,Account__c = a2.id);
        insert o2; 
        
        Site_Visit__c sv = new Site_Visit__c();
        sv.Is_Sales_Manager_Assigned__c = false;
        sv.Sales_Manager__c = null;
        sv.Project_Name__c = p.Id;
        sv.Opportunity__c = o1.Id;
        sv.Site_Visit_Count__c = 1;
       	sv.Comment__c = 'Test';
        insert sv;
        
        sv.Comment__c = 'tetsttt';
        update sv;
        
        Site_Visit__c sv1 = new Site_Visit__c();
        sv1.Is_Sales_Manager_Assigned__c = false;
        sv1.Sales_Manager__c = null;
        sv1.Project_Name__c = p.Id;
        sv1.Opportunity__c = o2.Id;
        sv1.Site_Visit_Count__c = 2;
        insert sv1;
                List<Site_Visit__c> svList = new  List<Site_Visit__c>();

        Site_Visit__c sv2 = new Site_Visit__c();
        sv2.Is_Sales_Manager_Assigned__c = false;
        sv2.Sales_Manager__c = null;
        sv2.Project_Name__c = p.Id;
        sv2.Opportunity__c = o2.Id;
        sv2.Site_Visit_Count__c = 2;
        sv2.Lead_Source__c = 'Channel Partner';
        sv2.Channel_Partner__c = testAccount1.id;
        sv2.CP_Project__c = cp1.id;
        insert sv2;
        svList.add(sv2);
        
     
        
        Ex_SiteVisitTriggerHandler.updateCPOnOppo(svList);
        
        o2.Lead_Source__c = 'Channel Partner';
        o2.Channel_Partner__c = testAccount1.id;
        o2.CP_Project__c = cp1.id;
        update o2; 
        Ex_SiteVisitHandlerServices.rollupOnOpportunity(sv1);
        Ex_SiteVisitHandlerServices.appCPProjectOnSV(svList);
        
        
        teamSet.add(tm.Id);
        teamSet.add(tm1.Id);
        teamSet.add(tm3.Id);
        
        
      Ex_SiteVisitHandlerServices.updateSalesManagerAvailability(teamSet);///rollupOnOpportunity
        
        
        Test.stopTest();
    }
    
    // Test method to cover the handler logic
    static testMethod void testHandlerLogic() {
        // Create test data
        Team__c testTeam = new Team__c(Name = 'Test Team');
        insert testTeam;
        
        Team_Member__c testMember = new Team_Member__c(Name = 'Test Member', Team__c = testTeam.Id);
        insert testMember;
        
        // Modify the test data (simulate before update operation)
        testMember.Name = 'Updated Test Member';
        update testMember;
        
        // Call the handler method (assuming you have a method to handle the trigger logic)
        Ex_TeamMemberTriggerHandler.beforeupdate();
        
        
        
        
    }
}