force-app/main/default/objects/CP_Project__c/CP_Project__c.object-meta.xml
<CustomObject>
    <label>CP Project</label>
    <nameField>
        <displayFormat>CPP-{00000}</displayFormat>
        <label>CP Project No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria.
Please select different CP Project</errorMessage>
        <filterItems>
            <field>CP_Project__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>Account__r.PersonContact.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Site_Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Count__c</fullName>
    <label>Site Visit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>AComments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Is_Sales_Manager_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Is_Sales_Manager_Assigned__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Sales Manager Assigned</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Site_Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Site Visit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/SM_Assignment_Date__c.field-meta.xml
<CustomField>
    <fullName>SM_Assignment_Date__c</fullName>
    <label>SM Assignment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Ex_SiteVisitTriggerHandler.cls
// -------------------------------------------
//   Project: Avant Infra 
//   Created By: Exceller Tech
//   Created Date: 06-09-2024
//   Author: Nitin Choudhary    
// -------------------------------------------
public class Ex_SiteVisitTriggerHandler {
    public static void afterInsert(List<Site_Visit__c> svList){
        Set<Id> newSet = new Set<id>();
        Set<Id>SvIds =new Set<Id>();
        for(Site_Visit__c sv: svList) {
            if(sv.Mobile__c != null && sv.Project__c != null){
                newSet.add(sv.Id);
            }
            If(Sv.Id != null)
                SvIds.add(Sv.id);
        }
        List<Site_visit__c> siteVisit = [Select Id , name ,CP_Project__c, Project__c,Opportunity__c, Is_Sales_Manager_Assigned__c,Sales_Manager__c,Site_Visit_Count__c,SM_Assignment_Date__c,
                                         OwnerId
                                         From Site_visit__C Where Id IN: SvIds ];
        Map<Id, List<Site_Visit__c>> svMap = new Map<Id, List<Site_Visit__c>>();
        Set<Id> oppIdSet = new Set<Id>();
        if(siteVisit != null && siteVisit.size()>0){
            for(Site_Visit__c sv: siteVisit) {
                if(!sv.Is_Sales_Manager_Assigned__c && sv.Sales_Manager__c == null && sv.Project__c != null && sv.Opportunity__c != null) {
                    if(!svMap.containsKey(sv.Project__c)) {
                        List<Site_Visit__c> newList = new List<Site_Visit__c>();
                        newList.add(sv);
                        svMap.put(sv.Project__c, newList);
                    } else {
                        svMap.get(sv.Project__c).add(sv);
                    }
                    oppIdSet.add(sv.Opportunity__c);
                } 
            }
        }
        system.debug('oppIdSet //:'+oppIdSet);
        if(!svMap.isEmpty() && svMap != null && !oppIdSet.isEmpty() && oppIdSet != null)
         Ex_SiteVisitHandlerServices.applyRoundRobin(svMap, oppIdSet);
        
    }
     public static void afterUpdate(Map<Id, Site_Visit__c> oldMap, Map<Id, Site_Visit__c> newMap) {
        Map<Id, Set<Id>> projectUserIdMap = new Map<Id, Set<Id>>();
        for(Site_Visit__c oldSV: oldMap.values()) {
            Site_Visit__c newSV = newMap.get(oldSV.Id);
            
            if(oldSV.Comments__c != newSV.Comments__c && newSV.Comments__c != null && !String.isBlank(newSV.Comments__c)  && newSV.Project__c != null){
                if(projectUserIdMap.containsKey(newSV.Project__c)) {
                    projectUserIdMap.get(newSV.Project__c).add(newSV.Sales_Manager__c);
                } else {
                    Set<Id> newIdSet = new Set<Id>();
                    newIdSet.add(newSV.Sales_Manager__c);
                    projectUserIdMap.put(newSV.Project__c, newIdSet);
                }
            }
                   
        }
       if(!projectUserIdMap.isEmpty() && projectUserIdMap != null) {
            Ex_SiteVisitHandlerServices.updateSalesManagerAvailability(projectUserIdMap);
        }  
       
    }

}