force-app/main/default/objects/CP_Project__c/CP_Project__c.object-meta.xml
<CustomObject>
    <label>CP Project</label>
    <nameField>
        <displayFormat>CPP-{00000}</displayFormat>
        <label>CP Project No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ola_Pickup__c/Ola_Pickup__c.object-meta.xml
<CustomObject>
    <label>Ola Pickup</label>
    <nameField>
        <displayFormat>Ola-{00000}</displayFormat>
        <label>Ola Pickup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ola Pickups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ola_Pickup__c/fields/Pickup_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Datetime__c</fullName>
    <label>Pickup Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ola_Pickup__c/fields/Pickup_Location__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Location__c</fullName>
    <label>Pickup Location</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Ola_Pickup__c/fields/Visit_Pre_Registration__c.field-meta.xml
<CustomField>
    <fullName>Visit_Pre_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit Pre-Registration</label>
    <referenceTo>Visit_Pre_Registration__c</referenceTo>
    <relationshipLabel>Ola Pickups</relationshipLabel>
    <relationshipName>Ola_Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Pre_Registration__c/Visit_Pre_Registration__c.object-meta.xml
<CustomObject>
    <label>Visit Pre Registration</label>
    <nameField>
        <displayFormat>VPR-{000000}</displayFormat>
        <label>Visit Pre Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Pre Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>Visit Pre-Registrations</relationshipLabel>
    <relationshipName>Visit_Pre_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Ola_Pickup_Facility__c.field-meta.xml
<CustomField>
    <fullName>Ola_Pickup_Facility__c</fullName>
    <label>Ola Pickup Facility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Pre_registration_OTP__c.field-meta.xml
<CustomField>
    <fullName>Pre_registration_OTP__c</fullName>
    <label>Pre registration OTP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Visit Pre Registrations</relationshipLabel>
    <relationshipName>Visit_Pre_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestEx_PreRegistrationController.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 30-11-2023
//-------------------------------------------//
@isTest
public class TestEx_PreRegistrationController {
    @isTest
    public static void testGetCPProject() {
        Project__c p = new Project__c();
        p.Name = 'test';
        insert p;
        
        CP_Project__c testCPProject1 = new CP_Project__c(Project__c = p.Id);
        CP_Project__c testCPProject2 = new CP_Project__c(Project__c = p.Id);
        insert new List<CP_Project__c>{testCPProject1, testCPProject2};
            
            Visit_Pre_Registration__c vp = new Visit_Pre_Registration__c();
        vp.Ola_Pickup_Facility__c = 'Yes';
        vp.Mobile__c = '8989898989';
        vp.Pre_registration_OTP__c = '1234';
        insert vp;
        
        if(vp != null && vp.Ola_Pickup_Facility__c == 'Yes'){
            Ola_Pickup__c op = new Ola_Pickup__c();
            op.Pickup_Location__c = 'Test ';
            op.Pickup_Datetime__c = system.now();
            op.Visit_Pre_Registration__c = vp.Id;
            insert op;
        }
        
        Test.startTest();
        List<Ex_PreRegistrationController.CPProjectWrapper> result = Ex_PreRegistrationController.getCPProject();
       // Ex_PreRegistrationController.sendOTP(vp.Mobile__c, testCPProject1.Id);
       // Ex_PreRegistrationController.validateOTP('1234', vp.Mobile__c);
        Ex_PreRegistrationController.saveData(testCPProject1.Id, 'customerName', vp.Mobile__c, '', '1 BHK', 'Yes', System.now(), 'Location', System.now());
        Ex_NumberToWord.convertNumbertoWords(100);
        Test.stopTest();        
    }
    
    
}