force-app/main/default/objects/CP_Project__c/CP_Project__c.object-meta.xml
<CustomObject>
    <label>CP Project</label>
    <nameField>
        <displayFormat>CPP-{00000}</displayFormat>
        <label>CP Project No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/fields/CP_Account__c.field-meta.xml
<CustomField>
    <fullName>CP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>CP Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ola_Pickup__c/Ola_Pickup__c.object-meta.xml
<CustomObject>
    <label>Ola Pickup</label>
    <nameField>
        <displayFormat>Ola-{00000}</displayFormat>
        <label>Ola Pickup Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ola Pickups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ola_Pickup__c/fields/Pickup_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Datetime__c</fullName>
    <label>Pickup Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ola_Pickup__c/fields/Pickup_Location__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Location__c</fullName>
    <label>Pickup Location</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Ola_Pickup__c/fields/Visit_Pre_Registration__c.field-meta.xml
<CustomField>
    <fullName>Visit_Pre_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Visit Pre-Registration</label>
    <referenceTo>Visit_Pre_Registration__c</referenceTo>
    <relationshipLabel>Ola Pickups</relationshipLabel>
    <relationshipName>Ola_Pickups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Pre_Registration__c/Visit_Pre_Registration__c.object-meta.xml
<CustomObject>
    <label>Visit Pre Registration</label>
    <nameField>
        <displayFormat>VPR-{000000}</displayFormat>
        <label>Visit Pre Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Pre Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Budget_Range</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Configuration_required__c.field-meta.xml
<CustomField>
    <fullName>Configuration_required__c</fullName>
    <label>Configuration required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Configuration_Required</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/CP_Number__c.field-meta.xml
<CustomField>
    <fullName>CP_Number__c</fullName>
    <label>CP Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>Visit Pre-Registrations</relationshipLabel>
    <relationshipName>Visit_Pre_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Ola_Pickup_Facility__c.field-meta.xml
<CustomField>
    <fullName>Ola_Pickup_Facility__c</fullName>
    <label>Ola Pickup Facility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Pre_registration_OTP__c.field-meta.xml
<CustomField>
    <fullName>Pre_registration_OTP__c</fullName>
    <label>Pre registration OTP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Visit Pre Registrations</relationshipLabel>
    <relationshipName>Visit_Pre_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/SPOC__c.field-meta.xml
<CustomField>
    <fullName>SPOC__c</fullName>
    <label>SPOC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Budget_Range.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Budget less than 30 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 30 to 40 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 40 to 50 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 50 to 60 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 60 to 70 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 70 to 80 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 80 to 90 lakhs</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 90 lac to 1Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 1Cr to 1.25 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 1.25Cr to 1.5 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 1.5Cr to 1.75 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 1.75Cr to 2 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 2Cr to 2.5 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 2.5Cr to 3 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 3Cr to 3.5 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget of 3.5Cr to 4 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget more than 4 Cr.</fullName>
    </customValue>
    <customValue>
        <fullName>Budget less than 20 lakhs</fullName>
        <isActive>false</isActive>
        <label>Budget less than 20 lakhs</label>
    </customValue>
    <customValue>
        <fullName>Budget of 20 to 30 lakhs</fullName>
        <isActive>false</isActive>
        <label>Budget of 20 to 30 lakhs</label>
    </customValue>
    <customValue>
        <fullName>Budget of 1Cr to 1.5 Cr.</fullName>
        <isActive>false</isActive>
        <label>Budget of 1Cr to 1.5 Cr.</label>
    </customValue>
    <customValue>
        <fullName>Budget of 1.5Cr to 2 Cr.</fullName>
        <isActive>false</isActive>
        <label>Budget of 1.5Cr to 2 Cr.</label>
    </customValue>
    <customValue>
        <fullName>Budget of 2 Cr to 3 Cr.</fullName>
        <isActive>false</isActive>
        <label>Budget of 2 Cr to 3 Cr.</label>
    </customValue>
    <customValue>
        <fullName>Budget 3 Cr.+</fullName>
        <isActive>false</isActive>
        <label>Budget 3 Cr.+</label>
    </customValue>
    <masterLabel>Budget Range</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Configuration_Required.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Villa</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Shop</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <masterLabel>Configuration Required</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_PreRegistrationController.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 21-11-2023
//-------------------------------------------//
public with sharing class Ex_PreRegistrationController {
    @AuraEnabled(cacheable=true)
    public static List<CPProjectWrapper> getCPProject(){
        String cpName = '';
        Id cpId;
        List<CPProjectWrapper> cpWrapperList = new List<CPProjectWrapper>();
        List<CP_Project__c> cpProjectList = new  List<CP_Project__c>();        
        cpProjectList = [Select Id,Name,Project__r.Name from CP_Project__c];
        if(!cpProjectList.isEmpty() && cpProjectList != null){
            for(CP_Project__c cp: cpProjectList){
                cpName = cp.Name + ' / '+ cp.Project__r.Name;
                cpId = cp.Id;
                cpWrapperList.add(new CPProjectWrapper(cpName,cpId));
            }
            
        }
        system.debug('cpWrapperList: '+ cpWrapperList);
        if(!cpWrapperList.isEmpty() && cpWrapperList != null){
            return cpWrapperList;
        } else{
            return null;
        }      
    }
    
    
    /*@AuraEnabled
public static String sendOTP(String mobile,String cpId){
String generatedOtp;
String message;
List<CP_Project__c> cpProjectList = [Select Id , Name, Mobile__c, SPOC_Name__c, Project__c, CP_Account__c from CP_Project__c where Id =: cpId ];
system.debug('cpProjectList: '+cpProjectList);

if(mobile != Null && !String.isBlank(mobile)) {
generatedOtp = String.valueOf((Math.random() * 9000) + 1000).substring(0, 4);
system.debug('generatedOtp: '+generatedOtp);
}
try{
if(!cpProjectList.isEmpty() && cpProjectList != null){
Visit_Pre_Registration__c vpr = new Visit_Pre_Registration__c();
vpr.Pre_registration_OTP__c = generatedOtp;
vpr.Mobile__c = mobile;
vpr.CP_Project__c = cpProjectList[0].Id;
vpr.Project__c = cpProjectList[0].Project__c;
if(cpProjectList[0].SPOC_Name__c != null){
vpr.SPOC__c = cpProjectList[0].SPOC_Name__c;
}
if(cpProjectList[0].Mobile__c != null){
vpr.CP_Number__c = cpProjectList[0].Mobile__c;
}
insert vpr;
message = 'OTP sent successfully ' + '' +'Please Enter OTP : ' + generatedOtp ;
} 
}catch(Exception ex){
system.debug('Error: '+ex.getMessage());
message = 'Error occured while sending OTP. Please contact system administrator.';
}

return message;
}*/
    
    /* @auraEnabled
public static Boolean validateOTP(String enterOtp, String mobile){
Boolean isVerified = false;
String message = '';
system.debug('Inside VerifyOtp');
String MasterOtp = '3011';
Visit_Pre_Registration__c vpr = [select Id,Pre_registration_OTP__c from Visit_Pre_Registration__c where Mobile__c =: mobile Order By CreatedDate DESC limit 1];
if(vpr != null){
if (enterOtp == vpr.Pre_registration_OTP__c && !String.isBlank(enterOtp) && enterOtp != null) {
system.debug('Otp Verify Successfully');
message = 'OTP Verified Successfully.';
isVerified = true;
} else if (enterOtp == masterOtp) {
system.debug('Master OTP Verified Successfully');
message = 'Master OTP Verified Successfully.';
isVerified = true;
} else{
system.debug('OTP verification failed');
message = 'OTP Verification Failed.';
isVerified = false;
}
}
return isVerified;
}*/
    
    
    @auraEnabled
    public static Id saveData(String cpId, string customerName,String customerNo,String Budget, String Configuration, String Facility, DateTime VisitDate, String Location, DateTime PickupDate){
        system.debug('customerNo: '+customerNo);
        system.debug('Budget: '+Budget);
        system.debug('Configuration: '+Configuration);
        system.debug('Facility: '+Facility);
        system.debug('VisitDate: '+VisitDate);
        system.debug('Location: '+Location);
        system.debug('PickupDate: '+PickupDate);
        List<Ola_Pickup__c> opList = new List<Ola_Pickup__c>();
        Id vprId;
        
        List<CP_Project__c> cpProjectList = [Select Id , Name, Mobile__c, SPOC_Name__c, Project__c, CP_Account__c from CP_Project__c where Id =: cpId];
        system.debug('cpProjectList: '+cpProjectList);
        
        // List<Visit_Pre_Registration__c> preList = new List<Visit_Pre_Registration__c>();
        //  preList = [Select Id,CP_Project__c,Customer_Name__c,Visit_Date__c from Visit_Pre_Registration__c where CP_Project__c =: cpId Order By CreatedDate DESC limit 1 ];
        //  System.debug('preList: '+preList.size());
        
        if(!cpProjectList.isEmpty() && cpProjectList != null){
            Visit_Pre_Registration__c vpr = new Visit_Pre_Registration__c();
            // vpr.Pre_registration_OTP__c = generatedOtp;
            vpr.Mobile__c = customerNo;
            vpr.CP_Project__c = cpProjectList[0].Id;
            vpr.Project__c = cpProjectList[0].Project__c;
            if(cpProjectList[0].SPOC_Name__c != null){
                vpr.SPOC__c = cpProjectList[0].SPOC_Name__c;
            }
            if(cpProjectList[0].Mobile__c != null){
                vpr.CP_Number__c = cpProjectList[0].Mobile__c;
            }
            vpr.Customer_Name__c = customerName ;
            vpr.Budget__c = Budget;
            vpr.Configuration_required__c = Configuration;
            vpr.Visit_Date__c = VisitDate;
            if(Location != null){
                vpr.Pickup_Location__c = Location;
            }
            if(PickupDate != null){
                vpr.Pickup_Datetime__c = PickupDate;
            }
            if(Facility != null){
                vpr.Ola_Pickup_Facility__c = Facility; 
            }
            try{
                insert  vpr ;
                vprId = vpr.Id;
            }catch(Exception ex){
                system.debug('Exception= ' +ex);
            }
            if(Facility != null && Facility == 'Yes'){
                Ola_Pickup__c op = new Ola_Pickup__c();
                op.Pickup_Location__c = Location;
                op.Pickup_Datetime__c = PickupDate;
                op.Visit_Pre_Registration__c = vpr.Id;
                op.Primary_Mobile__c = customerNo;
                opList.add(op);
            }else{
                return vpr.Id;
            }
        }
        try{
            if(!opList.isEmpty() && opList != null){
                insert opList[0];      
            } 
        }catch(Exception ex){
            system.debug('Exception= ' +ex);
        }
        return vprId;
    }
    
    public class CPProjectWrapper{
        @auraenabled  public String cpName {get;set;}
        @auraenabled  public Id cpId{get;set;}
        
        public CPProjectWrapper(String cpName,Id cpId){
            this.cpName = cpName;
            this.cpId = cpId;
            
        }
    }
}