force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Stage__c.field-meta.xml
<CustomField>
    <fullName>Booking_Stage__c</fullName>
    <label>Booking Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Booking_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <defaultValue>Today()+10</defaultValue>
    <label>Tentative Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Final_Agreement_Uploded_FileName__c.field-meta.xml
<CustomField>
    <fullName>Final_Agreement_Uploded_FileName__c</fullName>
    <label>Final Agreement Uploded FileName</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Index_Page_Uploded_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Index_Page_Uploded_File_Name__c</fullName>
    <label>Index Page Uploded File Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Is_Final_Agreement_uploaded__c.field-meta.xml
<CustomField>
    <fullName>Is_Final_Agreement_uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Final Agreement uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Is_Index_Page_Uploded__c.field-meta.xml
<CustomField>
    <fullName>Is_Index_Page_Uploded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Index Page Uploded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Booking__r.Project__r.Name</formula>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <formula>Booking__r.Tower__r.Name</formula>
    <label>Tower</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Verified_By_MIS__c.field-meta.xml
<CustomField>
    <fullName>Verified_By_MIS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verified By MIS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registration__c/fields/Verified_By_RM__c.field-meta.xml
<CustomField>
    <fullName>Verified_By_RM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Verified By RM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Booking_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Booking In-Process</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation in-process</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Welcome Call Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Possession Done</fullName>
    </customValue>
    <customValue>
        <fullName>Welcome Call Done</fullName>
        <isActive>false</isActive>
        <label>Welcome Call Done</label>
    </customValue>
    <masterLabel>Booking Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_BulkRegistrationFileDashboard.cls
/**
 * @description       : 
 * @author            : nitinSFDC@exceller.SFDoc
 * @group             : 
 * @last modified on  : 30-05-2025
 * @last modified by  : nitinSFDC@exceller.SFDoc
**/
public with sharing class Ex_BulkRegistrationFileDashboard {
    public Ex_BulkRegistrationFileDashboard() {
        
    }
    @AuraEnabled(cacheable=true)
    public static List<Project__c> getProject(){
        List<Project__c> plist=[select Id, Name FROM Project__c];
        return plist;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<Tower__c> getTower(String ProjectId){
        List<Tower__c> tlist=[select Id, Name,Project__c FROM Tower__c WHERE Project__r.id =: ProjectId];
        return tlist;
    }
    
    
    // @AuraEnabled
    // public static List<registrationWrapper> getRegistrationData(){
        //     try {
            
            
        //     } catch (Exception e) {
            //         throw new AuraHandledException(e.getMessage());
        //     }
    // }
    
    
    @AuraEnabled
    public static List<ContentDocumentLinkWrapper> fetchFiles(String objectName, String documentType, String towerId, String projectId) {
        List<ContentDocumentLinkWrapper> result = new List<ContentDocumentLinkWrapper>();
        Map<Id, Id> demandToDocumentsMap = new Map<Id, Id>();
        Set<String> docSet = new Set<String>();
        Map<Id, String> contentDocMap = new Map<Id, String>();
        if(String.isNotBlank(documentType)){
            documentType.toUpperCase();
        }
        
        try {
            // Fetch Registration Data
            List<Registration__c> getRegistrationData = [ 
                SELECT Id, Name, 
                Is_Final_Agreement_uploaded__c, Is_Index_Page_Uploded__c, Final_Agreement_Uploded_FileName__c, Index_Page_Uploded_File_Name__c, createdDate, Booking__r.Name, Registration_Date__c, 
                Booking__r.Booking_Stage__c, Booking__r.Unit__r.Name, Booking__r.Project__c, 
                Booking__r.Tower__c, Verified_By_MIS__c, Verified_By_RM__c
                FROM Registration__c 
                WHERE Booking__r.Project__c =: projectId 
                AND Booking__r.Tower__c =: towerId 
                AND Booking__c != null
            ];
            
            if (!getRegistrationData.isEmpty()) {
                Set<Id> rIds = new Set<Id>();
                
                for (Registration__c reg : getRegistrationData) {
                    List<String> docNames = new List<String>();
                    
                    //if(!documentType.equalsIgnoreCase('ALL')){
                        if (String.isNotBlank(reg.Final_Agreement_Uploded_FileName__c)) {
                            docNames.addAll(new List<String>(reg.Final_Agreement_Uploded_FileName__c.split('#')));
                        }
                        if (String.isNotBlank(reg.Index_Page_Uploded_File_Name__c)) {
                            docNames.addAll(new List<String>(reg.Index_Page_Uploded_File_Name__c.split('#')));
                        }
                        
                        
                        for (String docName : docNames) {
                            docName = docName.trim();
                            if (docName.contains(documentType)) {
                                docSet.add(docName);
                            }
                        }
                    // }
                    
                    
                    
                    
                    rIds.add(reg.Id);
                }
                
                String query = 'SELECT ContentDocumentId, ContentDocument.Title, ContentDocument.FileType, ContentDocument.ContentSize, ContentDocument.LastModifiedDate, ContentDocument.CreatedDate, LinkedEntity.Type, LinkedEntity.Id FROM ContentDocumentLink WHERE LinkedEntityId IN :rIds';
                if (String.isNotBlank(objectName)) {
                    query += ' AND LinkedEntity.Type = \'' + objectName + '\'';
                }
                
                List<ContentDocumentLink> contentDocumentLinks = Database.query(query);
                
                for (ContentDocumentLink cdl : contentDocumentLinks) {
                    if (!demandToDocumentsMap.containsKey(cdl.LinkedEntityId)) {
                        demandToDocumentsMap.put(cdl.LinkedEntityId, cdl.ContentDocumentId);
                    }
                    demandToDocumentsMap.get(cdl.LinkedEntityId);
                }
                
                Map<Id, ContentDocumentLink> registrationToDocumentMap = new Map<Id, ContentDocumentLink>();
                Set<Id> contentDocumentIds = new Set<Id>();
                
                for (ContentDocumentLink cdl : contentDocumentLinks) {
                    registrationToDocumentMap.put(cdl.LinkedEntityId, cdl);
                    contentDocumentIds.add(cdl.ContentDocumentId);
                }
                Map<Id, Id> contentDocumentToVersionMap = new Map<Id, Id>();
                
                if (!contentDocumentIds.isEmpty()) {
                    List<ContentVersion> contentVersions = [
                        SELECT Id, ContentDocumentId 
                        FROM ContentVersion 
                        WHERE ContentDocumentId IN :contentDocumentIds 
                        ORDER BY CreatedDate DESC
                    ];
                    
                    for (ContentVersion cv : contentVersions) {
                        if (!contentDocumentToVersionMap.containsKey(cv.ContentDocumentId)) {
                            contentDocumentToVersionMap.put(cv.ContentDocumentId, cv.Id);
                        }
                    }
                }
                
                if(docSet != null && !docSet.isEmpty()){
                    for (ContentDocumentLink doc : contentDocumentLinks) {
                        for (String docName : docSet) {
                            if (!contentDocMap.containsKey(doc.LinkedEntityId)) {
                                contentDocMap.put(doc.LinkedEntityId, docName);
                            }
                            contentDocMap.get(doc.LinkedEntityId);
                        }
                    }
                    System.debug('contentDocMap: '+contentDocMap);
                }
                
                for (Registration__c reg : getRegistrationData) {
                    if (contentDocMap.containsKey(reg.Id) && contentDocMap.get(reg.Id).contains(documentType)) {
                        if(demandToDocumentsMap.containsKey(reg.Id)){
                            if (registrationToDocumentMap.containsKey(reg.Id)) {
                                ContentDocumentLink cdl = registrationToDocumentMap.get(reg.Id);
                                
                                ContentDocumentLinkWrapper wrapper = new ContentDocumentLinkWrapper();
                                wrapper.registrationName = reg.Name;
                                wrapper.fileType = documentType;
                                wrapper.bookingId = reg.Booking__c;
                                wrapper.regId = reg.Id;
                                wrapper.UnitName = reg.Booking__r.Unit__r.Name;
                                wrapper.bookingNo = reg.Booking__r.Name;
                                wrapper.isDownloaded = false;
                                wrapper.createdDate = reg.CreatedDate;
                                wrapper.bookingStatus = reg.Booking__r.Booking_Stage__c;
                                wrapper.registrationDate = reg.Registration_Date__c;
                                wrapper.contentDocumentId = cdl.ContentDocumentId;
                                wrapper.isverifiedBYMIS = reg.Verified_By_MIS__c;
                                wrapper.isverifiedBYRM = reg.Verified_By_RM__c;
                                if(reg.Verified_By_MIS__c){
                                    wrapper.verifiedBYMIS = 'Verified';
                                }else{
                                    wrapper.verifiedBYMIS = 'Not Verified';
                                }
                                 if(reg.Verified_By_RM__c){
                                    wrapper.verifiedBYRM = 'Verified';
                                }else{
                                    wrapper.verifiedBYRM = 'Not Verified';
                                }
                                                                
                                // Assign the latest ContentVersionId
                                if (contentDocumentToVersionMap.containsKey(cdl.ContentDocumentId)) {
                                    wrapper.contentVersionId = contentDocumentToVersionMap.get(cdl.ContentDocumentId);
                                }
                                
                                result.add(wrapper);
                                
                                /*ContentDocumentLinkWrapper wrapper = new ContentDocumentLinkWrapper();
                                wrapper.registrationName = reg.Name;
                                wrapper.fileType = documentType;
                                wrapper.bookingId = reg.Booking__c;
                                wrapper.regId = reg.Id;
                                wrapper.unitName = String.valueOf(reg.Booking__r.Unit__r.Name);
                                wrapper.bookingNo = reg.Booking__r.Name;
                                wrapper.isDownloaded = false;
                                wrapper.createdDate = reg.createdDate;
                                wrapper.bookingStatus = reg.Booking__r.Booking_Stage__c;
                                wrapper.registrationDate = reg.Registration_Date__c;
                                wrapper.contentDocumentId = demandToDocumentsMap.get(reg.Id);
                                wrapper.contentVersionId = demandToDocumentsMap.get(reg.Id);
                                result.add(wrapper);*/
                            }
                            
                        }
                    }
                }
                
            }
        }catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
        
        if(result != null){
            System.debug('result: '+result);
            return result;
        }else{
            return null;
        }
        
        
    }
    
    
    
    public class ContentDocumentLinkWrapper {
        @AuraEnabled
        public Id contentDocumentId { get; set; }
        
        
        @AuraEnabled
        public Integer contentSize { get; set; }
        
        @AuraEnabled
        public Datetime registrationDate { get; set; }
        
        @AuraEnabled
        public Datetime createdDate { get; set; }
        
        @AuraEnabled
        public String linkedEntityType { get; set; }
        
        @AuraEnabled
        public String registrationName { get; set; }
        
        @AuraEnabled
        public String regId { get; set; }
        
        @AuraEnabled
        public String UnitName { get; set; }
        
        @AuraEnabled
        public String bookingNo { get; set; }
        
        @AuraEnabled
        public String bookingStatus { get; set; }
        
        @AuraEnabled
        public Boolean isDownloaded { get; set; }
        
        @AuraEnabled
        public String fileType { get; set; }
        
        @AuraEnabled
        public String bookingId {get;set;}
        
        @AuraEnabled
        public String contentVersionId {get;set;}

         @AuraEnabled
        public String verifiedBYMIS {get;set;}

         @AuraEnabled
        public String verifiedBYRM {get;set;}

         @AuraEnabled
        public Boolean isverifiedBYMIS {get;set;}

         @AuraEnabled
        public Boolean isverifiedBYRM {get;set;}
    }
    
    
    
}