force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Park__c/Car_Park__c.object-meta.xml
<CustomObject>
    <label>Car Park</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Park Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Park</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Park__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Car Park</relationshipLabel>
    <relationshipName>Car_Park</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Park__c/fields/Car_Park_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Park_Type__c</fullName>
    <label>Car Park Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Car_Park_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car_Park__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Car Park</relationshipLabel>
    <relationshipName>Car_Park</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Park__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <isActive>false</isActive>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>null</fullName>
                <isActive>false</isActive>
                <label>null</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car_Park__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Car Parks</relationshipLabel>
    <relationshipName>Car_Parks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Park__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Podium Parking</fullName>
            </value>
            <value>
                <fullName>Open Parking</fullName>
            </value>
            <value>
                <fullName>Stack Upper Parking</fullName>
            </value>
            <value>
                <fullName>Stack Lower Parking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car_Park_Required__c/Car_Park_Required__c.object-meta.xml
<CustomObject>
    <label>Car Park Required</label>
    <nameField>
        <displayFormat>CPR-{0000}</displayFormat>
        <label>Car Park Required Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Park Required</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Park_Required__c/fields/Car_Park_Count__c.field-meta.xml
<CustomField>
    <fullName>Car_Park_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Car Park Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car_Park_Required__c/fields/Car_Park_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Park_Type__c</fullName>
    <label>Car Park Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Podium Parking</fullName>
            </value>
            <value>
                <fullName>Open Parking</fullName>
            </value>
            <value>
                <fullName>Stack Upper Parking</fullName>
            </value>
            <value>
                <fullName>Stack Lower Parking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car_Park_Required__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Car Park Required</relationshipLabel>
    <relationshipName>Car_Park_Required</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Car_Park_Maintain_At__c.field-meta.xml
<CustomField>
    <fullName>Car_Park_Maintain_At__c</fullName>
    <label>Car Park Maintain At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Car_Park_Maintain_At</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Car_Park_Maintain_At.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Project</fullName>
        <default>true</default>
        <label>Project</label>
    </customValue>
    <customValue>
        <fullName>Tower</fullName>
    </customValue>
    <masterLabel>Car Park Maintain At</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Car_Park_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Podium Parking</fullName>
    </customValue>
    <customValue>
        <fullName>Open Parking</fullName>
    </customValue>
    <customValue>
        <fullName>Stack Upper Parking</fullName>
    </customValue>
    <customValue>
        <fullName>Stack Lower Parking</fullName>
    </customValue>
    <customValue>
        <fullName>Stack Parking</fullName>
    </customValue>
    <masterLabel>Car Park Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestEx_CarParkingAllotment.cls
@isTest
public class TestEx_CarParkingAllotment {
    @isTest
    static void testGetTowerFromBooking() {
        Project__c p = new Project__c();
        p.Name = 'Test Project';
        p.Car_Park_Maintain_At__c = 'Project';
        insert p;
        System.debug('p: '+p);
        
        
        tower__c t = new tower__c();
        t.Name = 'Test Tower';
        t.Project__c = p.Id;
        insert t ;
     
        
        Quotation__c quotation = new Quotation__c();
        quotation.Project__c = p.id;
        quotation.Tower__c = t.id;
        insert quotation;
        
        Booking__c booking = new Booking__c();
        booking.Quotation__c = quotation.Id;
        booking.Project__c = p.id;
      //  booking.Tower__c = t.id;
        insert booking;
        System.debug('Booking: '+booking);
        
        Car_Park__c carPark = new Car_Park__c(Status__c = 'Available',  Project__c = booking.Project__c , Type__c = 'Podium Parking', Booking__c = booking.Id);
        insert carPark;
        
        Car_Park__c carPark2 = new Car_Park__c(Status__c = 'Available',  Project__c = booking.Project__c , Type__c = 'Podium Parking' , Booking__c = booking.Id);
        insert carPark2;
        
        
        Car_Park_Required__c carParkRequired = new Car_Park_Required__c(
            Quotation__c = Booking.Quotation__c,
            Car_Park_Count__c = 2,
            Car_Park_Type__c = 'Podium Parking'
            
        );
        insert carParkRequired;
        
        Car_Park__c carPark1 = new Car_Park__c(Status__c = 'Available',  Project__c = booking.Project__c , Type__c = 'Podium Parking');
        insert carPark1;
       
        Ex_CarParkingAllotment.updateCarParkwithBooking(new List<Car_Park__c>{carPark1}, booking.Id);
        Ex_CarParkingAllotment.getCarParkRequiredWrapper(booking);
        List<Car_Park__c> carParkList = new List<Car_Park__c>();
        
        carParkList = Ex_CarParkingAllotment.getCarPark(booking ,'Podium Parking');
        Ex_CarParkingAllotment.getCarPark(booking ,'');
        Ex_CarParkingAllotment.getBookingRelatedCarPark(booking);
        Ex_CarParkingAllotment.getBooking(booking.Id);
        
    }
    
    
    
}