force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>Opportunity__r.Mobile__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account)</relationshipLabel>
    <relationshipName>Leads2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>AName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Leads (Opportunity)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>Account__r.PersonContact.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>NameA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WA_API_Details_Gupshup__c/WA_API_Details_Gupshup__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Gupshup APIs</description>
    <label>WA API Details Gupshup</label>
</CustomObject>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/Connection__c.field-meta.xml
<CustomField>
    <fullName>Connection__c</fullName>
    <label>Connection</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/Source_Phone__c.field-meta.xml
<CustomField>
    <fullName>Source_Phone__c</fullName>
    <label>Source Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/src_name__c.field-meta.xml
<CustomField>
    <fullName>src_name__c</fullName>
    <label>src.name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/token__c.field-meta.xml
<CustomField>
    <fullName>token__c</fullName>
    <label>token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/WhatsApp_Message__c.object-meta.xml
<CustomObject>
    <label>WhatsApp Message</label>
    <nameField>
        <displayFormat>WAM-{00000}</displayFormat>
        <label>WhatsApp Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WhatsApp Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WhatsApp_Message__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>WhatsApp Messages</relationshipLabel>
    <relationshipName>WhatsApp_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>WhatsApp Messages</relationshipLabel>
    <relationshipName>WhatsApp_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Message_Text__c.field-meta.xml
<CustomField>
    <fullName>Message_Text__c</fullName>
    <label>Message Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>WhatsApp Messages</relationshipLabel>
    <relationshipName>WhatsApp_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Outbound__c.field-meta.xml
<CustomField>
    <fullName>Outbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Outbound?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Reply1__c.field-meta.xml
<CustomField>
    <fullName>Reply1__c</fullName>
    <label>Reply1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Reply2__c.field-meta.xml
<CustomField>
    <fullName>Reply2__c</fullName>
    <label>Reply2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Title_1__c.field-meta.xml
<CustomField>
    <fullName>Title_1__c</fullName>
    <label>Title 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Title_2__c.field-meta.xml
<CustomField>
    <fullName>Title_2__c</fullName>
    <label>Title 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Type_1__c.field-meta.xml
<CustomField>
    <fullName>Type_1__c</fullName>
    <label>Type 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Call_To_Action_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Type_2__c.field-meta.xml
<CustomField>
    <fullName>Type_2__c</fullName>
    <label>Type 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Call_To_Action_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Value_1__c.field-meta.xml
<CustomField>
    <fullName>Value_1__c</fullName>
    <label>Value 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Value_2__c.field-meta.xml
<CustomField>
    <fullName>Value_2__c</fullName>
    <label>Value 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/Whatsapp_Template__c.object-meta.xml
<CustomObject>
    <label>Whatsapp Template</label>
    <nameField>
        <displayFormat>WT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Whatsapp Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Whatsapp_Template__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Whatsapp Templates</relationshipLabel>
    <relationshipName>Whatsapp_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Reply1__c.field-meta.xml
<CustomField>
    <fullName>Reply1__c</fullName>
    <label>Reply1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Reply2__c.field-meta.xml
<CustomField>
    <fullName>Reply2__c</fullName>
    <label>Reply2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Title_1__c.field-meta.xml
<CustomField>
    <fullName>Title_1__c</fullName>
    <label>Title 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Title_2__c.field-meta.xml
<CustomField>
    <fullName>Title_2__c</fullName>
    <label>Title 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Type_1__c.field-meta.xml
<CustomField>
    <fullName>Type_1__c</fullName>
    <label>Type 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Call_To_Action_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Type_2__c.field-meta.xml
<CustomField>
    <fullName>Type_2__c</fullName>
    <label>Type 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Call_To_Action_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Value_1__c.field-meta.xml
<CustomField>
    <fullName>Value_1__c</fullName>
    <label>Value 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Value_2__c.field-meta.xml
<CustomField>
    <fullName>Value_2__c</fullName>
    <label>Value 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Call_To_Action_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>PHONE_NUMBER</fullName>
        <label>Phone Number</label>
    </customValue>
    <customValue>
        <fullName>URL</fullName>
    </customValue>
    <masterLabel>Call To Action Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestEx_WhatsappMsg.cls
@isTest
public class TestEx_WhatsappMsg {
    
    public class MockHttpResponse implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            res.setBody('{"status": "Success"}');
            res.setStatusCode(200);
            return res;
        }
    }
	@isTest
    public static void testMethod1(){
        
        Project__c pro = new Project__c();
        pro.Name = 'Project A';
        insert pro;
        
        WA_API_Details_Gupshup__c wa = new WA_API_Details_Gupshup__c();
        wa.Name__c = 'SatyamDevelopersSFDC';
        wa.isActive__c = true;
        wa.token__c = 'Test';
        wa.Connection__c = 'test';
        wa.Channel__c = 'Test';
        wa.Source_Phone__c = '1212121212';
        wa.src_name__c = 'google';
        wa.API_Key__c = 'asdf';
        wa.Project_Name__c = 'Project A';
        insert wa;
        
        Lead__c ld = new Lead__c();
        ld.Mobile__c = '2112211221';
        ld.Project__c = pro.Id;
        insert ld;
        
        Account acc = new Account();
        acc.PersonMobilePhone = '1221122221';
       	//acc.POC_Mobile__c = '1212121212';
        acc.Phone = '1111122222';
        acc.LastName = 'Test';
        insert acc;
        
        Opportunity__c opp = new Opportunity__c();
        opp.Account__c = acc.Id;
        opp.Project__c = pro.Id;
        insert opp;

        Booking__c bk = new Booking__c();
        bk.Opportunity__c = opp.id;
        bk.Project__c = pro.Id;
        insert bk;
        
        Set<Id> recordIds1 = new Set<Id>();
        Set<Id> recordIds2 = new Set<Id>();
        Set<Id> recordIds3 = new Set<Id>();
        String str = ld.Id+',Test';
        List<String> s = new List<String>();
        s.add(str);
        recordIds1.add(ld.Id);
        recordIds2.add(opp.Id);
        recordIds3.add(bk.Id);
        String leadId = ld.Id;
        String oppoId = opp.Id;
        String bkId = bk.Id;
        
        Whatsapp_Template__c wt = new Whatsapp_Template__c();
        wt.Value_1__c = 'test';
        wt.Title_1__c = 'Test';
        wt.Type_1__c = 'PHONE_NUMBER';
        wt.Value_2__c = 'test';
        wt.Title_2__c = 'Test';
        wt.Type_2__c = 'URL';
        wt.Reply1__c = 'Yes';
        wt.Reply2__c = 'No';
        wt.Parameters__c = '{!Lead__r.Mobile}';
        wt.Template_ID__c = 'Test Template';
        wt.Parameters__c = 'Test';
        wt.Template__c = 'Test';
        insert wt;
        
        WhatsApp_Message__c wm = new WhatsApp_Message__c();
        wm.Message_Text__c = 'test';
        wm.Outbound__c = true;
        wm.Message_Type__c = 'Template';
        wm.Lead__c = ld.Id;
        insert wm;
        Map<String, Object> attachmentData = new Map<String, Object>();
        attachmentData.put(wm.Id,wm);
        
        
       	Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
        
        test.startTest();
        Ex_WhatsappMessageServicesNew.Ex_WhatsappMsg(recordIds1,'Test Template');
        Ex_WhatsappMessageServicesNew.Ex_WhatsappMsg(recordIds2,'Test Template');
        Ex_WhatsappMessageServicesNew.Ex_WhatsappMsg(recordIds3,'Test Template');
        Ex_WhatsappMessageServicesNew.sendMessage(recordIds1,'Test Template');
        Ex_WhatsappMessageServicesNew.generateHTMLString(leadId, wt.Parameters__c,wt.Template__c);
        Ex_WhatsappMessageServicesNew.generateHTMLString(oppoId, wt.Parameters__c,wt.Template__c);
        Ex_WhatsappMessageServicesNew.generateHTMLString(bkId, wt.Parameters__c,wt.Template__c);
        Ex_WhatsappMessageServicesNew.getRecordById(ld.Id);
        Ex_WhatsappMessageServicesNew.getPhoneNumber(ld);
        Ex_WhatsappMessageServicesNew.Ex_WhatsappUsingFlow(s);
  
        Ex_whatsAppMsgService.getSObjectName(ld.Id);
        Ex_whatsAppMsgService.getSObjectName(opp.Id);
        Ex_whatsAppMsgService.getSObjectName(bk.Id);
        Ex_whatsAppMsgService.getConversationStartDateTime(ld.Id);
        Ex_whatsAppMsgService.getConversationStartDateTime(opp.Id);
        Ex_whatsAppMsgService.getConversationStartDateTime(bk.Id);
        Ex_whatsAppMsgService.AllMsgs(ld.Id);
        Ex_whatsAppMsgService.AllMsgs(opp.Id);
        Ex_whatsAppMsgService.AllMsgs(bk.Id);
        Ex_whatsAppMsgService.refreshMessages(ld.Id);
        Ex_whatsAppMsgService.refreshMessages(opp.Id);
        Ex_whatsAppMsgService.refreshMessages(bk.Id);
		Ex_whatsAppMsgService.InsertMessage('Hie',ld.Id);
        Ex_whatsAppMsgService.SendTemplate(wt.Id,ld.Id);
        Ex_whatsAppMsgService.getTemplate(ld.Id, 'Marketing');
        Ex_whatsAppMsgService.removeHtmlTags('Hie');
        Ex_whatsAppMsgService.generateHTMLString(ld.Id, '{!Lead__c.First_Name__c}', 'Hie {{1}}');
        Ex_whatsAppMsgService.getAllRecordDetails(ld.Id);
        Ex_whatsAppMsgService.InsertAttachment(attachmentData, 'hi');
      
        test.stopTest();
    }
}