force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipt</relationshipLabel>
    <relationshipName>Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payment Successful</fullName>
            </value>
            <value>
                <fullName>Payment Failed - Insufficient Funds</fullName>
            </value>
            <value>
                <fullName>Payment Failed – Signature mismatch</fullName>
            </value>
            <value>
                <fullName>Payment Failed – PDC</fullName>
            </value>
            <value>
                <fullName>Payment Failed – Stop payment by client</fullName>
            </value>
            <value>
                <fullName>Payment Failed – Overwriting</fullName>
            </value>
            <value>
                <fullName>Payment Failed – Amount Mismatch</fullName>
            </value>
            <value>
                <fullName>Payment in Process</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Status__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Status__c</fullName>
    <label>Receipt Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UnProcessed</fullName>
                <default>true</default>
                <label>UnProcessed</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Processed-Finance Submission Pending</fullName>
            </value>
            <value>
                <fullName>Processed-Sent for Banking</fullName>
            </value>
            <value>
                <fullName>Dishonored</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Physical Verification Rejected</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Reverse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Type__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Type__c</fullName>
    <label>Receipt Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Flat Cost</fullName>
            </value>
            <value>
                <fullName>Tax</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>Registration Charges</fullName>
            </value>
            <value>
                <fullName>Other Charges</fullName>
            </value>
            <value>
                <fullName>Interest Flat Cost</fullName>
            </value>
            <value>
                <fullName>Interest GST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ex_ReceiptTriggerHandler.cls
//-------------------------------------------//
//  Project: Satyam
//  Created By: Exceller tech
//  Created Date: 06-11-2023
//-------------------------------------------//
public class Ex_ReceiptTriggerHandler {
    public static void beforeInsert(List<Receipt__c> receiptList) {
        Map<Id, Date> boookingInterestDateMap = new Map<Id, Date>();
        for(Receipt__c r: receiptList) {
            if(r.Booking__c != null && r.Date__c != null) {
                if(r.Date__c < system.today()) {
                    boookingInterestDateMap.put(r.Booking__c, r.Date__c);
                }
            } 
        }   
        if(!boookingInterestDateMap.isEmpty() && boookingInterestDateMap != null)
            Ex_InterestCalculateManagementServices.interestCalculate(boookingInterestDateMap);
    }
    
    public static void afterInsert(List<Receipt__c> receiptList) {
        Set<Id> rIdSet = new Set<Id>();
        Map<Id, Decimal> bookingReceiptMap = new Map<Id, Decimal>();
        
        for(Receipt__c r: receiptList) {
            rIdSet.add(r.Id);
            if(r.Receipt_Type__c != null && r.Receipt_Type__c.equalsIgnoreCase('Flat Cost') && r.Payment_Status__c != null && r.Payment_Status__c.equalsIgnoreCase('Payment Successful') && r.Booking__c != null){
                bookingReceiptMap.put(r.Booking__c,r.Amount__c);
            }
        }
        System.debug('bookingReceiptMap: '+bookingReceiptMap);
        if(!bookingReceiptMap.isEmpty() && bookingReceiptMap != null)
            Ex_ReceiptHandlerServices.updateAVReceipts(bookingReceiptMap);
        if(!rIdSet.isEmpty() && rIdSet != null)
            Ex_ReceiptHandlerServices.receiptApporation(rIdSet);
    }
    
    public static void afterUpdate(Map<Id, Receipt__c> oldMap, Map<Id, Receipt__c> newMap) {
        Set<Id> reverseReceiptIdSet = new Set<Id>();
        Set<Id> PaymentSuccessIdSet = new Set<Id>();
        Map<Id, Decimal> PaymentSuccessAVSetMap = new Map<Id, Decimal>();
        
        for(Receipt__c oldReceipt: oldMap.values()) {
            Receipt__c newReceipt = newMap.get(oldReceipt.Id);
            
            if(oldReceipt.Receipt_Status__c != newReceipt.Receipt_Status__c && newReceipt.Receipt_Status__c.equalsIgnoreCase('Reverse'))
                reverseReceiptIdSet.add(newReceipt.Id);
            if(oldReceipt.Payment_Status__c != newReceipt.Payment_Status__c && newReceipt.Payment_Status__c.equalsIgnoreCase('Payment Successful')){
                PaymentSuccessIdSet.add(newReceipt.Id);
                PaymentSuccessAVSetMap.put(newReceipt.Booking__c,newReceipt.Amount__c);
            }
        }
        if(!reverseReceiptIdSet.isEmpty() && reverseReceiptIdSet != null && Ex_CheckRecursive.runOnce())
            Ex_ReceiptHandlerServices.reverseReceiptCalculation(reverseReceiptIdSet);
        if(!PaymentSuccessIdSet.isEmpty() && PaymentSuccessIdSet != null && Ex_CheckRecursive.runOnce())
            Ex_ReceiptHandlerServices.receiptApporation(PaymentSuccessIdSet);
        if(!PaymentSuccessAVSetMap.isEmpty() && PaymentSuccessAVSetMap != null)
              Ex_ReceiptHandlerServices.updateAVReceipts(PaymentSuccessAVSetMap);
    }
    
    public static void beforeDelete(Map<Id, Receipt__c> oldMap, Map<Id, Receipt__c> newMap) {
        Set<Id> rIdSet = new Set<Id>();
        
        for(Receipt__c oldReceipt: oldMap.values()) {
            rIdSet.add(oldReceipt.Id);
        }
        if(!rIdSet.isEmpty() && rIdSet != null)
            Ex_ReceiptHandlerServices.deleteReceiptApportionCalculation(rIdSet);
        if(!rIdSet.isEmpty() && rIdSet != null)
            Ex_ReceiptHandlerServices.updateAVReceiptAmountCalculationonBooking(rIdSet);
    }
    
}