force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Booking_Registered__c.field-meta.xml
<CustomField>
    <fullName>Booking_Registered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Booking Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/By_Pass_Registration_Done__c.field-meta.xml
<CustomField>
    <fullName>By_Pass_Registration_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>By Pass Registration Done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Generate_Welcome_Call_Checklist_Master__c.field-meta.xml
<CustomField>
    <fullName>Generate_Welcome_Call_Checklist_Master__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate Welcome Call Checklist Master</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Registratio_Date__c.field-meta.xml
<CustomField>
    <fullName>Registratio_Date__c</fullName>
    <label>Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Ex_BookingTriggerHandler.cls
/**
 * @description       : 
 * @author            : nitinSFDC@exceller.SFDoc
 * @group             : 
 * @last modified on  : 20-01-2025
 * @last modified by  : nitinSFDC@exceller.SFDoc
**/
//-------------------------------------------//
//  Project: Satyam
//  Created By: Exceller tech
//  Created Date: 30-10-2023
//-------------------------------------------//
public class Ex_BookingTriggerHandler {
    public static void afterInsert(List<Booking__c> bList) {
        Map<Id, Booking__c> quotationBookingMap = new Map<Id, Booking__c>();
        Set<Id> towerIdSet = new Set<Id>();
        
        for(Booking__c b: bList) {
            if(b.Booking_Date__c != null && b.Tower__c != null) {
                quotationBookingMap.put(b.Quotation__c, b);
                towerIdSet.add(b.Tower__c);
            }
        }
        if(quotationBookingMap != null && !towerIdSet.isEmpty())
            Ex_BookingHanldlerServices.updatePaymentMilestoneDueDate(quotationBookingMap, towerIdSet);
    }
    public static void afterUpdate(Map<Id, Booking__c> oldMap, Map<Id, Booking__c> newMap) {
        List<Booking__c> newBookingList = new List<Booking__c>();
        Map<Id, Date> quotationRegistrationMap = new Map<Id,Date>();
        Boolean isBatchReq2 = false;
        
        
        for(Booking__c oldBooking: oldMap.values()) {
            Booking__c newBooking = newMap.get(oldBooking.Id);
            
            if(oldBooking.Generate_Welcome_Call_Checklist_Master__c != newBooking.Generate_Welcome_Call_Checklist_Master__c && newBooking.Generate_Welcome_Call_Checklist_Master__c == True) {
                newBookingList.add(newBooking);
            }
            if(oldBooking.Welcome_Call_Done__c != newBooking.Welcome_Call_Done__c && newBooking.Welcome_Call_Done__c) {
                isBatchReq2 = true;
                system.debug('Inside Batch Call: ');
            }
            if(oldBooking.Booking_Registered__c != newBooking.Booking_Registered__c && newBooking.Booking_Registered__c) {
                if(newBooking.Registratio_Date__c != null){
                    if(!quotationRegistrationMap.containsKey(newBooking.Quotation__c)){
                        quotationRegistrationMap.put(newBooking.Quotation__c,newBooking.Registratio_Date__c);
                    }else{
                        quotationRegistrationMap.get(newBooking.Quotation__c);
                    }
                }
                
            }
            if(oldBooking.By_Pass_Registration_Done__c != newBooking.By_Pass_Registration_Done__c && newBooking.Booking_Registered__c) {
                isBatchReq2 = true;
                system.debug('Inside Batch Call: ');
            }
        }
        if(!quotationRegistrationMap.isEmpty() && quotationRegistrationMap != null)
            Ex_UpdatePaymentMilestone.updateDueDate(quotationRegistrationMap);
        if(!newBookingList.isEmpty() && newBookingList != null) {
            Ex_BookingHanldlerServices.insertWelcomeCallChecklist(newBookingList);
        }
        if(isBatchReq2) {
            system.debug('Inside Batch Call: ');
            Database.executeBatch(new Ex_DemandRaiseBatch()); // Calling Batch Class
        }
    }
}