force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <defaultValue>Today()+10</defaultValue>
    <label>Tentative Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/Terms_Sheet__c.object-meta.xml
<CustomObject>
    <label>Terms Sheet</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Terms Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Terms_Sheet__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <formula>Booking__r.Agreement_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agreement Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Home Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Terms Sheets</relationshipLabel>
    <relationshipName>Terms_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/GST_Amount_Date__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>GST Amount Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Home_Loan__c.field-meta.xml
<CustomField>
    <fullName>Home_Loan__c</fullName>
    <label>Home-Loan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Home_Loan_Contribution_Self_Funding__c.field-meta.xml
<CustomField>
    <fullName>Home_Loan_Contribution_Self_Funding__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Home Loan Contribution / Self-Funding</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Home_Loan_Date__c.field-meta.xml
<CustomField>
    <fullName>Home_Loan_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Home Loan Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Own_Contribution_a__c.field-meta.xml
<CustomField>
    <fullName>Own_Contribution_a__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Own Contribution (a)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Own_Contribution_a_Date__c.field-meta.xml
<CustomField>
    <fullName>Own_Contribution_a_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Own Contribution (a) Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Own_Contribution_b__c.field-meta.xml
<CustomField>
    <fullName>Own_Contribution_b__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Own Contribution (b)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Own_Contribution_b_Date__c.field-meta.xml
<CustomField>
    <fullName>Own_Contribution_b_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Own Contribution (b) Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Registration_Date__c</fullName>
    <defaultValue>TODAY()+10</defaultValue>
    <label>Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <formula>Booking__r.Remarks__c</formula>
    <label>Remarks</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/SDR_Amount_Date__c.field-meta.xml
<CustomField>
    <fullName>SDR_Amount_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>SDR Amount Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Self_funding__c.field-meta.xml
<CustomField>
    <fullName>Self_funding__c</fullName>
    <label>Self-funding</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Self_Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>Self_Funding_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Self Funding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Token_Booking_Amount__c.field-meta.xml
<CustomField>
    <fullName>Token_Booking_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Token/ Booking Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Token_Booking_Amount_Date__c.field-meta.xml
<CustomField>
    <fullName>Token_Booking_Amount_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Token/ Booking Amount Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ex_PrintBookingTermSheetController.cls
public class Ex_PrintBookingTermSheetController {
    public Id bId {get;set;}
    public List<Terms_Sheet__c> tslist {get;set;}
    public Boolean showCheckBoxSelf {get;set;}
    public Boolean showCheckBoxHome {get;set;}
    
    
    public Ex_PrintBookingTermSheetController(){
        tslist = new list<Terms_Sheet__c>();
        showCheckBoxSelf = false;
        showCheckBoxHome = false;
        
        bId = (Id)ApexPages.currentPage().getParameters().get('bId');
        if(bId != null){
            
            tslist = [select Id,Self_funding__c, Home_Loan__c, Amount__c, Token_Booking_Amount__c,
                      Token_Booking_Amount_Date__c, Own_Contribution_a__c, Own_Contribution_a_Date__c,
                      Own_Contribution_b__c, Own_Contribution_b_Date__c, Home_Loan_Contribution_Self_Funding__c, Home_Loan_Date__c,
                      GST_Amount__c, GST_Amount_Date__c, SDR_Amount__c, SDR_Amount_Date__c , Primary_Applicant_Name__c, Registration_Date__c,
                      Unit__c, Agreement_Value__c, Remarks__c, Self_Funding_Amount__c from Terms_Sheet__c where Booking__c =: bId]; 
            if(tslist != null &&  tsList[0].Amount__c != null){
                if(tslist[0].Self_funding__c == 'Yes'){
                    showCheckBoxSelf = true;
                }
                if(tslist[0].Home_Loan__c == 'Yes'){
                    showCheckBoxHome = true;
                }
            }
        }
    }
}