force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Cancellation_Approver__c.field-meta.xml
<CustomField>
    <fullName>Booking_Cancellation_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Cancellation Approver(Level 1)</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Booking_Stage__c.field-meta.xml
<CustomField>
    <fullName>Booking_Stage__c</fullName>
    <label>Booking Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Booking_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Cancellation_Remark__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Remark__c</fullName>
    <label>Cancellation Remark</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Cancellation_Type__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Type__c</fullName>
    <label>Cancellation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Cancellation_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Refund_Amount__c.field-meta.xml
<CustomField>
    <fullName>Refund_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Refund Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Received__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Opportunity Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Booking_Cancellation_Approver__c.field-meta.xml
<CustomField>
    <fullName>Booking_Cancellation_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Cancellation Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Sale_Status__c.field-meta.xml
<CustomField>
    <fullName>Sale_Status__c</fullName>
    <label>Sale Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
                <isActive>false</isActive>
                <label>Available</label>
            </value>
            <value>
                <fullName>Booking In-Process</fullName>
                <isActive>false</isActive>
                <label>Booking In-Process</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Booking_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Booking In-Process</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation in-process</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Welcome Call Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Possession Done</fullName>
    </customValue>
    <customValue>
        <fullName>Welcome Call Done</fullName>
        <isActive>false</isActive>
        <label>Welcome Call Done</label>
    </customValue>
    <masterLabel>Booking Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Cancellation_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Cancelled By Puri Group</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelled By Customer</fullName>
    </customValue>
    <masterLabel>Cancellation Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Opportunity_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Follow-up</fullName>
        <default>true</default>
        <label>In Follow-up</label>
    </customValue>
    <customValue>
        <fullName>Booking In-Process</fullName>
    </customValue>
    <customValue>
        <fullName>Booked</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation In-Process</fullName>
    </customValue>
    <masterLabel>Opportunity Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_BookingCancellationHandler.cls
//-------------------------------------------//
//  Project: Satyam
//  Created By: Exceller tech
//  Created Date: 30-10-2023
//-------------------------------------------//
public class Ex_BookingCancellationHandler {
    @AuraEnabled(cacheable=false)
    public static String fetchBooking(Booking__c dataVal, String ctype, decimal amt,string remarks){
        try{
            Booking__c bk = [SELECT Id, Unit__c , Booking_Stage__c,Opportunity__c,Project__c,Project__r.Booking_Cancellation_Approver__c,
                             Total_Amount_Received__c FROM Booking__c WHERE Id=:dataVal.Id];
            System.debug('Booking Record: '+ bk);
          //  system.debug('Booking_Cancellation_Approver__c is: '+ bk.Project__r.Booking_Cancellation_Approver__c);
            if(bk!=null){
                bk.Booking_Stage__c = 'Cancellation in-process';
                bk.Cancellation_Type__c = ctype;
                bk.Refund_Amount__c = amt;
                bk.Cancellation_Remark__c = remarks;
                if(bk.Project__r.Booking_Cancellation_Approver__c != null){
                    bk.Booking_Cancellation_Approver__c = bk.Project__r.Booking_Cancellation_Approver__c;
                }
                update bk;
                
                /*system.debug('unit--->'+bk.Unit__c);
                Unit__c un = [SELECT Id, Sale_Status__c, Opportunity__c, Booking__c FROM Unit__c WHERE Id = :bk.Unit__c];
                if(un!=null){
                    un.Sale_Status__c = 'Vacant';
                    un.Opportunity__c = null;
                    un.Booking__c = null;
                    update un;
                }                
                
                // update Opportunity record
                Opportunity__c opp = [SELECT Id, Opportunity_Stage__c, Booking__c FROM Opportunity__c WHERE Id=:bk.Opportunity__c];
                if (opp != null) {
                    opp.Opportunity_Stage__c = 'Booking Cancelled';
                    opp.Booking__c = null;
                    update opp;
                }*/
                
                return 'success';
            }
            else{
                return 'error';
            }
        }
        catch(Exception ex){
            System.debug('Exception: '+ex.getMessage());
            return 'error';
        }
    }
    
    
}