force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>Opportunity__r.Mobile__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account)</relationshipLabel>
    <relationshipName>Leads2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Apply_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Apply_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field to assign the Lead to a member of the Presales Team. The assignment occurs only if the Presales Team is maintained on the Project and has active team members, designating one as the Lead owner using the Round Robin method.</description>
    <inlineHelpText>This field to assign the Lead to a member of the Presales Team. The assignment occurs only if the Presales Team is maintained on the Project and has active team members, designating one as the Lead owner using the Round Robin method.</inlineHelpText>
    <label>Apply Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</description>
    <inlineHelpText>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</inlineHelpText>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Source__c</fullName>
    <label>Lead Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lead_Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>AName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Leads (Opportunity)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Opted_In__c.field-meta.xml
<CustomField>
    <fullName>Opted_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Opted-In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead_Sub_source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_source__c</fullName>
    <label>Lead Sub-source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lead_Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>Account__r.PersonContact.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>NameA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/WA_API_Details_Gupshup__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Gupshup APIs</description>
    <label>WA API Details Gupshup</label>
</CustomObject>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/appId__c.field-meta.xml
<CustomField>
    <fullName>appId__c</fullName>
    <label>appId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/Connection__c.field-meta.xml
<CustomField>
    <fullName>Connection__c</fullName>
    <label>Connection</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>EndPoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/HandleId_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>HandleId_Endpoint__c</fullName>
    <label>HandleId Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/Source_Phone__c.field-meta.xml
<CustomField>
    <fullName>Source_Phone__c</fullName>
    <label>Source Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/src_name__c.field-meta.xml
<CustomField>
    <fullName>src_name__c</fullName>
    <label>src.name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/WhatsApp_Message__c.object-meta.xml
<CustomObject>
    <label>WhatsApp Message</label>
    <nameField>
        <displayFormat>WAM-{00000}</displayFormat>
        <label>WhatsApp Message Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WhatsApp Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WhatsApp_Message__c/fields/API_Status__c.field-meta.xml
<CustomField>
    <fullName>API_Status__c</fullName>
    <label>API Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>WhatsApp Messages</relationshipLabel>
    <relationshipName>WhatsApp_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Contains_File__c.field-meta.xml
<CustomField>
    <fullName>Contains_File__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contains File</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>WhatsApp Messages</relationshipLabel>
    <relationshipName>WhatsApp_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Message_Id__c.field-meta.xml
<CustomField>
    <fullName>Message_Id__c</fullName>
    <label>Message Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Message_Status__c.field-meta.xml
<CustomField>
    <fullName>Message_Status__c</fullName>
    <label>Message Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>enqueued</fullName>
            </value>
            <value>
                <fullName>failed</fullName>
            </value>
            <value>
                <fullName>sent</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>read</fullName>
            </value>
            <value>
                <fullName>deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Message_Text__c.field-meta.xml
<CustomField>
    <fullName>Message_Text__c</fullName>
    <label>Message Text</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
            <value>
                <fullName>Bulk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>WhatsApp Messages</relationshipLabel>
    <relationshipName>WhatsApp_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WhatsApp_Message__c/fields/Public_Link__c.field-meta.xml
<CustomField>
    <fullName>Public_Link__c</fullName>
    <label>Public Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Google</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregators</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Television</fullName>
    </customValue>
    <customValue>
        <fullName>Hoarding</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp</fullName>
    </customValue>
    <customValue>
        <fullName>Events</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Reference</fullName>
    </customValue>
    <customValue>
        <fullName>VDNB</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Calling</fullName>
    </customValue>
    <customValue>
        <fullName>Start Connect</fullName>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lead_Sub_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Google Search</fullName>
    </customValue>
    <customValue>
        <fullName>Google Display</fullName>
    </customValue>
    <customValue>
        <fullName>YouTube</fullName>
    </customValue>
    <customValue>
        <fullName>Discovery Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Gen Form</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Web Conversion</fullName>
    </customValue>
    <customValue>
        <fullName>MagicBricks</fullName>
    </customValue>
    <customValue>
        <fullName>NoBroker</fullName>
    </customValue>
    <customValue>
        <fullName>Housing</fullName>
    </customValue>
    <customValue>
        <fullName>99Acres</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Website</fullName>
    </customValue>
    <customValue>
        <fullName>ORM</fullName>
    </customValue>
    <customValue>
        <fullName>Jacket</fullName>
    </customValue>
    <customValue>
        <fullName>Power Jacket</fullName>
    </customValue>
    <customValue>
        <fullName>Full Page</fullName>
    </customValue>
    <customValue>
        <fullName>Half Page</fullName>
    </customValue>
    <customValue>
        <fullName>Inserts</fullName>
    </customValue>
    <customValue>
        <fullName>RJ Mentions</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Advertisement</fullName>
    </customValue>
    <customValue>
        <fullName>Show Sponsorship</fullName>
    </customValue>
    <customValue>
        <fullName>Billboard</fullName>
    </customValue>
    <customValue>
        <fullName>Bus Shelter</fullName>
    </customValue>
    <customValue>
        <fullName>Kiosk</fullName>
    </customValue>
    <customValue>
        <fullName>Cantilever</fullName>
    </customValue>
    <customValue>
        <fullName>Gantry</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Van</fullName>
    </customValue>
    <customValue>
        <fullName>Bus Panel</fullName>
    </customValue>
    <customValue>
        <fullName>Railway Station Boards</fullName>
    </customValue>
    <customValue>
        <fullName>External WhatsApp</fullName>
    </customValue>
    <masterLabel>Lead Sub Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RestLiveChatController.cls
@RestResource(urlMapping='/LiveChat/')
global without sharing class RestLiveChatController {

    public static String response;

    @HttpPost
    global static void LiveChat() {
        returnResponse rr = new returnResponse();
        response = String.valueOf(rr);

        // Parsing the request body into LiveChatController object
        LiveChatController parseData = LiveChatController.parse(RestContext.request.requestBody.toString());
        System.debug('parseData = ' + parseData);

        // Accessing data from the parsed object
        String type = parseData.type;

        // Validating request
        if (isValidRequest(parseData)) {
            if (type == 'user-event') {
                if (handleUserEvent(parseData)) {
                    //rr.returnCode = '200';
                } else {
                    //rr.returnCode = '400';
                }
            } else if (type == 'message') {
                if (handleMessage(parseData)) {
                    //rr.returnCode = '200';
                } else {
                    //rr.returnCode = '400';
                }
            }
            else if (type == 'message-event') {
                if (handleMessageStatus(parseData)) {
                    //rr.returnCode = '200';
                } else {
                    //rr.returnCode = '400';
                }
            }
        } else {
            //rr.returnCode = '400';
        }
    }

    // Validating the request
    public static Boolean isValidRequest(LiveChatController parseData) {
        return parseData != null && parseData.payload != null;
    }

    // Handling user-event requests
    public static Boolean handleUserEvent(LiveChatController parseData) {
        String phone = parseData.payload.phone;
        String actionType = parseData.payload.type;

        // Query WA API Details
        WA_API_Details_Gupshup__c apiDetails = getWAAPIDetails(parseData.app);
        System.debug('apiDetails: ' + apiDetails);

        return userevent(parseData, phone, actionType);
    }

    // Handling message requests
    public static Boolean handleMessage(LiveChatController parseData) {
        String phone_number = parseData.payload.sender.phone;
        String sendername = parseData.payload.sender.name;
        String message_text = parseData.payload.payload.text;
        String MessageId = parseData.payload.id;
        String messageType = parseData.payload.type;
        String fileurl = parseData.payload.payload.url;

        // Query WA API Details
        WA_API_Details_Gupshup__c apiDetails = getWAAPIDetails(parseData.app);
        System.debug('apiDetails: ' + apiDetails);

        return createWhatsAppMessage(parseData, phone_number, message_text, MessageId, messageType, fileurl, sendername);
    }

    // Handling message status requests
    public static Boolean handleMessageStatus(LiveChatController parseData) {
        String messageId = parseData.payload.id;
        String destination = parseData.payload.destination;
        String messageStatus = parseData.payload.type;

        return UpdateWhatsAppMessage(parseData, messageId, destination, messageStatus);
    }

    // Creating WhatsApp message
    public static Boolean createWhatsAppMessage(LiveChatController parseData, String phone_number, String message_text, String MessageId, String messageType, String fileurl, String sendername) {
        String MobileNumber = phone_number.substring(phone_number.length() - 10);

        system.debug('MobileNumber' + MobileNumber);
        
        // Query WA API Details
        WA_API_Details_Gupshup__c apiDetails = getWAAPIDetails(parseData.app);
        System.debug('apiDetails: ' + apiDetails);
        
        List<Project__c> project = [Select Id from Project__c where Name =: apiDetails.Project_Name__c];

        List<Opportunity__c> existingOpportunity = new List<Opportunity__c>();
        List<Booking__c> existingBooking = new List<Booking__c>();

        existingBooking = [SELECT Id, Mobile__c, Project__c, Project__r.Name
                           FROM Booking__c
                           WHERE (Mobile__c = :MobileNumber 
                           AND Project__r.Name =: apiDetails.Project_Name__c)
                           LIMIT 1];

        existingOpportunity = [SELECT Id, Mobile__c, Account__c,  Project__c, Project__r.Name
                               FROM Opportunity__c
                               WHERE ((Mobile__c = :MobileNumber OR Phone__c =: MobileNumber) 
                               AND Project__r.Name =: apiDetails.Project_Name__c)
                               LIMIT 1];

        List<Lead__c> existingLead = [SELECT Id, Mobile__c, isConverted__c, Project__c, Project__r.Name
                                      FROM Lead__c WHERE Mobile__c = :MobileNumber 
                                      AND isConverted__c =: FALSE 
                                      AND Project__r.Name =: apiDetails.Project_Name__c
                                      LIMIT 1];
        system.debug('existingLead :' + existingLead);

        // Creating WhatsApp message record
        if (!existingBooking.isEmpty() && existingBooking != null) {
            WhatsApp_Message__c whatsappMessage = new WhatsApp_Message__c();
            whatsappMessage.Customer_Phone__c = MobileNumber;
            whatsappMessage.Success__c = true;

            if (!existingBooking.isEmpty() && existingBooking != null) {
                whatsappMessage.Booking__c = existingBooking[0].Id;
            }

            whatsappMessage.Message_Text__c = message_text;
            whatsappMessage.API_Request__c = String.valueOf(parseData);
            whatsappMessage.API_Response__c = response;
            whatsappMessage.Message_Id__c = MessageId;
            whatsappMessage.API_Status__c = 'Success';
            whatsappMessage.Message_Type__c = 'Normal';
            if (messageType != 'text') {
                whatsappMessage.Contains_File__c = true;
                whatsappMessage.Public_Link__c = fileurl;
            }

            try {
                insert whatsappMessage;
                return true;
            } catch (Exception e) {
                return false;
            }
        } else if (!existingOpportunity.isEmpty() && existingOpportunity != null) {
            WhatsApp_Message__c whatsappMessage = new WhatsApp_Message__c();
            whatsappMessage.Customer_Phone__c = MobileNumber;
            whatsappMessage.Success__c = true;

            if (!existingOpportunity.isEmpty() && existingOpportunity != null) {
                whatsappMessage.Opportunity__c = existingOpportunity[0].Id;
            }

            whatsappMessage.Message_Text__c = message_text;
            whatsappMessage.API_Request__c = String.valueOf(parseData);
            whatsappMessage.API_Response__c = response;
            whatsappMessage.Message_Id__c = MessageId;
            whatsappMessage.API_Status__c = 'Success';
            whatsappMessage.Message_Type__c = 'Normal';
            if (messageType != 'text') {
                whatsappMessage.Contains_File__c = true;
                whatsappMessage.Public_Link__c = fileurl;
            }

            try {
                insert whatsappMessage;
                return true;
            } catch (Exception e) {
                return false;
            }
        } else if (!existingLead.isEmpty() && existingLead != null) {
            WhatsApp_Message__c whatsappMessage = new WhatsApp_Message__c();
            whatsappMessage.Customer_Phone__c = MobileNumber;
            whatsappMessage.Success__c = true;

            if (!existingLead.isEmpty() && existingLead != null) {
                whatsappMessage.Lead__c = existingLead[0].Id;
            }

            whatsappMessage.Message_Text__c = message_text;
            whatsappMessage.API_Request__c = String.valueOf(parseData);
            whatsappMessage.API_Response__c = response;
            whatsappMessage.Message_Id__c = MessageId;
            whatsappMessage.API_Status__c = 'Success';
            whatsappMessage.Message_Type__c = 'Normal';
            if (messageType != 'text') {
                whatsappMessage.Contains_File__c = true;
                whatsappMessage.Public_Link__c = fileurl;
            }
            
            try {
                insert whatsappMessage;
                return true;
            } catch (Exception e) {
                return false;
            }

            
        } else {
            
            try {
                Lead__c l = new Lead__c();
                l.Mobile__c = MobileNumber;
                //l.First_Name__c = 'Whatsapp';
                if(sendername != null)
                    l.Last_Name__c = sendername;
                
                if(!project.isEmpty() && project != null)
                	l.Project__c = project[0].Id;
                l.Apply_Round_Robin__c = true;
                l.Lead_Source__c = 'WhatsApp';
                l.Lead_Sub_Source__c = 'External WhatsApp';
                insert l;
                
                WhatsApp_Message__c whatsappMessage = new WhatsApp_Message__c();
                whatsappMessage.Customer_Phone__c = MobileNumber;
                whatsappMessage.Success__c = true;
                
                whatsappMessage.Lead__c = l.Id;
                
                whatsappMessage.Message_Text__c = message_text;
                whatsappMessage.API_Request__c = String.valueOf(parseData);
                whatsappMessage.API_Response__c = response;
                whatsappMessage.Message_Id__c = MessageId;
                whatsappMessage.API_Status__c = 'Success';
                whatsappMessage.Message_Type__c = 'Normal';
                if (messageType != 'text') {
                    whatsappMessage.Contains_File__c = true;
                    whatsappMessage.Public_Link__c = fileurl;
                }
                
                insert whatsappMessage;    
                return true;
                
            } catch (Exception e) {
                return false;
            }
        }
    }

    public static Boolean userevent(LiveChatController parseData, String phone_number, String actionType) {
        String MobileNumber = phone_number;
        system.debug('MobileNumber userevent :' + MobileNumber);

        // Querying existing records
        List<Account> existingAccount = [SELECT Id, PersonMobilePhone, Phone, Opted_In__c
                                          FROM Account
                                          WHERE PersonMobilePhone = :MobileNumber
                                          OR Phone = :MobileNumber
                                          LIMIT 1];
        List<Opportunity__c> existingOpportunity = new List<Opportunity__c>();
        system.debug('existingAccount :' + existingAccount);

        if (!existingAccount.isEmpty() && existingAccount != null) {
            existingOpportunity = [SELECT Id, Account__c, Mobile__c, Opted_In__c
                                   FROM Opportunity__c
                                   WHERE (Mobile__c = :MobileNumber
                                   AND Account__c =: existingAccount[0].Id)
                                   LIMIT 1];
        } else {
            existingOpportunity = [SELECT Id, Mobile__c, Account__c, Opted_In__c
                                   FROM Opportunity__c
                                   WHERE Mobile__c = :MobileNumber
                                   LIMIT 1];
            system.debug('existingOpportunity' + existingOpportunity);
        }

        List<Lead__c> existingLead = [SELECT Id, Mobile__c, Opted_In__c
                                      FROM Lead__c
                                      WHERE Mobile__c = :MobileNumber
                                      LIMIT 1];
        system.debug('existingLead' + existingLead);

        if (!existingAccount.isEmpty() && existingAccount != null) {

            if (actionType == 'opted-in')
                existingAccount[0].Opted_In__c = true;
            else if (actionType == 'opted-out')
                existingAccount[0].Opted_In__c = false;

            try {
                update existingAccount;
                if (!existingOpportunity.isEmpty() && existingOpportunity != null && existingOpportunity[0].Id != null) {

                    if (actionType == 'opted-in')
                        existingOpportunity[0].Opted_In__c = true;
                    else if (actionType == 'opted-out')
                        existingOpportunity[0].Opted_In__c = false;

                    update existingOpportunity;
                }
                return true;
            } catch (Exception e) {
                return false;
            }
        }
        if (!existingOpportunity.isEmpty() && existingOpportunity != null && existingOpportunity[0].Id != null) {

            if (actionType == 'opted-in')
                existingOpportunity[0].Opted_In__c = true;
            else if (actionType == 'opted-out')
                existingOpportunity[0].Opted_In__c = false;

            try {
                update existingOpportunity;
                return true;
            } catch (Exception e) {
                return false;
            }
        } else if (!existingLead.isEmpty() && existingLead != null) {
            System.debug('actionType = ' + actionType);

            if (actionType == 'opted-in') {
                existingLead[0].Opted_In__c = true;
            } else if (actionType == 'opted-out') {
                existingLead[0].Opted_In__c = false;
            }

            try {

                System.debug('existingLead = ' + existingLead);
                update existingLead;
                return true;
            } catch (Exception e) {
                System.debug(e.getMessage());
                return false;
            }
        }
        return false;
    }

    public static Boolean UpdateWhatsAppMessage(LiveChatController parseData, String messageId, String destination, String messageStatus) {
        String MobileNumber = destination.substring(destination.length() - 10);

        // Querying existing records
        List<WhatsApp_Message__c> WhatsappMessage = [SELECT Id, Message_Status__c, Message_Id__c, Lead__c, Opportunity__c,
                                                     Account__c, Customer_Phone__c
                                                     FROM WhatsApp_Message__c
                                                     WHERE Customer_Phone__c =: MobileNumber
                                                     AND Message_Id__c =: messageId
                                                     LIMIT 1];

        if (!WhatsappMessage.isEmpty() && WhatsappMessage != null && WhatsappMessage[0].Message_Id__c != null) {

            try {

                WhatsappMessage[0].Message_Status__c = messageStatus;
                update WhatsappMessage;

                return true;
            } catch (Exception e) {
                return false;
            }
        }

        return false;
    }

    public static WA_API_Details_Gupshup__c getWAAPIDetails(String appName) {
        List<WA_API_Details_Gupshup__c> apiDetailsList = [select Id, Name, API_Key__c, Channel__c, Connection__c, EndPoint__c, 
                                                          HandleId_Endpoint__c, Name__c, Source_Phone__c, appId__c, isActive__c,
                                                          src_name__c, token__c, EndPoint_URL__c, Project_Name__c
                                                          from WA_API_Details_Gupshup__c
                                                          WHERE Name__c = :appName
                                                          LIMIT 1];
        
        System.debug('apiDetailsList = '+ apiDetailsList);
        
        if (!apiDetailsList.isEmpty()) {
            return apiDetailsList[0];
        }
        return null;
    }

    global class returnResponse {
        webservice string returnCode;
        //webservice string message;
    }
}