force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Checklist__c/Booking_Checklist__c.object-meta.xml
<CustomObject>
    <label>Booking Checklist</label>
    <nameField>
        <displayFormat>BWC-{000000}</displayFormat>
        <label>Booking Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Checklist__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Checklists</relationshipLabel>
    <relationshipName>Booking_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestEx_BookingChecklistHandler.cls
@isTest
public class TestEx_BookingChecklistHandler {
    @isTest
    static void testcheckList(){
        Test.startTest();
        Booking__c bk = new Booking__c();
        insert bk;
        
        Booking_Checklist__c b = new Booking_Checklist__c();
        b.Booking__c = bk.Id;
        insert b;
        update b;
        
        Ex_CheckRecursive.runOnce();
        Test.StopTest();
    }
}