force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Amount_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Demanded__c</fullName>
    <label>Total Amount Demanded</label>
    <summarizedField>Demand__c.Total_Amount_Demanded__c</summarizedField>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Paid__c</fullName>
    <label>Total Amount Paid</label>
    <summarizedField>Demand__c.Total_Amount_Paid__c</summarizedField>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount__c</fullName>
    <label>Total Interest Amount</label>
    <summarizedField>Demand__c.Total_Interest_Amount__c</summarizedField>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Interest_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount_Paid__c</fullName>
    <label>Total Interest Amount Paid</label>
    <summarizedField>Demand__c.Total_Interest_Amount_Paid__c</summarizedField>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Interest_Amount_Waived__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount_Waived__c</fullName>
    <label>Total Interest Amount Waived</label>
    <summarizedField>Demand__c.Total_Interest_Amount_Waived__c</summarizedField>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Tax_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Demanded__c</fullName>
    <label>Total Tax Demanded</label>
    <summarizedField>Demand__c.Total_Tax_Demanded__c</summarizedField>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Tax_On_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_On_Interest_Amount__c</fullName>
    <label>Total Tax On Interest Amount</label>
    <summarizedField>Demand__c.Total_Tax_On_Interest_Amount__c</summarizedField>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Tax_On_Interest_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_On_Interest_Amount_Paid__c</fullName>
    <label>Total Tax On Interest Amount Paid</label>
    <summarizedField>Demand__c.Total_Tax_On_Interest_Amount_Paid__c</summarizedField>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Tax_On_Interest_Amount_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_On_Interest_Amount_Remaining__c</fullName>
    <formula>Total_Tax_On_Interest_Amount__c - Total_Tax_On_Interest_Amount_Paid__c - Total_Tax_On_Interest_Amount_Waived__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Tax On Interest Amount Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Tax_On_Interest_Amount_Waived__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_On_Interest_Amount_Waived__c</fullName>
    <label>Total Tax On Interest Amount Waived</label>
    <summarizedField>Demand__c.Total_Tax_On_Interest_Amount_Waived__c</summarizedField>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Tax_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Paid__c</fullName>
    <label>Total Tax Paid</label>
    <summarizedField>Demand__c.Total_Tax_Paid__c</summarizedField>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/fields/Agreement_Value_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value_Demanded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Agreement_Value_Paid__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Agreement_Value_Tax_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value_Tax_Demanded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value Tax Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Agreement_Value_Tax_Paid__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value_Tax_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value Tax Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Agreement_Value_Tax_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value_Tax_Remaining__c</fullName>
    <formula>Agreement_Value_Tax_Demanded__c -  Agreement_Value_Tax_Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agreement Value Tax Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Interest_Calculated_Till__c.field-meta.xml
<CustomField>
    <fullName>Interest_Calculated_Till__c</fullName>
    <label>Interest Calculated Till</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Other_Charges_Tax_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Other_Charges_Tax_Demanded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Other Charges Tax Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Amount_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Demanded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Amount_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Remaining__c</fullName>
    <formula>Total_Amount_Demanded__c -  Total_Amount_Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Interest_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Interest Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Interest_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Interest Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Interest_Amount_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount_Remaining__c</fullName>
    <formula>Total_Interest_Amount__c - Total_Interest_Amount_Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Interest Amount Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Interest_Amount_Waived__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount_Waived__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Interest Amount Waived</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Tax_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Demanded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Tax Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Tax_On_Interest_Amount_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_On_Interest_Amount_Remaining__c</fullName>
    <formula>Total_Tax_On_Interest_Amount__c - Total_Tax_On_Interest_Amount_Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Tax On Interest Amount Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Tax_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Tax Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/Payment_Milestone__c.object-meta.xml
<CustomObject>
    <label>Payment Milestone</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Milestone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Milestone__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <formula>Quotation__r.Booking__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Booking</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Payment Milestone</relationshipLabel>
    <relationshipName>Payment_Milestone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Rate_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Interest__c</fullName>
    <label>Rate of Interest</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ex_InterestCalculateManagementServices.cls
public class Ex_InterestCalculateManagementServices {
 
     public static void interestCalculate(Map<Id, Date> boookingInterestDateMap) {
        Map<String, List<Demand__c>> pendingDemandMap = new Map<String, List<Demand__c>>();
        List<Demand__c> updateDemandList = new List<Demand__c>();
        
        pendingDemandMap = getPendingDemandMap(boookingInterestDateMap.keySet());
        
        if(!pendingDemandMap.isEmpty() && pendingDemandMap != null) {
            for(Id bId: boookingInterestDateMap.keySet()) {
                if(pendingDemandMap.containsKey(bId)) {
                    for(Demand__c d: pendingDemandMap.get(bId)) {
                        if(boookingInterestDateMap.get(bId) > d.Due_Date__c && d.Booking__r.Project__r.Rate_of_Interest__c != null) {
                            Integer noOfDays = 0;
                            if(d.Interest_Calculated_Till__c != null) {
                                noOfDays = d.Interest_Calculated_Till__c.daysBetween(boookingInterestDateMap.get(bId));
                            } else {
                                noOfDays = d.Due_Date__c.daysBetween(boookingInterestDateMap.get(bId));
                            }
                            Decimal interestAmount = (((d.Total_Amount_Remaining__c + d.Total_Tax_Remaining__c) * (d.Booking__r.Project__r.Rate_of_Interest__c / 100)) * noOfDays).setscale(2, RoundingMode.HALF_UP);
                            System.debug('interestAmount:'+interestAmount + d.Id);
                            d.Total_Interest_Amount__c = d.Total_Interest_Amount__c + interestAmount;
                            System.debug('TotalinterestAmount:'+ d.Total_Interest_Amount__c);
                            d.Interest_Calculated_Till__c = boookingInterestDateMap.get(bId);
                            updateDemandList.add(d);
                        }
                    }
                }
            }
        }
        if(!updateDemandList.isEmpty() && updateDemandList != null)
            update updateDemandList;
    }
    
    public static Map<String, List<Demand__c>> getPendingDemandMap(Set<Id> bookingIdSet) {
        Map<String, List<Demand__c>> pendingDemandMap = new Map<String, List<Demand__c>>();
        List<Demand__c> demandList = [Select Id, Booking__c, Quotation__c, Payment_Milestone__c, Milestone_Name__c, Due_Date__c, Invoice_Date__c, Demand_Type__c, Booking__r.Project__r.Rate_of_Interest__c,
                                      Total_Interest_Amount__c, Total_Interest_Amount_Paid__c, Total_Interest_Amount_Waived__c, Total_Interest_Amount_Remaining__c, Interest_Calculated_Till__c,
                                      Total_Tax_On_Interest_Amount__c, Total_Tax_On_Interest_Amount_Paid__c, Total_Tax_On_Interest_Amount_Waived__c, Total_Tax_On_Interest_Amount_Remaining__c,
                                      Total_Amount_Demanded__c, Total_Amount_Paid__c, Total_Amount_Remaining__c, Total_Tax_Demanded__c, Total_Tax_Paid__c, Total_Tax_Remaining__c,
                                      Agreement_Value_Demanded__c, Agreement_Value_Paid__c, Agreement_Value_Remaining__c, Agreement_Value_Tax_Demanded__c, Agreement_Value_Tax_Paid__c, Agreement_Value_Tax_Remaining__c,
                                      Other_Charges_Demanded__c, Other_Charges_Paid__c, Other_Charges_Remaining__c, Other_Charges_Tax_Demanded__c, Other_Charges_Tax_Paid__c, Other_Charges_Tax_Remaining__c,
                                      Statutory_Charges_Demanded__c, Statutory_Charges_Paid__c, Statutory_Charges_Remaining__c, Statutory_Charges_Tax_Demanded__c, Statutory_Charges_Tax_Paid__c, Statutory_Charges_Tax_Remaining__c
                                      from Demand__c where Booking__c IN: bookingIdSet AND 
                                      (Total_Amount_Remaining__c > 0 OR Total_Tax_Remaining__c > 0)
                                      ORDER BY Due_Date__c ASC];
        //system.debug('demandList: '+demandList);
        
        if(demandList != null) {
            for(Demand__c d: demandList) {
                if(pendingDemandMap.containsKey(d.Booking__c)) {
                    pendingDemandMap.get(d.Booking__c).add(d);
                } else {
                    List<Demand__c> newList = new List<Demand__c>();
                    newList.add(d);
                    pendingDemandMap.put(d.Booking__c, newList);
                }
            }
        }
        return pendingDemandMap;
    }
}