force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Booking_Stage__c.field-meta.xml
<CustomField>
    <fullName>Booking_Stage__c</fullName>
    <label>Booking Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Booking_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/CRM_Head__c.field-meta.xml
<CustomField>
    <fullName>CRM_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRM Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Mode_of_Funding__c.field-meta.xml
<CustomField>
    <fullName>Mode_of_Funding__c</fullName>
    <label>Mode of Funding</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Loan</fullName>
            </value>
            <value>
                <fullName>Self Funding</fullName>
            </value>
            <value>
                <fullName>Partial Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Charge_Details__c/Charge_Details__c.object-meta.xml
<CustomObject>
    <label>Charge Details</label>
    <nameField>
        <label>Charge Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge_Details__c/fields/Charge_Amount__c.field-meta.xml
<CustomField>
    <fullName>Charge_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Charge_Details__c/fields/Charge_Bucket__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket__c</fullName>
    <label>Charge Bucket</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Charge_Details__c/fields/Charge_Rate__c.field-meta.xml
<CustomField>
    <fullName>Charge_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Charge_Details__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Charge_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Charge_Details__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Charge Details</relationshipLabel>
    <relationshipName>Charge_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/Payment_Milestone__c.object-meta.xml
<CustomObject>
    <label>Payment Milestone</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Milestone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Milestone__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <formula>Quotation__r.Booking__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Booking</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Milestone_Type__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Type__c</fullName>
    <label>Milestone Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Date Linked</fullName>
            </value>
            <value>
                <fullName>Construction Linked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Payment Milestone</relationshipLabel>
    <relationshipName>Payment_Milestone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Scheme__c/Payment_Scheme__c.object-meta.xml
<CustomObject>
    <label>Payment Scheme</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Scheme</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Scheme__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Payment Scheme</relationshipLabel>
    <relationshipName>Payment_Scheme</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/CRM_Head__c.field-meta.xml
<CustomField>
    <fullName>CRM_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRM Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/AV_GST_Percentage__c.field-meta.xml
<CustomField>
    <fullName>AV_GST_Percentage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>AV GST Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Configuration_Type__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Type__c</fullName>
    <label>Configuration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Configuration_Required</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Floor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Sales_Status__c.field-meta.xml
<CustomField>
    <fullName>Sales_Status__c</fullName>
    <label>Sales Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booking-In-Process</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Not for Sale</fullName>
                <isActive>false</isActive>
                <label>Not for Sale</label>
            </value>
            <value>
                <fullName>UnBlocked</fullName>
                <isActive>false</isActive>
                <label>UnBlocked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Total_carpet_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>Total_carpet_Sq_Ft__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total carpet (Sq. Ft.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Booking_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Booking In-Process</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation in-process</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Welcome Call Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Possession Done</fullName>
    </customValue>
    <customValue>
        <fullName>Welcome Call Done</fullName>
        <isActive>false</isActive>
        <label>Welcome Call Done</label>
    </customValue>
    <masterLabel>Booking Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Charge_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Amount</fullName>
    </customValue>
    <customValue>
        <fullName>Percentage</fullName>
    </customValue>
    <masterLabel>Charge Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Configuration_Required.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Villa</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Shop</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <masterLabel>Configuration Required</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestEx_ViewPaymentPlanController.cls
@isTest
public class TestEx_ViewPaymentPlanController {
    
    @isTest
    public static void testGetBooking() {
        // Create a test user
        Profile prof = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'testuser' + DateTime.now().getTime() + '@example.com',
            Username = 'testuser' + DateTime.now().getTime() + '@example.com',
            Alias = 'tuser',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = prof.Id,
            LanguageLocaleKey = 'en_US'
        );
        insert testUser;
        
        // Create Project
        Project__c project = new Project__c(Name = 'Test Project');
        insert project;
        
        // Create Tower
        Tower__c tower = new Tower__c(Name = 'Test Tower', Project__c = project.Id);
        insert tower;
        
        // Create Unit
        Unit__c unit = new Unit__c(
            Tower__c = tower.Id,
            Project__c = project.Id,
            Total_carpet_Sq_Ft__c = 10,
            Configuration_Type__c = '4 BHK',
            Floor__c = 1,
            Sales_Status__c = 'Vacant'
        );
        insert unit;
        
        // Create Quotation
        Quotation__c quotation = new Quotation__c(
            Unit__c = unit.Id,
            Project__c = project.Id,
            Tower__c = tower.Id,
            AV_GST_Percentage__c = 4
        );
        insert quotation;
        
        Charge_Details__c cd=new Charge_Details__c();
        cd.Quotation__c = quotation.id;
        cd.Name = 'Stamp Duty';
        cd.Charge_Type__c = 'Percentage';
        cd.Calculation_Area_Type__c = 'Carpet Area';
        cd.Charge_Amount__c=60000;
        cd.Charge_Bucket__c='Statutory Charges';
        cd.Charge_Percentage__c=10;
        cd.Charge_Rate__c=6767;
        insert cd;
        
        Payment_Milestone__c pm=new Payment_Milestone__c();
        pm.Quotation__c=quotation.id;
        pm.Milestone_Name__c='mile 1';
        pm.Is_Raised__c=true;
        pm.Milestone_Type__c='Date Linked';
        insert pm;
        
        
        // Create Booking
        Booking__c booking = new Booking__c(
            Booking_Date__c = System.today(),
            Mode_Of_Funding__c = 'Self Funding',
            Project__c = project.Id,
            Tower__c = tower.Id,
            Booking_Stage__c = 'Booking In-Process',
            Quotation__c = quotation.Id,
            Unit__c = unit.Id,
            Remarks__c = 'Test Booking',
            Loan_Bank_Name__c = 'HDFC Bank',
            Loan_Amount__c = 700.00,
            CRM_Head__c = testUser.Id
        );
        insert booking;
        
        Test.startTest();
        List<Booking__c> result = Ex_ViewPaymentPlanController.getBooking(booking.Id);
        Test.stopTest();
        
    }
    
    @isTest
    public static void testGetPaymentScheme() {
        
        // Create a test user
        Profile prof = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'testuser' + DateTime.now().getTime() + '@example.com',
            Username = 'testuser' + DateTime.now().getTime() + '@example.com',
            Alias = 'tuser',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = prof.Id,
            LanguageLocaleKey = 'en_US'
        );
        insert testUser;
        
        // Create Project
        Project__c project = new Project__c(Name = 'Test Project');
        insert project;
        
        // Create Tower
        Tower__c tower = new Tower__c(Name = 'Test Tower', Project__c = project.Id);
        insert tower;
        
        // Create Unit
        Unit__c unit = new Unit__c(
            Tower__c = tower.Id,
            Project__c = project.Id,
            Total_carpet_Sq_Ft__c = 10,
            Configuration_Type__c = '4 BHK',
            Floor__c = 1,
            Sales_Status__c = 'Vacant'
        );
        insert unit;
        
        Payment_Scheme__c pms = new Payment_Scheme__c(Name = 'Test Payment Scheme');
        insert pms;
        
        // Create Quotation
        Quotation__c quotation = new Quotation__c(
            Unit__c = unit.Id,
            Project__c = project.Id,
            Tower__c = tower.Id,
            AV_GST_Percentage__c = 4,
            Payment_Scheme__c = pms.id
            
        );
        insert quotation;
        
        Charge_Details__c cd=new Charge_Details__c();
        cd.Quotation__c = quotation.id;
        cd.Name = 'Stamp Duty';
        cd.Charge_Type__c = 'Percentage';
        cd.Calculation_Area_Type__c = 'Carpet Area';
        cd.Charge_Amount__c=60000;
        cd.Charge_Bucket__c='Statutory Charges';
        cd.Charge_Percentage__c=10;
        cd.Charge_Rate__c=6767;
        insert cd;
        
        Payment_Milestone__c pm=new Payment_Milestone__c();
        pm.Quotation__c = quotation.id;
        pm.Milestone_Name__c='mile 1';
        pm.Is_Raised__c=true;
        pm.Milestone_Type__c='Date Linked';
        insert pm;
        
        Booking__c booking = new Booking__c(
            Booking_Date__c = System.today(),
            Mode_Of_Funding__c = 'Self Funding',
            Project__c = project.Id,
            Tower__c = tower.Id,
            Booking_Stage__c = 'Booking In-Process',
            Quotation__c = quotation.Id,
            Unit__c = unit.Id,
            Remarks__c = 'Test Booking',
            Loan_Bank_Name__c = 'HDFC Bank',
            Loan_Amount__c = 700.00,
            CRM_Head__c = testUser.Id
        );
        insert booking;
        
        Test.startTest();
        String result = Ex_ViewPaymentPlanController.getPaymentScheme(pms.Id);
        Test.stopTest();       
        
    }
    
    @isTest
    public static void testGetPaymentMilestone() {
        
        Profile prof = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];
        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Email = 'testuser' + DateTime.now().getTime() + '@example.com',
            Username = 'testuser' + DateTime.now().getTime() + '@example.com',
            Alias = 'tuser',
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            ProfileId = prof.Id,
            LanguageLocaleKey = 'en_US'
        );
        insert testUser;
        
        // Create Project
        Project__c project = new Project__c(Name = 'Test Project');
        insert project;
        
        // Create Tower
        Tower__c tower = new Tower__c(Name = 'Test Tower', Project__c = project.Id);
        insert tower;
        
        // Create Unit
        Unit__c unit = new Unit__c(
            Tower__c = tower.Id,
            Project__c = project.Id,
            Total_carpet_Sq_Ft__c = 10,
            Configuration_Type__c = '4 BHK',
            Floor__c = 1,
            Sales_Status__c = 'Vacant'
        );
        insert unit;
        
        // Create Quotation
        Quotation__c quotation = new Quotation__c(
            Unit__c = unit.Id,
            Project__c = project.Id,
            Tower__c = tower.Id,
            AV_GST_Percentage__c = 4
        );
        insert quotation;
        
        Charge_Details__c cd=new Charge_Details__c();
        cd.Quotation__c = quotation.id;
        cd.Name = 'Stamp Duty';
        cd.Charge_Type__c = 'Percentage';
        cd.Calculation_Area_Type__c = 'Carpet Area';
        cd.Charge_Amount__c=60000;
        cd.Charge_Bucket__c='Statutory Charges';
        cd.Charge_Percentage__c=10;
        cd.Charge_Rate__c=6767;
        insert cd;
        
        Payment_Milestone__c pm=new Payment_Milestone__c();
        pm.Quotation__c=quotation.id;
        pm.Milestone_Name__c='mile 1';
        pm.Is_Raised__c=true;
        pm.Milestone_Type__c='Date Linked';
        insert pm;
        
        Booking__c booking = new Booking__c(
            Booking_Date__c = System.today(),
            Mode_Of_Funding__c = 'Self Funding',
            Project__c = project.Id,
            Tower__c = tower.Id,
            Booking_Stage__c = 'Booking In-Process',
            Quotation__c = quotation.Id,
            Unit__c = unit.Id,
            Remarks__c = 'Test Booking',
            Loan_Bank_Name__c = 'HDFC Bank',
            Loan_Amount__c = 700.00,
            CRM_Head__c = testUser.Id
        );
        insert booking;
        
        Test.startTest();
        List<Payment_Milestone__c> milestones = Ex_ViewPaymentPlanController.getPaymentMilestone(booking.Id);
        Test.stopTest();
        
    }
    
}