force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/Terms_Sheet__c.object-meta.xml
<CustomObject>
    <label>Terms Sheet</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Terms Sheet Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Terms Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Terms_Sheet__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <formula>Booking__r.Agreement_Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Agreement Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Terms_Sheet__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Terms Sheets</relationshipLabel>
    <relationshipName>Terms_Sheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestEx_PrintBookingTermSheetController.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 30-11-2023
//-------------------------------------------//
@Istest
public class TestEx_PrintBookingTermSheetController {
    @isTest
    public static void testTermSheet() {
        Booking__c b = new Booking__c();
        b.Agreement_Value__c = 100;
        insert b;
        
        Terms_Sheet__c tm = new Terms_Sheet__c();
        tm.Booking__c = b.Id;
        insert tm;
        
        Test.startTest();
        ApexPages.currentPage().getParameters().put('bId', b.Id);
        Ex_PrintBookingTermSheetController controller = new Ex_PrintBookingTermSheetController();
        Test.stopTest();
    }
    

}