force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Construction_Stage__c/Construction_Stage__c.object-meta.xml
<CustomObject>
    <label>Construction Stage</label>
    <nameField>
        <label>Construction Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Construction Stages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Construction_Stage__c/fields/Milestone_Status__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Status__c</fullName>
    <label>Milestone Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ongoing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Construction_Stage__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <formula>Tower__r.Project__r.Name</formula>
    <label>Project</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Construction_Stage__c/fields/Stage_Description__c.field-meta.xml
<CustomField>
    <fullName>Stage_Description__c</fullName>
    <label>Stage Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Construction_Stage__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Construction Stage</relationshipLabel>
    <relationshipName>Construction_Stage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Construction_Stage__c/fields/Unit_Wise_Milestone__c.field-meta.xml
<CustomField>
    <fullName>Unit_Wise_Milestone__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Unit Wise Milestone</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Construction_Stage_History__c/Construction_Stage_History__c.object-meta.xml
<CustomObject>
    <label>Construction Stage History</label>
    <nameField>
        <label>Construction Stage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Construction Stage Historys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Construction_Stage_History__c/fields/Construction_Stage__c.field-meta.xml
<CustomField>
    <fullName>Construction_Stage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Construction Stage</label>
    <referenceTo>Construction_Stage__c</referenceTo>
    <relationshipLabel>Construction Stage History1</relationshipLabel>
    <relationshipName>Construction_Stage_History1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Construction_Stage_History__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower Name</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Construction Stage Historys</relationshipLabel>
    <relationshipName>Construction_Stage_Historys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <label>Tower Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/Payment_Milestone__c.object-meta.xml
<CustomObject>
    <label>Payment Milestone</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Milestone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Milestone__c/fields/Construction_Stage__c.field-meta.xml
<CustomField>
    <fullName>Construction_Stage__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Construction Stage</label>
    <referenceTo>Construction_Stage__c</referenceTo>
    <relationshipLabel>Payment Milestone</relationshipLabel>
    <relationshipName>Payment_Milestone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/fields/Saleable_Area__c.field-meta.xml
<CustomField>
    <fullName>Saleable_Area__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Saleable Area</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Configuration_Required</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Floor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Inventory_Type__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Type__c</fullName>
    <label>Inventory Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/RERA_Carpet_Area_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>RERA_Carpet_Area_Sq_Ft__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RERA Carpet Area (Sq. Ft.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Sale_Status__c.field-meta.xml
<CustomField>
    <fullName>Sale_Status__c</fullName>
    <label>Sale Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
                <isActive>false</isActive>
                <label>Available</label>
            </value>
            <value>
                <fullName>Booking In-Process</fullName>
                <isActive>false</isActive>
                <label>Booking In-Process</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Saleable_Area__c.field-meta.xml
<CustomField>
    <fullName>Saleable_Area__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Saleable Area</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Configuration_Required.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Villa</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Shop</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <masterLabel>Configuration Required</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestEx_ConstructionStageUpdate.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 1-12-2023
//-------------------------------------------//
@isTest
public class TestEx_ConstructionStageUpdate {
      @isTest
    public static void Test_Ex_ConstructionStageUpdate1(){
       
        Project__c pro = new Project__c();
        pro.Name = 'Test Project';
        insert pro;
       
        Tower__c twr = new Tower__c();
        twr.Name = 'TowerA';
        twr.Project__c = pro.Id;
        insert twr;
       
      
        Unit__c un = new Unit__c();
        un.Name = '1BHK501';
        //un.For_Sale__c = 'Yes';
        un.Sale_Status__c = 'Vacant';
        un.Configuration__c = '1 BHK';
        un.Inventory_Type__c = 'Residential';
        un.Floor__c = 5;
        un.Project__c = pro.Id;
        un.Tower__c = twr.Id;
        un.Saleable_Area__c = 1000;
        un.RERA_Carpet_Area_Sq_Ft__c = 800;
        insert un;
       
        Construction_Stage__c cs1 = new Construction_Stage__c();
        cs1.Name = 'Slab 1';
        cs1.Stage_Description__c = 'Slab 1';
        cs1.Tower__c = twr.id;
        cs1.Milestone_Status__c = 'Completed';
        cs1.Unit_Wise_Milestone__c = true;
        cs1.Actual_Completion_Date__c = system.today() - 10;
        cs1.Expected_Completion_Date__c = system.today();
        cs1.Sequence_Number__c = 1;
        insert cs1;
       
        Construction_Stage_History__c csh = new Construction_Stage_History__c();
        csh.Construction_Stage__c = cs1.id;
        csh.Tower_Name__c = twr.id;
        csh.Actual_Completion_Date__c = system.today() - 10;
        csh.Expected_Completion_Date__c = system.today();
        csh.Floor__c = '5';
        insert csh;
       
        Test.startTest();
        List<Construction_Stage__c> resultList = Ex_ConstructionStageUpdate.Cosnstructionupdate(cs1.id, cs1.Actual_Completion_Date__c, cs1.Expected_Completion_Date__c);
        List<Construction_Stage__c> resultList2 =Ex_ConstructionStageUpdate.getCosnstructionStage(cs1.id);
        Test.stopTest();
       
    }
   
    @isTest
    static void testGetcons() {
        Tower__c twr = new Tower__c(Name = 'Test Tower');
        insert twr;
       
        Construction_Stage__c cs1 = new Construction_Stage__c();
        cs1.Name = 'Slab 2';
        cs1.Stage_Description__c = 'Slab 1';
        cs1.Tower__c = twr.id;
        cs1.Milestone_Status__c = 'Completed';
        cs1.Unit_Wise_Milestone__c = true;
        cs1.Actual_Completion_Date__c = system.today();
        cs1.Expected_Completion_Date__c = system.today();
        cs1.Sequence_Number__c = 1;
        insert cs1;
       
        Construction_Stage__c cs2 = new Construction_Stage__c();
        cs2.Name = 'Slab 2';
        cs2.Stage_Description__c = 'Slab 2';
        cs2.Tower__c = twr.id;
        cs2.Milestone_Status__c = 'Completed';
        cs2.Unit_Wise_Milestone__c = true;
        cs2.Actual_Completion_Date__c = system.today();
        cs2.Expected_Completion_Date__c = system.today();
        cs2.Sequence_Number__c = 2;
        insert cs2;
       
        Test.startTest();
        List<Construction_Stage__c> result = Ex_ConstructionStageUpdate.getcons(twr.Id, Date.today(), Date.today().addDays(10));
        Test.stopTest();
    }
   
   
    @isTest
    static void testGetFloor() {
       
        Project__c pro = new Project__c();
        pro.Name = 'Test Project';
        insert pro;
       
        Tower__c tower = new Tower__c(Name = 'Test Tower');
        insert tower;
       
       
        Unit__c un = new Unit__c();
        un.Name = '1BHK501';
        un.Sale_Status__c = 'Vacant';
        un.Configuration__c = '1 BHK';
        un.Inventory_Type__c = 'Residential';
        un.Floor__c = 5;
        un.Project__c = pro.Id;
        un.Tower__c = tower.Id;
        un.Saleable_Area__c = 1000;
        un.RERA_Carpet_Area_Sq_Ft__c = 800;      
        insert un;
       
        Test.startTest();
        Map<Decimal, List<Unit__c>> floorUnitsMap = Ex_ConstructionStageUpdate.getFloor(tower.Id);
        Test.stopTest();
    }

   
    @isTest
    static void testSaveMethod() {
        Project__c pro = new Project__c();
        pro.Name = 'Test Project';
        insert pro;
       
        Tower__c twr = new Tower__c(Name = 'Test Tower', Project__c = pro.Id);
        insert twr;
       
        Construction_Stage__c cs1 = new Construction_Stage__c();
        cs1.Name = 'Slab 1';
        cs1.Stage_Description__c = 'Slab 1';
        cs1.Tower__c = twr.Id;
        cs1.Milestone_Status__c = 'Completed';
        cs1.Unit_Wise_Milestone__c = false;
        cs1.Actual_Completion_Date__c = system.today();
        cs1.Sequence_Number__c = 1;
        insert cs1;
       
        Construction_Stage__c cs2 = new Construction_Stage__c();
        cs2.Name = 'Slab 1';
        cs2.Stage_Description__c = 'Slab 1';
        cs2.Tower__c = twr.Id;
        cs2.Milestone_Status__c = 'Completed';
        cs2.Unit_Wise_Milestone__c = false;
        cs2.Expected_Completion_Date__c = system.today();
        cs2.Sequence_Number__c = 1;
        insert cs2;
       
        
        Unit__c un = new Unit__c();
        un.Name = '1BHK501';
        un.Sale_Status__c = 'Booked';
        un.Configuration__c = '1 BHK';
        un.Inventory_Type__c = 'Residential';
        un.Floor__c = 5;
        un.Project__c = pro.Id;
        un.Tower__c = twr.Id;
        un.Saleable_Area__c = 1000;
        un.RERA_Carpet_Area_Sq_Ft__c = 800;
        insert un;
       
        Opportunity__c opp = new Opportunity__c();
        opp.Name = 'acc1';
        insert opp;
       
        Quotation__c q = new Quotation__c();
        q.Opportunity__c = opp.id;
        q.Tower__c = twr.id;
        q.Project__c = pro.Id;
        q.Unit__c = un.id;
        insert q;
       
        Payment_Milestone__c pm = new Payment_Milestone__c();
        pm.Milestone_Name__c = '1ST Slab';
        pm.Quotation__c = q.id;
        pm.Milestone_Type__c = 'Construction Linked';
        pm.Construction_Stage__c = cs1.id;
        pm.Due_Date__c = system.today();
        pm.Is_Due__c = true;
        pm.Is_Raised__c = false;
        pm.Milestone_Complete_At_Booking__c = false;
        insert pm;
       
        Payment_Milestone__c pm1 = new Payment_Milestone__c();
        pm1.Milestone_Name__c = '1ST Slab';
        pm1.Quotation__c = q.id;
        pm1.Milestone_Type__c = 'Construction Linked';
        pm1.Construction_Stage__c = cs2.id;
        pm1.Due_Date__c = system.today();
        pm1.Is_Due__c = false;
        pm1.Is_Raised__c = false;
        pm1.Milestone_Complete_At_Booking__c = false;
        insert pm1;
       
        Booking__c b = new Booking__c();
        b.Booking_Date__c = system.today();
        b.Mode_Of_Funding__c = 'Self Funding';
        b.Tower__c = twr.id;
        b.Project__c = pro.Id;
        b.Quotation__c = q.id;
        b.Opportunity__c = opp.id;
        b.Unit__c = un.id;
        insert b;
       
        un.Booking__c=b.id;
        update un;

        Ex_ConstructionStageUpdate.saveMethod('Expected Completion Date', Date.today(), cs1.Id, null, 'Test', 'Test');
        Ex_ConstructionStageUpdate.saveMethod('Actual Completion Date', Date.today(), cs1.Id, new List<String>{'1', '2'} , 'Test', 'Test');
       
    }
}