force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Amount_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Demanded__c</fullName>
    <label>Total Amount Demanded</label>
    <summarizedField>Demand__c.Total_Amount_Demanded__c</summarizedField>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Paid__c</fullName>
    <label>Total Amount Paid</label>
    <summarizedField>Demand__c.Total_Amount_Paid__c</summarizedField>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/fields/Total_Amount_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Demanded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Rate_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Interest__c</fullName>
    <label>Rate of Interest</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/TestEx_InterestCalculateManagement.cls
@isTest
public class TestEx_InterestCalculateManagement {
    @isTest
    public static void testInterestCalculate() {
        List<Booking__c> bookingList = new List<Booking__c>();
        List<Demand__c> demandList = new List<Demand__c>();
        Map<Id, Date> boookingInterestDateMap = new Map<Id, Date>();
        Set<Id> bookingIdSet = new Set<Id>();
        
        Project__c p= new Project__c();
        p.Rate_of_Interest__c = 12 ;
        insert p ;
        
        Booking__c b = new Booking__c();
        b.Project__c = p.Id ;
        bookingList.add(b);
        insert bookingList;
        
        Demand__c d = new Demand__c();
        d.Booking__c = b.Id ;
        d.Due_Date__c = system.today().addDays(-2);
        d.Total_Amount_Demanded__c = 200 ;
        d.Total_Amount_Demanded__c = 200 ;
        d.Total_Amount_Paid__c = 100;
        demandList.add(d);
        insert demandList;
        
        bookingIdSet.add(b.Id);
        boookingInterestDateMap.put(b.Id , system.today());
        Test.startTest();
        Ex_InterestCalculateManagementServices.interestCalculate(boookingInterestDateMap);
        Map<String, List<Demand__c>> result = Ex_InterestCalculateManagementServices.getPendingDemandMap(bookingIdSet);
        String jobId = System.schedule('Test Job', '0 0 0 1 1 ?', new Ex_InterestCalculationBatch());
        Ex_InterestCalculationBatch batchInstance = new Ex_InterestCalculationBatch();
        batchInstance.execute(null, demandList);
        Test.stopTest();
        
        
    }
    
}