force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Park__c/Car_Park__c.object-meta.xml
<CustomObject>
    <label>Car Park</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Park Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Park</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Park__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Car Park</relationshipLabel>
    <relationshipName>Car_Park</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Park__c/fields/Car_Park_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Park_Type__c</fullName>
    <label>Car Park Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Car_Park_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car_Park__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>UG 1</fullName>
            </value>
            <value>
                <fullName>UG 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car_Park__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Car Park</relationshipLabel>
    <relationshipName>Car_Park</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Park__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <isActive>false</isActive>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>null</fullName>
                <isActive>false</isActive>
                <label>null</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car_Park__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Car Parks</relationshipLabel>
    <relationshipName>Car_Parks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Park__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Podium Parking</fullName>
            </value>
            <value>
                <fullName>Open Parking</fullName>
            </value>
            <value>
                <fullName>Stack Upper Parking</fullName>
            </value>
            <value>
                <fullName>Stack Lower Parking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car_Park_Required__c/Car_Park_Required__c.object-meta.xml
<CustomObject>
    <label>Car Park Required</label>
    <nameField>
        <displayFormat>CPR-{0000}</displayFormat>
        <label>Car Park Required Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Park Required</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Park_Required__c/fields/Car_Park_Count__c.field-meta.xml
<CustomField>
    <fullName>Car_Park_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Car Park Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Car_Park_Required__c/fields/Car_Park_Type__c.field-meta.xml
<CustomField>
    <fullName>Car_Park_Type__c</fullName>
    <label>Car Park Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Podium Parking</fullName>
            </value>
            <value>
                <fullName>Open Parking</fullName>
            </value>
            <value>
                <fullName>Stack Upper Parking</fullName>
            </value>
            <value>
                <fullName>Stack Lower Parking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car_Park_Required__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Car Park Required</relationshipLabel>
    <relationshipName>Car_Park_Required</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Car_Park_Maintain_At__c.field-meta.xml
<CustomField>
    <fullName>Car_Park_Maintain_At__c</fullName>
    <label>Car Park Maintain At</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Car_Park_Maintain_At</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Car_Park_Maintain_At.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Project</fullName>
        <default>true</default>
        <label>Project</label>
    </customValue>
    <customValue>
        <fullName>Tower</fullName>
    </customValue>
    <masterLabel>Car Park Maintain At</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Car_Park_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Podium Parking</fullName>
    </customValue>
    <customValue>
        <fullName>Open Parking</fullName>
    </customValue>
    <customValue>
        <fullName>Stack Upper Parking</fullName>
    </customValue>
    <customValue>
        <fullName>Stack Lower Parking</fullName>
    </customValue>
    <customValue>
        <fullName>Stack Parking</fullName>
    </customValue>
    <masterLabel>Car Park Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_CarParkingAllotment.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 09-12-2023
//-------------------------------------------//
public class Ex_CarParkingAllotment {
    @AuraEnabled(cacheable=true)
    public static Booking__c getBooking(Id bookingId){
        Booking__c booking = [SELECT Tower__c, Quotation__c, Project__r.Car_Park_Maintain_At__c, Project__c FROM Booking__c WHERE Id = :bookingId];
        System.debug('bookingRecord: '+booking);
        if (booking != null) {
            return booking;
        } else {
            return null;
        }
    }
    
    @AuraEnabled(cacheable=false)
    public static List<Car_Park__c> getCarPark(Booking__c booking, String gettype){
        System.debug('booking: '+booking);
        System.debug('gettype: '+gettype);
        List<Car_Park__c> carParkList = new List<Car_Park__c>();
        if(booking != null){
            if(gettype == ''){
                System.debug('Car_Park_Maintain_At__c Before: '+booking.Project__r.Car_Park_Maintain_At__c);
                if(booking.Project__r.Car_Park_Maintain_At__c == 'Project'){
                    System.debug('Car_Park_Maintain_At__c After: '+booking.Project__r.Car_Park_Maintain_At__c);
                    carParkList = [SELECT Id, Name, Status__c, Floor__c, Type__c, Project__c
                                   FROM Car_Park__c 
                                   WHERE Project__c = :booking.Project__c Order by Floor__c  DESC];
                    System.debug('carParkList: '+carParkList);
                }else if(booking.Project__r.Car_Park_Maintain_At__c == 'Tower'){
                    carParkList = [SELECT Id, Name, Status__c, Floor__c, Type__c, Project__c
                                   FROM Car_Park__c 
                                   WHERE Tower__c = :booking.Tower__c Order by Floor__c  DESC];
                }
                if(!carParkList.isEmpty() && carParkList != null){
                    return carParkList;
                }else{
                    return null;
                }
                
            }else{
                if(booking.Project__r.Car_Park_Maintain_At__c == 'Project'){
                    carParkList = [SELECT Id, Name, Status__c, Floor__c, Type__c, Project__c 
                                   FROM Car_Park__c 
                                   WHERE Project__c = :booking.Project__c AND Type__c =: gettype Order by Floor__c  DESC];
                }else if(booking.Project__r.Car_Park_Maintain_At__c == 'Tower'){
                    carParkList = [SELECT Id, Name, Status__c, Floor__c, Type__c 
                                   FROM Car_Park__c 
                                   WHERE Tower__c = :booking.Tower__c AND Type__c =: gettype Order by Floor__c  DESC];
                    
                }
                System.debug('carParkList: '+carParkList);
                if(!carParkList.isEmpty() && carParkList != null){
                    return carParkList;
                }else{
                    return null;
                }
                
            }
        }else{
            return null;
        }
       
    }
    
   
    
    
   
    public static Map<String,List<Car_Park__c>> getBookingRelatedCarPark(Booking__c booking){
        System.debug('booking: '+booking);
        Map<String,List<Car_Park__c>> carParkTypeMap = new  Map<String,List<Car_Park__c>>();
        List<Car_Park__c> carParkList = new List<Car_Park__c>();
        if(booking != null){
            carParkList = [Select Id, Type__c from Car_Park__c Where Booking__c =: booking.Id AND Status__c = 'Booked'];
            System.debug('carParkList: '+carParkList.size());
            System.debug('carParkList: '+carParkList);
            if(!carParkList.isEmpty() && carParkList != null){
                for (Car_Park__c carPark : carParkList) {
                    if (carParkTypeMap.containsKey(carPark.Type__c)) {
                        carParkTypeMap.get(carPark.Type__c).add(carPark);
                    }else{
                        System.debug('carParkList: '+carParkList.size());
                        List<Car_Park__c> cpList = new  List<Car_Park__c>();
                        cpList.add(carPark);
                        System.debug('cpList :'+cpList);
                        carParkTypeMap.put(carPark.Type__c, cpList);
                    }
                    System.debug('carParkTypeMap: '+carParkTypeMap); 
                }
            }
            return carParkTypeMap;
        }else{
            return null;
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<wrapperCarParkRequired> getCarParkRequiredWrapper(Booking__c booking){
        List<wrapperCarParkRequired> wrapperCarParkRequiredList = new List<wrapperCarParkRequired>();
        Map<String,List<Car_Park__c>> carparkBookedMap = getBookingRelatedCarPark(booking);
        System.debug('carparkBookedMap: '+carparkBookedMap);
        List<Car_Park_Required__c> carParkRequiredList = [SELECT Id, Name, Car_Park_Count__c, Car_Park_Type__c
                                                          FROM Car_Park_Required__c
                                                          WHERE Quotation__c =: booking.Quotation__c];
       // System.debug('carParkRequiredList: '+carParkRequiredList);
        if(!carParkRequiredList.isEmpty() && carParkRequiredList != null){
            for(Car_Park_Required__c cpr : carParkRequiredList){
                if(!carparkBookedMap.isEmpty() && carparkBookedMap != null){
                    if (carparkBookedMap.containsKey(cpr.Car_Park_Type__c)) {
                        wrapperCarParkRequiredList.add(new wrapperCarParkRequired(cpr.Car_Park_Type__c, cpr.Car_Park_Count__c, carparkBookedMap.get(cpr.Car_Park_Type__c).size() , cpr.Car_Park_Count__c - carparkBookedMap.get(cpr.Car_Park_Type__c).size()));
                    }else{
                        wrapperCarParkRequiredList.add(new wrapperCarParkRequired(cpr.Car_Park_Type__c, cpr.Car_Park_Count__c, 0 , cpr.Car_Park_Count__c ));
                    }
                }else{
                    wrapperCarParkRequiredList.add(new wrapperCarParkRequired(cpr.Car_Park_Type__c, cpr.Car_Park_Count__c, 0 , cpr.Car_Park_Count__c ));
                }
            }
        }
        if(!wrapperCarParkRequiredList.isEmpty() && wrapperCarParkRequiredList != null){
            return wrapperCarParkRequiredList;
        }else{
            return null;
        }
    }
    @AuraEnabled
    public Static Boolean updateCarParkwithBooking(List<Car_Park__c> finalCarParkList, String bookingId){
        if(!finalCarParkList.isEmpty() && finalCarParkList != null){
            for (Car_Park__c carPark : finalCarParkList) {
                carPark.Booking__c = bookingId;
                carPark.Status__c = 'Booked';
            }
        }
        if(!finalCarParkList.isEmpty() && finalCarParkList != null){
            try {
                update finalCarParkList;
                return true;
            }catch(Exception ex){
                System.debug('An Error Occured Please Contact System Administrator:  '+ex.getMessage());
                return false;
            }
        }else{
            return false;
        }
    }
    
     public class wrapperCarParkRequired{
        @AuraEnabled
        public String carparktype {get;set;}
        @AuraEnabled
        public Decimal totalRequiredCount {get;set;}
        @AuraEnabled
        public Decimal allotedCount {get;set;}
        @AuraEnabled
        public Decimal unallotedCount {get;set;}
        
        public wrapperCarParkRequired(String carparktype,Decimal totalRequiredCount, Decimal allotedCount,Decimal unallotedCount ){
             this.carparktype = carparktype;
             this.totalRequiredCount = totalRequiredCount;
             this.allotedCount = allotedCount;
             this.unallotedCount = unallotedCount;
        }
     }
}