force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Total_Interest_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount_Paid__c</fullName>
    <label>Total Interest Amount Paid</label>
    <summarizedField>Demand__c.Total_Interest_Amount_Paid__c</summarizedField>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/fields/Total_Interest_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Interest Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ledger__c/Ledger__c.object-meta.xml
<CustomObject>
    <label>Ledger</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ledger__c/fields/Charge_Name__c.field-meta.xml
<CustomField>
    <fullName>Charge_Name__c</fullName>
    <label>Charge Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demand Cost</fullName>
            </value>
            <value>
                <fullName>Demand Tax</fullName>
            </value>
            <value>
                <fullName>Demand Interest</fullName>
            </value>
            <value>
                <fullName>Flat Cost</fullName>
            </value>
            <value>
                <fullName>Tax</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>TDS Challan</fullName>
            </value>
            <value>
                <fullName>Interest GST</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipt</relationshipLabel>
    <relationshipName>Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestEx_LedgerHandlerServices.cls
@isTest
public class TestEx_LedgerHandlerServices {
    @isTest
    public static void testReverseCalculationOnDemandAndReceipt() {
        Booking__c bk = new Booking__c();
        insert bk ;
        
        List<Demand__c> demandRecords = new List<Demand__c>();
        Demand__c demandRecord = new Demand__c();
        demandRecord.Booking__c = bk.Id ;
        demandRecord.Total_Interest_Amount_Paid__c= 200 ;
        demandRecords.add(demandRecord); 
        
        insert demandRecords; 
        
        List<Ledger__c> ledgerRecords = new List<Ledger__c>();
        Ledger__c  le = new Ledger__c();
        le.Type__c = 'Credit';
        le.Demand__c = demandRecords[0].Id ;
        le.Charge_Name__c = 'Interest';
        le.Amount__c = 100 ;
        le.Cancelled__c = false;
        ledgerRecords.add(le);
        
        insert ledgerRecords;
        
        delete ledgerRecords ;
        
        List<Receipt__c> receiptRecords = new List<Receipt__c>();
        insert receiptRecords;
    }
}