force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Agreement_Value_Tax__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value_Tax__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Applicant_Address__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Address__c</fullName>
    <label>Applicant Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh Grameena Vikas Bank</fullName>
            </value>
            <value>
                <fullName>Andhra Pragathi Grameena Bank</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh Rural Bank</fullName>
            </value>
            <value>
                <fullName>Aryavart Bank</fullName>
            </value>
            <value>
                <fullName>Assam Gramin Vikash Bank</fullName>
            </value>
            <value>
                <fullName>Au Small Finance Bank Limited</fullName>
            </value>
            <value>
                <fullName>Axis Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Bajaj Housing Finance</fullName>
            </value>
            <value>
                <fullName>Bandhan Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Bangiya Gramin Vikas Bank</fullName>
            </value>
            <value>
                <fullName>Bank of Baroda</fullName>
            </value>
            <value>
                <fullName>Bank of India</fullName>
            </value>
            <value>
                <fullName>Bank of Maharashtra</fullName>
            </value>
            <value>
                <fullName>Baroda Gujarat Gramin Bank</fullName>
            </value>
            <value>
                <fullName>Baroda Rajasthan Kshetriya Gramin Bank</fullName>
            </value>
            <value>
                <fullName>Baroda UP Bank*</fullName>
            </value>
            <value>
                <fullName>Canara Bank</fullName>
            </value>
            <value>
                <fullName>Capital Small Finance Bank Limited</fullName>
            </value>
            <value>
                <fullName>Central Bank of India</fullName>
            </value>
            <value>
                <fullName>Chaitanya Godavari Grameena Bank</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh Rajya Gramin Bank</fullName>
            </value>
            <value>
                <fullName>City Union Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>CSB Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Dakshin Bihar Gramin Bank</fullName>
            </value>
            <value>
                <fullName>DCB Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Dhanlaxmi Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>DNS Bank</fullName>
            </value>
            <value>
                <fullName>Ellaquai Dehati Bank</fullName>
            </value>
            <value>
                <fullName>Equitas Small Finance Bank Limited</fullName>
            </value>
            <value>
                <fullName>ESAF Small Finance Bank Limited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipt</relationshipLabel>
    <relationshipName>Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>DD</fullName>
            </value>
            <value>
                <fullName>Payment Gateway</fullName>
            </value>
            <value>
                <fullName>Debit Card</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>RTGSNEFT</fullName>
            </value>
            <value>
                <fullName>UPI</fullName>
            </value>
            <value>
                <fullName>IMPS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Number__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Number__c</fullName>
    <formula>(Booking__r.Project__r.Name) &amp; &apos;/&apos; &amp; Left(Booking__r.Tower__r.Name ,2) &amp; &apos;-&apos; &amp; Booking__r.Name &amp; &apos;/&apos; &amp; TEXT(Receipt_Date__c) &amp; &apos;/&apos; &amp; Name</formula>
    <label>Receipt Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Type__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Type__c</fullName>
    <label>Receipt Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Flat Cost</fullName>
            </value>
            <value>
                <fullName>Tax</fullName>
            </value>
            <value>
                <fullName>Stamp Duty</fullName>
            </value>
            <value>
                <fullName>Registration Charges</fullName>
            </value>
            <value>
                <fullName>Other Charges</fullName>
            </value>
            <value>
                <fullName>Interest Flat Cost</fullName>
            </value>
            <value>
                <fullName>Interest GST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/fields/RERA_No__c.field-meta.xml
<CustomField>
    <fullName>RERA_No__c</fullName>
    <label>RERA No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Floor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Ex_PrintReceiptController.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 21-11-2023
//-------------------------------------------//
public class Ex_PrintReceiptController {
    
    public Id rId {get;set;}
    public List<Receipt__c> rList {get;set;}
    public String amountInWords {get;set;}
    public decimal TotalAmount{get;set;}
    Public String Total {get;set;}
    public String showTotalAmount {get;set;}
    
    public Ex_PrintReceiptController(){
        rId=ApexPages.currentPage().getParameters().get('rId');
        rList = new List<Receipt__c>();
        
        if(rId != null) {
            rList = [Select Id, Name, Receipt_Number__c, Date__c,Payment_Mode__c,Amount__c,Receipt_Date__c,
                     Booking__r.Unit__c,Receipt_Type__c, Booking__r.Unit__r.Name, Booking__r.Unit__r.Floor__c, Booking__r.Unit__r.Tower__r.Name,
                     Booking__r.Unit__r.Project__r.Name, Booking__r.Unit__r.Tower__r.RERA_No__c,Booking__r.Applicant_Address__c,
                     Booking__r.Primary_Applicant_Name__c, Booking__r.Primary_Applicant_Mobile__c, Booking__r.Primary_Applicant_Email__c ,
                     Booking__r.Agreement_Value__c,Booking__r.Agreement_Value_Tax__c,Booking__r.Project__r.Name,Booking__r.Tower__r.Name,
                     Booking__r.Remarks__c,Transaction_ID__c,Bank_Name__c	
                     from Receipt__c where Id =: rId];
            system.debug('rList: '+rList);
            if(!rList.isEmpty() && rList != null){
                if(rList[0].Amount__c != 0) {
                    TotalAmount = Integer.valueOf((rList[0].Amount__c));
                    showTotalAmount = Ex_InventoryPriceManagementServices.currencyFormat(TotalAmount);
                    amountInWords=Ex_NumberToWord.convertNumbertoWords(Integer.valueOf(TotalAmount));
                    //Total = Ex_PrintReceiptController.currencyFormat(rlist[0].Booking__r.Agreement_Value__c + rList[0].Booking__r.Agreement_Value_Tax__c);
                }
            }
        }
    }

}