force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipt</relationshipLabel>
    <relationshipName>Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Transaction Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Payment Successful</fullName>
            </value>
            <value>
                <fullName>Payment Failed - Insufficient Funds</fullName>
            </value>
            <value>
                <fullName>Payment Failed – Signature mismatch</fullName>
            </value>
            <value>
                <fullName>Payment Failed – PDC</fullName>
            </value>
            <value>
                <fullName>Payment Failed – Stop payment by client</fullName>
            </value>
            <value>
                <fullName>Payment Failed – Overwriting</fullName>
            </value>
            <value>
                <fullName>Payment Failed – Amount Mismatch</fullName>
            </value>
            <value>
                <fullName>Payment in Process</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Status__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Status__c</fullName>
    <label>Receipt Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UnProcessed</fullName>
                <default>true</default>
                <label>UnProcessed</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Processed-Finance Submission Pending</fullName>
            </value>
            <value>
                <fullName>Processed-Sent for Banking</fullName>
            </value>
            <value>
                <fullName>Dishonored</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Physical Verification Rejected</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Reverse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Total_Money_Apportioned__c.field-meta.xml
<CustomField>
    <fullName>Total_Money_Apportioned__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Money Apportioned</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestEx_ReceiptTriggerHandler.cls
@isTest
public class TestEx_ReceiptTriggerHandler {

    @isTest
    public static void testReceiptTrigger(){
        Booking__c bk = new Booking__c();
        insert bk ;
        
        Receipt__c rc = new Receipt__c();
        rc.Booking__c = bk.Id ;
        rc.Date__c = system.today().addDays(-2);
        rc.Payment_Status__c = 'Payment Successful';
        rc.Total_Money_Apportioned__c = 100;
        rc.Amount__c = 100;
        insert rc ;
        rc.Receipt_Status__c = 'Reverse';
        update rc;
        
        Receipt__c rc1 = new Receipt__c();
        rc1.Booking__c = bk.Id ;
        rc1.Date__c = system.today().addDays(-2);
        rc1.Payment_Status__c = 'Other';
        rc1.Total_Money_Apportioned__c = 100;
        rc1.Amount__c = 100;
        insert rc1;
        rc.Payment_Status__c = 'Payment Successful';
        update rc;
        
        Demand__c d = new Demand__c();
        d.Booking__c = rc.Booking__c;
        insert d;
    }
}