force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Amount_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Demanded__c</fullName>
    <label>Total Amount Demanded</label>
    <summarizedField>Demand__c.Total_Amount_Demanded__c</summarizedField>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/fields/Total_Amount_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Demanded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>In Follow-up</fullName>
                <default>true</default>
                <label>In Follow-up</label>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Booking In-Process</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/SV_Count__c.field-meta.xml
<CustomField>
    <fullName>SV_Count__c</fullName>
    <label>SV Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/Payment_Milestone__c.object-meta.xml
<CustomObject>
    <label>Payment Milestone</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Milestone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Milestone__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <formula>Quotation__r.Booking__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Booking</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Charge_Bucket_1__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_1__c</fullName>
    <label>Charge Bucket 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agreement Value</fullName>
            </value>
            <value>
                <fullName>Other Charges</fullName>
            </value>
            <value>
                <fullName>Statutory Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Charge_Bucket_1_Total_Tax__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_1_Total_Tax__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Bucket 1 Total Tax</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Milestone_Type__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Type__c</fullName>
    <label>Milestone Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Date Linked</fullName>
            </value>
            <value>
                <fullName>Construction Linked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Payment Milestone</relationshipLabel>
    <relationshipName>Payment_Milestone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sequence No</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Last_Demand_No__c.field-meta.xml
<CustomField>
    <fullName>Last_Demand_No__c</fullName>
    <label>Last Demand No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Rate_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>Rate_of_Interest__c</fullName>
    <label>Rate of Interest</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GRE QR User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Charge_Bucket_1_Total_Tax__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_1_Total_Tax__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Bucket 1 Total Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_Ex_InterestCalculateMgmtService.cls
@isTest
public class Test_Ex_InterestCalculateMgmtService {
    
    @isTest
    public static void testInterestCalculate() {
          Map<String,Id> recordIdMap =Ex_MasterDataController.createMaster();
         Profile userProfile = [SELECT Id FROM Profile WHERE Name = 'Standard User' LIMIT 1];

        // Step 2: Create a test user
        User testUser = new User(
            LastName = 'Test User',
            Alias = 'tuser',
            Email = 'testuser@example.com',
            Username = 'testuser' + DateTime.now().getTime() + '@example.com',
            ProfileId = userProfile.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
        );
        insert testUser;
        
        List<Booking__c> bookingList = new List<Booking__c>();
        List<Demand__c> demandList = new List<Demand__c>();
        Map<Id, Date> boookingInterestDateMap = new Map<Id, Date>();
        Set<Id> bookingIdSet = new Set<Id>();
        
        
        Project__c p= new Project__c();
        p.Name='prj';
        p.User__c=testUser.id;
        p.Rate_of_Interest__c = 12 ;
        p.Last_Demand_No__c='55';
        insert p ;
        
        Opportunity__c op = new Opportunity__c();
        op.Name = 'Test';
        op.Stage__c = 'Booking In-Process';
        op.Close_Date__c = system.today().addDays(30);
        op.SV_Count__c =1 ;
        //op.c = 1 ;
        insert op ;

        Quotation__c q = new Quotation__c();
        q.Opportunity__c = op.id;
        q.Tower__c = recordIdMap.get('TOWER');
        q.Project__c =recordIdMap.get('PROJECT');
        q.Unit__c = recordIdMap.get('UNIT');
        insert q;       
        
        Booking__c b = new Booking__c();
        b.Project__c = p.Id ;
        bookingList.add(b);
        insert bookingList;
        
         Payment_Milestone__c paymentMilestone = new Payment_Milestone__c(
     
            Quotation__c = q.Id,
            Due_Date__c = System.today(),
            Charge_Bucket_1__c = 'Agreement Value',
            Charge_Bucket_1_Amount__c = 100000,
            Charge_Bucket_1_Total_Tax__c = 5000,
            Milestone_Type__c = 'Date Linked',
            Sequence_No__c = 1,
            Demand_Raised_Date__c = System.today()
        );
        insert paymentMilestone;
        
         Demand__c d = new Demand__c();
        d.Booking__c = b.Id ;
        d.Quotation__c=q.id;
        d.Payment_Milestone__c=paymentMilestone.id;
        d.Due_Date__c = system.today().addDays(-2);
        d.Total_Amount_Demanded__c = 200 ;
        d.Total_Amount_Demanded__c = 200 ;
        d.Total_Amount_Paid__c = 100;
        d.Invoice_Number__c='666774';
 
        demandList.add(d);
        insert demandList;
        
        bookingIdSet.add(b.Id);
        boookingInterestDateMap.put(b.Id , system.today());
        Test.startTest();
        Ex_InterestCalculateManagementServices.interestCalculate(boookingInterestDateMap);
        Map<String, List<Demand__c>> result = Ex_InterestCalculateManagementServices.getPendingDemandMap(bookingIdSet);
        String jobId = System.schedule('Test Ex_InterestCalculationBatch', '0 0 0 * * ?', new Ex_InterestCalculationBatch());
        Ex_InterestCalculationBatch batchInstance = new Ex_InterestCalculationBatch();
        batchInstance.execute(null, demandList);
        Test.stopTest();
        
        
    }

}