force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/fields/Interest_Calculated_Till__c.field-meta.xml
<CustomField>
    <fullName>Interest_Calculated_Till__c</fullName>
    <label>Interest Calculated Till</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Amount_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Remaining__c</fullName>
    <formula>Total_Amount_Demanded__c -  Total_Amount_Paid__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Ex_InterestCalculationBatch.cls
global class Ex_InterestCalculationBatch implements Database.Batchable <sObject>, Schedulable {
    public String query;
    public Date cDate = system.today();
    
    public Ex_InterestCalculationBatch() {
        query = 'Select Id, Name, Booking__c from Demand__c'
                +' where (Demand_Status__c = \'Raised\') AND (Total_Amount_Remaining__c > 0 OR Total_Tax_Remaining__c > 0) AND ((Interest_Calculated_Till__c = null AND Due_Date__c <: cDate) OR (Interest_Calculated_Till__c != null AND Interest_Calculated_Till__c <: cDate))';
        system.debug('Query is :::: '+Query);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext info, List<Demand__c> demandList) {
        system.debug('demandList: '+demandList.size());
        Map<Id, Date> boookingInterestDateMap = new Map<Id, Date>();
        
        if(!demandList.isEmpty() && demandList != null) {
            for(Demand__c d: demandList) {
                if(d.Booking__c != null) {
                    boookingInterestDateMap.put(d.Booking__c, cDate);
                }
            }
        }
        if(!boookingInterestDateMap.isEmpty() && boookingInterestDateMap != null)
            Ex_InterestCalculateManagementServices.interestCalculate(boookingInterestDateMap);
    }
    
    global void finish(Database.BatchableContext info) {     
    }   
    
    global void execute(SchedulableContext sc) {
        Ex_InterestCalculationBatch b = new Ex_InterestCalculationBatch(); 
        database.executebatch(b, 50);
    }
}