force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Assign_to_MIS__c.field-meta.xml
<CustomField>
    <fullName>Assign_to_MIS__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assign to MIS</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Assign_to_RM__c.field-meta.xml
<CustomField>
    <fullName>Assign_to_RM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assign to RM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Booking_Stage__c.field-meta.xml
<CustomField>
    <fullName>Booking_Stage__c</fullName>
    <label>Booking Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Booking_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Welcome_Call_Done_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Call_Done_DateTime__c</fullName>
    <label>Welcome Call Done DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking_Checklist__c/Booking_Checklist__c.object-meta.xml
<CustomObject>
    <label>Booking Checklist</label>
    <nameField>
        <displayFormat>BWC-{000000}</displayFormat>
        <label>Booking Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking_Checklist__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <label>Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking_Checklist__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Booking Checklists</relationshipLabel>
    <relationshipName>Booking_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking_Checklist__c/fields/Checklist_Status__c.field-meta.xml
<CustomField>
    <fullName>Checklist_Status__c</fullName>
    <label>Checklist Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved by MIS</fullName>
            </value>
            <value>
                <fullName>Rejected by MIS</fullName>
            </value>
            <value>
                <fullName>Approved by RM</fullName>
            </value>
            <value>
                <fullName>Rejected by RM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Closing_Manager__c.field-meta.xml
<CustomField>
    <fullName>Closing_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Closing Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Opportunities (Closing Manager)</relationshipLabel>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/MIS_User__c.field-meta.xml
<CustomField>
    <fullName>MIS_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MIS User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tower3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/fields/RM_User__c.field-meta.xml
<CustomField>
    <fullName>RM_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RM User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tower4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Booking_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Booking In-Process</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation in-process</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Welcome Call Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Possession Done</fullName>
    </customValue>
    <customValue>
        <fullName>Welcome Call Done</fullName>
        <isActive>false</isActive>
        <label>Welcome Call Done</label>
    </customValue>
    <masterLabel>Booking Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_BookingChecklistHandlerServices.cls
public class Ex_BookingChecklistHandlerServices {
      public static void handleAfterInsertOrUpdate(List<Booking_Checklist__c> checklistItems) {
        
        system.debug('checklistItems is::'+checklistItems);
        List<Booking__c> bookingsToUpdate = new List<Booking__c>();
        List<Booking_Checklist__c> bookingChecklistToUpdate = new List<Booking_Checklist__c>();
        Boolean allAccepted;
        
        List<Booking_Checklist__c> checklistRecords = [SELECT Id, Action__c, Booking__c,Checklist_Status__c 
                                                       FROM Booking_Checklist__c
                                                       WHERE Booking__c =:checklistItems[0].Booking__c];
        system.debug('checklistRecords is::'+checklistRecords);
        
        Booking__c booking = [SELECT Id, Welcome_Call_Done__c, Opportunity__r.OwnerId, Tower__r.RM_User__c,  Sales_Manager__c, Welcome_Call_Done_DateTime__c
                              FROM Booking__c 
                              WHERE Id = :checklistRecords[0].Booking__c LIMIT 1];
        system.debug('booking is::'+booking);
          
        for (Booking_Checklist__c record : checklistRecords) {
            system.debug('record is::'+record);
            if (record.Action__c == 'Reject') {
                allAccepted = False;
                break;
            }else{
                 allAccepted = True;
            }
        }
          
          
        
        system.debug('allAccepted is::'+allAccepted);
        if (allAccepted == True) {
            booking.Welcome_Call_Done__c = True;
            booking.Welcome_Call_Done_DateTime__c = Datetime.now(); 
            booking.Assign_to_RM__c = true;
            booking.OwnerId = booking.Tower__r.RM_User__c;
            //booking.Booking_Stage__c = 'Booking Confirmed';
            
        } else if (allAccepted == False) {
            booking.OwnerId = booking.Sales_Manager__c;
            booking.Assign_to_MIS__c = false;
           // booking.OwnerId = booking.Closing_Manager__c;
        }
        
        bookingsToUpdate.add(booking);
        system.debug('bookingsToUpdate is::'+bookingsToUpdate);
        
        if (!bookingsToUpdate.isEmpty()) {
            update bookingsToUpdate;
        }
          
          if( bookingChecklistToUpdate != null &&  !bookingChecklistToUpdate.isEmpty()){
              update  bookingChecklistToUpdate;
          }  
    }
    
    public static void updateBookingOwner(Set<Id> bookingIdSet){
        System.debug('Inside UpdteBooking::');
       List<Booking_Checklist__c> checklistRecords = [SELECT Id, Action__c, Booking__c,Checklist_Status__c 
                                                       FROM Booking_Checklist__c
                                                       WHERE Booking__c IN:bookingIdSet];
        
      Set<Id> bookingIds = new Set<Id>();  
     List<Booking__c> bkListToUpdate = new List<Booking__c>();  
        boolean allAcceptedByRM = null;
        if(checklistRecords != null && !checklistRecords.isEmpty()){
            for(Booking_Checklist__c bkChecklist : checklistRecords){
                if(bkChecklist.Checklist_Status__c.equalsIgnoreCase('Rejected by RM')){
                    allAcceptedByRM = false;
                    bookingIds.add(bkChecklist.Booking__c);
                    break;
                }else{
                    allAcceptedByRM = true;
                }
                
            }
            
            if(bookingIds != null && !bookingIds.isEmpty()){
                List<Booking__c> bkList = [Select Id, ownerId, Tower__r.MIS_User__c from Booking__c Where Id IN : bookingIds];
                
                if(bkList != null && !bkList.isEmpty()){
                    for(Booking__c bk : bkList){
                        bk.OwnerId = bk.Tower__r.MIS_User__c;
                        bkListToUpdate.add(bk);
                    }
                }
            }
        }
        
        if(bkListToUpdate != null && !bkListToUpdate.isEmpty()){
            update bkListToUpdate;
        }
        
    }

}