force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/CRM_Head__c.field-meta.xml
<CustomField>
    <fullName>CRM_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRM Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Generate_Welcome_Call_Checklist_Master__c.field-meta.xml
<CustomField>
    <fullName>Generate_Welcome_Call_Checklist_Master__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate Welcome Call Checklist Master</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/CRM_Head__c.field-meta.xml
<CustomField>
    <fullName>CRM_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRM Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipt</relationshipLabel>
    <relationshipName>Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/CRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>CRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRM Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/fields/Saleable_Area__c.field-meta.xml
<CustomField>
    <fullName>Saleable_Area__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Saleable Area</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Configuration_Required</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Floor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Inventory_Type__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Type__c</fullName>
    <label>Inventory Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/RERA_Carpet_Area_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>RERA_Carpet_Area_Sq_Ft__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RERA Carpet Area (Sq. Ft.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Sale_Status__c.field-meta.xml
<CustomField>
    <fullName>Sale_Status__c</fullName>
    <label>Sale Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Reserved</fullName>
            </value>
            <value>
                <fullName>Vacant</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
                <isActive>false</isActive>
                <label>Available</label>
            </value>
            <value>
                <fullName>Booking In-Process</fullName>
                <isActive>false</isActive>
                <label>Booking In-Process</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Saleable_Area__c.field-meta.xml
<CustomField>
    <fullName>Saleable_Area__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Saleable Area</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Checklist__c/Welcome_Call_Checklist__c.object-meta.xml
<CustomObject>
    <label>Welcome Call Checklist</label>
    <nameField>
        <displayFormat>WC-{00000}</displayFormat>
        <label>Welcome Call Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Welcome Call Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Welcome_Call_Checklist__c/fields/Accepted__c.field-meta.xml
<CustomField>
    <fullName>Accepted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accepted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Checklist__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Welcome Call Checklists</relationshipLabel>
    <relationshipName>Welcome_Call_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Checklist__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Details</fullName>
            </value>
            <value>
                <fullName>Client Signatures</fullName>
            </value>
            <value>
                <fullName>Strike Out</fullName>
            </value>
            <value>
                <fullName>Overwriting</fullName>
            </value>
            <value>
                <fullName>Future Correspondence</fullName>
            </value>
            <value>
                <fullName>Booking Details</fullName>
            </value>
            <value>
                <fullName>Receipt Details</fullName>
            </value>
            <value>
                <fullName>Source of Booking Details</fullName>
            </value>
            <value>
                <fullName>Deal Approval Details : Quotation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Welcome_Call_Checklist__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Welcome_Call_Checklist_Master__c/Welcome_Call_Checklist_Master__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Welcome Call Checklist Master</label>
</CustomObject>

force-app/main/default/globalValueSets/Configuration_Required.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Villa</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Shop</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <masterLabel>Configuration Required</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestEx_WelcomeCall.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 1-12-2023
//-------------------------------------------//
@isTest
public class TestEx_WelcomeCall {
    
     @isTest
    public static void testWelcomeCall() {
         Test.startTest();
        Booking__c b = new Booking__c();
        b.Agreement_Value__c = 100;
        b.Generate_Welcome_Call_Checklist_Master__c = False;
        insert b;
        
        Tower__c t = new Tower__c ();
        t.CRM_Manager__c =UserInfo.getUserId() ;
        insert t ;
        
        Project__c p = new Project__c ();
        p.CRM_Head__c = UserInfo.getUserId() ;
        insert p ;
        
        Booking__c b1 = new Booking__c();
        b1.Agreement_Value__c = 100;
        b1.Generate_Welcome_Call_Checklist_Master__c = False;
        b1.Tower__c = t.Id ;
        b1.Project__c = p.id ;
        b1.Welcome_Call_Done__c = true ;
        insert b1;
        b1.Generate_Welcome_Call_Checklist_Master__c = true;
        update b1;
        
        Welcome_Call_Checklist__c wc = new Welcome_Call_Checklist__c();
        wc.Decision__c = 'Rejected';
        wc.Booking__c = b1.Id;
        wc.Accepted__c = true;
        List<Welcome_Call_Checklist__c> WelcomeCallCheckList = new List<Welcome_Call_Checklist__c>();
        WelcomeCallCheckList.add(wc);
        insert WelcomeCallCheckList;
        

        
       // Test.startTest();
        Ex_WelcomeCall.getWelcomCallDetails(b.Id);
        Ex_WelcomeCall.changeGenarateCheckBoxValue(b1.Id);
        Ex_WelcomeCall.getWelcomCallDetails(b1.Id);
        Ex_WelcomeCall.checkGenerateWelcomeCallChecklist(b.Id);
        Ex_WelcomeCall.updateRecords(WelcomeCallCheckList, WelcomeCallCheckList, b1.Id, 'Test');
        Test.stoptest();

    }
    
    @isTest
    public static void testProjectLWC() {
        Project__c p = new Project__c();
        p.Name = 'Test';
        insert p;
        Test.startTest();  
        List<ContentDocumentLink> result = ProjectLwc.notes(p.Id);
        List<Project__c> pList = ProjectLwc.searchpro();
        Test.stoptest();
        
    }
  


    

    @isTest
    public static void testGetFieldDynamicValue() {
        Booking__c b1 = new Booking__c();
        b1.Agreement_Value__c = 100;
        b1.Generate_Welcome_Call_Checklist_Master__c = true;
        insert b1;
        
      //  String result = Ex_BookingHanldlerServices.getFieldDynamicValue(b1, 'Token Amount', null, null);
       // System.assertEquals(null, result);
    }

    @isTest
    public static void testGetBookingReceiptMap() {
        Booking__c b1 = new Booking__c();
        b1.Agreement_Value__c = 100;
        b1.Generate_Welcome_Call_Checklist_Master__c = true;
        insert b1;
        Set<Id> bId = new set<Id>();
        bId.add(b1.Id);

        
        Welcome_Call_Checklist__c wc = new Welcome_Call_Checklist__c();
        wc.Decision__c = 'Rejected';
        wc.Booking__c = b1.Id;
        wc.Accepted__c = true;
        List<Welcome_Call_Checklist__c> WelcomeCallCheckList = new List<Welcome_Call_Checklist__c>();
        WelcomeCallCheckList.add(wc);
        insert WelcomeCallCheckList;

        Test.startTest();
        Map<Id, List<Receipt__c>> receiptMap = Ex_BookingHanldlerServices.getBookingReceiptMap(bId);
      

        Test.stopTest();
        // Assert that the map is populated correctly

       
    }

    @isTest
    public static void testGetBookingUnitMap() {
        Test.startTest();
          Project__c pro = new Project__c();
        pro.Name = 'Test Project';
        insert pro;
       
        Tower__c twr = new Tower__c();
        twr.Name = 'TowerA';
        twr.Project__c = pro.Id;
        insert twr;
       
      
        Unit__c un = new Unit__c();
        un.Name = '1BHK501';
        //un.For_Sale__c = 'Yes';
        un.Sale_Status__c = 'Vacant';
        un.Configuration__c = '1 BHK';
        un.Inventory_Type__c = 'Residential';
        un.Floor__c = 5;
        un.Project__c = pro.Id;
        un.Tower__c = twr.Id;
        un.Saleable_Area__c = 1000;
        un.RERA_Carpet_Area_Sq_Ft__c = 800;
        insert un;
        
        Booking__c b1 = new Booking__c();
        b1.Agreement_Value__c = 100;
        b1.Generate_Welcome_Call_Checklist_Master__c = true;
        b1.Unit__c = un.id;
        b1.Project__c = pro.id;
        b1.Tower__c = twr.Id;
        insert b1;
        Set<Id> bId = new set<Id>();
        bId.add(b1.Id);

        
        Welcome_Call_Checklist__c wc = new Welcome_Call_Checklist__c();
        wc.Decision__c = 'Rejected';
        wc.Booking__c = b1.Id;
        wc.Accepted__c = true;
        List<Welcome_Call_Checklist__c> WelcomeCallCheckList = new List<Welcome_Call_Checklist__c>();
        WelcomeCallCheckList.add(wc);
        insert WelcomeCallCheckList;
        
        List<Unit__c> unitList = new List<Unit__c> ();
        unitList = [Select Id, Name,Booking__c,Booking__r.unit__c from Unit__c where Id =: b1.Unit__c];
            
        Ex_BookingHanldlerServices.getBookingUnitMap(bId);        
        
        Map<Id, Unit__c> bookingUnitMap = new Map<Id, Unit__c>();
        for (Unit__c unit : unitList) {
            bookingUnitMap.put(unit.Booking__c, unit);
        }
        
        
       // String result = Ex_BookingHanldlerServices.getFieldDynamicValue(b1, 'Unit Floor', bookingUnitMap , null);
        List<Welcome_Call_Checklist_Master__c> welcomeCallMasterList = Welcome_Call_Checklist_Master__c.getall().values();
        Welcome_Call_Checklist__c checklist = new Welcome_Call_Checklist__c();
        checklist.Category__c = ''	;
        checklist.Description__c = 'checklistMaster.Description__c';
        checklist.Booking__c = b1.Id;
        String result = Ex_BookingHanldlerServices.getFieldDynamicValue(b1, 'Unit Floor', bookingUnitMap , null);
        checklist.Values__c = result; 
        welcomeCallCheckList.add(checklist);
       // insert checklist;
    

        Test.stopTest();
      
    }



    
    
    
}