force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Registered__c.field-meta.xml
<CustomField>
    <fullName>Booking_Registered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Booking Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Booking_Stage__c.field-meta.xml
<CustomField>
    <fullName>Booking_Stage__c</fullName>
    <label>Booking Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Booking_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Generate_Welcome_Call_Checklist_Master__c.field-meta.xml
<CustomField>
    <fullName>Generate_Welcome_Call_Checklist_Master__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Generate Welcome Call Checklist Master</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Payment_Scheme__c.field-meta.xml
<CustomField>
    <fullName>Payment_Scheme__c</fullName>
    <formula>Quotation__r.Payment_Scheme__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Scheme</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Registration_Amount__c.field-meta.xml
<CustomField>
    <fullName>Registration_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Registration Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booking Confirmed</fullName>
            </value>
            <value>
                <fullName>AFS draft send</fullName>
            </value>
            <value>
                <fullName>Registration Scheduled</fullName>
            </value>
            <value>
                <fullName>Registration Completed</fullName>
            </value>
            <value>
                <fullName>Registration Rescheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Amount_Received__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Received__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount Received</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Welcome_call_comments__c.field-meta.xml
<CustomField>
    <fullName>Welcome_call_comments__c</fullName>
    <label>Welcome call comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Welcome_Call_Completion_Date__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Call_Completion_Date__c</fullName>
    <label>Welcome Call Completion Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Charge_Detail__c/Charge_Detail__c.object-meta.xml
<CustomObject>
    <label>Charge Detail</label>
    <nameField>
        <label>Charge Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge_Detail__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Charge Details</relationshipLabel>
    <relationshipName>Charge_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Opportunity Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Payment_Scheme__c.field-meta.xml
<CustomField>
    <fullName>Payment_Scheme__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Scheme</label>
    <referenceTo>Payment_Scheme__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Checklist__c/Welcome_Call_Checklist__c.object-meta.xml
<CustomObject>
    <label>Welcome Call Checklist</label>
    <nameField>
        <displayFormat>WC-{00000}</displayFormat>
        <label>Welcome Call Checklist Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Welcome Call Checklists</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Welcome_Call_Checklist__c/fields/Accepted__c.field-meta.xml
<CustomField>
    <fullName>Accepted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accepted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Checklist__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Welcome Call Checklists</relationshipLabel>
    <relationshipName>Welcome_Call_Checklists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Welcome_Call_Checklist__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Details</fullName>
            </value>
            <value>
                <fullName>Client Signatures</fullName>
            </value>
            <value>
                <fullName>Strike Out</fullName>
            </value>
            <value>
                <fullName>Overwriting</fullName>
            </value>
            <value>
                <fullName>Future Correspondence</fullName>
            </value>
            <value>
                <fullName>Booking Details</fullName>
            </value>
            <value>
                <fullName>Receipt Details</fullName>
            </value>
            <value>
                <fullName>Source of Booking Details</fullName>
            </value>
            <value>
                <fullName>Deal Approval Details : Quotation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Welcome_Call_Checklist__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Booking_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Booking In-Process</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation in-process</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Welcome Call Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Confirmed</fullName>
    </customValue>
    <customValue>
        <fullName>Possession Done</fullName>
    </customValue>
    <customValue>
        <fullName>Welcome Call Done</fullName>
        <isActive>false</isActive>
        <label>Welcome Call Done</label>
    </customValue>
    <masterLabel>Booking Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Opportunity_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Follow-up</fullName>
        <default>true</default>
        <label>In Follow-up</label>
    </customValue>
    <customValue>
        <fullName>Booking In-Process</fullName>
    </customValue>
    <customValue>
        <fullName>Booked</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation In-Process</fullName>
    </customValue>
    <masterLabel>Opportunity Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_WelcomeCall.cls
//-------------------------------------------//
//  Project: Satyam
//  Created By: Exceller tech
//  Created Date: 30-10-2023
//-------------------------------------------//
public class Ex_WelcomeCall {   
   @AuraEnabled(cacheable=true)
    public static List<Booking__c> checkGenerateWelcomeCallChecklist(String recId){
        List<Booking__c> checkList = [select Id,Total_Amount_Received__c,Payment_Scheme__c,Generate_Welcome_Call_Checklist_Master__c 
                                      from Booking__c 
                                      where Id=:recId AND Generate_Welcome_Call_Checklist_Master__c = False];
        return checkList; 
    }
    
    @AuraEnabled
    public static String changeGenarateCheckBoxValue(String rId){ 
        try{
            List<Booking__c> bookList = [select Id,Total_Amount_Received__c,Payment_Scheme__c,
                                         Generate_Welcome_Call_Checklist_Master__c from Booking__c where Id=:rId]; 
            system.debug('booking is::'+bookList);
            for(Booking__c b:bookList){
                b.Id = b.Id;
                b.Generate_Welcome_Call_Checklist_Master__c = True;
                update b;
            }
            return 'Generate Welcome Call Checklist Master changed to True';
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    
    @AuraEnabled
    public static List<Welcome_Call_Checklist__c> getWelcomCallDetails(string bId){
       
        try {
            List<Welcome_Call_Checklist__c> WelcomeCallCheckList = new List<Welcome_Call_Checklist__c>();
            WelcomeCallCheckList = [select Booking__c, Category__c, Description__c, Values__c, Decision__c, Accepted__c from Welcome_Call_Checklist__c 
                                    where Booking__c =: bId AND (Decision__c = '' OR Decision__c = 'Rejected') ];
            
            return WelcomeCallCheckList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage()); 
        }
    }
       
    @AuraEnabled
    public static Id updateRecords(List<Welcome_Call_Checklist__c> records, List<Welcome_Call_Checklist__c> finalList, String bookId, String rem) {
        system.debug('records is::'+records);
        system.debug('finalList is::'+finalList);
        system.debug('bookId is::'+bookId);
        system.debug('rem is::'+rem);
        List<Charge_Detail__c> chargeList = new List<Charge_Detail__c>();
        Decimal getRegistrationAmount = 0;
        Decimal getStampDutyAmount = 0;
        
        try {
            if (rem == null) {
                if (!records.isEmpty() && records != null) {
                    update records;
                }
                if (!finalList.isEmpty() && finalList != null) {
                    update finalList;
                }
            } else {
                if (!records.isEmpty() && records != null) {
                    update records;
                }
                if (!finalList.isEmpty() && finalList != null) {
                    update finalList;
                }
                List<Booking__c> bookingList = [SELECT Id, Welcome_call_comments__c,Quotation__c,/*Quotation__r.Stamp_Duty_Paid_By__c,
                                                 Quotation__r.Original_Stamp_duty__c,Quotation__r.Registration_Amount__c,*/
                                                 Welcome_Call_Done__c,Booking_Stage__c,/*Unit__r.Unit_Status__c,*/Unit__c,Opportunity__r.Opportunity_Stage__c,Opportunity__c,Registration_Status__c,Booking_Registered__c, 
                                                 Welcome_Call_Completion_Date__c, Welcome_Call_Status__c,Registration_Date__c,Tower__r.CRM_Manager__c,Sales_Head_Booking_From_B__c,Director__c,
                                                 Total_Amount_Received__c,Project__c,Project__r.Booking_1_Approver__c,project__r.Booking_2_Approver__c,Payment_Scheme__c,CRM_Head__c,Project__r.CRM_Head__c,
                                                 Project__r.Sales_Head_Booking_From_B__c,Project__r.Director__c

                                                FROM Booking__c WHERE Id = :bookId]; 
                System.debug('bookingList is::' + bookingList);
                
                List<Welcome_Call_Checklist__c> welcomeList = [SELECT Id, Booking__c, Accepted__c, LastModifiedDate FROM Welcome_Call_Checklist__c WHERE Booking__c = :bookId];
                System.debug('welcomeList is::' + welcomeList);
                
                boolean hasRejectedRecord = false; 
                
                for (Welcome_Call_Checklist__c wcc : welcomeList) {
                        if (wcc.Booking__c == bookingList[0].Id) {
                            bookingList[0].Welcome_call_comments__c = rem;
                            
                            if (wcc.Accepted__c == true) {
                                bookingList[0].Welcome_Call_Status__c = 'Welcome Call Completed';
                                bookingList[0].Welcome_Call_Completion_Date__c = System.now();
                                bookingList[0].Welcome_Call_Done__c = true;
                               /* if( bookingList[0].Welcome_Call_Done__c == true){
                                    if(bookingList[0].Tower__r.CRM_Manager__c != null && bookingList[0].Project__r.CRM_Head__c != null){
                                        bookingList[0].CRM_Head__c = bookingList[0].Project__r.CRM_Head__c;
                                        bookingList[0].Level_1_Approver__c =bookingList[0].Tower__r.CRM_Manager__c;
                                        bookingList[0].Sales_Head_Booking_From_B__c = bookingList[0].Project__r.Sales_Head_Booking_From_B__c;
                                        bookingList[0].Director__c =bookingList[0].Project__r.Director__c;

                                    }
                                }*/
                                update bookingList[0];
                                system.debug('booking updates are::' + bookingList[0]);
                            } else {
                                hasRejectedRecord = true;
                                break;
                            }
                          
                        }
                 }
               
                
                if (hasRejectedRecord) { 
                    bookingList[0].Welcome_Call_Status__c = 'Welcome Call Pending';
                  //  bookingList[0].Welcome_Call_Completion_Date__c = System.now();
                    bookingList[0].Welcome_Call_Done__c = false;
                    update bookingList[0];
                }
            }
            return bookId;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }  
}