force-app/main/default/objects/Visit_Pre_Registration__c/Visit_Pre_Registration__c.object-meta.xml
<CustomObject>
    <label>Visit Pre Registration</label>
    <nameField>
        <displayFormat>VPR-{000000}</displayFormat>
        <label>Visit Pre Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Pre Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Pre_Registration_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Pre_Registration_Expiry__c</fullName>
    <label>Pre Registration Expiry</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
                <default>true</default>
                <label>Valid</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ex_VisitPreRegistrationOTPValidityBatch.cls
global class Ex_VisitPreRegistrationOTPValidityBatch implements Database.Batchable<SObject>, Schedulable {
    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([SELECT Id, Status__c, Pre_Registration_Expiry__c 
                                         FROM Visit_Pre_Registration__c
                                         WHERE Pre_Registration_Expiry__c < :System.now() AND Status__c = 'Valid']);
        
    }
    
    global void execute(Database.BatchableContext bc, List<Visit_Pre_Registration__c> scope) {
        System.debug('Scope contains records: ' + scope);
        for (Visit_Pre_Registration__c preReg : scope) {
            preReg.Status__c = 'Expired';
        }
        update scope;
    }
    
    global void execute(SchedulableContext sc) {
        Ex_VisitPreRegistrationOTPValidityBatch batch = new Ex_VisitPreRegistrationOTPValidityBatch();
        Database.executeBatch(batch, 200); 
    }
    
    global void finish(Database.BatchableContext bc) {
        
    }
}