force-app/main/default/objects/CP_Lead__c/CP_Lead__c.object-meta.xml
<CustomObject>
    <label>CP Lead</label>
    <nameField>
        <displayFormat>CPL-{00000}</displayFormat>
        <label>CP Lead No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/CP_Lead__c.field-meta.xml
<CustomField>
    <fullName>CP_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Lead</label>
    <referenceTo>CP_Lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/Visit_Pre_Registration__c.object-meta.xml
<CustomObject>
    <label>Visit Pre Registration</label>
    <nameField>
        <displayFormat>VPR-{000000}</displayFormat>
        <label>Visit Pre Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Pre Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/CP_Lead__c.field-meta.xml
<CustomField>
    <fullName>CP_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Lead</label>
    <referenceTo>CP_Lead__c</referenceTo>
    <relationshipLabel>Visit Pre Registrations</relationshipLabel>
    <relationshipName>Visit_Pre_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Extend_Validity_In_Hours__c.field-meta.xml
<CustomField>
    <fullName>Extend_Validity_In_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Extend Validity (In Hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Visit Pre-Registrations</relationshipLabel>
    <relationshipName>Visit_Pre_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Pre_Registration_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Pre_Registration_Expiry__c</fullName>
    <label>Pre Registration Expiry</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Ex_VisitPreRegistrationHandler.cls
// -------------------------------------------
//   Project: Avant Infra 
//   Created By: Exceller Tech
//   Created Date: 09-09-2024
//   Author: Nitin Choudhary    
// -------------------------------------------
public class Ex_VisitPreRegistrationHandler {
    public static void beforeInsert(List<Visit_Pre_Registration__c> preList){
        List<Visit_Pre_Registration__c> vprLeadList = new List<Visit_Pre_Registration__c>();
        List<Visit_Pre_Registration__c> vprCPList = new List<Visit_Pre_Registration__c>();
        
        if(!preList.isEmpty() && preList != null){
            for (Visit_Pre_Registration__c vpr : preList) {
                if(vpr.Lead__c != null){
                    vprLeadList.add(vpr);
                }
                if(vpr.CP_Lead__c != null){
                    vprCPList.add(vpr);
                }
            }
        }
        
        if(!vprLeadList.isEmpty() && vprLeadList != null){
            Ex_VisitPreRegistrationHandlerServices.createVPRLead(vprLeadList);
        }
        if(!vprCPList.isEmpty() && vprCPList != null){
            Ex_VisitPreRegistrationHandlerServices.createVPRLead(vprCPList);
        }
    }
    
    public static void beforeUpdate(Map<Id, Visit_Pre_Registration__c> oldMap, Map<Id, Visit_Pre_Registration__c> newMap) {
        List<Visit_Pre_Registration__c> vprlList = new List<Visit_Pre_Registration__c>();
        
        for(Visit_Pre_Registration__c oldVpr: oldMap.values()) {
            Visit_Pre_Registration__c newVpr = newMap.get(oldVpr.Id);
            
            if(newVpr.Extend_Validity_In_Hours__c != null && newVpr.Pre_Registration_Expiry__c != null){
                vprlList.add(newvpr);
                
            }
                
        }
         if(!vprlList.isEmpty() && vprlList != null){
            Ex_VisitPreRegistrationHandlerServices.updateVpr(vprlList);
        }
        
    }
    
    
    
    
    
}