force-app/main/default/objects/Registration__c/Registration__c.object-meta.xml
<CustomObject>
    <label>Registration</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Registration__c/fields/Registration_Stage__c.field-meta.xml
<CustomField>
    <fullName>Registration_Stage__c</fullName>
    <label>Registration Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booking Confirmed</fullName>
                <default>true</default>
                <label>Booking Confirmed</label>
            </value>
            <value>
                <fullName>Registration Completed</fullName>
            </value>
            <value>
                <fullName>AFS draft send</fullName>
            </value>
            <value>
                <fullName>Registration Scheduled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ex_RegistrationTriggerHandler.cls
public class Ex_RegistrationTriggerHandler {
    
     public static void afterUpdate(Map<Id, Registration__c> oldMap, Map<Id, Registration__c> newMap) {
        Set<Id> rcSetId = new Set<Id>();
        
        for(Registration__c oldRegistration: oldMap.values()) {
            Registration__c newRegistration = newMap.get(oldRegistration.Id);
            
            if(oldRegistration.Registration_Stage__c != newRegistration.Registration_Stage__c && newRegistration.Registration_Stage__c != null && (newRegistration.Registration_Stage__c.equalsIgnoreCase('Registration Scheduled') || newRegistration.Registration_Stage__c.equalsIgnoreCase('Registration Completed'))){
                rcSetId.add(newRegistration.Id);
            }
        }
         if(!rcSetId.isEmpty() && rcSetId != null){
            Ex_RegistrationTriggerHandlerServices.sendEmailRegistrationSchedule(rcSetId);
        }
         
     }

}