force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</description>
    <inlineHelpText>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</inlineHelpText>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Ex_LeadConversionPopup.cls
// -------------------------------------------
//   Project: Avant Infra 
//   Created By: Exceller Tech
//   Created Date: 06-09-2024
//   Author: Nitin Choudhary    
// -------------------------------------------
public class Ex_LeadConversionPopup {
     @AuraEnabled (cacheable=true)
    public static Map<ID, Lead__c> isChecked(String ID){
        Map<ID, Lead__c> checkMap = new Map<ID, Lead__c>(); 
        for (Lead__c l : [select Id,IsConverted__c FROM Lead__c where id=:ID]){
            if(l.IsConverted__c == true){
                checkMap.put(l.Id,l);
            }   
            else{
                System.debug('error');
            } 
        }
        return checkMap;
    }
    

}