force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</description>
    <inlineHelpText>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</inlineHelpText>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Created_From__c.field-meta.xml
<CustomField>
    <fullName>Lead_Created_From__c</fullName>
    <label>Lead Created From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facebook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Start_Connect_Response__c.field-meta.xml
<CustomField>
    <fullName>Start_Connect_Response__c</fullName>
    <label>Start Connect Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Start_Connect_Status_Code__c.field-meta.xml
<CustomField>
    <fullName>Start_Connect_Status_Code__c</fullName>
    <label>Start Connect Status Code</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Google</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregators</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Television</fullName>
    </customValue>
    <customValue>
        <fullName>Hoarding</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp</fullName>
    </customValue>
    <customValue>
        <fullName>Events</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Reference</fullName>
    </customValue>
    <customValue>
        <fullName>VDNB</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Calling</fullName>
    </customValue>
    <customValue>
        <fullName>Start Connect</fullName>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_GetStartConnectAPIServices.cls
//-------------------------------------------//
//  Project: Satyam
//  Created By: Exceller tech
//  Created Date: 20-06-2024
//-------------------------------------------//
public class Ex_GetStartConnectAPIServices {
    
    @future(Callout=true)
    public static void getStartConnectData(Set<Id> leadId){
        System.debug('leadId: '+leadId);
        List<Lead__c> getList = new List<Lead__c>();
        List<Lead__c> leadList = new List<Lead__c>();
        
        if(!leadId.isEmpty()){
            getList = [Select Id, Name,Lead_Created_From__c,IsConverted__c, Lead_Source__c, Mobile__c, First_Name__c, Last_Name__c, Email__c, Project__c from Lead__c where Id IN: leadId AND IsConverted__c = false AND Lead_Created_From__c != 'CTI'];
        }
        String source = '';
        String user = '';
        String pass = '';
        String function = '';
        String phone_number = '';
        String phone_code = '';
        String list_id = '';
        String first_name = '';
        String last_name = '';
        String email = '';
        String vendor_lead_code = '';
        String strURL = '';
        String StartConnectUrl = '';
        
        
        if(System.label.StartConnectUser != null){
            user = System.label.StartConnectUser;
        }
        if(System.label.StartConnectPass != null){
            pass = System.label.StartConnectPass;
        }
        if(System.label.StartConnectListId != null){
            list_id = System.label.StartConnectListId;
        }
        if(System.label.StartConnectFunction != null){
            function = System.label.StartConnectFunction;
        }
        if(System.label.StartConnect != null){
            phone_code = System.label.StartConnect;
        }
        if(System.label.StartConnectUrl != null){
            StartConnectUrl = System.label.StartConnectUrl ;
        }
        
        System.debug('getList: '+getList);
        if(!getList.isEmpty() && getList != null){
            for(Lead__c l: getList){
                if(l.Lead_Source__c != null){
                    source = l.Lead_Source__c;
                }
                if(l.Mobile__c != null){
                    phone_number = l.Mobile__c;
                }
                if(l.First_Name__c != null){
                    first_name = l.First_Name__c;
                }
                if(l.Last_Name__c != null){
                    last_name = l.Last_Name__c;
                }
                if(l.Email__c != null){
                    email = l.Email__c;
                }
                if(l.Project__c != null){
                    vendor_lead_code = l.Project__c;
                }
                
                strURL = StartConnectUrl +
                    'source=' + EncodingUtil.urlEncode(source, 'UTF-8') + 
                    '&user=' + EncodingUtil.urlEncode(user, 'UTF-8') + 
                    '&pass=' + EncodingUtil.urlEncode(pass, 'UTF-8') + 
                    '&function=' + EncodingUtil.urlEncode(function, 'UTF-8') + 
                    '&phone_number=' + EncodingUtil.urlEncode(phone_number, 'UTF-8') + 
                    '&phone_code=' + EncodingUtil.urlEncode(phone_code, 'UTF-8') + 
                    '&list_id=' + EncodingUtil.urlEncode(list_id, 'UTF-8') + 
                    '&first_name=' + EncodingUtil.urlEncode(first_name, 'UTF-8') + 
                    '&last_name=' + EncodingUtil.urlEncode(last_name, 'UTF-8') + 
                    '&email=' + EncodingUtil.urlEncode(email, 'UTF-8') + 
                    '&vendor_lead_code=' + EncodingUtil.urlEncode(vendor_lead_code, 'UTF-8');
                System.debug('url: '+strURL);
                
                if(strURL != null){
                    if(!Test.isRunningTest()) {
                        HttpRequest req = new HttpRequest();
                        req.setEndpoint (strURL);
                        req.setMethod ('POST');
                        Http http = new Http();
                        HTTPResponse res = http.send(req);
                        system.debug('HTTPResponse : '+ res);  
                        system.debug('Responsebody : '+ res.getBody());  
                        if(req != null && res.getBody() != null){
                            l.Start_Connect_Status_Code__c = String.valueof(res);
                            l.Start_Connect_Response__c = res.getBody();
                            leadList.add(l);
                        }
                    }    
                }
            }
        }
        if(leadList != null && !leadList.isEmpty()){
            update leadList;
        }        
    }
}