force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account)</relationshipLabel>
    <relationshipName>Leads2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incoming</fullName>
                <default>true</default>
                <label>Incoming</label>
            </value>
            <value>
                <fullName>SNP</fullName>
            </value>
            <value>
                <fullName>Prospects</fullName>
            </value>
            <value>
                <fullName>Visit confirmed</fullName>
            </value>
            <value>
                <fullName>Visit Done</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>AName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Leads (Opportunity)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <formula>Account__r.Alternate_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account__r.PersonContact.Email</formula>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>Account__r.PersonContact.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>NameA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Opportunity Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Lead_validity_in_days__c.field-meta.xml
<CustomField>
    <fullName>Lead_validity_in_days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Lead validity in days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Opportunity Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Follow-up</fullName>
            </value>
            <value>
                <fullName>Closed Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/WA_API_Details_Gupshup__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Gupshup APIs</description>
    <label>WA API Details Gupshup</label>
</CustomObject>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/Connection__c.field-meta.xml
<CustomField>
    <fullName>Connection__c</fullName>
    <label>Connection</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/Source_Phone__c.field-meta.xml
<CustomField>
    <fullName>Source_Phone__c</fullName>
    <label>Source Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/src_name__c.field-meta.xml
<CustomField>
    <fullName>src_name__c</fullName>
    <label>src.name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WA_API_Details_Gupshup__c/fields/token__c.field-meta.xml
<CustomField>
    <fullName>token__c</fullName>
    <label>token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/Whatsapp_Template__c.object-meta.xml
<CustomObject>
    <label>Whatsapp Template</label>
    <nameField>
        <displayFormat>WT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Whatsapp Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Whatsapp_Template__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Whatsapp Templates</relationshipLabel>
    <relationshipName>Whatsapp_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Public_Link_1__c.field-meta.xml
<CustomField>
    <fullName>Public_Link_1__c</fullName>
    <label>Public Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Sample_Text__c.field-meta.xml
<CustomField>
    <fullName>Sample_Text__c</fullName>
    <label>Sample Text</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Template_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Template_Approval_Status__c</fullName>
    <label>Template Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
            <value>
                <fullName>PENDING_DELETION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Template_Category__c.field-meta.xml
<CustomField>
    <fullName>Template_Category__c</fullName>
    <label>Template Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MARKETING</fullName>
            </value>
            <value>
                <fullName>OTP</fullName>
            </value>
            <value>
                <fullName>UTILITY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TEXT</fullName>
            </value>
            <value>
                <fullName>IMAGE</fullName>
            </value>
            <value>
                <fullName>VIDEO</fullName>
            </value>
            <value>
                <fullName>DOCUMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Whatsapp_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Whatsapp_Template_Name__c</fullName>
    <label>Whatsapp Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Opportunity_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Follow-up</fullName>
        <default>true</default>
        <label>In Follow-up</label>
    </customValue>
    <customValue>
        <fullName>Booking In-Process</fullName>
    </customValue>
    <customValue>
        <fullName>Booked</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation In-Process</fullName>
    </customValue>
    <masterLabel>Opportunity Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestEx_TemplateMediaSelectorHandler.cls
@isTest
public class TestEx_TemplateMediaSelectorHandler {
    public class MockHttpResponse implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/x-www-form-urlencoded');
            res.setBody('{"status": "Success"}');
            res.setStatusCode(200);
            return res;
        }
    }
    
    @isTest
    public static void method1(){
        WA_API_Details_Gupshup__c wa = new WA_API_Details_Gupshup__c();
        wa.Name__c = 'ParadiseGroup';
        wa.isActive__c = true;
        wa.token__c = 'Test';
        wa.Connection__c = 'test';
        wa.Channel__c = 'Test';
        wa.Source_Phone__c = '1212121212';
        wa.src_name__c = 'google';
        wa.API_Key__c = 'asdf';
        wa.Project_Name__c = 'Project A';
        insert wa;
        
        Project__c pro = new Project__c();
        pro.Name = 'Project A';
        //pro.Lead_validity_in_days__c = 45;
        pro.Public_Link__c = 'www.google.com';
        insert pro;
        
        Lead__c l3 = new Lead__c();
        l3.Last_Name__c = 'Lead__c 1';
        l3.Mobile__c = '1122334455';
        l3.Phone__c = '7887755663';
        //l3.Alternate_Email__c = 'Test@gmail.com';
        l3.Email__c = 'Test2@gmail.com';
        l3.Project__c = pro.Id;
        l3.Last_Presales_Call_Date__c = System.Today();
        l3.Lead_Stage__c = 'Incoming';
        insert l3;
        
        
        
        Account a1 = new Account(FirstName = 'Test', LastName = 'Lead__c 1', PersonMobilePhone = '1122334455');
        insert a1;
        
        Opportunity__c o1 = new Opportunity__c(Name = 'Test1', /*Close_Date__c = System.today(),*/Opportunity_Stage__c = 'In Follow-up', Project__c = pro.Id,Account__c = a1.id);
        insert o1;
        
        
        Whatsapp_Template__c wt= new Whatsapp_Template__c();
        wt.Public_Link_1__c  = 'www.google.com';
        wt.Whatsapp_Template_Name__c = 'wtn';
        wt.Type__c = 'TEXT';
        wt.Public_Link_1__c = 'www.google.com';
        wt.Object__c = 'Lead__c';
        wt.Template_Category__c ='MARKETING';
        wt.Template_Approval_Status__c = 'APPROVED';
        wt.Sample_Text__c= 'tesad';
        wt.Template__c = 'templatewe';
        wt.Parameters__c = 'parameter';
        wt.Value_1__c = 'test';
        wt.Title_1__c = 'Test';
        wt.Type_1__c = 'PHONE_NUMBER';
        wt.Value_2__c = 'test';
        wt.Title_2__c = 'Test';
        wt.Type_2__c = 'URL';
        wt.Reply1__c = 'Yes';
        wt.Reply2__c = 'No';
        insert wt;
        
        Whatsapp_Template__c wt1= new Whatsapp_Template__c();
        wt1.API_Hit_Status__c = 'Success';
        insert wt1;
        
        Whatsapp_Template__c wt2= new Whatsapp_Template__c();
        wt2.Public_Link_1__c  = 'www.google.com';
        wt2.Whatsapp_Template_Name__c = 'wtn';
        wt2.Type__c = 'DOCUMENT';
        wt2.Object__c = 'Opportunity__c';
        wt2.Template_Category__c ='MARKETING';
        wt2.Template_Approval_Status__c = 'APPROVED';
        insert wt2;
        
        Whatsapp_Template__c wt3= new Whatsapp_Template__c();
        wt3.Public_Link_1__c  = 'www.google.com';
        wt3.Whatsapp_Template_Name__c = 'wtn';
        wt3.Type__c = 'DOCUMENT';
        wt3.Object__c = 'Account';
        wt3.Template_Category__c ='MARKETING';
        wt3.Template_Approval_Status__c = 'APPROVED';
        insert wt3;
        
        Whatsapp_Template__c wt4= new Whatsapp_Template__c();
        wt4.Public_Link_1__c  = 'www.google.com';
        wt4.Whatsapp_Template_Name__c = 'wtn';
        wt4.Type__c = 'DOCUMENT';
        wt4.Object__c = 'Site_Visit__c';
        wt4.Template_Category__c ='MARKETING';
        wt4.Template_Approval_Status__c = 'APPROVED';
        insert wt4;
        
        Whatsapp_Template__c wt5= new Whatsapp_Template__c();
        wt5.Public_Link_1__c  = 'www.google.com';
        wt5.Whatsapp_Template_Name__c = 'wtn';
        wt5.Type__c = 'DOCUMENT';
        wt5.Object__c = 'Quotation__c';
        wt5.Template_Category__c ='MARKETING';
        wt5.Template_Approval_Status__c = 'APPROVED';
        insert wt5;
        
                
        List<Whatsapp_Template__c> wtlist = new List<Whatsapp_Template__c>();
        wtlist.add(wt);
        
        string searchTerm = 'wtn';
        List<Id> idlist = new List<Id>();
        idlist.add(l3.Id);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse());
        
        Test.StartTest();
        Ex_TemplateMediaSelectorHandler.getStaticResources();
        Ex_TemplateMediaSelectorHandler.checkPublicURL(wt.Id);
        Ex_TemplateMediaSelectorHandler.UpdateTemplate(wtlist);
        Ex_TemplateMediaSelectorHandler.searchTemplateRecord(searchTerm);
        Ex_TemplateMediaSelectorHandler.getStaticResourcesforProject();
        Ex_TemplateMediaSelectorHandler.searchProjectRecord('searchTerm');
        
        string tempId = 'test';
       
        Ex_TemplateMediaSelectorHandler.checkPublicURLforProject(pro.id);
        Ex_TemplateMediaSelectorHandler.UpdateProject(new List<Project__c>{pro});
        
        
        Ex_LeadDashboard.getCategory(wt.Object__c, wt.Project__c);
        Ex_LeadDashboard.getTemplate(wt.Template_Category__c, wt.Object__c, wt.Project__c);
        Ex_LeadDashboard.getTemplate(wt2.Template_Category__c, wt2.Object__c,wt2.Project__c);
        Ex_LeadDashboard.getTemplate(wt3.Template_Category__c, wt3.Object__c,wt3.Project__c);
        Ex_LeadDashboard.getTemplate(wt4.Template_Category__c, wt4.Object__c,wt4.Project__c);
        Ex_LeadDashboard.getTemplate(wt5.Template_Category__c, wt5.Object__c,wt5.Project__c);
        Ex_LeadDashboard.previewTemplate(wt.id);
        Ex_LeadDashboard.getLeadsByDateAndProject(System.today(), System.today(), pro.Id, wt.Object__c, l3.Lead_Stage__c, l3.OwnerId);
        Ex_LeadDashboard.getLeadsByDateAndProject(System.today(), System.today(), pro.Id, wt3.Object__c,l3.Lead_Stage__c, l3.OwnerId);
        Ex_LeadDashboard.updateLeadSendWhatsApp(idlist, wt.Id, wt.Object__c);
        Ex_LeadDashboard.getPicklistValues('Lead__c', 'Lead_Stage__c');
        Ex_LeadDashboard.getPicklistValues1('Lead__c', 'Lead_Stage__c');
        Ex_LeadDashboard.getPicklistValues2('Lead__c', 'Lead_Stage__c');
        Ex_LeadDashboard.getPicklistValues3('Lead__c', 'Lead_Stage__c');
        
        
        Test.StopTest();
        
        
       
       
    }
    
    @isTest
    public static void method2(){
        Project__c pro = new Project__c();
        pro.Name = 'Project A';
        //pro.Lead_validity_in_days__c = 45;
        pro.Public_Link__c = '';
        insert pro;
        
        List<Project__c> testProjects = new List<Project__c>();
        testProjects.add(pro);
        
         Whatsapp_Template__c wt1= new Whatsapp_Template__c();
        wt1.API_Hit_Status__c = 'Success';
        wt1.Type__c = 'TEXT';
        insert wt1;
        
        List<Whatsapp_Template__c> wtlist = new List<Whatsapp_Template__c>();
       // wtlist.add(wt1);
        
        
        Ex_TemplateMediaSelectorHandler.checkPublicURL('wt1.id');
        Ex_TemplateMediaSelectorHandler.getStaticResources();
        Ex_TemplateMediaSelectorHandler.UpdateTemplate(wtlist);
        Ex_TemplateMediaSelectorHandler.searchTemplateRecord('searchTerm');
        Ex_TemplateMediaSelectorHandler.getStaticResourcesforProject();
        Ex_TemplateMediaSelectorHandler.searchProjectRecord(pro.id);
        
        string tempId = 'test';
       
        Ex_TemplateMediaSelectorHandler.checkPublicURLforProject(pro.id);
        Ex_TemplateMediaSelectorHandler.UpdateProject(testProjects);
        

        
    }
}