force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Campaign_Custom__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Custom__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campaign Custom</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Legacy_Record__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Legacy Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LeadTriggerHandler.cls
//-------------------------------------------//
//  Project: Nandi Vardhan Constructioin 
//  Created By: Exceller Consultancy
//  Created Date: 16-5-2023
//-------------------------------------------//
public class LeadTriggerHandler {
    public static void beforeInsert(List<Lead__c> leadList) {
        List<Lead__c> lList = new List<Lead__c>();
        Map<Id, List<Lead__c>> pLeadMap = new Map<Id, List<Lead__c>>();
        
        for(Lead__c l: leadList) {
            if(!l.Legacy_Record__c)
                lList.add(l);
        }
        if(!lList.isEmpty() && lList != null)
            LeadHandlerServices.duplicationCheck(lList);
    }
    
    public static void afterInsert(List<Lead__c> leadList) {
        List<Lead__c> lList = new List<Lead__c>();
        List<Lead__c> cLeadList = new List<Lead__c>();
        
        for(Lead__c l: leadList) {
            if(l.Campaign_Custom__c != null)
                lList.add(l);
            if(l.Campaign_Code__c != null)
                cLeadList.add(l);
        }
        if(!lList.isEmpty() && lList != null)
            CampaignHandlerServices.calculateCampaignPerformance('Lead', leadList, null);
        /*if(!cLeadList.isEmpty() && cLeadList != null)
			CampaignHandlerServices.createCampaignMember(cLeadList);*/
    }
    
    public static void beforeUpdate(Map<Id, Lead__c> oldMap, Map<Id, Lead__c> newMap) {
        List<Lead__c> lList = new List<Lead__c>();
        
        for(Lead__c oldLead: oldMap.values()) {
            Lead__c newLead = newMap.get(oldLead.Id);
            
            if(oldLead.Mobile__c != newLead.Mobile__c || oldLead.Phone__c != newLead.Phone__c || oldLead.Email__c != newLead.Email__c || oldLead.Alternate_Email_Id__c != newLead.Alternate_Email_Id__c || oldLead.Project__c != newLead.Project__c)
                lList.add(newLead);
        }
        if(!lList.isEmpty() && lList != null)
            LeadHandlerServices.duplicationCheck(lList);
    }
    
    /*public static void afterUpdate(Map<Id, Lead> oldMap, Map<Id, Lead> newMap) {
        List<Lead> cLeadList = new List<Lead>();
        
		for(Lead oldLead: oldMap.values()) {
            Lead newLead = newMap.get(oldLead.Id);
            
            if(oldLead.Campaign_Code__c != newLead.Campaign_Code__c && newLead.Campaign_Code__c != null)
                cLeadList.add(newLead);
        }
        if(!cLeadList.isEmpty() && cLeadList != null)
            CampaignHandlerServices.createCampaignMember(cLeadList);
    }*/
}