force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Whatsapp_Template__c/Whatsapp_Template__c.object-meta.xml
<CustomObject>
    <label>Whatsapp Template</label>
    <nameField>
        <displayFormat>WT-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Whatsapp Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Whatsapp_Template__c/fields/Parameters__c.field-meta.xml
<CustomField>
    <fullName>Parameters__c</fullName>
    <label>Parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Whatsapp Templates</relationshipLabel>
    <relationshipName>Whatsapp_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Public_Link_1__c.field-meta.xml
<CustomField>
    <fullName>Public_Link_1__c</fullName>
    <label>Public Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Template__c.field-meta.xml
<CustomField>
    <fullName>Template__c</fullName>
    <label>Template</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Template_Kind__c.field-meta.xml
<CustomField>
    <fullName>Template_Kind__c</fullName>
    <label>Template Kind</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Specific</fullName>
            </value>
            <value>
                <fullName>General</fullName>
                <default>true</default>
                <label>General</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Whatsapp_Template__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TEXT</fullName>
            </value>
            <value>
                <fullName>IMAGE</fullName>
            </value>
            <value>
                <fullName>VIDEO</fullName>
            </value>
            <value>
                <fullName>DOCUMENT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestEx_WhatsappTemplate.cls
@isTest
public class TestEx_WhatsappTemplate {
	@isTest
    public static void testMethod1(){
		Project__c pro = new Project__c();
        pro.Name = 'Project A';
        insert pro;
        
        String objectName = 'Lead__c';
        
        Whatsapp_Template__c wt = new Whatsapp_Template__c();
        wt.Type__c = 'TEXT';
        wt.Parameters__c = 'Param1,Param2';
        wt.Template__c = 'Test';
        wt.Public_Link_1__c = 'www.google.com';
        wt.Template_Kind__c = 'General';
        insert wt;
        
        Whatsapp_Template__c wt1 = new Whatsapp_Template__c();
        wt1.Type__c = 'TEXT';
        wt1.Parameters__c = 'Param1,Param2';
        wt1.Template__c = 'Test';
        wt.Public_Link_1__c = 'www.google.com';
        
        List<Whatsapp_Template__c> wtList = new List<Whatsapp_Template__c>();
        wtList.add(wt1);
        
        List<String> variableList = new List<String>();
        variableList.add('Param1');
        variableList.add('Param2');
        
        test.startTest();
        Ex_WhatsappTemplate.getObjectField(objectName);
        Ex_WhatsappTemplate.getWhatsappTemplate(wt.Id);
        Ex_WhatsappTemplate.getpara(wt.Id);
        Ex_WhatsappTemplate.Save('Test','Test','MARKETING',variableList,'IMAGE','Test','Header',variableList,wtList, wt.Template_Kind__c, pro.id);
        Ex_WhatsappTemplate.QuickSave(wt.Id,'Test','Test','MARKETING',variableList,'IMAGE','Header');
        Ex_WhatsappTemplate.uploadFile('Test','Test',wt.Id,'0');
        Ex_WhatsappTemplate.getApiDetails();
        test.stopTest();
    }
}