force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Direct_Lead__c.field-meta.xml
<CustomField>
    <fullName>Direct_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field tracks the creation and conversion of a Lead, Account and Opportunity into an Account and Opportunity when a customer engages in a project. It is used to mark cases where there was no prior Lead in the system, initiating a direct lead conversion process.</description>
    <inlineHelpText>This field is automatically checked when a customer engages in a project and there is no existing Lead, Account and Opportunity, triggering the creation of a new Lead and its conversion into an Account and Opportunity.</inlineHelpText>
    <label>Direct Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Presales_Call_Count__c.field-meta.xml
<CustomField>
    <fullName>Presales_Call_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Presales Call Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Ex_LeadTriggerHandler.cls
public class Ex_LeadTriggerHandler {
    public static void beforeInsert(List<Lead__c> leadList) {
        List<Lead__c> lList = new List<Lead__c>();
        List<Lead__c> lListforDirect = new List<Lead__c>();
        
        for(Lead__c l: leadList) {
            if(l.Direct_Lead__c != true)
                lList.add(l);
            else
                lListforDirect.add(l);                
        }
        if(!lList.isEmpty() && lList != null)
            Ex_LeadHandlerServices.duplicationCheck('Yes', lList);
        if(!lListforDirect.isEmpty() && lListforDirect != null)
            Ex_LeadHandlerServices.duplicationCheck('No', lListforDirect);
    }
    
    
    public static void beforeUpdate(Map<Id, Lead__c> oldMap, Map<Id, Lead__c> newMap) {
        List<Lead__c> lList = new List<Lead__c>();
        List<Lead__c> LeadList = new List<Lead__c>();
        
        for(Lead__c oldLead: oldMap.values()) {
            Lead__c newLead = newMap.get(oldLead.Id);
            
            if(oldLead.Mobile__c != newLead.Mobile__c || oldLead.Phone__c != newLead.Phone__c || oldLead.Project__c != newLead.Project__c || 
               oldLead.Email__c != newLead.Email__c || oldLead.Alternate_Email__c != newLead.Alternate_Email__c)
            {
                lList.add(newLead);
            }
            
            if(oldLead.Presales_Call_Count__c != newLead.Presales_Call_Count__c && newLead.Presales_Call_Count__c == 1){
                LeadList.add(newLead);
            }
        }
        if(!lList.isEmpty() && lList != null)
            Ex_LeadHandlerServices.duplicationCheck('No', lList);
        if(!LeadList.isEmpty() && LeadList != null){
            Ex_LeadHandlerServices.updateFirstCallDate(LeadList);
        }
    }
}