force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Apply_Round_Robin__c.field-meta.xml
<CustomField>
    <fullName>Apply_Round_Robin__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field to assign the Lead to a member of the Presales Team. The assignment occurs only if the Presales Team is maintained on the Project and has active team members, designating one as the Lead owner using the Round Robin method.</description>
    <inlineHelpText>This field to assign the Lead to a member of the Presales Team. The assignment occurs only if the Presales Team is maintained on the Project and has active team members, designating one as the Lead owner using the Round Robin method.</inlineHelpText>
    <label>Apply Round Robin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <displayFormat>L-{000000}</displayFormat>
    <label>Lead Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/User_Active_Status__c.field-meta.xml
<CustomField>
    <fullName>User_Active_Status__c</fullName>
    <description>To check if Owner is Active/Inactive</description>
    <formula>Owner:User.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>To check if Owner is Active/Inactive</inlineHelpText>
    <label>User Active Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GRE QR User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Team_Type__c.field-meta.xml
<CustomField>
    <fullName>Team_Type__c</fullName>
    <label>Team Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Presales Team</fullName>
            </value>
            <value>
                <fullName>Sales Team</fullName>
            </value>
            <value>
                <fullName>Unapproved Discount Team</fullName>
            </value>
            <value>
                <fullName>Booking Approval</fullName>
                <isActive>false</isActive>
                <label>Booking Approval</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Assignment_Counter__c.field-meta.xml
<CustomField>
    <fullName>Assignment_Counter__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Assignment Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Availability__c.field-meta.xml
<CustomField>
    <fullName>Availability__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Availability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Is_User_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_User_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is User Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Last_Assignment_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Last_Assignment_DateTime__c</fullName>
    <label>Last Assignment DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Last_Assignment_Milliseconds__c.field-meta.xml
<CustomField>
    <fullName>Last_Assignment_Milliseconds__c</fullName>
    <label>Last Assignment Milliseconds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/User_Active_Status__c.field-meta.xml
<CustomField>
    <fullName>User_Active_Status__c</fullName>
    <formula>User__r.IsActive</formula>
    <label>User Active Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LeadHandlerServices.cls
//-------------------------------------------//
//  Project: Nandi Vardhan Constructioin 
//  Created By: Exceller Consultancy
//  Created Date: 16-5-2023
//-------------------------------------------//
public class LeadHandlerServices {
	public static void duplicationCheck(List<Lead__c> leadList) {
        Map<Lead__c, List<DuplicationHandlerServices.duplicateWrapper>> duplicateWrapperMap = new Map<Lead__c, List<DuplicationHandlerServices.duplicateWrapper>>();
        duplicateWrapperMap = DuplicationHandlerServices.duplicationCheck(leadList);
        Map<Id, List<Lead__c>> projectLeadMap = new Map<Id, List<Lead__c>>();
        for(Lead__c l: leadList) {
            String errMsg = '';
            if(duplicateWrapperMap.containsKey(l)) {
                for(DuplicationHandlerServices.duplicateWrapper dw: duplicateWrapperMap.get(l)) {
                    if(dw.objectType.equalsIgnoreCase('Lead'))
                        errMsg = 'Duplicate Lead Found with Name: '+dw.dupLead.Name+' & Id: '+dw.dupLead.Lead_Id__c;
                    else if(dw.objectType.equalsIgnoreCase('Opportunity'))
                        errMsg = 'Duplicate Opportunity Found with Name: '+dw.dupOpp.Name+' & Id: '+dw.dupOpp.Opportunity_Id__c;
                }
                if(!test.isRunningTest() && errMsg != null)
                    l.addError(errMsg);
            }  else {
                if(l.Apply_Round_Robin__c && l.Project__c != null) {
                    if(projectLeadMap.containsKey(l.Project__c)) {
                        projectLeadMap.get(l.Project__c).add(l);
                    } else {
                        List<Lead__c> newList = new List<Lead__c>();
                        newList.add(l);
                        projectLeadMap.put(l.Project__c, newList);
                    }
                }
            }
        }
        if(!projectLeadMap.isEmpty() && projectLeadMap != null)
            applyRoundRobinLogic(projectLeadMap);
        system.debug('projectLeadMap :' +projectLeadMap);
    }
    
    public static void applyRoundRobinLogic(Map<Id, List<Lead__c>> projectLeadMap) {
        Map<Id, List<Team_Member__c>> projectTeamMemberMap = new Map<Id, List<Team_Member__c>>();
        Map<Id, Team_Member__c> memberMapToUpdate = new Map<Id, Team_Member__c>();
        
        projectTeamMemberMap = getProjectTeamMemberMap(projectLeadMap.keySet());
        system.debug('projectTeamMemberMap: '+projectTeamMemberMap);
        
        for(Id pId: projectLeadMap.keySet()) {
            List<Lead__c> leadList = projectLeadMap.get(pId);
            List<Team_Member__c> tmList = projectTeamMemberMap.get(pId);
            
            Integer index = 0;
            for(Lead__c l: leadList) {
                // Pick the next person to be assigned
                if(tmList != null ) {
                    Team_Member__c member = tmList.get(Math.mod(index, tmList.size()));
                    
                    l.OwnerId = member.User__c;
                    system.debug('Owner:'+l.OwnerId);
                    DateTime now = DateTime.now();
                    
                    member.Last_Assignment_DateTime__c = now;
                    member.Last_Assignment_Milliseconds__c = now.millisecondGMT();
                    member.Assignment_Counter__c = member.Assignment_Counter__c + 1;
                    memberMapToUpdate.put(member.Id, member);
                    index++;
                }
            }
        }
        if(!memberMapToUpdate.isEmpty() && memberMapToUpdate != null) {
            List<Team_Member__c> updateTMList = memberMapToUpdate.values();
            system.debug('updateTmList'+updateTMList);
            update updateTMList;
        }
    }
    
    public static Map<Id, List<Team_Member__c>> getProjectTeamMemberMap(Set<Id> pIdSet) {
        Map<Id, List<Team_Member__c>> projectTeamMemberMap = new Map<Id, List<Team_Member__c>>();
        List<Team_Member__c> tmList = new List<Team_Member__c>();
        
        tmList = [Select Id, Team__c, Team__r.Project__c, User__c, Last_Assignment_DateTime__c, User_Active_Status__c, Last_Assignment_Milliseconds__c, Assignment_Counter__c from Team_Member__c
                  where Team__r.Project__c =: pIdSet AND Is_User_Active__c = true AND User_Active_Status__c = true AND Availability__c = true AND Team__r.Team_Type__c = 'Sales Team' 
                  ORDER BY Last_Assignment_DateTime__c, Last_Assignment_Milliseconds__c];
        system.debug('tmList: '+tmList);
        
        if(!tmList.isEmpty() && tmList != null) {
            for(Team_Member__c tm: tmList) {
                if(projectTeamMemberMap.containsKey(tm.Team__r.Project__c)) {
                    projectTeamMemberMap.get(tm.Team__r.Project__c).add(tm);
                } else {
                    List<Team_Member__c> newList = new List<Team_Member__c>();
                    newList.add(tm);
                    projectTeamMemberMap.put(tm.Team__r.Project__c, newList);
                }
            }
        }
        return projectTeamMemberMap;
    }
}