force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</description>
    <inlineHelpText>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</inlineHelpText>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Google</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregators</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Television</fullName>
    </customValue>
    <customValue>
        <fullName>Hoarding</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp</fullName>
    </customValue>
    <customValue>
        <fullName>Events</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Reference</fullName>
    </customValue>
    <customValue>
        <fullName>VDNB</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Calling</fullName>
    </customValue>
    <customValue>
        <fullName>Start Connect</fullName>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_ShowSimilarLeadController.cls
public class Ex_ShowSimilarLeadController {
	@AuraEnabled(Cacheable=true)
    public static List<Lead__c> getLeadData(Id recordId){
        List<Lead__c> leadlist = new List<Lead__c>();
        List<Lead__c> updateList = new List<Lead__c>();
        if(recordId != null){
            Lead__c ld = [Select Id, Mobile__c, Phone__c, Email__c, Alternate_Email__c, Project__r.Name, Project__c,First_Name__c,Last_Name__c from Lead__c where Id =: recordId ];
            //System.debug('ld: '+ld);
            if(ld.Mobile__c != null){
                leadlist =  [Select Id, Mobile__c, Phone__c, Project__r.Name, Project__c,First_Name__c,Last_Name__c,Lead_Source__c,OwnerId, Owner.Name from Lead__c where Id !=: ld.Id AND(Mobile__c =: ld.Mobile__c OR Phone__c =: ld.Mobile__c)AND IsConverted__c = false ];
                //System.debug('Size of leadlist: ' + leadlist.size());
            }
            if(ld.Phone__c != null){
                leadlist =  [Select Id, Mobile__c, Phone__c, Project__r.Name, Project__c,First_Name__c,Last_Name__c,Lead_Source__c,OwnerId, Owner.Name from Lead__c where Id !=: ld.Id AND(Phone__c =: ld.Phone__c OR Phone__c =: ld.Mobile__c)AND IsConverted__c = false ];
                //System.debug('Size of leadlist: ' + leadlist.size());
            }
            if(ld.Email__c != null){
                leadlist =  [Select Id, Mobile__c, Phone__c, Email__c, Alternate_Email__c, Project__r.Name, Project__c,First_Name__c,Last_Name__c,Lead_Source__c,OwnerId, Owner.Name from Lead__c where Id !=: ld.Id AND(Email__c =: ld.Email__c OR Alternate_Email__c =: ld.Email__c) AND IsConverted__c = false ];
                //System.debug('Size of leadlist: ' + leadlist.size());
            }
            if(ld.Alternate_Email__c != null){
                leadlist =  [Select Id, Mobile__c, Phone__c, Email__c, Alternate_Email__c, Project__r.Name, Project__c,First_Name__c,Last_Name__c,Lead_Source__c,OwnerId, Owner.Name from Lead__c where Id !=: ld.Id AND(Alternate_Email__c =: ld.Alternate_Email__c OR Alternate_Email__c =: ld.Email__c) AND IsConverted__c = false ];
                //System.debug('Size of leadlist: ' + leadlist.size());
            }
            if(!leadlist.isEmpty() && leadlist != null){
                updateList.addAll(leadlist);
            }
        }
        System.debug('updateList: '+updateList.size());
        if(!updateList.isEmpty() && updateList != null && updateList.size() > 0){
            return updateList;
        }else{
            return null;
        }
    }
}