force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account)</relationshipLabel>
    <relationshipName>Leads2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Created_From__c.field-meta.xml
<CustomField>
    <fullName>Lead_Created_From__c</fullName>
    <label>Lead Created From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facebook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Lead_Identifier__c</fullName>
    <label>Lead Identifier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>CTI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Leads (Opportunity)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <formula>Account__r.Alternate_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>Account__r.PersonContact.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <label>Opportunity Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Opportunity_Stage</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Site_Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Count__c</fullName>
    <label>Site Visit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Opportunity_Stage.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>In Follow-up</fullName>
        <default>true</default>
        <label>In Follow-up</label>
    </customValue>
    <customValue>
        <fullName>Booking In-Process</fullName>
    </customValue>
    <customValue>
        <fullName>Booked</fullName>
    </customValue>
    <customValue>
        <fullName>Booking Cancelled</fullName>
    </customValue>
    <customValue>
        <fullName>Lost</fullName>
    </customValue>
    <customValue>
        <fullName>Cancellation In-Process</fullName>
    </customValue>
    <masterLabel>Opportunity Stage</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestEx_StarConnectServices_API.cls
@isTest
public class TestEx_StarConnectServices_API{
    
    @isTest
    static void testGetData() {
        Project__c p = new Project__c();
        p.Name = 'Test Project';
        insert p;
        
        // Mock the request parameters
        RestContext.request = new RestRequest();
        RestContext.request.addParameter('name', 'Test Name');
        RestContext.request.addParameter('email', 'test@example.com');
        RestContext.request.addParameter('mobile', '1234567890');
        RestContext.request.addParameter('alternateNo', '0987654321');
        RestContext.request.addParameter('projectId', p.Id);
        RestContext.request.addParameter('Location', 'Test Location');
        RestContext.request.addParameter('callType', 'Inbound');
        RestContext.request.addParameter('AgentName', 'Test Agent');
        RestContext.request.addParameter('virtualNo', '1112223333');
        RestContext.request.addParameter('callStatus', 'Completed');
        RestContext.request.addParameter('subStage', 'Budget does not match');
        RestContext.request.addParameter('audioFile', 'test_audio.mp3');
        RestContext.request.addParameter('callDuration', '300');
        RestContext.request.addParameter('NextfollupDate', '2024-07-02 14:10:00');
        RestContext.request.addParameter('proposedVisitDate', '2024-07-05 14:10:00');
        RestContext.request.addParameter('proposedVisitTime', '11:40:00 AM');
        RestContext.request.addParameter('remarks', 'Test Remarks');
        Test.StartTest();
        RestContext.response = new RestResponse();
       Ex_StarConnectServices.Rest_result result = Ex_StarConnectServices.getData();
        Test.StopTest();
        
        
    }
        
    @isTest
    static void testDuplicationHandler() {
        Project__c p = new Project__c();
        p.Name = 'Test Project';
        insert p;
        
        Lead__c existingLead = new Lead__c();
        existingLead.Last_Name__c = 'Test Name';
        existingLead.Mobile__c = '1234567890';
        existingLead.Project__c = p.Id;
        existingLead.Lead_Created_From__c = 'Start Connect';
        existingLead.Lead_Identifier__c = 'CTI';
        insert existingLead;
       
        Set<Id> leadSet = new Set<Id>();
        leadSet.add(existingLead.Id);
        Ex_GetStartConnectAPIServices.getStartConnectData(leadSet);
        
        // Mock the request parameters
        RestContext.request = new RestRequest();
        RestContext.request.addParameter('name', 'Test Name');
        RestContext.request.addParameter('email', 'test@example.com');
        RestContext.request.addParameter('mobile', '1234567890');
        RestContext.request.addParameter('alternateNo', '0987654321');
        RestContext.request.addParameter('projectId', p.Id);
        RestContext.request.addParameter('Location', 'Test Location');
        RestContext.request.addParameter('callType', 'Inbound');
        RestContext.request.addParameter('AgentName', 'Test Agent');
        RestContext.request.addParameter('virtualNo', '1112223333');
        RestContext.request.addParameter('callStatus', 'Completed');
        RestContext.request.addParameter('subStage', 'Budget does not match');
        RestContext.request.addParameter('audioFile', 'test_audio.mp3');
        RestContext.request.addParameter('callDuration', '300');
        RestContext.request.addParameter('NextfollupDate', '2024-07-02 14:10:00');
        RestContext.request.addParameter('proposedVisitDate', '2024-07-05 14:10:00');
        RestContext.request.addParameter('proposedVisitTime', '11:40:00 AM');
        RestContext.request.addParameter('remarks', 'Test Remarks');
        Test.StartTest();
        RestContext.response = new RestResponse();
        Ex_StarConnectServices.Rest_result result = Ex_StarConnectServices.getData();
        Test.StopTest();
        
    }
    
     @isTest
    public static void opportunityPresent() {
        Project__c project = new Project__c(Name = 'Test Project Opp');
        insert project;
        
        String RecTypeId= Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        
        Account a2 = new Account(Salutation = 'Mr.' ,FirstName = 'Test', LastName = 'Lead 2', PersonMobilePhone = '1122334456', PersonEmail = 'lead2@test.in', Alternate_Email__c = 'lead@test.in',RecordTypeId = RecTypeId);
        insert a2;
        
        Opportunity__c op = new Opportunity__c(Name = 'Test1', Opportunity_Stage__c = 'In Follow-up', Site_Visit_Count__c = 1,  Project__c = project.Id, Account__c = a2.id);
        insert op;
        
       RestContext.request = new RestRequest();
        RestContext.request.addParameter('name', 'Test Name');
        RestContext.request.addParameter('email', 'lead2@test.in');
        RestContext.request.addParameter('mobile', '911122334456');
        RestContext.request.addParameter('alternateNo', '1122334456');
        RestContext.request.addParameter('projectId', project.Id);
        RestContext.request.addParameter('Location', 'Test Location');
        RestContext.request.addParameter('callType', 'Inbound');
        RestContext.request.addParameter('AgentName', 'Test Agent');
        RestContext.request.addParameter('virtualNo', '1112223333');
        RestContext.request.addParameter('callStatus', 'Completed');
        RestContext.request.addParameter('subStage', 'Budget does not match');
        RestContext.request.addParameter('audioFile', '');
        RestContext.request.addParameter('callDuration', '300');
        RestContext.request.addParameter('NextfollupDate', '2024-07-02 14:10:00');
        RestContext.request.addParameter('proposedVisitDate', '2024-07-05 14:10:00');
        RestContext.request.addParameter('proposedVisitTime', '11:40:00 AM');
        RestContext.request.addParameter('remarks', 'Test Remarks');
        Test.StartTest();
        RestContext.response = new RestResponse();
        Ex_StarConnectServices.Rest_result result = Ex_StarConnectServices.getData();
        Test.StopTest();
    }
}