force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>IF(NOT(ISBLANK(First_Name__c)), First_Name__c + &apos; &apos; + Last_Name__c, Last_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</description>
    <inlineHelpText>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</inlineHelpText>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/Ex_RESTLeadDatapush.cls
@RestResource(urlMapping='/PushLead/*')
global class Ex_RESTLeadDatapush {
   
    @HttpPOST
    global static Rest_result sendleaddata(String SFDC_Id) {
     
        Rest_result result = new Rest_result();
       
        try {        
            if (SFDC_Id != null && !String.isBlank(SFDC_Id)) {
               
                List<Lead__c> leadRecords = [SELECT Id,Name, Mobile__c, Full_Name__c, Email__c FROM Lead__c WHERE Id = :SFDC_Id AND IsConverted__c = False];
               
                if (leadRecords != null && !leadRecords.isEmpty()) {
                    Lead__c rec = leadRecords[0];
                   
                    result.returnCode = 200;
                    result.message = 'Lead Data Send Successfully';
                    result.LeadId = rec.Name;
                   
                } else {
                    result.returnCode = 204;
                    result.message = 'Invalid SFDC ID';
                    return result;
                }
            } else {
                result.returnCode = 204;
                result.message = 'Please Provide SFDC_Id';
                return result;
            }
        } catch (Exception ex) {
            result.returnCode = 500;
            result.message = 'Exception Occurred: ' + ex.getMessage();
        }
        return result;  
    }

    global class Rest_result {
        webservice Integer returnCode;
        webservice String message;
        webservice String LeadId;
    }
}