force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incoming</fullName>
                <default>true</default>
                <label>Incoming</label>
            </value>
            <value>
                <fullName>SNP</fullName>
            </value>
            <value>
                <fullName>Prospects</fullName>
            </value>
            <value>
                <fullName>Visit confirmed</fullName>
            </value>
            <value>
                <fullName>Visit Done</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Pre_Registration__c/Visit_Pre_Registration__c.object-meta.xml
<CustomObject>
    <label>Visit Pre Registration</label>
    <nameField>
        <displayFormat>VPR-{000000}</displayFormat>
        <label>Visit Pre Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visit Pre Registrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Extend_Validity_In_Hours__c.field-meta.xml
<CustomField>
    <fullName>Extend_Validity_In_Hours__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Extend Validity (In Hours)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Visit Pre-Registrations</relationshipLabel>
    <relationshipName>Visit_Pre_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Pre_Registration_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Pre_Registration_Expiry__c</fullName>
    <label>Pre Registration Expiry</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Pre_registration_OTP__c.field-meta.xml
<CustomField>
    <fullName>Pre_registration_OTP__c</fullName>
    <label>Pre registration OTP</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visit_Pre_Registration__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Visit Pre Registrations</relationshipLabel>
    <relationshipName>Visit_Pre_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestEx_VisitPreRegistrationHanadler.cls
@isTest
public class TestEx_VisitPreRegistrationHanadler {

    @isTest
    public static void testGenerateOTP(){
        Project__c p = new Project__c();
        p.Name = 'Test Project';
        p.Project_Logo__c = 'Test image';
        insert p;
        
        Lead__c l2 = new Lead__c(First_Name__c = 'Test', Last_Name__c = 'Lead 2', Lead_Stage__c = 'Incoming', Mobile__c = '1122334499', Email__c = 'lead9@test.in', Alternate_Email__c = 'lead0@test.in', Project__c = p.Id);
         insert l2;
        
        Visit_Pre_Registration__c vpr = new Visit_Pre_Registration__c();
        vpr.Customer_Name__c = 'Test Customer';
        vpr.Mobile_Number__c = '1234567890';
        vpr.Lead__c = l2.Id;
        vpr.Project__c = p.Id;
        //vpr.Pre_Registration_OTP__c = '123456';
        vpr.Extend_Validity_In_Hours__c = 48;
        vpr.Pre_Registration_Expiry__c = System.now(); 
        insert vpr;
        List<Visit_Pre_Registration__c> vprList = new List<Visit_Pre_Registration__c>();
        vprList.add(vpr);
        Map<Id,Visit_Pre_Registration__c> newVprMap = new Map<Id,Visit_Pre_Registration__c>();
        newVprMap.put(vpr.id,vpr);
        
      /*  Test.startTest();
         Ex_VisitPreRegistrationHandler.beforeInsert(vprList);
         Ex_VisitPreRegistrationHandler.beforeUpdate(newVprMap, newVprMap);
         Ex_VisitPreRegistrationHandlerServices.createVPRLead(vprList);
         Ex_VisitPreRegistrationHandlerServices.updateVpr(vprList);
        Test.stopTest();*/
        
    }
}