force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account)</relationshipLabel>
    <relationshipName>Leads2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/IsConverted__c.field-meta.xml
<CustomField>
    <fullName>IsConverted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</description>
    <inlineHelpText>This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.This field is automatically checked when the Lead is successfully converted into an Account and Opportunity.</inlineHelpText>
    <label>IsConverted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Source__c</fullName>
    <label>Lead Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lead_Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Walkin_Source__c.field-meta.xml
<CustomField>
    <fullName>Walkin_Source__c</fullName>
    <label>Walkin Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Lead_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Walkin_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Walkin_Sub_Source__c</fullName>
    <label>Walkin Sub-Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Walkin_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Lead_Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Assignment_TAT__c.field-meta.xml
<CustomField>
    <fullName>Assignment_TAT__c</fullName>
    <defaultValue>30</defaultValue>
    <label>Assignment TAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Source_TAT__c.field-meta.xml
<CustomField>
    <fullName>Source_TAT__c</fullName>
    <description>This field represents the Turnaround Time (TAT) for a project, which is used in calculating the validity date of associated opportunities to The Project</description>
    <inlineHelpText>This field represents the Turnaround Time (TAT) for a project, which is used in calculating the validity date of associated opportunities to the Project</inlineHelpText>
    <label>Source TAT</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Lead_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Google</fullName>
    </customValue>
    <customValue>
        <fullName>Facebook</fullName>
    </customValue>
    <customValue>
        <fullName>Aggregators</fullName>
    </customValue>
    <customValue>
        <fullName>Organic</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>Television</fullName>
    </customValue>
    <customValue>
        <fullName>Hoarding</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>WhatsApp</fullName>
    </customValue>
    <customValue>
        <fullName>Events</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Direct</fullName>
    </customValue>
    <customValue>
        <fullName>Reference</fullName>
    </customValue>
    <customValue>
        <fullName>VDNB</fullName>
    </customValue>
    <customValue>
        <fullName>Cold Calling</fullName>
    </customValue>
    <customValue>
        <fullName>Start Connect</fullName>
    </customValue>
    <masterLabel>Lead Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Lead_Sub_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Google Search</fullName>
    </customValue>
    <customValue>
        <fullName>Google Display</fullName>
    </customValue>
    <customValue>
        <fullName>YouTube</fullName>
    </customValue>
    <customValue>
        <fullName>Discovery Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Gen Form</fullName>
    </customValue>
    <customValue>
        <fullName>Instagram</fullName>
    </customValue>
    <customValue>
        <fullName>Web Conversion</fullName>
    </customValue>
    <customValue>
        <fullName>MagicBricks</fullName>
    </customValue>
    <customValue>
        <fullName>NoBroker</fullName>
    </customValue>
    <customValue>
        <fullName>Housing</fullName>
    </customValue>
    <customValue>
        <fullName>99Acres</fullName>
    </customValue>
    <customValue>
        <fullName>Corporate Website</fullName>
    </customValue>
    <customValue>
        <fullName>ORM</fullName>
    </customValue>
    <customValue>
        <fullName>Jacket</fullName>
    </customValue>
    <customValue>
        <fullName>Power Jacket</fullName>
    </customValue>
    <customValue>
        <fullName>Full Page</fullName>
    </customValue>
    <customValue>
        <fullName>Half Page</fullName>
    </customValue>
    <customValue>
        <fullName>Inserts</fullName>
    </customValue>
    <customValue>
        <fullName>RJ Mentions</fullName>
    </customValue>
    <customValue>
        <fullName>Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Advertisement</fullName>
    </customValue>
    <customValue>
        <fullName>Show Sponsorship</fullName>
    </customValue>
    <customValue>
        <fullName>Billboard</fullName>
    </customValue>
    <customValue>
        <fullName>Bus Shelter</fullName>
    </customValue>
    <customValue>
        <fullName>Kiosk</fullName>
    </customValue>
    <customValue>
        <fullName>Cantilever</fullName>
    </customValue>
    <customValue>
        <fullName>Gantry</fullName>
    </customValue>
    <customValue>
        <fullName>Mobile Van</fullName>
    </customValue>
    <customValue>
        <fullName>Bus Panel</fullName>
    </customValue>
    <customValue>
        <fullName>Railway Station Boards</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
    </customValue>
    <masterLabel>Lead Sub Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestEx_LeadConversionServices.cls
@isTest
public class TestEx_LeadConversionServices {
	
    @isTest
    public static void testconvertLead(){
        
        Project__c p = new Project__c();
        p.Name = 'Project 1';
        p.Source_TAT__c = 45;
        p.Assignment_TAT__c = 60;
		insert p;        
        
        // Create an Account record
        Account acc = new Account();
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        acc.FirstName = 'John';
        acc.LastName = 'Doe';
        acc.Phone = '9999888801';
        insert acc;
        
        List<Lead__c> ldList = new List<Lead__c>();
        
        Lead__c ld1 = new Lead__c();
        ld1.Mobile__c = '9999888801';
        ld1.Email__c = 'nineeight1@gmail.com';
        ld1.Lead_Source__c = 'Google';
        ld1.Lead_Sub_Source__c = 'Google Search';
        ld1.Project__c = p.Id;
        ld1.First_Name__c = 'First Name';
        ld1.Last_Name__c = 'Last name';
        ld1.OwnerId = UserInfo.getUserId();
        ld1.IsConverted__c = true;
        ld1.Account__c = acc.Id; 
        
        Lead__c ld2 = new Lead__c();
        ld2.Mobile__c = '9999888801';
        ld2.Email__c = 'nineeight1@gmail.com';
        ld2.Lead_Source__c = 'Google';
        ld2.Lead_Sub_Source__c = 'Google Search';
        ld2.Project__c = p.Id;
        ld2.Last_Name__c = 'Last name';
        ld2.OwnerId = UserInfo.getUserId();
        ld2.IsConverted__c = true;
        ld2.Account__c = acc.Id;
        
        Lead__c ld3 = new Lead__c();
        ld3.Mobile__c = '9999888801';
        ld3.Email__c = 'nineeight1@gmail.com';
        ld3.Lead_Source__c = 'Channel Partner';
        ld3.Lead_Sub_Source__c = 'Channel Partner';
        ld3.Walkin_Source__c = 'Channel Partner';
        ld3.Walkin_Sub_Source__c = 'Channel Partner';
        ld3.Project__c = p.Id;
        ld3.Last_Name__c = 'Last name';
        ld3.OwnerId = UserInfo.getUserId();
        ld3.IsConverted__c = true;
        ld3.Account__c = acc.Id;
        
        ldList.add(ld1);
        ldList.add(ld2);
        ldList.add(ld3);
        
        insert ldList;
        
        List<Task> taskList = new List<Task>();
    
        Id presalesCallRTId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Presales_Call' AND SObjectType = 'Task' LIMIT 1].Id;

        Task task1 = new Task();
        task1.Subject = 'Follow Up';
        task1.Next_Follow_Up_Date__c = System.today()+3;
        task1.WhatId = ld1.Id; 
        task1.RecordTypeId = presalesCallRTId;
        insert task1;
                
        Test.startTest();
        Ex_LeadConversionServices.convertLead(ldList);
        Map<Id, List<Task>> resultMap = Ex_LeadConversionServices.getLeadTaskMap(ldList);
        Test.stopTest();
    }

	@isTest
    public static void testconvertLead2(){
        
        Project__c p = new Project__c();
        p.Name = 'Project 1';
        p.Source_TAT__c = 45;
        p.Assignment_TAT__c = 60;
		insert p;        
        
        List<Lead__c> ldList = new List<Lead__c>();
        
        Lead__c ld1 = new Lead__c();
        ld1.Mobile__c = '9999888801';
        ld1.Email__c = 'nineeight1@gmail.com';
        ld1.Lead_Source__c = 'Google';
        ld1.Lead_Sub_Source__c = 'Google Search';
        ld1.Project__c = p.Id;
        ld1.First_Name__c = 'First Name';
        ld1.Last_Name__c = 'Last name';
        ld1.OwnerId = UserInfo.getUserId();
        ld1.IsConverted__c = true; 
        
        Lead__c ld2 = new Lead__c();
        ld2.Mobile__c = '9999888801';
        ld2.Email__c = 'nineeight1@gmail.com';
        ld2.Lead_Source__c = 'Google';
        ld2.Lead_Sub_Source__c = 'Google Search';
        ld2.Project__c = p.Id;
        ld2.Last_Name__c = 'Last name';
        ld2.OwnerId = UserInfo.getUserId();
        ld2.IsConverted__c = true;
        
        Lead__c ld3 = new Lead__c();
        ld3.Mobile__c = '9999888801';
        ld3.Email__c = 'nineeight1@gmail.com';
        ld3.Lead_Source__c = 'Channel Partner';
        ld3.Lead_Sub_Source__c = 'Channel Partner';
        ld3.Walkin_Source__c = 'Channel Partner';
        ld3.Walkin_Sub_Source__c = 'Channel Partner';
        ld3.Project__c = p.Id;
        ld3.Last_Name__c = 'Last name';
        ld3.OwnerId = UserInfo.getUserId();
        ld3.IsConverted__c = true;
        
        ldList.add(ld1);
        ldList.add(ld2);
        ldList.add(ld3);
        
        insert ldList;
        
        List<Task> taskList = new List<Task>();

        Id presalesCallRTId = [SELECT Id FROM RecordType WHERE DeveloperName = 'Presales_Call' AND SObjectType = 'Task' LIMIT 1].Id;

        Task task1 = new Task();
        task1.Subject = 'Follow Up';
        task1.Next_Follow_Up_Date__c = System.today()+2;
        task1.WhatId = ld1.Id; 
        task1.RecordTypeId = presalesCallRTId; 
        insert task1;
                
        Test.startTest();
        Ex_LeadConversionServices.convertLead(ldList);
        Map<Id, List<Task>> resultMap = Ex_LeadConversionServices.getLeadTaskMap(ldList);
        Test.stopTest();
    }
}