force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>Lead ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account)</relationshipLabel>
    <relationshipName>Leads2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Master_Source__c.field-meta.xml
<CustomField>
    <fullName>Master_Source__c</fullName>
    <businessOwnerUser>umaid.shaikh@nandivardhan.com</businessOwnerUser>
    <label>Master Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Master_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Leads (Opportunity)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incoming</fullName>
                <default>true</default>
                <label>Incoming</label>
            </value>
            <value>
                <fullName>SNP</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Visit Confirmed</fullName>
            </value>
            <value>
                <fullName>Visit Done</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub-Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Not Answering</fullName>
            </value>
            <value>
                <fullName>SNP</fullName>
            </value>
            <value>
                <fullName>In Follow-up (Cold)</fullName>
            </value>
            <value>
                <fullName>In Follow-up (Warm)</fullName>
            </value>
            <value>
                <fullName>Visit proposed (Hot)</fullName>
            </value>
            <value>
                <fullName>Visit confirmed</fullName>
            </value>
            <value>
                <fullName>Visit Done</fullName>
            </value>
            <value>
                <fullName>Budget does not match</fullName>
            </value>
            <value>
                <fullName>Location mismatch</fullName>
            </value>
            <value>
                <fullName>Area/Configuration Mismatch</fullName>
            </value>
            <value>
                <fullName>Possession does not match</fullName>
            </value>
            <value>
                <fullName>Booked with someone else</fullName>
            </value>
            <value>
                <fullName>Not answering / responding</fullName>
            </value>
            <value>
                <fullName>General Enquiry</fullName>
            </value>
            <value>
                <fullName>Residential Property Enquiry</fullName>
            </value>
            <value>
                <fullName>DND</fullName>
            </value>
            <value>
                <fullName>Commercial Property Enquiry</fullName>
            </value>
            <value>
                <fullName>Junk</fullName>
            </value>
            <value>
                <fullName>Loan Issues</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Substage_Reason__c.field-meta.xml
<CustomField>
    <fullName>Substage_Reason__c</fullName>
    <label>Substage Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Stage__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Switched Off, Not Reachable, Not Answering</fullName>
            </value>
            <value>
                <fullName>Looking for Smaller configuration/area</fullName>
            </value>
            <value>
                <fullName>Looking for bigger configuration/area</fullName>
            </value>
            <value>
                <fullName>Looking for RTMI</fullName>
            </value>
            <value>
                <fullName>Looking for early possession</fullName>
            </value>
            <value>
                <fullName>After Pitched</fullName>
            </value>
            <value>
                <fullName>Before Pitched</fullName>
            </value>
            <value>
                <fullName>Invalid customer contact number</fullName>
            </value>
            <value>
                <fullName>Invalid Enquiry</fullName>
            </value>
            <value>
                <fullName>Test Enquiry</fullName>
            </value>
            <value>
                <fullName>False Enquiry</fullName>
            </value>
            <value>
                <fullName>Not looking for the property</fullName>
            </value>
            <value>
                <fullName>Abusive Clients</fullName>
            </value>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Booked Customers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <formula>Account__r.Alternate_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Alternate_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email_Id__c</fullName>
    <formula>Account__r.Alternate_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Alternate Email Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <formula>Account__r.PersonContact.Email</formula>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <formula>IF(ISPICKVAL(Stage__c , &quot;In Follow-up&quot;), True,  False)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Master_Source__c.field-meta.xml
<CustomField>
    <fullName>Master_Source__c</fullName>
    <label>Master Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Master_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <formula>Account__r.PersonContact.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mobile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>In Follow-up</fullName>
                <default>true</default>
                <label>In Follow-up</label>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Booking In-Process</fullName>
            </value>
            <value>
                <fullName>Booking Cancelled</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Sub_source__c.field-meta.xml
<CustomField>
    <fullName>Sub_Source__c</fullName>
    <label>Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_Source</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Sub_Source_Details__c.field-meta.xml
<CustomField>
    <fullName>Sub_Source_Details__c</fullName>
    <label>Sub-Source Details</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Sub_Source_Details</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub-Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Warm</fullName>
            </value>
            <value>
                <fullName>Cold</fullName>
            </value>
            <value>
                <fullName>Spot Booking</fullName>
            </value>
            <value>
                <fullName>Normal Booking</fullName>
            </value>
            <value>
                <fullName>Before Registration</fullName>
            </value>
            <value>
                <fullName>After Registration</fullName>
            </value>
            <value>
                <fullName>Did not like layout of the flat</fullName>
            </value>
            <value>
                <fullName>Location Mismatch</fullName>
            </value>
            <value>
                <fullName>Booked in other project</fullName>
            </value>
            <value>
                <fullName>Booked in resale</fullName>
            </value>
            <value>
                <fullName>Plan to buy home is Postponed / cancelled</fullName>
            </value>
            <value>
                <fullName>Not Answering. Pre-sales to follow-up</fullName>
            </value>
            <value>
                <fullName>Not Vastu compliant</fullName>
            </value>
            <value>
                <fullName>Budget does not match</fullName>
            </value>
            <value>
                <fullName>Area/Configuration Mismatch</fullName>
            </value>
            <value>
                <fullName>Possession does not match</fullName>
            </value>
            <value>
                <fullName>General Enquiry</fullName>
            </value>
            <value>
                <fullName>Loan Issues</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Negotiation</fullName>
            </value>
            <value>
                <fullName>Choice of Unit</fullName>
            </value>
            <value>
                <fullName>Conditional sale</fullName>
            </value>
            <value>
                <fullName>Residential Property Enquiry</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Master_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Direct Walk In</fullName>
    </customValue>
    <customValue>
        <fullName>Digital</fullName>
    </customValue>
    <customValue>
        <fullName>Recommended by Friends/Relatives</fullName>
    </customValue>
    <customValue>
        <fullName>Hoardings</fullName>
    </customValue>
    <customValue>
        <fullName>Newspaper</fullName>
    </customValue>
    <customValue>
        <fullName>Radio</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Exhibition</fullName>
    </customValue>
    <customValue>
        <fullName>Television</fullName>
    </customValue>
    <customValue>
        <fullName>Emailers</fullName>
    </customValue>
    <customValue>
        <fullName>Movie Theater</fullName>
    </customValue>
    <customValue>
        <fullName>Events</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Management Reference</fullName>
    </customValue>
    <customValue>
        <fullName>Referral and Loyalty Programme</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Channel Partner</fullName>
        <isActive>false</isActive>
        <label>Channel Partner</label>
    </customValue>
    <masterLabel>Master Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sub_Source.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Mindicator</fullName>
    </customValue>
    <customValue>
        <fullName>Timesjob</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Whatsapp</fullName>
    </customValue>
    <customValue>
        <fullName>Call Verified</fullName>
    </customValue>
    <customValue>
        <fullName>One Native</fullName>
    </customValue>
    <customValue>
        <fullName>Taboola</fullName>
    </customValue>
    <customValue>
        <fullName>Times Colombia</fullName>
    </customValue>
    <customValue>
        <fullName>Yahoo Native</fullName>
    </customValue>
    <customValue>
        <fullName>Quikr</fullName>
    </customValue>
    <customValue>
        <fullName>99Acres</fullName>
    </customValue>
    <customValue>
        <fullName>Housing</fullName>
    </customValue>
    <customValue>
        <fullName>Magicbricks</fullName>
    </customValue>
    <customValue>
        <fullName>NoBroker</fullName>
    </customValue>
    <customValue>
        <fullName>Google Search</fullName>
    </customValue>
    <customValue>
        <fullName>Google Display</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube LG</fullName>
    </customValue>
    <customValue>
        <fullName>Youtube Bumper Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Discovery Ads</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Gen</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Gen Insta</fullName>
    </customValue>
    <customValue>
        <fullName>Web Conversion</fullName>
    </customValue>
    <customValue>
        <fullName>Lead Generation</fullName>
    </customValue>
    <customValue>
        <fullName>InMail</fullName>
    </customValue>
    <customValue>
        <fullName>Chat</fullName>
    </customValue>
    <customValue>
        <fullName>Website</fullName>
    </customValue>
    <customValue>
        <fullName>ORM</fullName>
    </customValue>
    <customValue>
        <fullName>Social Media</fullName>
    </customValue>
    <customValue>
        <fullName>User</fullName>
    </customValue>
    <masterLabel>Sub-Source</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sub_Source_Details.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Mindicator Exit</fullName>
    </customValue>
    <customValue>
        <fullName>Mindicator Push</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>SMS</fullName>
    </customValue>
    <customValue>
        <fullName>Whatsapp</fullName>
    </customValue>
    <customValue>
        <fullName>Native</fullName>
    </customValue>
    <customValue>
        <fullName>Polyvalent</fullName>
    </customValue>
    <customValue>
        <fullName>Adcounty</fullName>
    </customValue>
    <customValue>
        <fullName>Brandex</fullName>
    </customValue>
    <customValue>
        <fullName>PivotRoots</fullName>
    </customValue>
    <customValue>
        <fullName>FirstEconomy</fullName>
    </customValue>
    <customValue>
        <fullName>OLX</fullName>
    </customValue>
    <customValue>
        <fullName>No Broker</fullName>
    </customValue>
    <customValue>
        <fullName>One Native</fullName>
    </customValue>
    <customValue>
        <fullName>Taboola</fullName>
    </customValue>
    <customValue>
        <fullName>Times Colombia</fullName>
    </customValue>
    <customValue>
        <fullName>Yahoo Native</fullName>
    </customValue>
    <customValue>
        <fullName>Call Verified Leads</fullName>
    </customValue>
    <customValue>
        <fullName>99Acres</fullName>
    </customValue>
    <customValue>
        <fullName>Housing</fullName>
    </customValue>
    <customValue>
        <fullName>Magicbricks</fullName>
    </customValue>
    <customValue>
        <fullName>NoBroker</fullName>
    </customValue>
    <customValue>
        <fullName>Brand</fullName>
    </customValue>
    <customValue>
        <fullName>Offer Specific</fullName>
    </customValue>
    <customValue>
        <fullName>Generic</fullName>
    </customValue>
    <customValue>
        <fullName>Competition</fullName>
    </customValue>
    <customValue>
        <fullName>SDC</fullName>
    </customValue>
    <customValue>
        <fullName>GDN-Intent</fullName>
    </customValue>
    <customValue>
        <fullName>GDN-Inmarket</fullName>
    </customValue>
    <customValue>
        <fullName>GDN-Affinity</fullName>
    </customValue>
    <masterLabel>Sub-Source Details</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SearchPageController.cls
//-------------------------------------------//
//  Project: Nandi Vardhan Constructioin 
//  Created By: Exceller Consultancy
//  Created Date: 17-5-2023
//-------------------------------------------//
public class SearchPageController {
    public String strProjectId {get;set;}
    public List<SelectOption> lstProjectList {get;set;}
    public Lead__c l {get;set;}
    public List<Account> accList {get;set;}
    public List<Opportunity__c> oppList {get;set;}
    public List<Lead__c> leadList {get;set;}
    public boolean isAccount {get;set;}
    public boolean isLead {get;set;}
    public boolean isOpp {get;set;}
    public boolean isSearch {get;set;}
    public string QRProject {get;set;}
    public boolean flagQR {get;set;}
    
    public SearchPageController() {
        strProjectId = '';
        flagQR = false;
        l = new Lead__c();
        lstProjectList = new List<SelectOption >();
        QRProject = ApexPages.currentPage().getParameters().get('project');
        system.debug('project: '+ QRProject);
        List <Project__c> listPr = new List <Project__c>();
        List <User> listUr = [Select Id, Name/*Project_Name__c*/ from User where ID =: userInfo.getUserId()];
        if(QRProject != '' && QRProject != null)
        {
            listPr = [Select Id, Name from Project__c Where Id =: QRProject];
            flagQR = true;
        }
        else
        	listPr = [Select Id, Name from Project__c /*Where Name =:listUr[0].Project_Name__c*/];
        System.debug('Project ::' + listPr);
     	lstProjectList.add(new SelectOption('', '---Please Select Project---'));
        if (listPr != null && listPr.size() > 0) {
            for (Project__c Pr: listPr) {
                lstProjectList.add(new SelectOption(Pr.id, pr.name));
            }
        }         
        accList = new List<Account>();
        oppList = new List<Opportunity__c>();
        leadList = new List<Lead__c>();
        isSearch = false;
        isAccount = false;
        isLead = false;
        isOpp = false; 
    }
    
    public void search() {
        isAccount = false;
        isLead = false;
        isOpp = false; 
    
        if(l.Mobile__c != Null && l.Mobile__c != '') {
            accList = [Select Id, Name, PersonMobilePhone, Phone, PersonEmail, Alternate_Email__c, Owner.Name from Account 
                       where (PersonMobilePhone =: l.Mobile__c OR Phone =: l.Mobile__c) AND IsPersonAccount = true];
            system.debug('accList: '+accList);
            
            if(!accList.isEmpty()) {
                isAccount = true;
                
                oppList = [Select Id, Name, Project__c, Project__r.Name, Account__r.PersonMobilePhone, Account__r.PersonEmail, Owner.Name from Opportunity__c
                           where Account__c =: accList[0].Id AND Project__c =: strProjectId AND Is_Active__c = true];
                system.debug('oppList: '+oppList);
                
                if(!oppList.isEmpty()) {
                    isOpp = true;
                }
            } else {
                if(l.Email__c != Null && l.Email__c != '') {
                    accList = [Select Id, Name, PersonMobilePhone, Phone, PersonEmail, Alternate_Email__c, Owner.Name from Account 
                               where (PersonEmail =: l.Email__c OR Alternate_Email__c =: l.Email__c) AND IsPersonAccount = true];
                    system.debug('accList: '+accList);
                    
                    if(!accList.isEmpty()) {
                        isAccount = true;
                
                        oppList = [Select Id, Name, Project__c, Project__r.Name, Account__r.PersonMobilePhone, Account__r.PersonEmail, Owner.Name from Opportunity__c
                                   where Account__c =: accList[0].Id AND Project__c =: strProjectId AND Is_Active__c = true];
                        system.debug('oppList: '+oppList);
                        
                        if(!oppList.isEmpty()) {
                            isOpp = true;
                        }
                    }
                } 
            }
            
            if(oppList.isEmpty()) {
                leadList = [Select Id, Name, Mobile__c, Phone__c,Salutation__c, Email__c, Alternate_Email_Id__c, Project__c, Project__r.Name,Stage__c, Sub_Stage__c, Substage_Reason__c,
                                    Master_Source__c, Sub_Source__c, Sub_Source_Details__c, Lead_Source__c, Owner.Name from Lead__c
                            where (Mobile__c =: l.Mobile__c OR Phone__c =: l.Mobile__c) AND Project__c =: strProjectId AND IsConverted__c = false];
                system.debug('leadList: '+leadList);
                
                if(!leadList.isEmpty()) {
                    isLead = true;
                } else {
                    if(l.Email__c != Null && l.Email__c != '') {
                        leadList = [Select Id, Name, Mobile__c, Phone__c,Salutation__c, Email__c, Alternate_Email_Id__c, Project__c, Project__r.Name,Stage__c, Sub_Stage__c, Substage_Reason__c,
                                    Master_Source__c, Sub_Source__c, Sub_Source_Details__c, Lead_Source__c, Owner.Name from Lead__c
                                    where (Email__c =: l.Email__c OR Alternate_Email_Id__c =: l.Email__c) AND Project__c =: strProjectId AND IsConverted__c = false];
                        system.debug('leadList: '+leadList);
                        
                        if(!leadList.isEmpty()) {
                            isLead = true;
                        }
                    }
                }
            }
        }
        isSearch = true;
    }
    
    public PageReference continueMethod() {
        if(l.Email__c == Null) {
            l.Email__c = '';
        }
        Pagereference objReference = new Pagereference('/apex/SiteVisitForm?project=' + strProjectId +'&mobile='+l.Mobile__c+ '&email='+l.Email__c+'&QR='+flagQR);
        objReference.setRedirect(true);
        return objReference;
    }
    
    public PageReference cancel() {
        Pagereference objReference = new Pagereference('/lightning/page/home');
        objReference.setRedirect(true);
        return objReference;
    }
}