force-app/main/default/objects/Car_Park__c/Car_Park__c.object-meta.xml
<CustomObject>
    <label>Car Park</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Car Park Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Car Park</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car_Park__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <label>Floor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>UG 1</fullName>
            </value>
            <value>
                <fullName>UG 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Car_Park__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Car Park</relationshipLabel>
    <relationshipName>Car_Park</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car_Park__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Podium Parking</fullName>
            </value>
            <value>
                <fullName>Open Parking</fullName>
            </value>
            <value>
                <fullName>Stack Upper Parking</fullName>
            </value>
            <value>
                <fullName>Stack Lower Parking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Charge_Details__c/Charge_Details__c.object-meta.xml
<CustomObject>
    <label>Charge Details</label>
    <nameField>
        <label>Charge Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Charge Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge_Details__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Charge Details</relationshipLabel>
    <relationshipName>Charge_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/Payment_Milestone__c.object-meta.xml
<CustomObject>
    <label>Payment Milestone</label>
    <nameField>
        <displayFormat>PM-{0000}</displayFormat>
        <label>Payment Milestone Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Milestone</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Milestone__c/fields/Charge_Bucket_1__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_1__c</fullName>
    <label>Charge Bucket 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agreement Value</fullName>
            </value>
            <value>
                <fullName>Other Charges</fullName>
            </value>
            <value>
                <fullName>Statutory Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Charge_Bucket_1_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_1_Percentage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Bucket 1 Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Charge_Bucket_1_Total_Tax__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_1_Total_Tax__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Bucket 1 Total Tax</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Charge_Bucket_2_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_2_Percentage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Bucket 2 Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Charge_Bucket_4_Amount__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_4_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Bucket 4 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Charge_Bucket_4_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_4_Percentage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Bucket 4 Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Charge_Bucket_5_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_5_Percentage__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Bucket 5 Percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Payment Milestone</relationshipLabel>
    <relationshipName>Payment_Milestone</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Milestone__c/fields/Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Sequence_No__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Sequence No</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Charge_Bucket_1_Total_Tax__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_1_Total_Tax__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Bucket 1 Total Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Charge_Bucket_2__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_2__c</fullName>
    <label>Charge Bucket 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agreement Value</fullName>
            </value>
            <value>
                <fullName>Other Charges</fullName>
            </value>
            <value>
                <fullName>Statutory Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Charge_Bucket_2_Amount__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_2_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Bucket 2 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Charge_Bucket_2_Total_Tax__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_2_Total_Tax__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Bucket 2 Total Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Charge_Bucket_3__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_3__c</fullName>
    <label>Charge Bucket 3</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agreement Value</fullName>
            </value>
            <value>
                <fullName>Other Charges</fullName>
            </value>
            <value>
                <fullName>Statutory Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Charge_Bucket_3_Amount__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_3_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Bucket 3 Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Charge_Bucket_3_Total_Tax__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_3_Total_Tax__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Bucket 3 Total Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Charge_Bucket_4__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_4__c</fullName>
    <label>Charge Bucket 4</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Agreement Value</fullName>
            </value>
            <value>
                <fullName>Other Charges</fullName>
            </value>
            <value>
                <fullName>Statutory Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Charge_Bucket_4_Total_Tax__c.field-meta.xml
<CustomField>
    <fullName>Charge_Bucket_4_Total_Tax__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge Bucket 4 Total Tax</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotation</relationshipLabel>
    <relationshipName>Quotation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tower</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Unit</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Configuration_Type__c.field-meta.xml
<CustomField>
    <fullName>Configuration_Type__c</fullName>
    <label>Configuration Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Configuration_Required</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Floor__c.field-meta.xml
<CustomField>
    <fullName>Floor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Floor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/RERA_Carpet_Area_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>RERA_Carpet_Area_Sq_Ft__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RERA Carpet Area (Sq. Ft.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/RERA_Carpet_Area_Sq_Mtr__c.field-meta.xml
<CustomField>
    <fullName>RERA_Carpet_Area_Sq_Mtr__c</fullName>
    <defaultValue>0</defaultValue>
    <label>RERA Carpet Area (Sq. Mtr.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Unit</relationshipLabel>
    <relationshipName>Unit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Configuration_Required.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>1.5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>4 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>5 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Villa</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 1 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 2 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Jodi 3 BHK</fullName>
    </customValue>
    <customValue>
        <fullName>Shop</fullName>
    </customValue>
    <customValue>
        <fullName>Office</fullName>
    </customValue>
    <masterLabel>Configuration Required</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Ex_PrintQuotationController.cls
public class Ex_PrintQuotationController {
    public string qId{get;set;}
    public Quotation__c q{get;set;}
    public List<Quotation__c> qList {get;set;}
    public List<Car_Park__c> carList{get;set;}
    public List<Unit__c> uList{get;set;}
    public List<Charge_Details__c> cdList{get;set;}
    public Map<String, String> flatDetails {get;set;}
    public Map<String, String> considerationAmount {get;set;}
    public Map<String, String> societyCharges {get;set;}
    public Map<String, String> nonAccountableCharges {get;set;}
    public List<Map<String, String>> paymentSchedule {get;set;}
    public Map<String, String> paymentScheduleTotal {get;set;}
    public Map<String, String> flatCostBankingDetails {get;set;}
    public Map<String, String> gstCostBankingDetails {get;set;}
    public String createdDate {get;set;}
    public Decimal totalSDRCharges {get;set;}
    public String totalSDRChargesFormatted {get;set;}
    public Decimal totalOtherCharges {get;set;}
    public String totalOtherChargesFormatted {get;set;}
    public Decimal totalAgreementValue {get;set;}
    public String totalAgreementValueFormatted {get;set;}
    public Decimal grandTotal {get;set;}
    public String grandTotalFormatted {get;set;}
    public Quotation__c quotation {get; set;}
    
    public Ex_PrintQuotationController(){
        qId=ApexPages.currentPage().getParameters().get('qId');
        q=new Quotation__c();
        qList = new List<Quotation__c>();
        carList = new List<Car_Park__c>();
        uList = new List<Unit__c>();
        cdList = new List<Charge_Details__c>();
        flatDetails = new Map<String,String>();
        considerationAmount = new Map<String,String>();
        societyCharges = new Map<String,String>();
        nonAccountableCharges = new Map<String,String>();
        paymentSchedule = new List<Map<String,String>>();
        flatCostBankingDetails = new Map<String,String>();
        gstCostBankingDetails = new Map<String,String>();
        paymentScheduleTotal = new Map<String, String>();
        totalSDRCharges = 0;
        totalSDRChargesFormatted = '';
        totalOtherCharges = 0;
        totalOtherChargesFormatted = '';
        totalAgreementValue = 0;
        totalAgreementValueFormatted = '';
        grandTotal = 0;
        grandTotalFormatted = '';
        
        List<Quotation__c> quotationList = new List<Quotation__c>();
        quotation = new Quotation__c();
        List<Payment_Milestone__c> paymentMilestoneList = new List<Payment_Milestone__c>();
        
        if (qId != null) {
            quotationList = [SELECT Id, Name, CreatedDate, Car_Park_Required_Count__c, Project__r.Quotation_Terms_and_Conditions__c,
                             Unit__c, Unit__r.Floor__c, Unit__r.Configuration_Type__c, Unit__r.RERA_Carpet_Area_Sq_Ft__c, Unit__r.RERA_Carpet_Area_Sq_Mtr__c,
                             Project__c, Project__r.Project_Logo__c
                             FROM Quotation__c WHERE Id = :qId
                            ];
            if (quotationList != null && !quotationList.isEmpty()) {
                quotation = quotationList[0];
                createdDate = String.valueOf(quotation.CreatedDate.format('dd/MM/yyyy'));
                flatDetails.put('Car_Park_Required_Count__c', quotation.Car_Park_Required_Count__c != null ? String.valueOf(quotation.Car_Park_Required_Count__c) : ' ');
                flatDetails.put('Quotation_Terms_and_Conditions__c', quotation.Project__r.Quotation_Terms_and_Conditions__c != null ? String.valueOf(quotation.Project__r.Quotation_Terms_and_Conditions__c) : ' ');

                
                paymentMilestoneList = [SELECT Id, Name, Sequence_No__c, Quotation__c, Milestone_Name__c, Due_Date__c,
                                        Charge_Bucket_1__c, Charge_Bucket_1_Percentage__c, Charge_Bucket_1_Amount__c, Charge_Bucket_1_Total_Tax__c,
                                        Charge_Bucket_2__c, Charge_Bucket_2_Percentage__c, Charge_Bucket_2_Amount__c, Charge_Bucket_2_Total_Tax__c,
                                        Charge_Bucket_3__c, Charge_Bucket_3_Percentage__c, Charge_Bucket_3_Amount__c, Charge_Bucket_3_Total_Tax__c,
                                        Charge_Bucket_4__c, Charge_Bucket_4_Percentage__c, Charge_Bucket_4_Amount__c, Charge_Bucket_4_Total_Tax__c,
                                        Charge_Bucket_5__c, Charge_Bucket_5_Percentage__c, Charge_Bucket_5_Amount__c, Charge_Bucket_5_Total_Tax__c
                                        FROM Payment_Milestone__c WHERE Quotation__c = : qId 
                                        ORDER BY Sequence_No__c ASC ];
                
                
                Decimal totalChargeBucketPercentage = 0;
                Decimal totalChargeBucketAmount = 0;
                Decimal totalChargeBucketTotalTax = 0;
                Decimal totalChargeBucketTotal = 0;
                Decimal totalChargeBucketTDS = 0;
                
                for(Payment_Milestone__c paymentMilestone : paymentMilestoneList){
                    Map<String, String> currPaymentMilestone = new Map<String, String>();
                    
                    currPaymentMilestone.put('Sequence_No__c', paymentMilestone.Sequence_No__c != null ? String.valueOf(paymentMilestone.Sequence_No__c) : ' ');
                    currPaymentMilestone.put('Milestone_Name__c', paymentMilestone.Milestone_Name__c != null ? String.valueOf(paymentMilestone.Milestone_Name__c) : ' ');
                    //currPaymentMilestone.put('TDS_Amount__c',  paymentMilestone.TDS_Amount__c != null ? String.valueOf(currencyFormat(paymentMilestone.TDS_Amount__c)): ' ');
                    currPaymentMilestone.put('Due_Date__c',  paymentMilestone.Due_Date__c != null ? paymentMilestone.Due_Date__c.format(): ' ');
                    currPaymentMilestone.put('Total_Tax__c', ' ');
                    currPaymentMilestone.put('Percentage__c', ' ');
                    currPaymentMilestone.put('Amount__c', ' ');
                    currPaymentMilestone.put('Total', ' ');
                    
                    //totalChargeBucketTDS += (Decimal)paymentMilestone.TDS_Amount__c;
                    
                    for(Integer i=1; i<5; i++){
                        String chargeBucketName = 'Charge_Bucket_' + i + '__c';
                        String chargeBucketPercentage = 'Charge_Bucket_' + i + '_Percentage__c';
                        String chargeBucketAmount = 'Charge_Bucket_' + i + '_Amount__c';
                        String chargeBucketTotalTax = 'Charge_Bucket_' + i + '_Total_Tax__c';
                        
                        if(paymentMilestone.get(chargeBucketName) != null && paymentMilestone.get(chargeBucketName) == 'Agreement Value'){
                            Decimal chargeBucketPercentageValue =  (Decimal)paymentMilestone.get(chargeBucketPercentage);
                            Decimal chargeBucketAmountValue =  (Decimal)paymentMilestone.get(chargeBucketAmount);
                            Decimal chargeBucketTotalTaxValue =  (Decimal)paymentMilestone.get(chargeBucketTotalTax);
                            Decimal chargeBucketTotalValue =  (Decimal)paymentMilestone.get(chargeBucketAmount) + (Decimal)paymentMilestone.get(chargeBucketTotalTax);
                            
                            totalChargeBucketPercentage += chargeBucketPercentageValue;
                            totalChargeBucketAmount += chargeBucketAmountValue;
                            totalChargeBucketTotalTax += chargeBucketTotalTaxValue;
                            totalChargeBucketTotal  += chargeBucketTotalValue;
                            
                            currPaymentMilestone.put('Total_Tax__c', String.valueOf(currencyFormat(chargeBucketTotalTaxValue)));
                            currPaymentMilestone.put('Percentage__c', String.valueOf(currencyFormat(chargeBucketPercentageValue)));
                            currPaymentMilestone.put('Amount__c', String.valueOf(currencyFormat(chargeBucketAmountValue)));
                            currPaymentMilestone.put('Total', String.valueOf(currencyFormat(chargeBucketTotalValue)));
                            break;
                        }
                    }
                    System.debug('currPaymentMilestone : ' + currPaymentMilestone);
                    paymentSchedule.add(currPaymentMilestone);
                    
                }
                
                // A total of all Payment Milestone
                paymentScheduleTotal.put('Milestone_Name', 'Total');
                paymentScheduleTotal.put('Total_Percentage', String.valueOf(currencyFormat(totalChargeBucketPercentage)));
                paymentScheduleTotal.put('Total_TDS', String.valueOf(currencyFormat(totalChargeBucketTDS)));
                paymentScheduleTotal.put('Total_Amount', String.valueOf(currencyFormat(totalChargeBucketAmount)));
                paymentScheduleTotal.put('Total_Tax', String.valueOf(currencyFormat(totalChargeBucketTotalTax)));
                paymentScheduleTotal.put('Total_Total', String.valueOf(currencyFormat(totalChargeBucketTotal)));
            }
            else {
                System.debug('Quotatation list is either null or empty');
            }
        }
        else {
            System.debug('Unable to get Id for selected Quotation');
        }
        
       
        
        if(qId != null){
            qList = [Select Id,CreatedDate,Unit__c, Car_Park_Required_Count__c, Charge_Bucket_1_Amount__c,Charge_Bucket_1__c from Quotation__c where Id=:qId];
            system.debug('qList is::'+qList);
            for(Quotation__c q:qList){
                /*if(q.Charge_Bucket_1__c == 'Agreement Value'){
                    chargeBucket = String.valueOf(q.Charge_Bucket_1_Amount__c);
                }*/
            }
            
            uList = [Select Id,Floor__c, Name, Tower__c, Tower__r.Name, Inventory_Type__c, Configuration_Type__c, Total_carpet_Sq_Ft__c From Unit__c where Id=:qList[0].Unit__c];
            system.debug('uList is::'+uList);
            if (uList != null && !uList.isEmpty()){
                Unit__c unit = uList[0];
                flatDetails.put('Tower__c', unit.Tower__r.Name != null ? String.valueOf(unit.Tower__r.Name) : ' ');
                flatDetails.put('Flat_No__c', unit.Name != null ? String.valueOf(unit.Name) : ' ');
                flatDetails.put('Floor__c', unit.Floor__c != null ? String.valueOf(unit.Floor__c) : ' ');
                flatDetails.put('Type__c', unit.Inventory_Type__c != null ? String.valueOf(unit.Inventory_Type__c) : ' ');
                flatDetails.put('Configuration_Type__c',  unit.Configuration_Type__c != null ? String.valueOf(unit.Configuration_Type__c) : ' ');
                flatDetails.put('Total_carpet_Sq_Ft__c', unit.Total_carpet_Sq_Ft__c != null ? String.valueOf(unit.Total_carpet_Sq_Ft__c) : ' ');
            }
        }
    }
    
    public String currencyFormat(Decimal amt) {
        String formattedAmount = '';
        Decimal tempAmt = amt.setscale(2,RoundingMode.HALF_UP);
        String stringAmt = tempAmt.toPlainString();
        String decimalPart;
        List<String> tempStr = new List<String>();
        if(String.isNotBlank(stringAmt)) {
            tempStr = stringAmt.split('\\.');
            if(tempStr != null && tempStr.size() ==2) {
                decimalPart = tempStr[1];
            }
        }
        formattedAmount = (tempAmt.format().contains('.')?tempAmt.format():(tempAmt.format()+'.'+decimalPart));
        return formattedAmount;
    } 
    
}