force-app/main/default/objects/CP_Document__c/CP_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CP Document</label>
</CustomObject>

force-app/main/default/objects/CP_Document__c/fields/Document_Required__c.field-meta.xml
<CustomField>
    <fullName>Document_Required__c</fullName>
    <label>Document Required</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/CP_Project__c.object-meta.xml
<CustomObject>
    <label>CP Project</label>
    <nameField>
        <displayFormat>CPP-{00000}</displayFormat>
        <label>CP Project No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CP Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CP_Project__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/CP_Account__c.field-meta.xml
<CustomField>
    <fullName>CP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>CP Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CP_Project__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>CP Projects</relationshipLabel>
    <relationshipName>CP_Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Document No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/CP_Account__c.field-meta.xml
<CustomField>
    <fullName>CP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pan Card</fullName>
            </value>
            <value>
                <fullName>GST Registration Certificate</fullName>
            </value>
            <value>
                <fullName>RERA Certificate</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Opportunity</label>
    <nameField>
        <label>Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunity</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>CP Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Channel Partner)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria.
Please select different CP Project</errorMessage>
        <filterItems>
            <field>CP_Project__c.Project__c</field>
            <operation>equals</operation>
            <valueField>$Source.Project__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Site_Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Count__c</fullName>
    <label>Site Visit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Sales_Head__c.field-meta.xml
<CustomField>
    <fullName>Sales_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>SV-{00000}</displayFormat>
        <label>Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Site Visits (Channel Partner)</relationshipLabel>
    <relationshipName>Site_Visits1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/CP_Project__c.field-meta.xml
<CustomField>
    <fullName>CP_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Project</label>
    <referenceTo>CP_Project__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Site Visit</relationshipLabel>
    <relationshipName>Site_Visit</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Site_Visit_Count__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Site Visit Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Site_Visit_Date__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit_Date__c</fullName>
    <label>Site Visit Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team_Member__c/fields/Site_Visit__c.field-meta.xml
<CustomField>
    <fullName>Site_Visit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Visit</label>
    <referenceTo>Site_Visit__c</referenceTo>
    <relationshipLabel>Team Members</relationshipLabel>
    <relationshipName>Team_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/test_Ex_SiteVisitTrigger.cls
@isTest
public class test_Ex_SiteVisitTrigger {
    @isTest
    public static void test_beforeInsert(){
        Test.startTest();
        
        CP_Document__c cp = new CP_Document__c();
        cp.Name = 'Yes';
        cp.Document_Required__c = 'Pan Card';
        insert cp;
        system.debug('cp doc is::'+cp);
        
        Account acc = new Account();
        acc.Name = '360 realtors';
       // acc.Salutation = 'Ms.';
        acc.RecordTypeId = Schema.SObjectType.account.getRecordTypeInfosByName().get('CP Account').getRecordTypeId();
        insert acc;
        system.debug('Account is::'+acc);
        
        Account acc1 = new Account();
        acc1.RecordTypeId = Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        acc1.LastName = '360 realtors';
        acc1.Salutation = 'Ms.';
        insert acc1;
        system.debug('Account is::'+acc1);
        
        Document__c d = new Document__c();
        d.CP_Account__c = acc.Id;
        d.Document_Type__c = cp.Document_Required__c;
        insert d;
        
        Project__c p = new Project__c();
        p.name = 'Test Project';
        p.Sales_Head__c = userInfo.getUserId();
        insert p;
        system.debug('Project is::'+p);
        
        CP_Project__c cpp = new CP_Project__c();
        cpp.CP_Account__c = acc.Id;
        cpp.Project__c = p.Id;
        insert cpp;
        system.debug('cpp is::'+cpp);
        
        Opportunity__c opp = new Opportunity__c();
        opp.Account__c = acc1.Id;
        opp.Project__c = p.Id;
        insert opp;
        
        Site_Visit__c sv = new Site_Visit__c();
        sv.Salutation__c = 'Mr.';
        sv.OwnerId = userInfo.getUserId();
        sv.Project_Name__c = p.Id;
        sv.CP_Project__c = cpp.Id;
        sv.Opportunity__c = opp.Id;
        sv.Sales_Manager__c = userInfo.getUserId();
        sv.Channel_Partner__c = acc.Id;
        sv.Site_Visit_Count__c = 1;
        
        
        Site_Visit__c sv1 = new Site_Visit__c();
        sv1.OwnerId = userInfo.getUserId();
        sv1.Project_Name__c = p.Id;
        sv1.CP_Project__c = cpp.Id;
        sv1.Opportunity__c = opp.Id;
        sv1.Sales_Manager__c = userInfo.getUserId();
        sv1.Site_Visit_Date__c = system.today();
        sv1.Comment__c = 'Test comment';
        sv1.Configuration_Required__c = '2 BHK';
        sv1.Project_Type__c = 'Residential';
        sv1.Budget__c = 'Budget less than 20 lakhs';
        sv1.Buying_Purpose__c = 'Self-Use';
        sv1.Possession_Timeframe_Required__c = 'RTMI (Ready to Move in)';
        sv1.Opportunity_Stage__c = 'In Follow-up';
        sv1.Opportunity_Sub_Stage__c = 'Hot';
        sv1.Opportunity_Sub_Stage_Reason__c = 'All Good Expected Closure';
        sv1.Locality__c = 'Central';
        sv1.Locality_details__c = 'Bhandup';
        sv1.Country__c = 'India';
        sv1.City_Name__c = 'Raigad';
        sv1.City_Type__c = 'Mumbai';
        
        insert sv1;
        
       // sv1.Comment__c = 'test comment 1';
      //  sv1.Salutation__c = 'Mr.';
       // update sv1;
        
        Set<Id> uIdSet = new Set<Id>();
        uIdSet.add(sv1.Sales_Manager__c);
        
        Site_Visit__c sv2 = new Site_Visit__c();
        sv2.OwnerId = userInfo.getUserId();
        sv2.Project_Name__c = p.Id;
        sv2.CP_Project__c = cpp.Id;
        sv2.Opportunity__c = opp.Id;
        
        insert sv2;
        
        sv2.Sales_Manager__c = userInfo.getUserId();
        update sv2;
        
        List<Site_Visit__c> svList = new List<Site_Visit__c>();
        svList.add(sv);

        Team__c t = new Team__c();
        t.Team_Type__c = 'Sales Team';
        t.Project__c = p.Id;
        insert t;
        
        Team_Member__c tm = new Team_Member__c();
        tm.User__c = sv2.Sales_Manager__c;
        tm.Availability__c = true;
        tm.Team__c = t.Id;
        insert tm;
        tm.Availability__c = false;
        update tm;
        
        Ex_SiteVisitHandlerServices.appCPProjectOnSV(svList);
        Ex_SiteVisitHandlerServices.rollupOnOpportunity(sv);
        Ex_SiteVisitHandlerServices.updateSalesManagerAvailability(uIdSet);
        Ex_SiteVisitTriggerHandler.updateCPOnOppo(svList);
        Test.stopTest();
    }
}