force-app/main/default/objects/CP_Document__c/CP_Document__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>CP Document</label>
</CustomObject>

force-app/main/default/objects/CP_Document__c/fields/Document_Required__c.field-meta.xml
<CustomField>
    <fullName>Document_Required__c</fullName>
    <label>Document Required</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Document No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/CP_Account__c.field-meta.xml
<CustomField>
    <fullName>CP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pan Card</fullName>
            </value>
            <value>
                <fullName>GST Registration Certificate</fullName>
            </value>
            <value>
                <fullName>RERA Certificate</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ex_CPAccountTriggerHandlerService.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 03-11-2023
//-------------------------------------------//
public class Ex_CPAccountTriggerHandlerService {
    public static void InsertDocument(List<Account> accountlist){
        List<Document__c> dlist = new List<Document__c>();
        
        for(Account acc:accountlist){
            String customValues = CP_Document__c.getValues('Yes').Document_Required__c;
            system.debug('customValues::'+customValues);
            List<String> slist = customValues.split(',');
            System.debug('string list=' + slist);
            for (String s : slist) {
                System.debug('document type=' + s);
                Document__c d = new Document__c();
			    d.Document_Type__c = s; 
                d.CP_Account__c = acc.Id;
                dlist.add(d);
                System.debug('dlist' + dlist);
            }
        }
        if (!dlist.isEmpty() && dlist != null) {
            insert dlist;
        }
    }
    
    Public Static Void Check_MAHARERADuplication(List<Account> accList){
        System.debug('Account value In Handler Services Check_MAHARERADuplicatio '+ accList);
        map<String,Account>  mapOfacc = new map<String, Account>();
        List<Account> acList =  new List<Account>();
        acList=[Select Id,Name,MahaRERA_Registration_No__c from Account where RecordType.DeveloperName = 'CP_Account'];
        System.debug('acList: '+acList);
        if (!acList.isEmpty() && acList!=null){
            for (Account ac:acList){
                if(ac.MahaRERA_Registration_No__c!=null ){
                    mapOfacc.put(ac.MahaRERA_Registration_No__c,ac);
                }
            }
            for(Account acc:accList){
                If(acc.MahaRERA_Registration_No__c !=null )
                    if(mapOfacc.containsKey(acc.MahaRERA_Registration_No__c)){
                        acc.addError('CP Account with same MahaRera Number already exists');
                    }
            }
        }              
    } 
}