force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Document No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/CP_Account__c.field-meta.xml
<CustomField>
    <fullName>CP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pan Card</fullName>
            </value>
            <value>
                <fullName>GST Registration Certificate</fullName>
            </value>
            <value>
                <fullName>RERA Certificate</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Ex_CPDocumentUploadController.cls
/**
* @File Name : Ex_CPDocumentUploadController.cls
* @Description : for CP Document Upload 
* @Author : Nitin Choudhary
* @Last Modified By : Nitin Choudhary
* @Last Modified On : September 18, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | September 18, 2024 |   | Initial Version
**/

public class Ex_CPDocumentUploadController {
	@AuraEnabled
    public static List<Document__c> getCPDocumentDetails(string id ){
        List<Document__c> sList = new List<Document__c>(); 
        
        List<Document__c> dhList = [SELECT ID, Name, Document_Type__c, CP_Account__c, Uploaded__c FROM Document__c where CP_Account__r.Id=:id];
        return dhList;
    }
    
    @AuraEnabled
    public static Id uploadFile(String cpDocumentList ){ 
        System.debug('cpDocumentList' +cpDocumentList);
        Document__c cpDocument = new Document__c();
        List<Object> documentsList = (List<Object>) JSON.deserializeUntyped(cpDocumentList);   
        if (documentsList != null && !documentsList.isEmpty()) {
            for (Object document1 : documentsList) {
                if (document1 instanceof Map<String, Object>) {
                    Map<String, Object> documentMap = (Map<String, Object>) document1;
                    system.debug('documentMap  ' +documentMap);
                    cpDocument.Uploaded__c = (Boolean) documentMap.get('Uploaded__c');
                    cpDocument.Id = (Id) documentMap.get('Id');
                    update cpDocument;
                    String base64 = (string) documentMap.get('base64');
                    String filename = (string) documentMap.get('filename');
                    
                    if (base64 != null && filename != null) {
                        ContentVersion cv = createContentVersion(base64, filename);
                        ContentDocumentLink cdl = createContentLink(cv.Id, cpDocument.Id);
                        if (cv == null || cdl == null) {
                            return null;
                        }
                    }
                }
            }
        }
        return cpDocument.Id;
    }
    
    @testvisible
    private static ContentVersion createContentVersion(String base64, String filename) {
        ContentVersion cv = new ContentVersion();
        cv.VersionData = EncodingUtil.base64Decode(base64);
        cv.Title = filename;
        cv.PathOnClient = filename;
        try {
            insert cv;
            return cv;
        } catch(DMLException e) {
            System.debug(e);
            return null;
        }
    }
    @testvisible
    private static ContentDocumentLink createContentLink(String contentVersionId, String recordId) {
        if (contentVersionId == null || recordId == null) { return null; }
        ContentDocumentLink cdl = new ContentDocumentLink();
        cdl.ContentDocumentId = [
            SELECT ContentDocumentId
            FROM ContentVersion
            WHERE Id =: contentVersionId
        ].ContentDocumentId;
        cdl.LinkedEntityId = recordId;
        cdl.ShareType = 'V';
        try {
            insert cdl;
            return cdl;
        } catch(DMLException e) {
            System.debug(e);
            return null;
        }
    }
}