force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Document No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/CP_Account__c.field-meta.xml
<CustomField>
    <fullName>CP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pan Card</fullName>
            </value>
            <value>
                <fullName>GST Registration Certificate</fullName>
            </value>
            <value>
                <fullName>RERA Certificate</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Ex_CPDocumentUploadServices.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 03-11-2023
//-------------------------------------------//
public class Ex_CPDocumentUploadServices {
     @AuraEnabled
    public static List<Document__c> CPAccountDocument_Uploads(string id ){
        List<Document__c> sList = new List<Document__c>(); 

        List<Document__c> dhList = [SELECT ID,Name,Document_Type__c,CP_Account__C,Uploaded__c FROM Document__c where CP_Account__r.Id=:id];
        
        for(Document__c doc:dhList){
            if(doc.Uploaded__c == false){
                sList.add(doc);
            }
        }   
        System.debug(slist.size());
        return sList;
    }
     
   @AuraEnabled()
    public static void Uploads(string did ){ 
        System.debug('did = '+ did);
        List<Document__c> dList = new List<Document__c>(); 
        List<ContentDocumentLink> cdlist = new List<ContentDocumentLink>();
        List<ContentVersion> contentVersionList= new List<ContentVersion>();
        
        contentVersionList = [Select Id,ContentDocumentId from ContentVersion where id =:did];
        System.debug('ContentDocumentId = '+ contentVersionList[0].ContentDocumentId);
        
        cdlist = [SELECT LinkedEntityId FROM ContentDocumentLink  WHERE ContentDocumentId  =:contentVersionList[0].ContentDocumentId AND LinkedEntityId in (SELECT Id FROM Document__c) and LinkedEntity.Type=:'Document__c' ];
        System.debug('LinkedEntityId = '+ cdlist[0].LinkedEntityId);
        
        List<Document__c> dhList = [SELECT ID, Name, Document_Type__c, CP_Account__c, Uploaded__c FROM Document__c where Id=:cdlist[0].LinkedEntityId];
        
        for(Document__c docnew : dhList){
            System.debug('docnew' + docnew);
            docnew.Uploaded__c = true;
            dList.add(docnew);
        }   
        
        System.debug(dlist);
        Update dList[0];
        
    }


}