force-app/main/default/objects/Team_Member__c/Team_Member__c.object-meta.xml
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team_Member__c/fields/Availability__c.field-meta.xml
<CustomField>
    <fullName>Availability__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Availability</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Ex_TeamMemberTriggerHandler.cls
public class Ex_TeamMemberTriggerHandler {
    public static void afterUpdate(Map<Id, Team_Member__c> oldMap, Map<Id, Team_Member__c> newMap) {
        Set<Id> tmIdSet = new Set<Id>(); 
        
        for(Team_Member__c oldMember: oldMap.values()) {
            Team_Member__c newMember = newMap.get(oldMember.Id);
            
            if(oldMember.Availability__c != newMember.Availability__c && newMember.Availability__c == true) {
                tmIdSet.add(newMember.Id);
            }
        }
        if(!tmIdSet.isEmpty() && tmIdSet != null) 
            Ex_TeamMemberHandlerServices.checkVisitForAssignment(tmIdSet);
    }
}