force-app/main/default/objects/Ledger__c/Ledger__c.object-meta.xml
<CustomObject>
    <label>Ledger</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ledger__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ex_LedgerTriggerHandler.cls
public class Ex_LedgerTriggerHandler {
     public static void beforeDelete(Map<Id, Ledger__c> oldMap, Map<Id, Ledger__c> newMap) {
        Set<Id> lIdSet = new Set<Id>();

        for(Ledger__c oldLedger: oldMap.values()) {
            if(oldLedger.Type__c.equalsIgnoreCase('Credit') && !oldLedger.Cancelled__c)
                lIdSet.add(oldLedger.Id);
        }
        if(!lIdSet.isEmpty() && lIdSet != null)
            Ex_LedgerHandlerServices.reverseCalculationOnDemandAndReceipt(lIdSet);
    }
}