force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Receipt_Status__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Status__c</fullName>
    <label>Receipt Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UnProcessed</fullName>
                <default>true</default>
                <label>UnProcessed</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Processed-Finance Submission Pending</fullName>
            </value>
            <value>
                <fullName>Processed-Sent for Banking</fullName>
            </value>
            <value>
                <fullName>Dishonored</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Physical Verification Rejected</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>Reverse</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ex_ReceiptAction.cls
public class Ex_ReceiptAction {
 @AuraEnabled
    public static boolean receiptrecord( String Selectoption , String Remarks, String recordId){
        
        try{
            System.debug('Selectoption: ' +Selectoption);
            System.debug('Remarks: ' +Remarks);
            System.debug('recordId: ' +recordId);
            
            Receipt__c rec = [Select Id, Name, Receipt_Status__c, Remarks__c From Receipt__c where Id =:recordId];
            System.debug('demnd: ' +rec); 
            rec.Receipt_Status__c = Selectoption;
            system.debug('Demand Status: ' +rec.Receipt_Status__c);
            rec.Remarks__c = Remarks;
            system.debug('Remarks: ' +rec.Remarks__c);
            update rec;
            
            if(Selectoption == 'Delete'){
                system.debug('Inside Delete ::::');
                delete rec;
            }
            
            return true;
        }
        catch(Exception e){
            System.debug('An error occurred while saving the records: ' + e.getMessage());
            return false;
        }
    }
    
}