force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/fields/Agreement_Value_Paid__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Agreement_Value_Tax_Paid__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value_Tax_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value Tax Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Interest_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Interest Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Tax_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Tax Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ledger__c/Ledger__c.object-meta.xml
<CustomObject>
    <label>Ledger</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ledger__c/fields/Charge_Name__c.field-meta.xml
<CustomField>
    <fullName>Charge_Name__c</fullName>
    <label>Charge Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Demand Cost</fullName>
            </value>
            <value>
                <fullName>Demand Tax</fullName>
            </value>
            <value>
                <fullName>Demand Interest</fullName>
            </value>
            <value>
                <fullName>Flat Cost</fullName>
            </value>
            <value>
                <fullName>Tax</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>TDS Challan</fullName>
            </value>
            <value>
                <fullName>Interest GST</fullName>
            </value>
            <value>
                <fullName>TDS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Tax_Ledger__c.field-meta.xml
<CustomField>
    <fullName>Tax_Ledger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Tax Ledger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
            </value>
            <value>
                <fullName>Debit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Total_Money_Apportioned__c.field-meta.xml
<CustomField>
    <fullName>Total_Money_Apportioned__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Money Apportioned</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Ex_LedgerHandlerServices.cls
//-------------------------------------------//
//  Project: Satyam
//  Created By: Exceller tech
//  Created Date: 06-11-2023
//-------------------------------------------//
public class Ex_LedgerHandlerServices {
    public static void reverseCalculationOnDemandAndReceipt(Set<Id> lIdSet) {
        List<Demand__c> updateDemandList = new List<Demand__c>();
        List<Receipt__c> updateReceiptList = new List<Receipt__c>();
        List<Ledger__c> creditLedgerList = new List<Ledger__c>();
        List<Demand__c> demandList = new List<Demand__c>();
        Map<Id, Demand__c> demandMap = new Map<Id, Demand__c>();
        Map<Id, List<Ledger__c>> demandCreditLedgerMap = new Map<Id, List<Ledger__c>>();
        List<Receipt__c> receiptList = new List<Receipt__c>();
        Map<Id, Receipt__c> receiptMap = new Map<Id, Receipt__c>();
        Map<Id, List<Ledger__c>> receiptCreditLedgerMap = new Map<Id, List<Ledger__c>>();
        
        creditLedgerList = [Select Id, Name, Charge_Name__c, Amount__c, Demand__c, Tax_Ledger__c, Receipt__c from Ledger__c where Id IN: lIdSet AND Type__c = 'Credit'];
        system.debug('creditLedgerList: '+creditLedgerList);
        
        if(!creditLedgerList.isEmpty() && creditLedgerList != null) {
            for(Ledger__c l: creditLedgerList) {
                if(demandCreditLedgerMap.containsKey(l.Demand__c)) {
                    demandCreditLedgerMap.get(l.Demand__c).add(l);
                } else {
                    List<Ledger__c> newList = new List<Ledger__c>();
                    newList.add(l);
                    demandCreditLedgerMap.put(l.Demand__c, newList);
                }
                if(receiptCreditLedgerMap.containsKey(l.Receipt__c)) {
                    receiptCreditLedgerMap.get(l.Receipt__c).add(l);
                } else {
                    List<Ledger__c> newList = new List<Ledger__c>();
                    newList.add(l);
                    receiptCreditLedgerMap.put(l.Receipt__c, newList);
                }
            }
            if(!demandCreditLedgerMap.isEmpty() && demandCreditLedgerMap != null) {
                demandList = getDemandInfo(demandCreditLedgerMap.keySet());
                system.debug('demandList: '+demandList);
                
                if(demandList != null) {
                    for(Demand__c d: demandList) {
                        demandMap.put(d.Id, d);
                    }
                    for(Id dId: demandMap.keySet()) {
                        Demand__c d = demandMap.get(dId);
                        for(Ledger__c l: demandCreditLedgerMap.get(d.Id)) {
                            if(l.Charge_Name__c.equalsIgnoreCase('Interest')) {
                                d.Total_Interest_Amount_Paid__c = d.Total_Interest_Amount_Paid__c - l.Amount__c;
                            } else if(l.Charge_Name__c.equalsIgnoreCase('Flat Cost')) {
                                if(l.Tax_Ledger__c) {
                                    if(d.Demand_Type__c.equalsIgnoreCase('Flat Cost')) {
                                        d.Agreement_Value_Tax_Paid__c = d.Agreement_Value_Tax_Paid__c - l.Amount__c;
                                    }
                                    d.Total_Tax_Paid__c = d.Total_Tax_Paid__c - l.Amount__c;
                                } else {
                                    if(d.Demand_Type__c.equalsIgnoreCase('Flat Cost')) {
                                        d.Agreement_Value_Paid__c = d.Agreement_Value_Paid__c - l.Amount__c;
                                    }
                                    d.Total_Amount_Paid__c = d.Total_Amount_Paid__c - l.Amount__c;
                                }
                            }
                        }
                        updateDemandList.add(d);
                    }
                }
            }
            if(!receiptCreditLedgerMap.isEmpty() && receiptCreditLedgerMap != null) {
                receiptList = getReceiptInfo(receiptCreditLedgerMap.keySet());
                system.debug('receiptList: '+receiptList);
                
                if(receiptList != null) {
                    for(Receipt__c r: receiptList) {
                        receiptMap.put(r.Id, r);
                    }
                    for(Id receiptId: receiptMap.keySet()) {
                        Receipt__c r = receiptMap.get(receiptId);
                        for(Ledger__c l: receiptCreditLedgerMap.get(r.Id)) {
                            r.Total_Money_Apportioned__c = r.Total_Money_Apportioned__c - l.Amount__c;
                        }
                        updateReceiptList.add(r);
                    }
                }
            }
            if(!updateDemandList.isEmpty() && updateDemandList != null)
                update updateDemandList;
            if(!updateReceiptList.isEmpty() && updateReceiptList != null)
                update updateReceiptList;
        }
    }
    
    public static List<Demand__c> getDemandInfo(Set<Id> demandIdSet) {
        List<Demand__c> demandList = new List<Demand__c>();
        String[] types = new String[]{'Demand__c'};
            string queryFields = '';
        Schema.DescribeSobjectResult[] results = Schema.describeSObjects(types);
        
        for(Schema.DescribeSobjectResult res : results) {
            string sObjectname = res.getName();
            Map <String, Schema.SObjectField> fieldMap = res.fields.getMap();
            
            for(Schema.SObjectField sfield : fieldMap.Values()) { 
                schema.describefieldresult dfield = sfield.getDescribe();
                String fieldLabel = dfield.getLabel();
                
                if(queryFields == null || queryFields == '') {
                    queryFields = dField.getName();
                } else {
                    queryFields = queryFields + ', ' + dField.getName();
                }
            }
        }
        String soqlQuery = 'Select ' + queryFields  + ' from Demand__c Where Id IN :demandIdSet'; 
        system.debug('soqlQuery: '+soqlQuery);
        demandList = Database.query(soqlQuery);
        if(demandList.size() > 0) {
            return demandList;
        } else {
            return null;
        }
    }
    
    public static List<Receipt__c> getReceiptInfo(Set<Id> receiptIdSet) {
        List<Receipt__c> receiptList = new List<Receipt__c>();
        String[] types = new String[]{'Receipt__c'};
            string queryFields = '';
        Schema.DescribeSobjectResult[] results = Schema.describeSObjects(types);
        
        for(Schema.DescribeSobjectResult res : results) {
            string sObjectname = res.getName();
            Map <String, Schema.SObjectField> fieldMap = res.fields.getMap();
            
            for(Schema.SObjectField sfield : fieldMap.Values()) { 
                schema.describefieldresult dfield = sfield.getDescribe();
                String fieldLabel = dfield.getLabel();
                
                if(queryFields == null || queryFields == '') {
                    queryFields = dField.getName();
                } else {
                    queryFields = queryFields + ', ' + dField.getName();
                }
            }
        }
        String soqlQuery = 'Select ' + queryFields  + ' from Receipt__c Where Id IN :receiptIdSet'; 
        system.debug('soqlQuery: '+soqlQuery);
        receiptList = Database.query(soqlQuery);
        if(receiptList.size() > 0) {
            return receiptList;
        } else {
            return null;
        }
    }
    
}