force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Applicant_Number__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Number__c</fullName>
    <label>Applicant Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Applicant</fullName>
            </value>
            <value>
                <fullName>Second Applicant</fullName>
            </value>
            <value>
                <fullName>Third Applicant</fullName>
            </value>
            <value>
                <fullName>Fourth Applicant</fullName>
            </value>
            <value>
                <fullName>Fifth Applicant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Applicant</relationshipLabel>
    <relationshipName>Applicant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Advance_maintenance_24_months_GST_18__c.field-meta.xml
<CustomField>
    <fullName>Advance_maintenance_24_months_GST_18__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Advance maintenance 24 months + GST (18%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Sanctioned_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sanctioned_Loan_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>It is used in case of mode funding amount is home loan</inlineHelpText>
    <label>Sanctioned Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh Grameena Vikas Bank</fullName>
            </value>
            <value>
                <fullName>Andhra Pragathi Grameena Bank</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh Rural Bank</fullName>
            </value>
            <value>
                <fullName>Aryavart Bank</fullName>
            </value>
            <value>
                <fullName>Assam Gramin Vikash Bank</fullName>
            </value>
            <value>
                <fullName>Au Small Finance Bank Limited</fullName>
            </value>
            <value>
                <fullName>Axis Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Bajaj Housing Finance</fullName>
            </value>
            <value>
                <fullName>Bandhan Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Bangiya Gramin Vikas Bank</fullName>
            </value>
            <value>
                <fullName>Bank of Baroda</fullName>
            </value>
            <value>
                <fullName>Bank of India</fullName>
            </value>
            <value>
                <fullName>Bank of Maharashtra</fullName>
            </value>
            <value>
                <fullName>Baroda Gujarat Gramin Bank</fullName>
            </value>
            <value>
                <fullName>Baroda Rajasthan Kshetriya Gramin Bank</fullName>
            </value>
            <value>
                <fullName>Baroda UP Bank*</fullName>
            </value>
            <value>
                <fullName>Canara Bank</fullName>
            </value>
            <value>
                <fullName>Capital Small Finance Bank Limited</fullName>
            </value>
            <value>
                <fullName>Central Bank of India</fullName>
            </value>
            <value>
                <fullName>Chaitanya Godavari Grameena Bank</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh Rajya Gramin Bank</fullName>
            </value>
            <value>
                <fullName>City Union Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>CSB Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Dakshin Bihar Gramin Bank</fullName>
            </value>
            <value>
                <fullName>DCB Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>Dhanlaxmi Bank Ltd.</fullName>
            </value>
            <value>
                <fullName>DNS Bank</fullName>
            </value>
            <value>
                <fullName>Ellaquai Dehati Bank</fullName>
            </value>
            <value>
                <fullName>Equitas Small Finance Bank Limited</fullName>
            </value>
            <value>
                <fullName>ESAF Small Finance Bank Limited</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipt</relationshipLabel>
    <relationshipName>Receipt</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestEx_BookingFormBController.cls
@isTest
public class TestEx_BookingFormBController {
    @isTest
    public static void testBooking() {
        Booking__c b = new Booking__c();
        b.Agreement_Value__c = 100;
        b.Sanctioned_Loan_Amount__c = 65 ;
        b.Advance_maintenance_24_months_GST_18__c = 18;
        insert b;
        
        Applicant__c ap = new Applicant__c();
        ap.Booking__c = b.Id ;
        ap.Applicant_Number__c = '655';
        insert ap ;
        
        Receipt__c rc = new Receipt__c();
        rc.Booking__c = b.Id ;
        rc.Receipt_Date__c = system.today();
        rc.Bank_Name__c = 'Andhra Pradesh Grameena Vikas Bank' ;
        rc.Amount__c = 7655;
        rc.Transaction_Id__c = '6555';
        insert rc ;
            
            
        Test.startTest();
        ApexPages.currentPage().getParameters().put('bId', b.Id);
        Ex_BookingFormBController controller = new Ex_BookingFormBController();
        Ex_BookingFormBController.calculateAge(system.today());
        Test.stopTest();
    }
}