force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Applicant_Number__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Number__c</fullName>
    <label>Applicant Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Applicant</fullName>
            </value>
            <value>
                <fullName>Second Applicant</fullName>
            </value>
            <value>
                <fullName>Third Applicant</fullName>
            </value>
            <value>
                <fullName>Fourth Applicant</fullName>
            </value>
            <value>
                <fullName>Fifth Applicant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Applicant_Title__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Title__c</fullName>
    <label>Applicant Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Applicant</relationshipLabel>
    <relationshipName>Applicant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/All_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>All_Applicant_Name__c</fullName>
    <label>All Applicant Name</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Applicant_Address__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Address__c</fullName>
    <label>Applicant Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Title__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Title__c</fullName>
    <label>Primary Applicant Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Ex_ApplicantHandlerServices.cls
public class Ex_ApplicantHandlerServices {
    public static void updateApplicantsonBooking(Map<Id, List<Applicant__c>> newBookMap){
        System.debug('newBookMap: '+newBookMap);
        List<Booking__c> bkList = new List<Booking__c>();
        List<Booking__c> updatedBookings = new List<Booking__c>();
        
        bkList  = [Select Id, Name, Primary_Applicant_Mobile__c, All_Applicant_Name__c, Primary_Applicant_Email__c, Applicant_Address__c, Primary_Applicant_Name__c, Primary_Applicant_Title__c
                   from Booking__c where Id =: newBookMap.keySet()] ;
        System.debug('bkList: '+bklist);
        if(bklist != null && !bklist.isEmpty()){
            for(Booking__c bk: bkList){
                List<Applicant__c> applicants = newBookMap.get(bk.Id);
                System.debug('applicants: '+applicants);
                if(applicants != null && !applicants.isEmpty()){
                    String AllApplicantName = '';
                    for(Applicant__c ap: applicants){
                        if(ap.Applicant_Number__c.equalsIgnoreCase('Primary Applicant') && ap.Applicant_Number__c != null){
                            bk.Primary_Applicant_Title__c = ap.Applicant_Title__c;
                            bk.Primary_Applicant_Name__c = ap.Name;
                            bk.Primary_Applicant_Mobile__c = ap.Mobile_Number__c;
                            bk.Primary_Applicant_Email__c = ap.Applicant_Email__c;
                            bk.Applicant_Address__c = ap.Permanent_Address__c;
                            AllApplicantName += ap.Applicant_Title__c + ' '+ ap.Name ; 
                            if(applicants.indexOf(ap) < applicants.size() - 1){
                                AllApplicantName += ', ';
                            }
                        }
                    }
                    if(String.isNotBlank(AllApplicantName)){
                        bk.All_Applicant_Name__c = AllApplicantName;
                    }
                }
                updatedBookings.add(bk);
            }
        }
        System.debug('updatedBookings: '+updatedBookings);
        if (!updatedBookings.isEmpty() && updatedBookings  != null) {
            try {
                update updatedBookings;
                System.debug('Updated Bookings: ' + updatedBookings);
            } catch (DmlException e) {
                System.debug('Error updating bookings: ' + e.getMessage());
            }
        }
    }
}