force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Applicant</relationshipLabel>
    <relationshipName>Applicant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestEx_PrintBookingFormController.cls
//-------------------------------------------//
//  Client: Satyam Developers
//  Created By: Exceller Consultancy
//  Created Date: 30-11-2023
//-------------------------------------------//
@Istest
public class TestEx_PrintBookingFormController {
    @isTest
    public static void testConstructor() {
    Booking__c b = new Booking__c();
    b.Agreement_Value__c = 100;
    insert b;
        
        Applicant__c ap = new Applicant__c();
        ap.Booking__c = b.Id;
        insert ap;      
        
        
    Test.startTest();
    ApexPages.currentPage().getParameters().put('bId', b.Id);
    Ex_PrintBookingFormController controller = new Ex_PrintBookingFormController();
    Test.stopTest();
    }
}