force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Email__c</fullName>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Applicant_Number__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Number__c</fullName>
    <label>Applicant Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Applicant</fullName>
            </value>
            <value>
                <fullName>Second Applicant</fullName>
            </value>
            <value>
                <fullName>Third Applicant</fullName>
            </value>
            <value>
                <fullName>Fourth Applicant</fullName>
            </value>
            <value>
                <fullName>Fifth Applicant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Applicant_Title__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Title__c</fullName>
    <label>Applicant Title</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Applicant</relationshipLabel>
    <relationshipName>Applicant</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/Ex_ApplicantTriggerHandler.cls
public class Ex_ApplicantTriggerHandler {
    public static void afterUpdate(Map<Id, Applicant__c> oldMap, Map<Id, Applicant__c> newMap) {
        Map<Id, List<Applicant__c>> newBookMap = new Map<Id, List<Applicant__c>>();
        List<Booking__c> updateBooking = new List<Booking__c>();
        for(Applicant__c oldApplicant: oldMap.values()) {
            Applicant__c newApplicant = newMap.get(oldApplicant.Id);
            
            if(newApplicant.Booking__c != null && (oldApplicant.Applicant_Number__c != newApplicant.Applicant_Number__c || oldApplicant.Mobile_Number__c != newApplicant.Mobile_Number__c 
               || oldApplicant.Applicant_Email__c != newApplicant.Applicant_Email__c || oldApplicant.Name != newApplicant.Name
               || oldApplicant.Applicant_Title__c != newApplicant.Applicant_Title__c || oldApplicant.Permanent_Address__c != newApplicant.Permanent_Address__c)){
                  
                   if(!newBookMap.containskey(newApplicant.Booking__c)){
                       List<Applicant__c> newList = new List<Applicant__c>();
                       newList.add(newApplicant);
                       newBookMap.put(newApplicant.Booking__c, newList);
                   }else{
                       newBookMap.get(newApplicant.Booking__c).add(newApplicant);
                   }
              }
        }
        System.debug('newBookMap: '+newBookMap);
        if(!newBookMap.isEmpty() && newBookMap != null){
            Ex_ApplicantHandlerServices.updateApplicantsonBooking(newBookMap);
        }
    }
}