force-app/main/default/objects/SMS__c/SMS__c.object-meta.xml
<CustomObject>
    <label>SMS</label>
    <nameField>
        <label>SMS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMSs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SMS__c/fields/Sender_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Sender_Mobile_No__c</fullName>
    <label>Sender Mobile No</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SMS__c/fields/Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Template_Id__c</fullName>
    <label>Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/fields/Param_1_Name__c.field-meta.xml
<CustomField>
    <fullName>Param_1_Name__c</fullName>
    <label>Param 1 Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_1_Status__c.field-meta.xml
<CustomField>
    <fullName>Param_1_Status__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Param 1 Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_1_Value__c.field-meta.xml
<CustomField>
    <fullName>Param_1_Value__c</fullName>
    <label>Param 1 Value</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_2_Name__c.field-meta.xml
<CustomField>
    <fullName>Param_2_Name__c</fullName>
    <label>Param 2 Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_2_Status__c.field-meta.xml
<CustomField>
    <fullName>Param_2_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Param 2 Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_2_Value__c.field-meta.xml
<CustomField>
    <fullName>Param_2_Value__c</fullName>
    <label>Param 2 Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_3_Name__c.field-meta.xml
<CustomField>
    <fullName>Param_3_Name__c</fullName>
    <label>Param 3 Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_3_Status__c.field-meta.xml
<CustomField>
    <fullName>Param_3_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Param 3 Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_3_Value__c.field-meta.xml
<CustomField>
    <fullName>Param_3_Value__c</fullName>
    <label>Param 3 Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_4_Name__c.field-meta.xml
<CustomField>
    <fullName>Param_4_Name__c</fullName>
    <label>Param 4 Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_4_Status__c.field-meta.xml
<CustomField>
    <fullName>Param_4_Status__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Param 4 Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_4_Value__c.field-meta.xml
<CustomField>
    <fullName>Param_4_Value__c</fullName>
    <label>Param 4 Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Vendor_Status__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Status__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Vendor Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Vendor_Url__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Url__c</fullName>
    <label>Vendor Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/TestEx_SMSHandlerServices.cls
@isTest
public class TestEx_SMSHandlerServices {
    @isTest
    public static void outboundSMS(){
        
        
        
        Vendor__c v = new Vendor__c();
        v.Name = 'Test Vendor';
        v.Vendor_Url__c = 'https://example.com';
        v.Param_1_Name__c = 'param1';
        v.Param_1_Value__c = 'value1';
        v.Param_1_Status__c = true;
        v.Param_2_Name__c = 'param2';
        v.Param_2_Value__c = 'value2';
        v.Param_2_Status__c = true;
        v.Param_3_Name__c = 'param3';
        v.Param_3_Value__c = 'value3';
        v.Param_3_Status__c = true;
        v.Param_4_Name__c = 'param4';
        v.Param_4_Value__c = 'value4';
        v.Param_4_Status__c = true;
        v.Vendor_Status__c = true;
        
        insert v;
        
        
        
        Test.startTest();
        SMS__c s = new SMS__c();
        s.Sender_Mobile_No__c = '1234567890';
        s.Message__c = 'Test message';
        s.Template_Id__c = 'template123';
        insert s;
        Test.stopTest();
        
    }
    
}