force-app/main/default/objects/SMS__c/SMS__c.object-meta.xml
<CustomObject>
    <label>SMS</label>
    <nameField>
        <label>SMS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMSs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131071</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SMS__c/fields/Sender_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Sender_Mobile_No__c</fullName>
    <label>Sender Mobile No</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SMS__c/fields/Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Template_Id__c</fullName>
    <label>Template Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/Vendor__c.object-meta.xml
<CustomObject>
    <label>Vendor</label>
    <nameField>
        <label>Vendor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor__c/fields/Param_1_Name__c.field-meta.xml
<CustomField>
    <fullName>Param_1_Name__c</fullName>
    <label>Param 1 Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_1_Status__c.field-meta.xml
<CustomField>
    <fullName>Param_1_Status__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Param 1 Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_1_Value__c.field-meta.xml
<CustomField>
    <fullName>Param_1_Value__c</fullName>
    <label>Param 1 Value</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_2_Name__c.field-meta.xml
<CustomField>
    <fullName>Param_2_Name__c</fullName>
    <label>Param 2 Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_2_Status__c.field-meta.xml
<CustomField>
    <fullName>Param_2_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Param 2 Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_2_Value__c.field-meta.xml
<CustomField>
    <fullName>Param_2_Value__c</fullName>
    <label>Param 2 Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_3_Name__c.field-meta.xml
<CustomField>
    <fullName>Param_3_Name__c</fullName>
    <label>Param 3 Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_3_Status__c.field-meta.xml
<CustomField>
    <fullName>Param_3_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Param 3 Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_3_Value__c.field-meta.xml
<CustomField>
    <fullName>Param_3_Value__c</fullName>
    <label>Param 3 Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_4_Name__c.field-meta.xml
<CustomField>
    <fullName>Param_4_Name__c</fullName>
    <label>Param 4 Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_4_Status__c.field-meta.xml
<CustomField>
    <fullName>Param_4_Status__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Param 4 Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_4_Value__c.field-meta.xml
<CustomField>
    <fullName>Param_4_Value__c</fullName>
    <label>Param 4 Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_5_Name__c.field-meta.xml
<CustomField>
    <fullName>Param_5_Name__c</fullName>
    <label>Param 5 Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_5_Status__c.field-meta.xml
<CustomField>
    <fullName>Param_5_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Param 5 Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Param_5_Value__c.field-meta.xml
<CustomField>
    <fullName>Param_5_Value__c</fullName>
    <label>Param 5 Value</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Vendor_Status__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Status__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Vendor Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vendor__c/fields/Vendor_Url__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Url__c</fullName>
    <label>Vendor Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/SMSHandlerServices.cls
public class SMSHandlerServices {
   
    @future(Callout=true) 
    public static void outboundSMS(set<Id> smsIds){
        system.debug('Inside::outboundSMS');
        string myphone = '';
        string mymsg = '';
        string strURL = ''; 
        string tempId = '';
        
        if(smsIds != null && smsIds.size() > 0) {
            List<SMS__c> smslist = new list<SMS__c> ();
            smslist = [SELECT Id,Name, Sender_Mobile_No__c,Message__c,Template_Id__c FROM 
                       SMS__c where Id in :smsIds];
            
            
            List <Vendor__c> vendorlist = new List<Vendor__c>();       
            vendorlist = [SELECT id, Name, Vendor_Url__c ,Param_1_Name__c,Param_1_Value__c,Param_1_Status__c,
                          Param_2_Name__c, Param_2_Value__c, Param_2_Status__c,
                          Param_3_Name__c, Param_3_Value__c, Param_3_Status__c,
                          Param_4_Name__c, Param_4_Value__c, Param_4_Status__c,
                          Param_5_Name__c, Param_5_Value__c, Param_5_Status__c
                          FROM Vendor__c WHERE Vendor_Status__c = true limit 1]; 
            
            for(SMS__c newsms :smslist) {
                if(newsms.Sender_Mobile_No__c!= null) {
                    myphone = newsms.Sender_Mobile_No__c;
                }       
                if(newsms.Message__c!= null) {
                    mymsg = newsms.Message__c;
                }
                if(newsms.Template_Id__c != null){
                    tempId = newsms.Template_Id__c;
                }
                
                mymsg = EncodingUtil.URLENCODE(mymsg,'UTF-8');
                mymsg = mymsg.replace('%2B%E2%80%9D','%20');
                mymsg = mymsg.replace('%2B%E2%80%9C','%20');
                mymsg = mymsg.replace('+','%20');
                
                if(vendorlist != null && !vendorlist.isEmpty() && vendorlist[0].Param_1_Status__c == TRUE && 
                   vendorlist[0].Param_2_Status__c == TRUE && vendorlist[0].Param_3_Status__c  == TRUE && vendorlist[0].Param_4_Status__c == TRUE) {        
                       strURL = vendorlist[0].Vendor_Url__c + 
                           '?'+vendorlist[0].Param_1_Name__c + '=' + vendorlist[0].Param_1_Value__c + 
                           '&' + vendorlist[0].Param_3_Name__c + '=' + vendorlist[0].Param_3_Value__c +
                           '&' + vendorlist[0].Param_4_Name__c + '=' + vendorlist[0].Param_4_Value__c + 
                           '&' + vendorlist[0].Param_2_Name__c + '=' + vendorlist[0].Param_2_Value__c + 
                           '&templateId='+ tempId +
                           '&mobile='+ myphone + 
                           '&message='+ mymsg ;
                   }
                system.debug('Url:::'+strURL);
                if(strURL != null){
                    if(!Test.isRunningTest()) {
                        HttpRequest req = new HttpRequest();
                        req.setEndpoint (strURL);
                        req.setMethod ('POST');
                        Http http = new Http();
                        HTTPResponse res = http.send(req);
                        system.debug('HTTPResponse : '+ res);  
                    }    
                }
            }
        }
    } 
}