force-app/main/default/objects/SMS__c/SMS__c.object-meta.xml
<CustomObject>
    <label>SMS</label>
    <nameField>
        <label>SMS Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMSs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS__c/fields/Sender_Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Sender_Mobile_No__c</fullName>
    <label>Sender Mobile No</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/SMSTriggerHandler.cls
public class SMSTriggerHandler {
    public static void afterInsert(List<SMS__c> smsList) {
        Set<Id> smsIdSet = new Set<Id>();
        
        for(SMS__c s: smsList) {
            if(s.Id != null && s.Sender_Mobile_No__c != null) {
                smsIdSet.add(s.Id);
            }
        }   
        if(!smsIdSet.isEmpty() && smsIdSet != null)
            SMSHandlerServices.outboundSMS(smsIdSet);
    }
}